import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C2_MIR_02_IDENTITY: SkillIdentity = {
  code: "C2.MIR.02",
  strand_code: "C2.MIR",
  competency_code: "C2",
  name: "Ảnh gương",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["predict", "infer"],
  tier: "advanced",
  prerequisites: ["C2.MIR.01"],
  learning_objectives: [
    {
      code: "LO-C2.MIR.02-01",
      behaviour: "Nhận biết và thực hành Ảnh gương ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C2.MIR.02-02",
      behaviour: "Vận dụng Ảnh gương trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C2.MIR.02-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Ảnh gương",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C2_MIR_02_DATASET: SkillDataset = {
  skill_code: "C2.MIR.02",
  concept_label: "Ảnh gương",
  surface: "game",
  items: [
    {
      id: "bowl",
      label: "cái bát",
      image: {
        kind: "emoji",
        ref: "🥣",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "spoon",
      label: "cái thìa",
      image: {
        kind: "emoji",
        ref: "🥄",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "cup",
      label: "cái cốc",
      image: {
        kind: "emoji",
        ref: "🥤",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "bed",
      label: "cái giường",
      image: {
        kind: "emoji",
        ref: "🛏️",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "chair",
      label: "cái ghế",
      image: {
        kind: "emoji",
        ref: "🪑",
      },
      category: {
        type: "đồ dùng",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Ảnh gương",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Ảnh gương",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Ảnh gương nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ hình {label} nhé!",
  },
  ordering: ["bowl", "spoon", "cup", "bed", "chair"],
};

export const C2_MIR_02_SEED: SkillSeed = {
  identity: C2_MIR_02_IDENTITY,
  dataset: C2_MIR_02_DATASET,
  levels: [
    {
      code: "GL-C2-FLI-SHP-0006",
      template: "GT-019",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0007",
      template: "GT-019",
      band: "5-6",
      difficulty: 1,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0008",
      template: "GT-019",
      band: "5-6",
      difficulty: 2,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0009",
      template: "GT-019",
      band: "5-6",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0010",
      template: "GT-019",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-SYM-MIR-0006",
      template: "GT-021",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0007",
      template: "GT-021",
      band: "5-6",
      difficulty: 1,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0008",
      template: "GT-021",
      band: "5-6",
      difficulty: 2,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0009",
      template: "GT-021",
      band: "5-6",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0010",
      template: "GT-021",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-MIR-PAIR-0003",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-PAIR-0004",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-SORT-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-SORT-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-SHAD-0001",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-SHAD-0002",
      template: "GT-007",
      band: "4-5",
      difficulty: 4,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-SIZE-0001",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-SIZE-0002",
      template: "GT-009",
      band: "4-5",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-PUZZ-0001",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-PUZZ-0002",
      template: "GT-010",
      band: "4-5",
      difficulty: 4,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
