import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C2_MIR_01_IDENTITY: SkillIdentity = {
  code: "C2.MIR.01",
  strand_code: "C2.MIR",
  competency_code: "C2",
  name: "Đối xứng trục dọc",
  age_min: 4,
  age_max: 4,
  difficulty: 3,
  thinking_processes: ["observe", "predict"],
  tier: "core",
  prerequisites: ["C2.GEO.02"],
  learning_objectives: [
    {
      code: "LO-C2.MIR.01-01",
      behaviour: "Nhận biết và thực hành Đối xứng trục dọc ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C2.MIR.01-02",
      behaviour: "Vận dụng Đối xứng trục dọc trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C2.MIR.01-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đối xứng trục dọc",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C2_MIR_01_DATASET: SkillDataset = {
  skill_code: "C2.MIR.01",
  concept_label: "Đối xứng trục dọc",
  surface: "game",
  items: [
    {
      id: "dog",
      label: "con chó",
      image: {
        kind: "emoji",
        ref: "🐕",
      },
      category: {
        type: "động vật",
      },
    },
    {
      id: "cat",
      label: "con mèo",
      image: {
        kind: "emoji",
        ref: "🐈",
      },
      category: {
        type: "động vật",
      },
    },
    {
      id: "chicken",
      label: "con gà",
      image: {
        kind: "emoji",
        ref: "🐓",
      },
      category: {
        type: "động vật",
      },
    },
    {
      id: "duck",
      label: "con vịt",
      image: {
        kind: "emoji",
        ref: "🦆",
      },
      category: {
        type: "động vật",
      },
    },
    {
      id: "fish",
      label: "con cá",
      image: {
        kind: "emoji",
        ref: "🐟",
      },
      category: {
        type: "động vật",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Đối xứng trục dọc",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Đối xứng trục dọc",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Đối xứng trục dọc nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ hình {label} nhé!",
  },
  ordering: ["dog", "cat", "chicken", "duck", "fish"],
};

export const C2_MIR_01_SEED: SkillSeed = {
  identity: C2_MIR_01_IDENTITY,
  dataset: C2_MIR_01_DATASET,
  levels: [
    {
      code: "GL-C2-FLI-SHP-0001",
      template: "GT-019",
      band: "4-5",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0002",
      template: "GT-019",
      band: "4-5",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0003",
      template: "GT-019",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0004",
      template: "GT-019",
      band: "4-5",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-FLI-SHP-0005",
      template: "GT-019",
      band: "4-5",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D2-10",
    },
    {
      code: "GL-C2-SYM-MIR-0001",
      template: "GT-021",
      band: "4-5",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0002",
      template: "GT-021",
      band: "4-5",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0003",
      template: "GT-021",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0004",
      template: "GT-021",
      band: "4-5",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-SYM-MIR-0005",
      template: "GT-021",
      band: "4-5",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-MIR-TAP-0001",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-TAP-0002",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-TCNT-0001",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-TCNT-0002",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-TCMP-0001",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-TCMP-0002",
      template: "GT-003",
      band: "3-4",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-PAIR-0001",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-PAIR-0002",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-PATT-0001",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-PATT-0002",
      template: "GT-005",
      band: "3-4",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
  ],
};
