import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_05_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.05",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Dung tích",
  age_min: 5,
  age_max: 5,
  difficulty: 3,
  thinking_processes: ["compare", "predict"],
  tier: "core",
  prerequisites: ["C1.MEAS.04"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.05-01",
      behaviour: "Nhận biết và thực hành Dung tích ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.05-02",
      behaviour: "Vận dụng Dung tích trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.05-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Dung tích",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_05_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.05",
  concept_label: "Dung tích",
  surface: "game",
  items: [
    {
      id: "dim_capacity_empty_less",
      label: "bình nước cạn",
      glyph: "🏺",
      value: 0,
      audio_path: "/audio/voice/c1/meas/pot_empty.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "capacity",
    },
    {
      id: "dim_capacity_less",
      label: "bình nước vơi",
      glyph: "🏺",
      value: 1,
      audio_path: "/audio/voice/c1/meas/pitcher_empty.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "capacity",
    },
    {
      id: "dim_capacity_half",
      label: "bình nước vừa",
      glyph: "🏺",
      value: 2,
      audio_path: "/audio/voice/c1/meas/pitcher_half.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "capacity",
    },
    {
      id: "dim_capacity_more",
      label: "bình nước đầy",
      glyph: "🏺",
      value: 3,
      audio_path: "/audio/voice/c1/meas/pitcher_full.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "capacity",
    },
    {
      id: "fill_unit_1",
      label: "mức 1",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "volume",
    },
    {
      id: "fill_unit_2",
      label: "mức 2",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "volume",
    },
    {
      id: "fill_unit_3",
      label: "mức 3",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "volume",
    },
    {
      id: "fill_unit_4",
      label: "mức 4",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "volume",
    },
    {
      id: "fill_unit_5",
      label: "mức 5",
      glyph: "5",
      value: 5,
      audio_path: "/audio/voice/common/numbers/5.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "volume",
    },
    {
      id: "fill_unit_6",
      label: "mức 6",
      glyph: "6",
      value: 6,
      audio_path: "/audio/voice/common/numbers/6.mp3",
      image: {
        kind: "emoji",
        ref: "🏺",
      },
      contrast_group: "volume",
    },
  ],
  relations: [
    {
      type: "contrast",
      source_id: "dim_capacity_more",
      target_id: "dim_capacity_less",
      metadata: {
        dimension: "capacity",
      },
    },
    {
      type: "sequence",
      source_id: "dim_capacity_empty_less",
      target_id: "dim_capacity_less",
    },
    {
      type: "sequence",
      source_id: "dim_capacity_less",
      target_id: "dim_capacity_half",
    },
    {
      type: "sequence",
      source_id: "dim_capacity_half",
      target_id: "dim_capacity_more",
    },
  ],
  axes: {
    capacity: {
      values: ["cạn", "vơi", "vừa", "đầy"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "number-rod",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "number-rod",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "number-rod",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "number-rod",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "number-rod",
    },
  ],
  phrasing: {
    prompt_template: "Vật nào có kích thước {label} hơn?",
    narration_template: "Chúng mình cùng tìm hiểu về Dung tích nhé",
  },
  ordering: [
    "dim_capacity_more",
    "dim_capacity_half",
    "dim_capacity_less",
    "dim_capacity_empty_less",
  ],
};

export const C1_MEAS_05_SEED: SkillSeed = {
  identity: C1_MEAS_05_IDENTITY,
  dataset: C1_MEAS_05_DATASET,
  levels: [
    {
      code: "GL-C1-LIQ-POUR-0001",
      template: "GT-032",
      band: "5-6",
      difficulty: 1,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-09",
    },
    {
      code: "GL-C1-LIQ-POUR-0002",
      template: "GT-032",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D5-09",
    },
    {
      code: "GL-C1-LIQ-POUR-0003",
      template: "GT-032",
      band: "5-6",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D5-09",
    },
    {
      code: "GL-C1-LIQ-POUR-0004",
      template: "GT-032",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D5-09",
    },
    {
      code: "GL-C1-LIQ-POUR-0005",
      template: "GT-032",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-09",
    },
    {
      code: "GL-C1-MEAS-CAP-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-CAP-0002",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0018",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0019",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0020",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0005",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0006",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0007",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0008",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0005",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0006",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0007",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0008",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0020",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0021",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0022",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0023",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SORT-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SORT-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SORT-0003",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
  ],
};
