import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_04_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.04",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Nhiều ít",
  age_min: 3,
  age_max: 3,
  difficulty: 1,
  thinking_processes: ["compare"],
  tier: "basic",
  prerequisites: ["C1.CMP.04", "C1.CMP.05"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.04-01",
      behaviour: "Nhận biết và thực hành Nhiều ít ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.04-02",
      behaviour: "Vận dụng Nhiều ít trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.04-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Nhiều ít",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_04_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.04",
  concept_label: "Nhiều ít",
  surface: "game",
  items: [
    {
      id: "dim_quantity_more",
      label: "nhiều bông hoa",
      value: 5,
      image: {
        kind: "emoji",
        ref: "🌸",
      },
      contrast_group: "quantity",
      category: {
        quantity: "nhiều",
      },
    },
    {
      id: "dim_quantity_less",
      label: "ít bông hoa",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🌸",
      },
      contrast_group: "quantity",
      category: {
        quantity: "ít",
      },
    },
    {
      id: "dim_quantity_apple_more",
      label: "nhiều quả táo",
      value: 5,
      image: {
        kind: "emoji",
        ref: "🍎",
      },
      contrast_group: "quantity",
      category: {
        quantity: "nhiều",
      },
    },
    {
      id: "dim_quantity_apple_less",
      label: "ít quả táo",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🍎",
      },
      contrast_group: "quantity",
      category: {
        quantity: "ít",
      },
    },
    {
      id: "dim_quantity_candy_more",
      label: "nhiều viên kẹo",
      value: 6,
      image: {
        kind: "emoji",
        ref: "🍬",
      },
      contrast_group: "quantity",
      category: {
        quantity: "nhiều",
      },
    },
    {
      id: "dim_quantity_candy_less",
      label: "ít viên kẹo",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🍬",
      },
      contrast_group: "quantity",
      category: {
        quantity: "ít",
      },
    },
    {
      id: "dim_quantity_star_more",
      label: "nhiều ngôi sao",
      value: 5,
      image: {
        kind: "emoji",
        ref: "⭐",
      },
      contrast_group: "quantity",
      category: {
        quantity: "nhiều",
      },
    },
    {
      id: "dim_quantity_star_less",
      label: "ít ngôi sao",
      value: 2,
      image: {
        kind: "emoji",
        ref: "⭐",
      },
      contrast_group: "quantity",
      category: {
        quantity: "ít",
      },
    },
  ],
  relations: [
    {
      type: "contrast",
      source_id: "dim_quantity_more",
      target_id: "dim_quantity_less",
      metadata: {
        dimension: "quantity",
      },
    },
    {
      type: "contrast",
      source_id: "dim_quantity_apple_more",
      target_id: "dim_quantity_apple_less",
      metadata: {
        dimension: "quantity",
      },
    },
    {
      type: "contrast",
      source_id: "dim_quantity_candy_more",
      target_id: "dim_quantity_candy_less",
      metadata: {
        dimension: "quantity",
      },
    },
    {
      type: "contrast",
      source_id: "dim_quantity_star_more",
      target_id: "dim_quantity_star_less",
      metadata: {
        dimension: "quantity",
      },
    },
  ],
  axes: {
    quantity: {
      values: ["ít", "nhiều"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với nhiều ít",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng nhiều ít",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt nhiều ít với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi nhiều ít",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục nhiều ít và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Bên nào nhiều hơn hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Nhiều ít nhé",
  },
};

export const C1_MEAS_04_SEED: SkillSeed = {
  identity: C1_MEAS_04_IDENTITY,
  dataset: C1_MEAS_04_DATASET,
  levels: [
    {
      code: "GL-C1-RUL-SLOT-0009",
      template: "GT-008",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-05",
    },
    {
      code: "GL-C1-RUL-SLOT-0010",
      template: "GT-008",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-05",
    },
    {
      code: "GL-C1-BAL-OBJ-0006",
      template: "GT-014",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0007",
      template: "GT-014",
      band: "5-6",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0008",
      template: "GT-014",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0009",
      template: "GT-014",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0010",
      template: "GT-014",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-MEAS-TAP-0013",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0014",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0015",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0016",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0017",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0015",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0016",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0017",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0018",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0019",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0015",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0016",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0017",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0018",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0019",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0011",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0012",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0013",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0014",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0015",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
