import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_02_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.02",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Cao thấp",
  age_min: 3,
  age_max: 3,
  difficulty: 1,
  thinking_processes: ["compare"],
  tier: "basic",
  prerequisites: ["C1.CMP.08", "C1.CMP.09"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.02-01",
      behaviour: "Nhận biết và thực hành Cao thấp ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.02-02",
      behaviour: "Vận dụng Cao thấp trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.02-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Cao thấp",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_02_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.02",
  concept_label: "Cao thấp",
  surface: "game",
  items: [
    {
      id: "dim_height_tree_more",
      label: "cây cổ thụ cao",
      glyph: "🌲",
      value: 4,
      image: {
        kind: "emoji",
        ref: "🌲",
      },
      contrast_group: "height",
    },
    {
      id: "dim_height_more",
      label: "hươu cao cổ cao",
      glyph: "🦒",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🦒",
      },
      contrast_group: "height",
    },
    {
      id: "dim_height_less",
      label: "chú cừu thấp",
      glyph: "🐑",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🐑",
      },
      contrast_group: "height",
    },
    {
      id: "dim_height_flower_less",
      label: "bụi hoa thấp",
      glyph: "🌼",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🌼",
      },
      contrast_group: "height",
    },
  ],
  relations: [
    {
      type: "contrast",
      source_id: "dim_height_tree_more",
      target_id: "dim_height_flower_less",
      metadata: {
        dimension: "height",
      },
    },
    {
      type: "contrast",
      source_id: "dim_height_more",
      target_id: "dim_height_less",
      metadata: {
        dimension: "height",
      },
    },
  ],
  axes: {
    height: {
      values: ["rất thấp", "thấp", "cao", "rất cao"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "number-rod",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "number-rod",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "number-rod",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "number-rod",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "number-rod",
    },
  ],
  phrasing: {
    prompt_template: "Vật nào có kích thước {label} hơn?",
    narration_template: "Chúng mình cùng tìm hiểu về Cao thấp nhé",
  },
};

export const C1_MEAS_02_SEED: SkillSeed = {
  identity: C1_MEAS_02_IDENTITY,
  dataset: C1_MEAS_02_DATASET,
  levels: [
    {
      code: "GL-C1-MSR-UNIT-0006",
      template: "GT-030",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D5-04",
    },
    {
      code: "GL-C1-MSR-UNIT-0007",
      template: "GT-030",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D5-04",
    },
    {
      code: "GL-C1-MSR-UNIT-0008",
      template: "GT-030",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D5-04",
    },
    {
      code: "GL-C1-MSR-UNIT-0009",
      template: "GT-030",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D5-04",
    },
    {
      code: "GL-C1-MSR-UNIT-0010",
      template: "GT-030",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D5-04",
    },
    {
      code: "GL-C1-MEAS-HGT-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-HGT-0002",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-SZO-ORD-0005",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-SZO-ORD-0006",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-SZO-ORD-0007",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-SZO-ORD-0008",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-RUL-SLOT-0005",
      template: "GT-008",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-05",
    },
    {
      code: "GL-C1-RUL-SLOT-0006",
      template: "GT-008",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D5-05",
    },
    {
      code: "GL-C1-MEAS-TAP-0005",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0006",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0007",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0008",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0006",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0007",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0008",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0009",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0010",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0006",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0007",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0008",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0009",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0010",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0006",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0007",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0008",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0009",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MEMO-0010",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
    },
  ],
};
