import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_15_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.15",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Sắp xếp trật tự kích thước",
  age_min: 4,
  age_max: 4,
  difficulty: 3,
  thinking_processes: ["sequence", "compare"],
  tier: "core",
  prerequisites: ["C1.MEAS.01"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.15-01",
      behaviour:
        "Nhận biết và thực hành Sắp xếp trật tự kích thước ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.15-02",
      behaviour:
        "Vận dụng Sắp xếp trật tự kích thước trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.15-03",
      behaviour:
        "Giải quyết vấn đề nâng cao liên quan tới Sắp xếp trật tự kích thước",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_15_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.15",
  concept_label: "Sắp xếp trật tự kích thước",
  surface: "game",
  items: [
    {
      id: "order_size_1",
      label: "quả bóng nhỏ nhất",
      glyph: "⚽",
      value: 1,
      image: {
        kind: "emoji",
        ref: "⚽",
      },
      contrast_group: "ordered_size",
      category: {
        size_order: "nhỏ nhất",
      },
    },
    {
      id: "order_size_2",
      label: "quả bóng nhỏ",
      glyph: "⚽",
      value: 2,
      image: {
        kind: "emoji",
        ref: "⚽",
      },
      contrast_group: "ordered_size",
      category: {
        size_order: "nhỏ",
      },
    },
    {
      id: "order_size_3",
      label: "quả bóng to",
      glyph: "⚽",
      value: 3,
      image: {
        kind: "emoji",
        ref: "⚽",
      },
      contrast_group: "ordered_size",
      category: {
        size_order: "to",
      },
    },
    {
      id: "order_size_4",
      label: "quả bóng to nhất",
      glyph: "⚽",
      value: 4,
      image: {
        kind: "emoji",
        ref: "⚽",
      },
      contrast_group: "ordered_size",
      category: {
        size_order: "to nhất",
      },
    },
  ],
  relations: [
    {
      type: "contrast",
      source_id: "order_size_4",
      target_id: "order_size_1",
      metadata: {
        dimension: "size_gradient",
      },
    },
    {
      type: "sequence",
      source_id: "order_size_1",
      target_id: "order_size_2",
    },
    {
      type: "sequence",
      source_id: "order_size_2",
      target_id: "order_size_3",
    },
    {
      type: "sequence",
      source_id: "order_size_3",
      target_id: "order_size_4",
    },
  ],
  axes: {
    size_order: {
      values: ["nhỏ nhất", "nhỏ", "to", "to nhất"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với sắp xếp trật tự kích thước",
      representation: "number-rod",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng sắp xếp trật tự kích thước",
      representation: "number-rod",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt sắp xếp trật tự kích thước với phương án nhiễu",
      representation: "number-rod",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi sắp xếp trật tự kích thước",
      representation: "number-rod",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục sắp xếp trật tự kích thước và tự làm một mình",
      representation: "number-rod",
    },
  ],
  phrasing: {
    prompt_template: "Bé xếp các vật từ nhỏ nhất đến to nhất nhé!",
    narration_template:
      "Chúng mình cùng tìm hiểu về Sắp xếp trật tự kích thước nhé",
  },
  ordering: ["order_size_1", "order_size_2", "order_size_3", "order_size_4"],
};

export const C1_MEAS_15_SEED: SkillSeed = {
  identity: C1_MEAS_15_IDENTITY,
  dataset: C1_MEAS_15_DATASET,
  levels: [
    {
      code: "GL-C1-COIN-CMP-0006",
      template: "GT-031",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0007",
      template: "GT-031",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0008",
      template: "GT-031",
      band: "5-6",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0009",
      template: "GT-031",
      band: "5-6",
      difficulty: 4,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0010",
      template: "GT-031",
      band: "5-6",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-CLK-TIM-0006",
      template: "GT-016",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0007",
      template: "GT-016",
      band: "5-6",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0008",
      template: "GT-016",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0009",
      template: "GT-016",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0010",
      template: "GT-016",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-MEAS-TAP-0045",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0046",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0047",
      template: "GT-001",
      band: "3-4",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0048",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0037",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0038",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0039",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0040",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0033",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0034",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0035",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0036",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0048",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0049",
      template: "GT-005",
      band: "3-4",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0050",
      template: "GT-005",
      band: "3-4",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0051",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0024",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0025",
      template: "GT-007",
      band: "3-4",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0026",
      template: "GT-007",
      band: "3-4",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0027",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
  ],
};
