import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_10_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.10",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Thời gian: trước/sau",
  age_min: 4,
  age_max: 4,
  difficulty: 2,
  thinking_processes: ["sequence"],
  tier: "basic",
  prerequisites: [],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.10-01",
      behaviour: "Nhận biết và thực hành Thời gian: trước/sau ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.10-02",
      behaviour: "Vận dụng Thời gian: trước/sau trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.10-03",
      behaviour:
        "Giải quyết vấn đề nâng cao liên quan tới Thời gian: trước/sau",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_10_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.10",
  concept_label: "Thời gian: trước/sau",
  surface: "game",
  items: [
    {
      id: "time_before",
      label: "trước khi rửa tay",
      glyph: "🧼",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🧼",
      },
      contrast_group: "time",
      category: {
        time_order: "trước",
      },
    },
    {
      id: "time_after",
      label: "sau khi ăn cơm",
      glyph: "🍚",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🍚",
      },
      contrast_group: "time",
      category: {
        time_order: "sau",
      },
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "time_before",
      target_id: "time_after",
    },
  ],
  axes: {
    time_order: {
      values: ["trước", "sau"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với thời gian: trước/sau",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng thời gian: trước/sau",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt thời gian: trước/sau với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi thời gian: trước/sau",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục thời gian: trước/sau và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Việc nào xảy ra trước hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Thời gian: trước/sau nhé",
  },
  ordering: ["time_before", "time_after"],
};

export const C1_MEAS_10_SEED: SkillSeed = {
  identity: C1_MEAS_10_IDENTITY,
  dataset: C1_MEAS_10_DATASET,
  levels: [
    {
      code: "GL-C1-VOL-TAP-0004",
      template: "GT-001",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D5-01",
    },
    {
      code: "GL-C1-VOL-TAP-0005",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-01",
    },
    {
      code: "GL-C1-VOL-TAP-0006",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D5-01",
    },
    {
      code: "GL-C1-MEAS-SLOT-0001",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SLOT-0002",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SLOT-0003",
      template: "GT-008",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SLOT-0004",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SLOT-0005",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MAZE-0001",
      template: "GT-013",
      band: "4-5",
      difficulty: 1,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MAZE-0002",
      template: "GT-013",
      band: "4-5",
      difficulty: 2,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MAZE-0003",
      template: "GT-013",
      band: "4-5",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MAZE-0004",
      template: "GT-013",
      band: "4-5",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MAZE-0005",
      template: "GT-013",
      band: "4-5",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-BOND-0001",
      template: "GT-018",
      band: "4-5",
      difficulty: 1,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-BOND-0002",
      template: "GT-018",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-BOND-0003",
      template: "GT-018",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-BOND-0004",
      template: "GT-018",
      band: "4-5",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-BOND-0005",
      template: "GT-018",
      band: "4-5",
      difficulty: 2,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MTRX-0001",
      template: "GT-023",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MTRX-0002",
      template: "GT-023",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MTRX-0003",
      template: "GT-023",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MTRX-0004",
      template: "GT-023",
      band: "4-5",
      difficulty: 1,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-MTRX-0005",
      template: "GT-023",
      band: "4-5",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
  ],
};
