import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_14_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.14",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Tiền xu đơn giản",
  age_min: 6,
  age_max: 6,
  difficulty: 4,
  thinking_processes: ["count", "compare"],
  tier: "advanced",
  prerequisites: ["C1.NREC.03", "C1.CNT.01"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.14-01",
      behaviour: "Nhận biết và thực hành Tiền xu đơn giản ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.14-02",
      behaviour: "Vận dụng Tiền xu đơn giản trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.14-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Tiền xu đơn giản",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_14_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.14",
  concept_label: "Tiền xu đơn giản",
  surface: "game",
  items: [
    {
      id: "coin_1",
      label: "đồng xu một nghìn",
      glyph: "🪙",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🪙",
      },
      contrast_group: "money",
    },
    {
      id: "coin_2",
      label: "đồng xu hai nghìn",
      glyph: "🪙",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🪙",
      },
      contrast_group: "money",
    },
    {
      id: "coin_5",
      label: "đồng xu năm nghìn",
      glyph: "🪙",
      value: 5,
      image: {
        kind: "emoji",
        ref: "🪙",
      },
      contrast_group: "money",
    },
    {
      id: "coin_10",
      label: "đồng xu mười nghìn",
      glyph: "🪙",
      value: 10,
      image: {
        kind: "emoji",
        ref: "🪙",
      },
      contrast_group: "money",
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "coin_1",
      target_id: "coin_2",
    },
    {
      type: "sequence",
      source_id: "coin_2",
      target_id: "coin_5",
    },
    {
      type: "sequence",
      source_id: "coin_5",
      target_id: "coin_10",
    },
    {
      type: "contrast",
      source_id: "coin_10",
      target_id: "coin_1",
      metadata: {
        dimension: "monetary_value",
      },
    },
  ],
  axes: {
    coin_value: {
      values: ["1k", "2k", "5k", "10k"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "number-rod",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "number-rod",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "number-rod",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "number-rod",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "number-rod",
    },
  ],
  phrasing: {
    prompt_template: "Vật nào có kích thước {label} hơn?",
    narration_template: "Chúng mình cùng tìm hiểu về Tiền xu đơn giản nhé",
  },
};

export const C1_MEAS_14_SEED: SkillSeed = {
  identity: C1_MEAS_14_IDENTITY,
  dataset: C1_MEAS_14_DATASET,
  levels: [
    {
      code: "GL-C1-COIN-CMP-0001",
      template: "GT-031",
      band: "5-6",
      difficulty: 1,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0002",
      template: "GT-031",
      band: "5-6",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0003",
      template: "GT-031",
      band: "5-6",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0004",
      template: "GT-031",
      band: "5-6",
      difficulty: 2,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-COIN-CMP-0005",
      template: "GT-031",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D5-10",
    },
    {
      code: "GL-C1-CLK-TIM-0001",
      template: "GT-016",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0002",
      template: "GT-016",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0003",
      template: "GT-016",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0004",
      template: "GT-016",
      band: "5-6",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-CLK-TIM-0005",
      template: "GT-016",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-08",
    },
    {
      code: "GL-C1-MEAS-TAP-0041",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0042",
      template: "GT-001",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0043",
      template: "GT-001",
      band: "5-6",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0044",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0033",
      template: "GT-002",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0034",
      template: "GT-002",
      band: "5-6",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0035",
      template: "GT-002",
      band: "5-6",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0036",
      template: "GT-002",
      band: "5-6",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0017",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0018",
      template: "GT-003",
      band: "5-6",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0019",
      template: "GT-003",
      band: "5-6",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0020",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0029",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0030",
      template: "GT-004",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0031",
      template: "GT-004",
      band: "5-6",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0032",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0044",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0045",
      template: "GT-005",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0046",
      template: "GT-005",
      band: "5-6",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0047",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
  ],
};
