import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_13_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.13",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Đồng hồ: giờ đúng",
  age_min: 6,
  age_max: 6,
  difficulty: 4,
  thinking_processes: ["observe", "match"],
  tier: "advanced",
  prerequisites: ["C1.NREC.03", "C1.MEAS.10"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.13-01",
      behaviour: "Nhận biết và thực hành Đồng hồ: giờ đúng ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.13-02",
      behaviour: "Vận dụng Đồng hồ: giờ đúng trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.13-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đồng hồ: giờ đúng",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_13_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.13",
  concept_label: "Đồng hồ: giờ đúng",
  surface: "game",
  items: [
    {
      id: "clock_1",
      label: "đồng hồ một giờ",
      glyph: "🕐",
      value: 1,
      audio_path: "/audio/voice/c1/meas/clock_1.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "clock",
    },
    {
      id: "num_clock_1",
      label: "số một",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
      contrast_group: "number",
    },
    {
      id: "clock_2",
      label: "đồng hồ hai giờ",
      glyph: "🕑",
      value: 2,
      audio_path: "/audio/voice/c1/meas/clock_2.mp3",
      image: {
        kind: "emoji",
        ref: "🕑",
      },
      contrast_group: "clock",
    },
    {
      id: "num_clock_2",
      label: "số hai",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
      contrast_group: "number",
    },
    {
      id: "clk_hour_1",
      label: "1 giờ",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_2",
      label: "2 giờ",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_3",
      label: "3 giờ",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_4",
      label: "4 giờ",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_5",
      label: "5 giờ",
      glyph: "5",
      value: 5,
      audio_path: "/audio/voice/common/numbers/5.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_6",
      label: "6 giờ",
      glyph: "6",
      value: 6,
      audio_path: "/audio/voice/common/numbers/6.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_7",
      label: "7 giờ",
      glyph: "7",
      value: 7,
      audio_path: "/audio/voice/common/numbers/7.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_8",
      label: "8 giờ",
      glyph: "8",
      value: 8,
      audio_path: "/audio/voice/common/numbers/8.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_9",
      label: "9 giờ",
      glyph: "9",
      value: 9,
      audio_path: "/audio/voice/common/numbers/9.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_10",
      label: "10 giờ",
      glyph: "10",
      value: 10,
      audio_path: "/audio/voice/common/numbers/10.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_11",
      label: "11 giờ",
      glyph: "11",
      value: 11,
      audio_path: "/audio/voice/common/numbers/11.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
    {
      id: "clk_hour_12",
      label: "12 giờ",
      glyph: "12",
      value: 12,
      audio_path: "/audio/voice/common/numbers/12.mp3",
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "time",
    },
  ],
  relations: [
    {
      type: "pair",
      source_id: "clock_1",
      target_id: "num_clock_1",
    },
    {
      type: "pair",
      source_id: "clock_2",
      target_id: "num_clock_2",
    },
  ],
  axes: {
    hour: {
      values: ["1 giờ", "2 giờ"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "number-rod",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "number-rod",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "number-rod",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "number-rod",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "number-rod",
    },
  ],
  phrasing: {
    prompt_template: "Vật nào có kích thước {label} hơn?",
    narration_template: "Chúng mình cùng tìm hiểu về Đồng hồ: giờ đúng nhé",
  },
};

export const C1_MEAS_13_SEED: SkillSeed = {
  identity: C1_MEAS_13_IDENTITY,
  dataset: C1_MEAS_13_DATASET,
  levels: [
    {
      code: "GL-C1-MEAS-CARD-0123",
      template: "GT-016",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      montessori_ref: "WB18-D1",
    },
    {
      code: "GL-C1-MEAS-CARD-0124",
      template: "GT-016",
      band: "5-6",
      difficulty: 4,
      theme: "home",
      rounds: 3,
      montessori_ref: "WB18-D1",
    },
    {
      code: "GL-C1-MEAS-CLK-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-CLK-0002",
      template: "GT-001",
      band: "5-6",
      difficulty: 2,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-SZO-ORD-0009",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-SZO-ORD-0010",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-MEAS-TAP-0038",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0039",
      template: "GT-001",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0040",
      template: "GT-001",
      band: "5-6",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0029",
      template: "GT-002",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0030",
      template: "GT-002",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0031",
      template: "GT-002",
      band: "5-6",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0032",
      template: "GT-002",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0013",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0014",
      template: "GT-003",
      band: "5-6",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0015",
      template: "GT-003",
      band: "5-6",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0016",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0025",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0026",
      template: "GT-004",
      band: "5-6",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0027",
      template: "GT-004",
      band: "5-6",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0028",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0040",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0041",
      template: "GT-005",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0042",
      template: "GT-005",
      band: "5-6",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0043",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-CLK-0003",
      template: "GT-016",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D1-08",
    },
  ],
};
