import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_08_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.08",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Đo bằng đơn vị phi chuẩn",
  age_min: 5,
  age_max: 5,
  difficulty: 3,
  thinking_processes: ["count", "compare"],
  tier: "core",
  prerequisites: ["C1.MEAS.01", "C1.CNT.01"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.08-01",
      behaviour: "Nhận biết và thực hành Đo bằng đơn vị phi chuẩn ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.08-02",
      behaviour: "Vận dụng Đo bằng đơn vị phi chuẩn trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.08-03",
      behaviour:
        "Giải quyết vấn đề nâng cao liên quan tới Đo bằng đơn vị phi chuẩn",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_08_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.08",
  concept_label: "Đo bằng đơn vị phi chuẩn",
  surface: "game",
  items: [
    {
      id: "unit_2",
      label: "dài hai gang tay",
      glyph: "🖐️",
      value: 2,
      audio_path: "/audio/voice/c1/meas/span_2.mp3",
      image: {
        kind: "emoji",
        ref: "🖐️",
      },
      contrast_group: "span",
    },
    {
      id: "unit_3",
      label: "dài ba gang tay",
      glyph: "🖐️",
      value: 3,
      audio_path: "/audio/voice/c1/meas/span_3.mp3",
      image: {
        kind: "emoji",
        ref: "🖐️",
      },
      contrast_group: "span",
    },
    {
      id: "unit_4",
      label: "dài bốn gang tay",
      glyph: "🖐️",
      value: 4,
      audio_path: "/audio/voice/c1/meas/span_4.mp3",
      image: {
        kind: "emoji",
        ref: "🖐️",
      },
      contrast_group: "span",
    },
    {
      id: "unit_5",
      label: "dài năm gang tay",
      glyph: "🖐️",
      value: 5,
      audio_path: "/audio/voice/c1/meas/span_5.mp3",
      image: {
        kind: "emoji",
        ref: "🖐️",
      },
      contrast_group: "span",
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "unit_2",
      target_id: "unit_3",
    },
    {
      type: "sequence",
      source_id: "unit_3",
      target_id: "unit_4",
    },
    {
      type: "sequence",
      source_id: "unit_4",
      target_id: "unit_5",
    },
    {
      type: "contrast",
      source_id: "unit_5",
      target_id: "unit_2",
      metadata: {
        dimension: "length_spans",
      },
    },
  ],
  axes: {
    measure: {
      values: ["2", "3", "4", "5"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "number-rod",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "number-rod",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "number-rod",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "number-rod",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "number-rod",
    },
  ],
  phrasing: {
    prompt_template: "Vật nào có kích thước {label} hơn?",
    narration_template:
      "Chúng mình cùng tìm hiểu về Đo bằng đơn vị phi chuẩn nhé",
  },
};

export const C1_MEAS_08_SEED: SkillSeed = {
  identity: C1_MEAS_08_IDENTITY,
  dataset: C1_MEAS_08_DATASET,
  levels: [
    {
      code: "GL-C1-HGT-TAP-0005",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-02",
    },
    {
      code: "GL-C1-MEAS-TAP-0027",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0028",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0029",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0017",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0018",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0019",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0020",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0001",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0002",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0003",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0004",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0017",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0018",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0019",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0020",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0032",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0033",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0034",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0035",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-UNIT-0001",
      template: "GT-030",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-04",
    },
    {
      code: "GL-C1-MEAS-UNIT-0002",
      template: "GT-030",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-04",
    },
    {
      code: "GL-C1-MEAS-UNIT-0003",
      template: "GT-030",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-04",
    },
    {
      code: "GL-C1-MEAS-UNIT-0004",
      template: "GT-030",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D1-04",
    },
    {
      code: "GL-C1-MEAS-BAL-0001",
      template: "GT-014",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-03",
    },
    {
      code: "GL-C1-MEAS-BAL-0002",
      template: "GT-014",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-03",
    },
  ],
};
