import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_MEAS_13_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.13",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Đồng hồ: giờ đúng",
  age_min: 6,
  age_max: 6,
  difficulty: 4,
  thinking_processes: ["observe", "match"],
  tier: "advanced",
  prerequisites: ["C1.NREC.03", "C1.MEAS.10"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.13-01",
      behaviour: "Nhận biết và thực hành Đồng hồ: giờ đúng ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.13-02",
      behaviour: "Vận dụng Đồng hồ: giờ đúng trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.13-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đồng hồ: giờ đúng",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_13_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.13",
  concept_label: "Đồng hồ: giờ đúng",
  surface: "game",
  items: [
    {
      id: "clock_1",
      label: "đồng hồ chỉ một giờ",
      glyph: "🕐",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🕐",
      },
      contrast_group: "clock",
      category: {
        hour: "1 giờ",
      },
    },
    {
      id: "clock_2",
      label: "đồng hồ chỉ hai giờ",
      glyph: "🕑",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🕑",
      },
      contrast_group: "clock",
      category: {
        hour: "2 giờ",
      },
    },
    {
      id: "clock_3",
      label: "đồng hồ chỉ ba giờ",
      glyph: "🕒",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🕒",
      },
      contrast_group: "clock",
      category: {
        hour: "3 giờ",
      },
    },
    {
      id: "clock_4",
      label: "đồng hồ chỉ bốn giờ",
      glyph: "🕓",
      value: 4,
      image: {
        kind: "emoji",
        ref: "🕓",
      },
      contrast_group: "clock",
      category: {
        hour: "4 giờ",
      },
    },
    {
      id: "clock_5",
      label: "đồng hồ chỉ năm giờ",
      glyph: "🕔",
      value: 5,
      image: {
        kind: "emoji",
        ref: "🕔",
      },
      contrast_group: "clock",
      category: {
        hour: "5 giờ",
      },
    },
    {
      id: "clock_6",
      label: "đồng hồ chỉ sáu giờ",
      glyph: "🕕",
      value: 6,
      image: {
        kind: "emoji",
        ref: "🕕",
      },
      contrast_group: "clock",
      category: {
        hour: "6 giờ",
      },
    },
    {
      id: "clock_7",
      label: "đồng hồ chỉ bảy giờ",
      glyph: "🕖",
      value: 7,
      image: {
        kind: "emoji",
        ref: "🕖",
      },
      contrast_group: "clock",
      category: {
        hour: "7 giờ",
      },
    },
    {
      id: "clock_8",
      label: "đồng hồ chỉ tám giờ",
      glyph: "🕗",
      value: 8,
      image: {
        kind: "emoji",
        ref: "🕗",
      },
      contrast_group: "clock",
      category: {
        hour: "8 giờ",
      },
    },
    {
      id: "clock_9",
      label: "đồng hồ chỉ chín giờ",
      glyph: "🕘",
      value: 9,
      image: {
        kind: "emoji",
        ref: "🕘",
      },
      contrast_group: "clock",
      category: {
        hour: "9 giờ",
      },
    },
    {
      id: "clock_10",
      label: "đồng hồ chỉ mười giờ",
      glyph: "🕙",
      value: 10,
      image: {
        kind: "emoji",
        ref: "🕙",
      },
      contrast_group: "clock",
      category: {
        hour: "10 giờ",
      },
    },
    {
      id: "clock_11",
      label: "đồng hồ chỉ mười một giờ",
      glyph: "🕚",
      value: 11,
      image: {
        kind: "emoji",
        ref: "🕚",
      },
      contrast_group: "clock",
      category: {
        hour: "11 giờ",
      },
    },
    {
      id: "clock_12",
      label: "đồng hồ chỉ mười hai giờ",
      glyph: "🕛",
      value: 12,
      image: {
        kind: "emoji",
        ref: "🕛",
      },
      contrast_group: "clock",
      category: {
        hour: "12 giờ",
      },
    },
    {
      id: "clk_hour_1",
      label: "1 giờ",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      contrast_group: "time",
      category: {
        hour: "1 giờ",
      },
    },
    {
      id: "clk_hour_2",
      label: "2 giờ",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      contrast_group: "time",
      category: {
        hour: "2 giờ",
      },
    },
    {
      id: "clk_hour_3",
      label: "3 giờ",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      contrast_group: "time",
      category: {
        hour: "3 giờ",
      },
    },
    {
      id: "clk_hour_4",
      label: "4 giờ",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      contrast_group: "time",
      category: {
        hour: "4 giờ",
      },
    },
    {
      id: "clk_hour_5",
      label: "5 giờ",
      glyph: "5",
      value: 5,
      audio_path: "/audio/voice/common/numbers/5.mp3",
      contrast_group: "time",
      category: {
        hour: "5 giờ",
      },
    },
    {
      id: "clk_hour_6",
      label: "6 giờ",
      glyph: "6",
      value: 6,
      audio_path: "/audio/voice/common/numbers/6.mp3",
      contrast_group: "time",
      category: {
        hour: "6 giờ",
      },
    },
    {
      id: "clk_hour_7",
      label: "7 giờ",
      glyph: "7",
      value: 7,
      audio_path: "/audio/voice/common/numbers/7.mp3",
      contrast_group: "time",
      category: {
        hour: "7 giờ",
      },
    },
    {
      id: "clk_hour_8",
      label: "8 giờ",
      glyph: "8",
      value: 8,
      audio_path: "/audio/voice/common/numbers/8.mp3",
      contrast_group: "time",
      category: {
        hour: "8 giờ",
      },
    },
    {
      id: "clk_hour_9",
      label: "9 giờ",
      glyph: "9",
      value: 9,
      audio_path: "/audio/voice/common/numbers/9.mp3",
      contrast_group: "time",
      category: {
        hour: "9 giờ",
      },
    },
    {
      id: "clk_hour_10",
      label: "10 giờ",
      glyph: "10",
      value: 10,
      audio_path: "/audio/voice/common/numbers/10.mp3",
      contrast_group: "time",
      category: {
        hour: "10 giờ",
      },
    },
    {
      id: "clk_hour_11",
      label: "11 giờ",
      glyph: "11",
      value: 11,
      audio_path: "/audio/voice/common/numbers/11.mp3",
      contrast_group: "time",
      category: {
        hour: "11 giờ",
      },
    },
    {
      id: "clk_hour_12",
      label: "12 giờ",
      glyph: "12",
      value: 12,
      audio_path: "/audio/voice/common/numbers/12.mp3",
      contrast_group: "time",
      category: {
        hour: "12 giờ",
      },
    },
  ],
  relations: [
    {
      type: "pair",
      source_id: "clock_1",
      target_id: "clk_hour_1",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_2",
      target_id: "clk_hour_2",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_3",
      target_id: "clk_hour_3",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_4",
      target_id: "clk_hour_4",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_5",
      target_id: "clk_hour_5",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_6",
      target_id: "clk_hour_6",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_7",
      target_id: "clk_hour_7",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_8",
      target_id: "clk_hour_8",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_9",
      target_id: "clk_hour_9",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_10",
      target_id: "clk_hour_10",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_11",
      target_id: "clk_hour_11",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
    {
      type: "pair",
      source_id: "clock_12",
      target_id: "clk_hour_12",
      metadata: {
        relation: "clock_face_to_hour",
      },
    },
  ],
  axes: {
    hour: {
      values: [
        "1 giờ",
        "2 giờ",
        "3 giờ",
        "4 giờ",
        "5 giờ",
        "6 giờ",
        "7 giờ",
        "8 giờ",
        "9 giờ",
        "10 giờ",
        "11 giờ",
        "12 giờ",
      ],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với đồng hồ: giờ đúng",
      representation: "number-rod",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng đồng hồ: giờ đúng",
      representation: "number-rod",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt đồng hồ: giờ đúng với phương án nhiễu",
      representation: "number-rod",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi đồng hồ: giờ đúng",
      representation: "number-rod",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục đồng hồ: giờ đúng và tự làm một mình",
      representation: "number-rod",
    },
  ],
  phrasing: {
    prompt_template: "Đồng hồ đang chỉ mấy giờ hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Đồng hồ: giờ đúng nhé",
  },
};

export const C1_MEAS_13_SEED: SkillSeed = {
  identity: C1_MEAS_13_IDENTITY,
  dataset: C1_MEAS_13_DATASET,
  levels: [
    {
      code: "GL-C1-MEAS-CARD-0123",
      template: "GT-016",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      montessori_ref: "WB18-D1",
    },
    {
      code: "GL-C1-MEAS-CARD-0124",
      template: "GT-016",
      band: "5-6",
      difficulty: 4,
      theme: "home",
      rounds: 3,
      montessori_ref: "WB18-D1",
    },
    {
      code: "GL-C1-MEAS-CLK-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-CLK-0002",
      template: "GT-001",
      band: "5-6",
      difficulty: 2,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-SZO-ORD-0009",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-SZO-ORD-0010",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-06",
    },
    {
      code: "GL-C1-MEAS-TAP-0038",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0039",
      template: "GT-001",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0040",
      template: "GT-001",
      band: "5-6",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0029",
      template: "GT-002",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0030",
      template: "GT-002",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0031",
      template: "GT-002",
      band: "5-6",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0032",
      template: "GT-002",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0013",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0014",
      template: "GT-003",
      band: "5-6",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0015",
      template: "GT-003",
      band: "5-6",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCMP-0016",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0025",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0026",
      template: "GT-004",
      band: "5-6",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0027",
      template: "GT-004",
      band: "5-6",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0028",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0040",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0041",
      template: "GT-005",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0042",
      template: "GT-005",
      band: "5-6",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0043",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-CLK-0003",
      template: "GT-016",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D1-08",
    },
  ],
};
