import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";
import { getMeasureDimension } from "#src/inventories/index";

export const C1_MEAS_03_IDENTITY: SkillIdentity = {
  code: "C1.MEAS.03",
  strand_code: "C1.MEAS",
  competency_code: "C1",
  name: "Nặng nhẹ",
  age_min: 4,
  age_max: 4,
  difficulty: 2,
  thinking_processes: ["compare"],
  tier: "basic",
  prerequisites: ["C1.CMP.10", "C1.CMP.11"],
  learning_objectives: [
    {
      code: "LO-C1.MEAS.03-01",
      behaviour: "Nhận biết và thực hành Nặng nhẹ ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.MEAS.03-02",
      behaviour: "Vận dụng Nặng nhẹ trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.MEAS.03-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Nặng nhẹ",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_MEAS_03_DATASET: SkillDataset = {
  skill_code: "C1.MEAS.03",
  concept_label: "Nặng nhẹ",
  surface: "game",
  items: [
    {
      id: "dim_weight_rock_more",
      label: "tảng đá nặng",
      value: 4,
      image: {
        kind: "emoji",
        ref: "🪨",
      },
      contrast_group: "weight",
      category: {
        weight: "rất nặng",
      },
    },
    {
      id: "dim_weight_more",
      label: "con voi nặng",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🐘",
      },
      contrast_group: "weight",
      category: {
        weight: "nặng",
      },
    },
    {
      id: "dim_weight_less",
      label: "chú kiến nhẹ",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🐜",
      },
      contrast_group: "weight",
      category: {
        weight: "nhẹ",
      },
    },
    {
      id: "dim_weight_leaf_less",
      label: "chiếc lá nhẹ",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🍃",
      },
      contrast_group: "weight",
      category: {
        weight: "rất nhẹ",
      },
    },
  ],
  relations: [
    {
      type: "contrast",
      source_id: "dim_weight_rock_more",
      target_id: "dim_weight_leaf_less",
      metadata: {
        dimension: getMeasureDimension("dim_weight").unit_kind,
      },
    },
    {
      type: "contrast",
      source_id: "dim_weight_more",
      target_id: "dim_weight_less",
      metadata: {
        dimension: getMeasureDimension("dim_weight").unit_kind,
      },
    },
  ],
  axes: {
    weight: {
      values: ["rất nhẹ", "nhẹ", "nặng", "rất nặng"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với nặng nhẹ",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng nặng nhẹ",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt nặng nhẹ với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi nặng nhẹ",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục nặng nhẹ và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Vật nào nặng hơn hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Nặng nhẹ nhé",
  },
};

export const C1_MEAS_03_SEED: SkillSeed = {
  identity: C1_MEAS_03_IDENTITY,
  dataset: C1_MEAS_03_DATASET,
  levels: [
    {
      code: "GL-C1-RUL-SLOT-0007",
      template: "GT-008",
      band: "4-5",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D5-05",
    },
    {
      code: "GL-C1-RUL-SLOT-0008",
      template: "GT-008",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D5-05",
    },
    {
      code: "GL-C1-BAL-OBJ-0001",
      template: "GT-014",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0002",
      template: "GT-014",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0003",
      template: "GT-014",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0004",
      template: "GT-014",
      band: "5-6",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-BAL-OBJ-0005",
      template: "GT-014",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-03",
    },
    {
      code: "GL-C1-MEAS-TAP-0009",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0010",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0011",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TAP-0012",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0001",
      template: "GT-002",
      band: "4-5",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0002",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0003",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-TCNT-0004",
      template: "GT-002",
      band: "4-5",
      difficulty: 1,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0001",
      template: "GT-004",
      band: "4-5",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0002",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0003",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PAIR-0004",
      template: "GT-004",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0011",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0012",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0013",
      template: "GT-005",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-PATT-0014",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0011",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0012",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0013",
      template: "GT-007",
      band: "3-4",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-MEAS-SHAD-0014",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
  ],
};
