export const ALLOWED_EVENT_NAMES = new Set<string>([
  "game_started",
  "instructionewed",
  "game_paused",
  "game_resumed",
  "game_completed",
  "game_abandoned",
  "intro_period_started",
  "intro_item_presented",
  "intro_item_deferred",
  "intro_recall_answered",
  "tts_unavailable",
  "round_started",
  "question_shown",
  "answer_selected",
  "answer_correct",
  "answer_incorrect",
  "round_completed",
  "round_retried",
  "round_skipped",
  "hint_requested",
  "scaffold_escalated",
  "scaffold_resolved",
  "demo_shown",
  "asset_load_failed",
  "fps_sample",
  "parent_gate_shown",
  "parent_gate_passed",
  "parent_gate_failed",
  // Tương tác trong khuôn — catalog §7.2
  "item_selected",
  "selection_submitted",
  "item_dragged",
  "item_dropped",
  "item_sorted",
  "item_placed",
  "pair_selected",
  "pair_matched",
  "step_reordered",
  "sequence_submitted",
  "bond_selected",
  "part_filled",
  "clue_revealed",
  "candidate_eliminated",
  "option_previewed",
  "option_selected",
  "path_step",
  "path_blocked",
  "path_submitted",
  "equation_solved",
  "value_selected",
  "flash_shown",
  "flash_hidden",
  "flash_replayed",
  "balance_changed",
  "cell_filled",
  "constraint_violated",
  "hand_rotated",
  "time_submitted",
  "model_rotated",
  "item_revealed",
  "checkpoint_reached",
  "trace_completed",
  "item_tapped",
  "count_undone",
  "count_submitted",
  "item_removed",
  "item_restored",
  "unit_placed",
  "unit_removed",
  "coin_placed",
  "coin_removed",
  "cup_selected",
  "liquid_poured",
  "yarn_placed",
  "yarn_removed",
  "pattern_played",
  "beat_tapped",
  "command_added",
  "command_removed",
  "program_run",
  "program_failed",
  "element_placed",
  "element_removed",
  "creation_submitted",
  "rule_detected",
]);

export const PII_FIELDS = new Set<string>([
  "display_name",
  "birth_year",
  "user_id",
  "email",
  "ip",
  "score",
]);

export const EVENT_PAYLOAD_FIELDS: Readonly<
  Record<string, ReadonlySet<string>>
> = {
  game_started: new Set([
    "template_code",
    "difficulty",
    "age_band",
    "device",
    "reduced_motion",
    "round_index",
  ]),
  instructionewed: new Set(["modality", "replay_count"]),
  game_paused: new Set(["reason"]),
  game_resumed: new Set(["paused_ms"]),
  game_completed: new Set(["duration_ms", "rounds_total", "rounds_correct"]),
  game_abandoned: new Set(["duration_ms", "last_round_index", "reason"]),
  intro_period_started: new Set(["period", "step_index"]),
  intro_item_presented: new Set(["item_id", "period", "tts_used"]),
  intro_item_deferred: new Set(["item_id", "miss_count"]),
  intro_recall_answered: new Set(["item_id", "answer_correct"]),
  tts_unavailable: new Set(["prompt_id", "reason"]),
  round_started: new Set(["round_index", "item_count", "distractor_count"]),
  question_shown: new Set(["round_index", "prompt_kind"]),
  answer_selected: new Set([
    "round_index",
    "attempt_index",
    "target_slot",
    "elapsed_ms",
    "option_id",
    "value",
    "is_correct",
  ]),
  answer_correct: new Set(["round_index", "attempt_index", "elapsed_ms"]),
  answer_incorrect: new Set([
    "round_index",
    "attempt_index",
    "elapsed_ms",
    "error_kind",
  ]),
  round_completed: new Set([
    "round_index",
    "attempts",
    "hints_used",
    "duration_ms",
  ]),
  round_retried: new Set(["round_index", "retry_index"]),
  round_skipped: new Set(["round_index", "reason"]),
  hint_requested: new Set(["round_index", "source"]),
  scaffold_escalated: new Set([
    "round_index",
    "level",
    "trigger",
    "elapsed_ms",
  ]),
  scaffold_resolved: new Set(["round_index", "level", "trigger", "elapsed_ms"]),
  demo_shown: new Set(["round_index", "speed"]),
  asset_load_failed: new Set(["asset_kind", "asset_ref", "retry_count"]),
  fps_sample: new Set(["p50", "p95", "min", "sample_count"]),
  parent_gate_shown: new Set(["trigger"]),
  parent_gate_passed: new Set(["attempts"]),
  parent_gate_failed: new Set(["attempts"]),
  item_selected: new Set(["item_id", "is_correct", "round_index"]),
  selection_submitted: new Set(["is_correct", "round_index"]),
  item_dragged: new Set(["item_id", "round_index"]),
  item_dropped: new Set([
    "item_id",
    "container_id",
    "is_correct",
    "round_index",
  ]),
  item_sorted: new Set(["item_id", "group_id", "is_correct", "round_index"]),
  item_placed: new Set(["item_id", "slot_id", "is_correct", "round_index"]),
  pair_selected: new Set(["item_id", "round_index"]),
  pair_matched: new Set([
    "pair_id",
    "left_item_id",
    "right_item_id",
    "round_index",
  ]),
  step_reordered: new Set([
    "from_index",
    "to_index",
    "current_sequence",
    "round_index",
  ]),
  sequence_submitted: new Set(["is_correct", "round_index"]),
  bond_selected: new Set(["option_id", "part_id", "is_correct", "round_index"]),
  part_filled: new Set(["part_id", "value", "round_index"]),
  clue_revealed: new Set([
    "clue_id",
    "revealed_count",
    "remaining_count",
    "round_index",
  ]),
  candidate_eliminated: new Set(["candidate_id", "clue_id", "round_index"]),
  option_previewed: new Set([
    "option_id",
    "row_matches",
    "col_matches",
    "round_index",
  ]),
  option_selected: new Set(["option_id", "is_correct", "round_index"]),
  path_step: new Set(["row", "col", "step_index", "round_index"]),
  path_blocked: new Set(["row", "col", "reason", "retreated", "round_index"]),
  path_submitted: new Set(["is_correct", "step_count", "round_index"]),
  equation_solved: new Set(["symbol_id", "value", "round_index"]),
  value_selected: new Set(["value", "is_correct", "round_index"]),
  flash_shown: new Set(["duration_ms", "round_index"]),
  flash_hidden: new Set(["elapsed_ms", "round_index"]),
  flash_replayed: new Set(["round_index"]),
  balance_changed: new Set(["tilt_angle", "state", "round_index"]),
  cell_filled: new Set(["row", "col", "symbol_id", "is_valid", "round_index"]),
  constraint_violated: new Set(["row", "col", "symbol_id", "round_index"]),
  hand_rotated: new Set(["hand", "time", "round_index"]),
  time_submitted: new Set(["time", "card_id", "is_correct", "round_index"]),
  model_rotated: new Set(["angle", "hidden_cubes_remaining", "round_index"]),
  item_revealed: new Set(["item_id", "round_index"]),
  checkpoint_reached: new Set([
    "waypoint_id",
    "checkpoint_index",
    "total_waypoints",
    "round_index",
  ]),
  trace_completed: new Set(["shape_name", "round_index"]),
  item_tapped: new Set(["item_id", "current_total", "step", "round_index"]),
  count_undone: new Set(["item_id", "current_total", "step", "round_index"]),
  count_submitted: new Set([
    "submitted_total",
    "target_total",
    "is_correct",
    "round_index",
  ]),
  item_removed: new Set([
    "item_id",
    "removed_count",
    "target_remove_count",
    "round_index",
  ]),
  item_restored: new Set([
    "item_id",
    "removed_count",
    "remaining_needed",
    "round_index",
  ]),
  unit_placed: new Set([
    "slot_index",
    "placed_count",
    "target_count",
    "round_index",
  ]),
  unit_removed: new Set(["slot_index", "placed_count", "round_index"]),
  coin_placed: new Set([
    "coin_id",
    "value",
    "current_total",
    "target_amount",
    "round_index",
  ]),
  coin_removed: new Set([
    "coin_id",
    "value",
    "current_total",
    "target_amount",
    "round_index",
  ]),
  cup_selected: new Set(["cup_id", "fill_units", "is_correct", "round_index"]),
  liquid_poured: new Set([
    "cup_id",
    "fill_units",
    "target_units",
    "round_index",
  ]),
  yarn_placed: new Set([
    "cell_index",
    "color_id",
    "is_correct",
    "row",
    "col",
    "round_index",
  ]),
  yarn_removed: new Set([
    "cell_index",
    "color_id",
    "row",
    "col",
    "round_index",
  ]),
  pattern_played: new Set([
    "tempo_bpm",
    "pattern_length",
    "is_replay",
    "round_index",
  ]),
  beat_tapped: new Set([
    "instrument_id",
    "step_index",
    "is_correct",
    "round_index",
  ]),
  command_added: new Set(["command", "command_index", "round_index"]),
  command_removed: new Set(["command", "command_index", "round_index"]),
  program_run: new Set(["command_count", "round_index"]),
  program_failed: new Set(["failed_step", "reason", "round_index"]),
  element_placed: new Set(["slot_index", "element_id", "round_index"]),
  element_removed: new Set(["slot_index", "removed_id", "round_index"]),
  creation_submitted: new Set(["placed_items", "round_index"]),
  rule_detected: new Set([
    "detected",
    "motif",
    "repetitions",
    "score",
    "is_win",
    "round_index",
  ]),
};
