import type { ContentSeed } from "#src/seed-content/types";
import { SEED_MONT_A01 } from "./seed-mont-a01.js";
import { SEED_MONT_A02 } from "./seed-mont-a02.js";
import { SEED_MONT_A05 } from "./seed-mont-a05.js";
import { SEED_MONT_A06 } from "./seed-mont-a06.js";
import { SEED_MONT_A07 } from "./seed-mont-a07.js";
import { SEED_MONT_A08 } from "./seed-mont-a08.js";
import { SEED_MONT_A11 } from "./seed-mont-a11.js";
import { SEED_MONT_A13 } from "./seed-mont-a13.js";
import { SEED_MONT_A15 } from "./seed-mont-a15.js";
import { SEED_MONT_A18 } from "./seed-mont-a18.js";
import { SEED_MONT_B02 } from "./seed-mont-b02.js";
import { SEED_MONT_B11 } from "./seed-mont-b11.js";
import { SEED_MONT_B15 } from "./seed-mont-b15.js";

export const C1_BASE_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C1-CNT-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title: "Đếm số táo đỏ",
      instruction: "Em hãy đếm xem có mấy quả táo nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "a1", emoji: "🍎" },
        { id: "a2", emoji: "🍎" },
        { id: "a3", emoji: "🍎" },
      ],
      target_count: 3,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title: "Đếm chuối vàng",
      instruction: "Em đếm xem có bao nhiêu quả chuối.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "b1", emoji: "🍌" },
        { id: "b2", emoji: "🍌" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0003",
      content_version: 1,
      template_code: "GT-001",
      title: "Đếm cam mọng nước",
      instruction: "Cùng đếm số quả cam nào em nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "o1", emoji: "🍊" },
        { id: "o2", emoji: "🍊" },
        { id: "o3", emoji: "🍊" },
        { id: "o4", emoji: "🍊" },
      ],
      target_count: 4,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0004",
      content_version: 1,
      template_code: "GT-001",
      title: "Đếm dưa hấu",
      instruction: "Hãy đếm số miếng dưa hấu tươi mát.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.02"],
      learning_objective_codes: ["LO-C1.CNT.02-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "w1", emoji: "🍉" },
        { id: "w2", emoji: "🍉" },
        { id: "w3", emoji: "🍉" },
        { id: "w4", emoji: "🍉" },
        { id: "w5", emoji: "🍉" },
      ],
      target_count: 5,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0005",
      content_version: 1,
      template_code: "GT-001",
      title: "Đếm chùm nho ngọt",
      instruction: "Em đếm xem có mấy chùm nho.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "g1", emoji: "🍇" },
        { id: "g2", emoji: "🍇" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C1-SORT-BOX-0006",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại quả đỏ và quả vàng",
      instruction: "Bỏ quả đỏ vào giỏ đỏ em nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sort"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "red_basket", label: "Giỏ đỏ", target_color: "red" }],
      drag_items: [
        { id: "a1", emoji: "🍎", color: "red" },
        { id: "b1", emoji: "🍌", color: "yellow" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C1-SORT-BOX-0007",
      content_version: 1,
      template_code: "GT-002",
      title: "Thu hoạch dâu tây",
      instruction: "Em kéo dâu tây vào hộp nhựa.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sort"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "strawberry_box", label: "Hộp dâu", target_type: "strawberry" },
      ],
      drag_items: [
        { id: "s1", emoji: "🍓", type: "strawberry" },
        { id: "c1", emoji: "🥕", type: "carrot" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C1-SORT-BOX-0008",
      content_version: 1,
      template_code: "GT-002",
      title: "Xếp dứa chín",
      instruction: "Hãy xếp quả dứa vào giỏ cây.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sort"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "pineapple_basket", label: "Giỏ dứa", target_type: "pineapple" },
      ],
      drag_items: [
        { id: "p1", emoji: "🍍", type: "pineapple" },
        { id: "p2", emoji: "🍍", type: "pineapple" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C1-SORT-BOX-0009",
      content_version: 1,
      template_code: "GT-002",
      title: "Thu gom cà rốt",
      instruction: "Hãy kéo cà rốt vào túi thỏ.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sort"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "carrot_bag", label: "Túi cà rốt", target_type: "carrot" },
      ],
      drag_items: [
        { id: "c1", emoji: "🥕", type: "carrot" },
        { id: "c2", emoji: "🥕", type: "carrot" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C1-CMP-NUM-0010",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh đĩa trái cây",
      instruction: "Chọn bên có nhiều trái cây hơn.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["compare"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🍎" }, { emoji: "🍎" }, { emoji: "🍎" }],
      right_group: [{ emoji: "🍎" }],
      target: "more",
    },
    difficulty_params: { max_difference: 2 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C1-CMP-NUM-0011",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh số kẹo",
      instruction: "Chọn bên có ít kẹo hơn nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["compare"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🍬" }],
      right_group: [
        { emoji: "🍬" },
        { emoji: "🍬" },
        { emoji: "🍬" },
        { emoji: "🍬" },
      ],
      target: "less",
    },
    difficulty_params: { max_difference: 3 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C1-CMP-NUM-0012",
      content_version: 1,
      template_code: "GT-003",
      title: "Bên nào nhiều bóng hơn",
      instruction: "Chọn nhóm bóng nhiều hơn em nha.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [
        { emoji: "⚽" },
        { emoji: "⚽" },
        { emoji: "⚽" },
        { emoji: "⚽" },
      ],
      right_group: [{ emoji: "⚽" }, { emoji: "⚽" }],
      target: "more",
    },
    difficulty_params: { max_difference: 2 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C1-CMP-NUM-0013",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh bánh ngọt",
      instruction: "Chọn nhóm bánh ít hơn.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["compare"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🧁" }, { emoji: "🧁" }],
      right_group: [
        { emoji: "🧁" },
        { emoji: "🧁" },
        { emoji: "🧁" },
        { emoji: "🧁" },
        { emoji: "🧁" },
      ],
      target: "less",
    },
    difficulty_params: { max_difference: 3 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C1-SEQ-PAT-0014",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy quy luật hoa quả AB",
      instruction: "Chọn quả tiếp theo đúng quy luật.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.09"],
      learning_objective_codes: ["LO-C1.NREC.09-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sequence"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🍎", "🍌", "🍎", "🍌", "🍎"],
      options: ["🍎", "🍌", "🍊"],
      correct_option: "🍌",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C1-SEQ-PAT-0015",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy số tự nhiên 1 đến 5",
      instruction: "Điền số tiếp theo vào vị trí trống.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.09"],
      learning_objective_codes: ["LO-C1.NREC.09-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["1", "2", "3", "4"],
      options: ["3", "5", "6"],
      correct_option: "5",
    },
    difficulty_params: { pattern_length: 5 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C1-SEQ-PAT-0016",
      content_version: 1,
      template_code: "GT-004",
      title: "Quy luật xe chạy AABB",
      instruction: "Chọn chiếc xe tiếp theo trong hàng.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.09"],
      learning_objective_codes: ["LO-C1.NREC.09-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🚗", "🚗", "🚕", "🚕", "🚗"],
      options: ["🚗", "🚕", "🚙"],
      correct_option: "🚗",
    },
    difficulty_params: { pattern_length: 4 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C1-POS-LOC-0017",
      content_version: 1,
      template_code: "GT-005",
      title: "Vị trí quả táo trên bàn",
      instruction: "Chạm vào quả táo nằm phía trên.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "premium",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [{ id: "a_top", emoji: "🍎", position: "top" }],
        [{ id: "b_bottom", emoji: "🍌", position: "bottom" }],
      ],
      target_id: "a_top",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C1-POS-LOC-0018",
      content_version: 1,
      template_code: "GT-005",
      title: "Tìm thỏ trong hang",
      instruction: "Chạm vào chú thỏ ở bên trái.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "r_left", emoji: "🐰", position: "left" },
          { id: "r_right", emoji: "🐻", position: "right" },
        ],
      ],
      target_id: "r_left",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C1-SUB-FAST-0019",
      content_version: 1,
      template_code: "GT-006",
      title: "Nhìn nhanh số lượng sao",
      instruction: "Nhìn nhanh xem có mấy ngôi sao.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.11"],
      learning_objective_codes: ["LO-C1.CNT.11-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "⭐️" }, { emoji: "⭐️" }, { emoji: "⭐️" }],
      flash_duration_ms: 1500,
      options: [2, 3, 4],
      correct_answer: 3,
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C1-SUB-FAST-0020",
      content_version: 1,
      template_code: "GT-006",
      title: "Nhìn nhanh chùm bóng bay",
      instruction: "Nói xem có bao nhiêu quả bóng.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.CNT.11"],
      learning_objective_codes: ["LO-C1.CNT.11-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [
        { emoji: "🎈" },
        { emoji: "🎈" },
        { emoji: "🎈" },
        { emoji: "🎈" },
      ],
      flash_duration_ms: 1200,
      options: [3, 4, 5],
      correct_answer: 4,
    },
    difficulty_params: { flash_duration_ms: 1200 },
  },
  // Level 31 (GT-010 - Substitution)
  {
    header: {
      code: "GL-C1-SUB-SYM-0031",
      content_version: 1,
      template_code: "GT-010",
      title: "Hệ phương trình trái cây hai bước",
      instruction: "Bé tính xem quả chuối bằng mấy.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.06"],
      learning_objective_codes: ["LO-C1.CNT.06-01"],
      what_tags: ["cnt"],
      thinking_tags: ["infer"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy suy nghĩ xem Quả chuối có giá trị bằng mấy nhé!",
      symbols: [
        { symbol_id: "apple", asset: { kind: "emoji", ref: "🍎" } },
        { symbol_id: "banana", asset: { kind: "emoji", ref: "🍌" } },
      ],
      equations: [
        { equation_id: "eq_1", left: ["apple", "apple"], right_value: 10 },
        { equation_id: "eq_2", left: ["apple", "banana"], right_value: 8 },
      ],
      question: { kind: "value", symbol_id: "banana" },
      options: [
        { value: 2, is_correct: false },
        { value: 3, is_correct: true },
        { value: 5, is_correct: false },
        { value: 8, is_correct: false },
      ],
    },
    difficulty_params: {
      equation_count: 2,
      step_count: 2,
      distractor_count: 3,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 32 (GT-010 - Substitution)
  {
    header: {
      code: "GL-C1-SUB-SYM-0032",
      content_version: 1,
      template_code: "GT-010",
      title: "Tính tổng hoa và cỏ may mắn",
      instruction: "Bé tìm giá trị của hoa hướng dương.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.CNT.06"],
      learning_objective_codes: ["LO-C1.CNT.06-01"],
      what_tags: ["cnt"],
      thinking_tags: ["infer"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy tính xem Bông hoa hướng dương có giá trị là bao nhiêu?",
      symbols: [
        { symbol_id: "rose", asset: { kind: "emoji", ref: "🌹" } },
        { symbol_id: "sunflower", asset: { kind: "emoji", ref: "🌻" } },
      ],
      equations: [
        { equation_id: "eq_1", left: ["rose", "rose", "rose"], right_value: 9 },
        { equation_id: "eq_2", left: ["rose", "sunflower"], right_value: 7 },
      ],
      question: { kind: "value", symbol_id: "sunflower" },
      options: [
        { value: 3, is_correct: false },
        { value: 4, is_correct: true },
        { value: 5, is_correct: false },
      ],
    },
    difficulty_params: {
      equation_count: 2,
      step_count: 2,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 33 (GT-010 - Substitution)
  {
    header: {
      code: "GL-C1-SUB-SYM-0033",
      content_version: 1,
      template_code: "GT-010",
      title: "Hệ phương trình ba loài động vật",
      instruction: "Bé tính giá trị của chú mèo con.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.CNT.06"],
      learning_objective_codes: ["LO-C1.CNT.06-01"],
      what_tags: ["cnt"],
      thinking_tags: ["infer"],
      theme_tag: "animal",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy tìm giá trị của Mèo con nhé!",
      symbols: [
        { symbol_id: "dog", asset: { kind: "emoji", ref: "🐶" } },
        { symbol_id: "cat", asset: { kind: "emoji", ref: "🐱" } },
      ],
      equations: [
        { equation_id: "e1", left: ["dog", "dog"], right_value: 12 },
        { equation_id: "e2", left: ["dog", "cat"], right_value: 10 },
      ],
      question: { kind: "value", symbol_id: "cat" },
      options: [
        { value: 2, is_correct: false },
        { value: 4, is_correct: true },
        { value: 6, is_correct: false },
      ],
    },
    difficulty_params: {
      equation_count: 2,
      step_count: 2,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 34 (GT-014 - Balance Scale)
  {
    header: {
      code: "GL-C1-BAL-SCL-0034",
      content_version: 1,
      template_code: "GT-014",
      title: "So sánh nặng nhẹ giữa dưa hấu và táo",
      instruction: "Chạm vào đĩa cân nặng hơn.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MSR.01"],
      learning_objective_codes: ["LO-C1.MSR.01-01"],
      what_tags: ["msr"],
      thinking_tags: ["compare"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào đĩa cân của loại quả NẶNG HƠN nhé!",
      goal: "pick_heavier",
      left_pan: [
        {
          item_id: "watermelon",
          asset: { kind: "emoji", ref: "🍉" },
          weight: 5,
        },
      ],
      right_pan: [
        { item_id: "apple", asset: { kind: "emoji", ref: "🍎" }, weight: 1 },
      ],
      tray: [
        { item_id: "w1", asset: { kind: "emoji", ref: "1️⃣" }, weight: 1 },
        { item_id: "w2", asset: { kind: "emoji", ref: "2️⃣" }, weight: 2 },
      ],
    },
    difficulty_params: {
      tray_count: 2,
      weight_span: 5,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 35 (GT-014 - Balance Scale)
  {
    header: {
      code: "GL-C1-BAL-SCL-0035",
      content_version: 1,
      template_code: "GT-014",
      title: "Đặt quả cân để tạo thăng bằng",
      instruction: "Kéo quả cân vào đĩa để cân thăng bằng.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.MSR.01"],
      learning_objective_codes: ["LO-C1.MSR.01-01"],
      what_tags: ["msr"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé hãy kéo quả cân thích hợp vào đĩa phải để chiếc cân thăng bằng nhé!",
      goal: "balance",
      left_pan: [
        { item_id: "gift", asset: { kind: "emoji", ref: "🎁" }, weight: 3 },
      ],
      right_pan: [],
      tray: [
        { item_id: "w1", asset: { kind: "emoji", ref: "1️⃣" }, weight: 1 },
        { item_id: "w2", asset: { kind: "emoji", ref: "2️⃣" }, weight: 2 },
        { item_id: "w3", asset: { kind: "emoji", ref: "3️⃣" }, weight: 3 },
      ],
    },
    difficulty_params: {
      tray_count: 3,
      weight_span: 3,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 36 (GT-014 - Balance Scale)
  {
    header: {
      code: "GL-C1-BAL-SCL-0036",
      content_version: 1,
      template_code: "GT-014",
      title: "Bắc cầu ba vật phẩm tìm vật nặng nhất",
      instruction: "Tìm con vật nặng nhất trong ba bạn.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.MSR.01"],
      learning_objective_codes: ["LO-C1.MSR.01-01"],
      what_tags: ["msr"],
      thinking_tags: ["compare"],
      theme_tag: "animal",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Quan sát hai lần cân, bé hãy chọn con vật NẶNG NHẤT nhé!",
      goal: "pick_heavier",
      left_pan: [
        {
          item_id: "elephant",
          asset: { kind: "emoji", ref: "🐘" },
          weight: 10,
        },
      ],
      right_pan: [
        { item_id: "bear", asset: { kind: "emoji", ref: "🐻" }, weight: 5 },
      ],
      tray: [
        {
          item_id: "opt_elephant",
          asset: { kind: "emoji", ref: "🐘" },
          weight: 10,
        },
        { item_id: "opt_bear", asset: { kind: "emoji", ref: "🐻" }, weight: 5 },
        {
          item_id: "opt_mouse",
          asset: { kind: "emoji", ref: "🐭" },
          weight: 1,
        },
      ],
    },
    difficulty_params: {
      tray_count: 3,
      weight_span: 10,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 37 (GT-016 - Clock Hands)
  {
    header: {
      code: "GL-C1-CLK-HND-0037",
      content_version: 1,
      template_code: "GT-016",
      title: "Đọc đồng hồ giờ đúng",
      instruction: "Bé nhìn đồng hồ chỉ mấy giờ.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MSR.04"],
      learning_objective_codes: ["LO-C1.MSR.04-01"],
      what_tags: ["time"],
      thinking_tags: ["observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Đồng hồ đang chỉ mấy giờ vậy bé ơi?",
      mode: "read",
      target_time: { hour: 8, minute: 0 },
      options: [
        { hour: 7, minute: 0, is_correct: false },
        { hour: 8, minute: 0, is_correct: true },
        { hour: 9, minute: 0, is_correct: false },
      ],
      activity_cards: [],
    },
    difficulty_params: {
      minute_step: 60,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 38 (GT-016 - Clock Hands)
  {
    header: {
      code: "GL-C1-CLK-HND-0038",
      content_version: 1,
      template_code: "GT-016",
      title: "Xoay kim đặt bốn giờ rưỡi",
      instruction: "Bé xoay kim đồng hồ bốn giờ rưỡi.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.MSR.04"],
      learning_objective_codes: ["LO-C1.MSR.04-01"],
      what_tags: ["time"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xoay kim đồng hồ về đúng 4 giờ 30 phút nhé!",
      mode: "set",
      target_time: { hour: 4, minute: 30 },
      initial_time: { hour: 12, minute: 0 },
      options: [],
      activity_cards: [],
    },
    difficulty_params: {
      minute_step: 30,
      distractor_count: 0,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 39 (GT-016 - Clock Hands)
  {
    header: {
      code: "GL-C1-CLK-HND-0039",
      content_version: 1,
      template_code: "GT-016",
      title: "Ghép đồng hồ với hoạt động trong ngày",
      instruction: "Chọn đồng hồ chỉ giờ bé đi ngủ.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.MSR.04"],
      learning_objective_codes: ["LO-C1.MSR.04-01"],
      what_tags: ["time"],
      thinking_tags: ["observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn chiếc đồng hồ chỉ đúng 9 giờ tối lúc bé đi ngủ nhé!",
      mode: "match_activity",
      target_time: { hour: 21, minute: 0 },
      options: [],
      activity_cards: [
        {
          activity_id: "act_sleep",
          name_vi: "Bé đi ngủ buổi tối (9 giờ)",
          asset: { kind: "emoji", ref: "🛏️" },
          expected_time: { hour: 21, minute: 0 },
        },
      ],
    },
    difficulty_params: {
      minute_step: 60,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 40 (GT-012 - Flash Recall for C1)
  {
    header: {
      code: "GL-C1-MEM-FLASH-0040",
      content_version: 1,
      template_code: "GT-012",
      title: "Nhìn nhanh đếm ba quả táo",
      instruction: "Bé nhìn thật nhanh đếm quả táo.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt", "mem"],
      thinking_tags: ["recall", "count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nhìn thật nhanh có mấy quả táo nhé!",
      arrangement: "dice",
      flash_items: [
        { item_id: "ap_1", asset: { kind: "emoji", ref: "🍎" } },
        { item_id: "ap_2", asset: { kind: "emoji", ref: "🍎" } },
        { item_id: "ap_3", asset: { kind: "emoji", ref: "🍎" } },
      ],
      options: [
        { value: 2, is_correct: false },
        { value: 3, is_correct: true },
        { value: 4, is_correct: false },
      ],
    },
    difficulty_params: {
      flash_ms: 1500,
      item_count: 3,
      distractor_count: 2,
      allow_replay: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
];

export const C1_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  ...C1_BASE_LEVELS,
  ...SEED_MONT_A01,
  ...SEED_MONT_A02,
  ...SEED_MONT_A05,
  ...SEED_MONT_A06,
  ...SEED_MONT_A07,
  ...SEED_MONT_A08,
  ...SEED_MONT_A11,
  ...SEED_MONT_A13,
  ...SEED_MONT_A15,
  ...SEED_MONT_A18,
  ...SEED_MONT_B02,
  ...SEED_MONT_B11,
  ...SEED_MONT_B15,
];
