import type { ContentSeed } from "../types.js";

export const C1_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C1-CNT-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Đếm số táo đỏ",
      instruction_vi: "Em hãy đếm xem có mấy quả táo nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "a1", emoji: "🍎" },
        { id: "a2", emoji: "🍎" },
        { id: "a3", emoji: "🍎" },
      ],
      target_count: 3,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Đếm chuối vàng",
      instruction_vi: "Em đếm xem có bao nhiêu quả chuối.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "b1", emoji: "🍌" },
        { id: "b2", emoji: "🍌" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0003",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Đếm cam mọng nước",
      instruction_vi: "Cùng đếm số quả cam nào em nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "o1", emoji: "🍊" },
        { id: "o2", emoji: "🍊" },
        { id: "o3", emoji: "🍊" },
        { id: "o4", emoji: "🍊" },
      ],
      target_count: 4,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0004",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Đếm dưa hấu",
      instruction_vi: "Hãy đếm số miếng dưa hấu tươi mát.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.02"],
      learning_objective_codes: ["LO-C1.CNT.02-01"],
      what_tags: ["cnt"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "w1", emoji: "🍉" },
        { id: "w2", emoji: "🍉" },
        { id: "w3", emoji: "🍉" },
        { id: "w4", emoji: "🍉" },
        { id: "w5", emoji: "🍉" },
      ],
      target_count: 5,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C1-CNT-CARD-0005",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Đếm chùm nho ngọt",
      instruction_vi: "Em đếm xem có mấy chùm nho.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "g1", emoji: "🍇" },
        { id: "g2", emoji: "🍇" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C1-SORT-BOX-0006",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại quả đỏ và quả vàng",
      instruction_vi: "Bỏ quả đỏ vào giỏ đỏ em nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "red_basket", label: "Giỏ đỏ", target_color: "red" }],
      drag_items: [
        { id: "a1", emoji: "🍎", color: "red" },
        { id: "b1", emoji: "🍌", color: "yellow" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C1-SORT-BOX-0007",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Thu hoạch dâu tây",
      instruction_vi: "Em kéo dâu tây vào hộp nhựa.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "strawberry_box", label: "Hộp dâu", target_type: "strawberry" },
      ],
      drag_items: [
        { id: "s1", emoji: "🍓", type: "strawberry" },
        { id: "c1", emoji: "🥕", type: "carrot" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C1-SORT-BOX-0008",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Xếp dứa chín",
      instruction_vi: "Hãy xếp quả dứa vào giỏ cây.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "pineapple_basket", label: "Giỏ dứa", target_type: "pineapple" },
      ],
      drag_items: [
        { id: "p1", emoji: "🍍", type: "pineapple" },
        { id: "p2", emoji: "🍍", type: "pineapple" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C1-SORT-BOX-0009",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Thu gom cà rốt",
      instruction_vi: "Hãy kéo cà rốt vào túi thỏ.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "carrot_bag", label: "Túi cà rốt", target_type: "carrot" },
      ],
      drag_items: [
        { id: "c1", emoji: "🥕", type: "carrot" },
        { id: "c2", emoji: "🥕", type: "carrot" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C1-CMP-NUM-0010",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "So sánh đĩa trái cây",
      instruction_vi: "Chọn bên có nhiều trái cây hơn.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🍎" }, { emoji: "🍎" }, { emoji: "🍎" }],
      right_group: [{ emoji: "🍎" }],
      target: "more",
    },
    difficulty_params: { max_difference: 2 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C1-CMP-NUM-0011",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "So sánh số kẹo",
      instruction_vi: "Chọn bên có ít kẹo hơn nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🍬" }],
      right_group: [
        { emoji: "🍬" },
        { emoji: "🍬" },
        { emoji: "🍬" },
        { emoji: "🍬" },
      ],
      target: "less",
    },
    difficulty_params: { max_difference: 3 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C1-CMP-NUM-0012",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "Bên nào nhiều bóng hơn",
      instruction_vi: "Chọn nhóm bóng nhiều hơn em nha.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [
        { emoji: "⚽" },
        { emoji: "⚽" },
        { emoji: "⚽" },
        { emoji: "⚽" },
      ],
      right_group: [{ emoji: "⚽" }, { emoji: "⚽" }],
      target: "more",
    },
    difficulty_params: { max_difference: 2 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C1-CMP-NUM-0013",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "So sánh bánh ngọt",
      instruction_vi: "Chọn nhóm bánh ít hơn.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.05"],
      learning_objective_codes: ["LO-C1.NREC.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["analytical"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🧁" }, { emoji: "🧁" }],
      right_group: [
        { emoji: "🧁" },
        { emoji: "🧁" },
        { emoji: "🧁" },
        { emoji: "🧁" },
        { emoji: "🧁" },
      ],
      target: "less",
    },
    difficulty_params: { max_difference: 3 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C1-SEQ-PAT-0014",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Dãy quy luật hoa quả AB",
      instruction_vi: "Chọn quả tiếp theo đúng quy luật.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.09"],
      learning_objective_codes: ["LO-C1.NREC.09-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sequential"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🍎", "🍌", "🍎", "🍌", "🍎"],
      options: ["🍎", "🍌", "🍊"],
      correct_option: "🍌",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C1-SEQ-PAT-0015",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Dãy số tự nhiên 1 đến 5",
      instruction_vi: "Điền số tiếp theo vào vị trí trống.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.09"],
      learning_objective_codes: ["LO-C1.NREC.09-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["1", "2", "3", "4"],
      options: ["3", "5", "6"],
      correct_option: "5",
    },
    difficulty_params: { pattern_length: 5 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C1-SEQ-PAT-0016",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Quy luật xe chạy AABB",
      instruction_vi: "Chọn chiếc xe tiếp theo trong hàng.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.NREC.09"],
      learning_objective_codes: ["LO-C1.NREC.09-01"],
      what_tags: ["cnt"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🚗", "🚗", "🚕", "🚕", "🚗"],
      options: ["🚗", "🚕", "🚙"],
      correct_option: "🚗",
    },
    difficulty_params: { pattern_length: 4 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C1-POS-LOC-0017",
      content_version: 1,
      template_code: "GT-005",
      title_vi: "Vị trí quả táo trên bàn",
      instruction_vi: "Chạm vào quả táo nằm phía trên.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "premium",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["spatial"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [{ id: "a_top", emoji: "🍎", position: "top" }],
        [{ id: "b_bottom", emoji: "🍌", position: "bottom" }],
      ],
      target_id: "a_top",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C1-POS-LOC-0018",
      content_version: 1,
      template_code: "GT-005",
      title_vi: "Tìm thỏ trong hang",
      instruction_vi: "Chạm vào chú thỏ ở bên trái.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["spatial"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "r_left", emoji: "🐰", position: "left" },
          { id: "r_right", emoji: "🐻", position: "right" },
        ],
      ],
      target_id: "r_left",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C1-SUB-FAST-0019",
      content_version: 1,
      template_code: "GT-006",
      title_vi: "Nhìn nhanh số lượng sao",
      instruction_vi: "Nhìn nhanh xem có mấy ngôi sao.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.11"],
      learning_objective_codes: ["LO-C1.CNT.11-01"],
      what_tags: ["cnt"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "⭐️" }, { emoji: "⭐️" }, { emoji: "⭐️" }],
      flash_duration_ms: 1500,
      options: [2, 3, 4],
      correct_answer: 3,
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C1-SUB-FAST-0020",
      content_version: 1,
      template_code: "GT-006",
      title_vi: "Nhìn nhanh chùm bóng bay",
      instruction_vi: "Nói xem có bao nhiêu quả bóng.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.CNT.11"],
      learning_objective_codes: ["LO-C1.CNT.11-01"],
      what_tags: ["cnt"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [
        { emoji: "🎈" },
        { emoji: "🎈" },
        { emoji: "🎈" },
        { emoji: "🎈" },
      ],
      flash_duration_ms: 1200,
      options: [3, 4, 5],
      correct_answer: 4,
    },
    difficulty_params: { flash_duration_ms: 1200 },
  },
];
