import type { ContentSeed } from "#src/seed-content/types";

/**
 * Batch: SEED-GT033
 * Dệt hoa văn lưới (weave-grid)
 * 10 levels, GT-033, legacy_v1_ref: "D3-07", band 5-6, themes: home, school, food, nature, festival, art
 */
export const SEED_GT033: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0001",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt thảm len 2x2 cơ bản",
      instruction: "Bé chọn màu dệt vào ô trống nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn sợi len màu đúng để dệt vào ô trống nhé!",
      grid: { rows: 2, cols: 2 },
      palette: [
        {
          color_id: "red",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Đỏ",
        },
        {
          color_id: "blue",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh dương",
        },
      ],
      cells: ["red", "blue", "blue", null],
      solution: ["red", "blue", "blue", "red"],
      row_rule: "Mỗi hàng gồm Đỏ và Xanh",
      col_rule: "Mỗi cột gồm Đỏ và Xanh",
    },
    difficulty_params: {
      grid_size: 2,
      color_count: 2,
      blank_count: 1,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0002",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt lưới lá cây 2x2",
      instruction: "Bé chọn màu hoàn thành hoa văn nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn sợi len màu phù hợp để hoàn thành dệt lưới nhé!",
      grid: { rows: 2, cols: 2 },
      palette: [
        {
          color_id: "green",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh lá",
        },
        {
          color_id: "yellow",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Vàng",
        },
      ],
      cells: ["yellow", null, "green", "yellow"],
      solution: ["yellow", "green", "green", "yellow"],
      row_rule: "Mỗi hàng gồm Vàng và Xanh lá",
      col_rule: "Mỗi cột gồm Vàng và Xanh lá",
    },
    difficulty_params: {
      grid_size: 2,
      color_count: 2,
      blank_count: 1,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0003",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt bàn cờ ca rô 3x3",
      instruction: "Bé dệt ô trống hoàn thành bàn cờ nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "sequence", "infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy dệt hoàn thiện hoa văn ca rô 3x3 nhé!",
      grid: { rows: 3, cols: 3 },
      palette: [
        {
          color_id: "red",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Đỏ",
        },
        {
          color_id: "blue",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh",
        },
      ],
      cells: ["red", "blue", "red", "blue", null, "blue", "red", null, "red"],
      solution: [
        "red",
        "blue",
        "red",
        "blue",
        "red",
        "blue",
        "red",
        "blue",
        "red",
      ],
      row_rule: "Xen kẽ Đỏ và Xanh",
      col_rule: "Xen kẽ Đỏ và Xanh",
    },
    difficulty_params: {
      grid_size: 3,
      color_count: 2,
      blank_count: 2,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0004",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt khăn trải bàn hoa quả 3x3",
      instruction: "Bé dệt màu vào khăn trải bàn nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "sequence", "infer"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn màu dệt vào 2 ô trống trên khăn trải bàn nhé!",
      grid: { rows: 3, cols: 3 },
      palette: [
        {
          color_id: "orange",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Cam",
        },
        {
          color_id: "green",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh lá",
        },
      ],
      cells: [
        "orange",
        null,
        "orange",
        "green",
        "orange",
        "green",
        null,
        "green",
        "orange",
      ],
      solution: [
        "orange",
        "green",
        "orange",
        "green",
        "orange",
        "green",
        "orange",
        "green",
        "orange",
      ],
      row_rule: "Cam và Xanh lá xen kẽ",
      col_rule: "Cam và Xanh lá xen kẽ",
    },
    difficulty_params: {
      grid_size: 3,
      color_count: 2,
      blank_count: 2,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0005",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt dải lụa lễ hội 3 màu",
      instruction: "Bé dệt màu theo quy luật 3 màu nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy hoàn thành dệt tấm lụa lễ hội 3x3 nhé!",
      grid: { rows: 3, cols: 3 },
      palette: [
        {
          color_id: "red",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Đỏ",
        },
        {
          color_id: "yellow",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Vàng",
        },
        {
          color_id: "blue",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh",
        },
      ],
      cells: [
        "red",
        "yellow",
        "blue",
        "yellow",
        null,
        "red",
        "blue",
        "red",
        null,
      ],
      solution: [
        "red",
        "yellow",
        "blue",
        "yellow",
        "blue",
        "red",
        "blue",
        "red",
        "yellow",
      ],
      row_rule: "Dịch chuyển tuần hoàn 3 màu",
      col_rule: "Dịch chuyển tuần hoàn 3 màu",
    },
    difficulty_params: {
      grid_size: 3,
      color_count: 3,
      blank_count: 2,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0006",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt thảm phòng khách 3 màu (3 ô trống)",
      instruction: "Bé dệt 3 ô theo hoa văn thảm nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy dệt tiếp 3 ô màu để hoàn thành thảm nhé!",
      grid: { rows: 3, cols: 3 },
      palette: [
        {
          color_id: "purple",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Tím",
        },
        {
          color_id: "yellow",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Vàng",
        },
        {
          color_id: "green",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh lá",
        },
      ],
      cells: [
        "purple",
        null,
        "green",
        null,
        "green",
        "purple",
        "green",
        "purple",
        null,
      ],
      solution: [
        "purple",
        "yellow",
        "green",
        "yellow",
        "green",
        "purple",
        "green",
        "purple",
        "yellow",
      ],
      row_rule: "Tuần hoàn Tím - Vàng - Xanh lá",
      col_rule: "Tuần hoàn Tím - Vàng - Xanh lá",
    },
    difficulty_params: {
      grid_size: 3,
      color_count: 3,
      blank_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0007",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt thảm hoa thiên nhiên 3x3",
      instruction: "Bé dệt 3 ô hoàn thành tranh hoa nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy dệt 3 ô trống theo quy luật đối xứng màu nhé!",
      grid: { rows: 3, cols: 3 },
      palette: [
        {
          color_id: "red",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Đỏ",
        },
        {
          color_id: "yellow",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Vàng",
        },
        {
          color_id: "blue",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh dương",
        },
      ],
      cells: [
        "red",
        "blue",
        null,
        "blue",
        null,
        "yellow",
        null,
        "yellow",
        "red",
      ],
      solution: [
        "red",
        "blue",
        "red",
        "blue",
        "yellow",
        "yellow",
        "red",
        "yellow",
        "red",
      ],
      row_rule: "Đối xứng màu qua tâm",
      col_rule: "Đối xứng màu qua tâm",
    },
    difficulty_params: {
      grid_size: 3,
      color_count: 3,
      blank_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0008",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt tranh vải nghệ thuật 4x4",
      instruction: "Bé dệt 3 ô trên lưới ca rô nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "sequence", "infer"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy dệt hoàn thiện hoa văn ca rô 4x4 nhé!",
      grid: { rows: 4, cols: 4 },
      palette: [
        {
          color_id: "blue",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh",
        },
        {
          color_id: "yellow",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Vàng",
        },
      ],
      cells: [
        "blue",
        "yellow",
        "blue",
        null,
        "yellow",
        "blue",
        null,
        "blue",
        "blue",
        null,
        "blue",
        "yellow",
        "yellow",
        "blue",
        "yellow",
        "blue",
      ],
      solution: [
        "blue",
        "yellow",
        "blue",
        "yellow",
        "yellow",
        "blue",
        "yellow",
        "blue",
        "blue",
        "yellow",
        "blue",
        "yellow",
        "yellow",
        "blue",
        "yellow",
        "blue",
      ],
      row_rule: "Xanh và Vàng xen kẽ",
      col_rule: "Xanh và Vàng xen kẽ",
    },
    difficulty_params: {
      grid_size: 4,
      color_count: 2,
      blank_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0009",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt dải cờ lễ hội 4x4",
      instruction: "Bé dệt 3 ô theo tuần hoàn 4 màu nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 5,
      access_tier: "premium",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn đúng màu dệt vào 3 ô trống trên lưới 4x4 nhé!",
      grid: { rows: 4, cols: 4 },
      palette: [
        {
          color_id: "red",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Đỏ",
        },
        {
          color_id: "yellow",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Vàng",
        },
        {
          color_id: "green",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh lá",
        },
        {
          color_id: "blue",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh dương",
        },
      ],
      cells: [
        "red",
        "yellow",
        "green",
        "blue",
        "yellow",
        null,
        "blue",
        "red",
        "green",
        "blue",
        null,
        "yellow",
        "blue",
        "red",
        "yellow",
        null,
      ],
      solution: [
        "red",
        "yellow",
        "green",
        "blue",
        "yellow",
        "green",
        "blue",
        "red",
        "green",
        "blue",
        "red",
        "yellow",
        "blue",
        "red",
        "yellow",
        "green",
      ],
      row_rule: "Dịch chuyển tuần hoàn 4 màu",
      col_rule: "Dịch chuyển tuần hoàn 4 màu",
    },
    difficulty_params: {
      grid_size: 4,
      color_count: 4,
      blank_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-WEAVE-0010",
      legacy_v1_ref: "D3-07",
      content_version: 1,
      template_code: "GT-033",
      title: "Dệt thảm lớp học thông minh 4x4",
      instruction: "Bé dệt 4 ô hoàn thành tấm thảm nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 5,
      access_tier: "premium",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "colour"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé hãy chọn màu dệt vào 4 ô trống để hoàn thiện tấm thảm 4x4 nhé!",
      grid: { rows: 4, cols: 4 },
      palette: [
        {
          color_id: "purple",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Tím",
        },
        {
          color_id: "orange",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Cam",
        },
        {
          color_id: "green",
          asset: { kind: "emoji", ref: "EMJ-yarn" },
          name_vi: "Xanh lá",
        },
      ],
      cells: [
        "purple",
        "orange",
        "green",
        null,
        "orange",
        "green",
        null,
        "orange",
        "green",
        null,
        "orange",
        "green",
        null,
        "orange",
        "green",
        "purple",
      ],
      solution: [
        "purple",
        "orange",
        "green",
        "purple",
        "orange",
        "green",
        "purple",
        "orange",
        "green",
        "purple",
        "orange",
        "green",
        "purple",
        "orange",
        "green",
        "purple",
      ],
      row_rule: "Tuần hoàn Tím - Cam - Xanh lá",
      col_rule: "Tuần hoàn Tím - Cam - Xanh lá",
    },
    difficulty_params: {
      grid_size: 4,
      color_count: 3,
      blank_count: 4,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
];
