import type { ContentSeed } from "#src/seed-content/types";

export const SEED_GT036: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-PAT-FCR-0001",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Tự tạo quy luật hoa lá",
      instruction: "Bé tự xếp hoa lá theo quy luật lặp lại nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tự xếp hoa lá theo quy luật lặp lại nhé!",
      palette: [
        { id: "flower", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
        { id: "tree", asset: { kind: "emoji", ref: "EMJ-deciduous-tree" } },
      ],
      track_length: 6,
      min_repetitions: 3,
    },
    difficulty_params: {
      palette_size: 2,
      track_length: 6,
      min_repetitions: 3,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0002",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật dụng cụ vẽ",
      instruction: "Bé tự xếp bút màu theo quy luật lặp lại nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tự xếp bút màu theo quy luật lặp lại nhé!",
      palette: [
        { id: "crayon", asset: { kind: "emoji", ref: "EMJ-crayon" } },
        { id: "pencil", asset: { kind: "emoji", ref: "EMJ-pencil" } },
      ],
      track_length: 6,
      min_repetitions: 3,
    },
    difficulty_params: {
      palette_size: 2,
      track_length: 6,
      min_repetitions: 3,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0003",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật nông trại vui vẻ",
      instruction: "Bé xếp quả táo và củ cà rốt lặp lại nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp quả táo và cà rốt theo quy luật lặp lại nhé!",
      palette: [
        { id: "apple", asset: { kind: "emoji", ref: "EMJ-red-apple" } },
        { id: "carrot", asset: { kind: "emoji", ref: "EMJ-carrot" } },
      ],
      track_length: 8,
      min_repetitions: 2,
    },
    difficulty_params: {
      palette_size: 2,
      track_length: 8,
      min_repetitions: 2,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0004",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật sinh vật biển",
      instruction: "Bé xếp cá, vỏ ốc và cua theo quy luật nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp các bạn cá và vỏ ốc theo quy luật lặp lại nhé!",
      palette: [
        { id: "fish", asset: { kind: "emoji", ref: "EMJ-fish" } },
        { id: "shell", asset: { kind: "emoji", ref: "EMJ-spiral-shell" } },
        { id: "crab", asset: { kind: "emoji", ref: "EMJ-crab" } },
      ],
      track_length: 9,
      min_repetitions: 3,
    },
    difficulty_params: {
      palette_size: 3,
      track_length: 9,
      min_repetitions: 3,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0005",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật đồ dùng học tập",
      instruction: "Bé xếp sách vở và chuông reo theo quy luật nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp sách vở và chuông reo theo quy luật nhé!",
      palette: [
        { id: "book", asset: { kind: "emoji", ref: "EMJ-open-book" } },
        { id: "bell", asset: { kind: "emoji", ref: "EMJ-bell" } },
        { id: "scissors", asset: { kind: "emoji", ref: "EMJ-scissors" } },
      ],
      track_length: 6,
      min_repetitions: 2,
    },
    difficulty_params: {
      palette_size: 3,
      track_length: 6,
      min_repetitions: 2,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0006",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật lễ hội vui nhộn",
      instruction: "Bé xếp bóng bay và hộp quà theo quy luật nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.PAT.08"],
      learning_objective_codes: ["LO-C1.PAT.08-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp bóng bay và quà tặng lặp lại nhé!",
      palette: [
        { id: "balloon", asset: { kind: "emoji", ref: "EMJ-balloon" } },
        { id: "gift", asset: { kind: "emoji", ref: "EMJ-gift" } },
        { id: "sparkles", asset: { kind: "emoji", ref: "EMJ-sparkles" } },
      ],
      track_length: 9,
      min_repetitions: 3,
    },
    difficulty_params: {
      palette_size: 3,
      track_length: 9,
      min_repetitions: 3,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0007",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật các hành tinh vũ trụ",
      instruction: "Bé xếp sao và mặt trăng lặp lại 4 lần nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.PAT.08"],
      learning_objective_codes: ["LO-C1.PAT.08-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp ngôi sao và mặt trăng lặp lại 4 lần nhé!",
      palette: [
        { id: "star", asset: { kind: "emoji", ref: "EMJ-star" } },
        { id: "moon", asset: { kind: "emoji", ref: "EMJ-crescent-moon" } },
      ],
      track_length: 8,
      min_repetitions: 4,
    },
    difficulty_params: {
      palette_size: 2,
      track_length: 8,
      min_repetitions: 4,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0008",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật đồ vật trong nhà",
      instruction: "Bé xếp đồ đạc trong nhà theo quy luật nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.PAT.08"],
      learning_objective_codes: ["LO-C1.PAT.08-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tự xếp đồ đạc trong nhà theo quy luật lặp lại nhé!",
      palette: [
        { id: "chair", asset: { kind: "emoji", ref: "EMJ-chair" } },
        { id: "door", asset: { kind: "emoji", ref: "EMJ-door" } },
        {
          id: "cup",
          asset: { kind: "emoji", ref: "EMJ-tea" },
        },
      ],
      track_length: 12,
      min_repetitions: 3,
    },
    difficulty_params: {
      palette_size: 3,
      track_length: 12,
      min_repetitions: 3,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0009",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật 4 loài cây hoa",
      instruction: "Bé tự xếp 4 loại hoa lá theo quy luật lặp nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.PAT.08"],
      learning_objective_codes: ["LO-C1.PAT.08-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp các loài cây hoa theo quy luật 3 lần lặp nhé!",
      palette: [
        { id: "flower", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
        { id: "tree", asset: { kind: "emoji", ref: "EMJ-deciduous-tree" } },
        { id: "leaf", asset: { kind: "emoji", ref: "EMJ-maple-leaf" } },
        { id: "sun", asset: { kind: "emoji", ref: "EMJ-sun" } },
      ],
      track_length: 12,
      min_repetitions: 3,
    },
    difficulty_params: {
      palette_size: 4,
      track_length: 12,
      min_repetitions: 3,
      strictness: "relaxed",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-FCR-0010",
      template_code: "GT-036",
      legacy_v1_ref: "D3-05",
      content_version: 1,
      title: "Quy luật mỹ thuật chuẩn xác",
      instruction: "Bé xếp dải màu kết thúc chuẩn xác ranh giới nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.PAT.08"],
      learning_objective_codes: ["LO-C1.PAT.08-01"],
      what_tags: ["pattern", "rule"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp dụng cụ vẽ tranh kết thúc chuẩn xác ranh giới nhé!",
      palette: [
        { id: "palette", asset: { kind: "emoji", ref: "EMJ-artist-palette" } },
        { id: "crayon", asset: { kind: "emoji", ref: "EMJ-crayon" } },
        { id: "brush", asset: { kind: "emoji", ref: "EMJ-paintbrush" } },
      ],
      track_length: 9,
      min_repetitions: 3,
    },
    difficulty_params: {
      palette_size: 3,
      track_length: 9,
      min_repetitions: 3,
      strictness: "strict",
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
];
