import type { ContentSeed } from "#src/seed-content/types";

/**
 * Batch: SEED-GT029
 * Bớt khỏi nhóm (remove-from-set)
 * 10 levels, GT-029, legacy_v1_ref: "D1-12", band 4-5 & 5-6, themes: food, farm, ocean, school, nature, space
 */
export const SEED_GT029: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-REM-SET-0001",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 1 quả táo trong nhóm 4 quả",
      instruction: "Bé bớt 1 quả táo rồi đếm lại nhé.",
      age_min: 4,
      age_max: 5,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 1 quả táo rồi xem còn lại mấy quả nhé!",
      remove_count: 1,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "🍎" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "🍎" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "🍎" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "🍎" } },
      ],
      answer_options: [
        { option_id: "opt_2", value: 2, is_correct: false },
        { option_id: "opt_3", value: 3, is_correct: true },
        { option_id: "opt_4", value: 4, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 4,
      remove_count: 1,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0002",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 2 chú gà trong nhóm 5 chú",
      instruction: "Bé bớt 2 chú gà rồi đếm lại nhé.",
      age_min: 4,
      age_max: 5,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 2 chú gà rồi xem còn lại mấy chú nhé!",
      remove_count: 2,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "🐤" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "🐤" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "🐤" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "🐤" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "🐤" } },
      ],
      answer_options: [
        { option_id: "opt_2", value: 2, is_correct: false },
        { option_id: "opt_3", value: 3, is_correct: true },
        { option_id: "opt_4", value: 4, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 5,
      remove_count: 2,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0003",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 2 chú cá trong nhóm 6 chú",
      instruction: "Bé bớt 2 chú cá xem còn mấy chú?",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 2 chú cá rồi đếm xem còn mấy chú nhé!",
      remove_count: 2,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "🐠" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "🐠" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "🐠" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "🐠" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "🐠" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "🐠" } },
      ],
      answer_options: [
        { option_id: "opt_3", value: 3, is_correct: false },
        { option_id: "opt_4", value: 4, is_correct: true },
        { option_id: "opt_5", value: 5, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 6,
      remove_count: 2,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0004",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 3 cây bút trong nhóm 5 cây",
      instruction: "Bé bớt 3 cây bút xem còn mấy cây?",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.01"],
      learning_objective_codes: ["LO-C1.CNT.01-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 3 cây bút rồi đếm xem còn lại mấy cây nhé!",
      remove_count: 3,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "✏️" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "✏️" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "✏️" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "✏️" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "✏️" } },
      ],
      answer_options: [
        { option_id: "opt_1", value: 1, is_correct: false },
        { option_id: "opt_2", value: 2, is_correct: true },
        { option_id: "opt_3", value: 3, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 5,
      remove_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0005",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 3 bông hoa trong nhóm 6 bông",
      instruction: "Bé bớt 3 bông hoa xem còn mấy bông?",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 3 bông hoa rồi xem còn lại mấy bông nhé!",
      remove_count: 3,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "🌸" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "🌸" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "🌸" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "🌸" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "🌸" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "🌸" } },
      ],
      answer_options: [
        { option_id: "opt_2", value: 2, is_correct: false },
        { option_id: "opt_3", value: 3, is_correct: true },
        { option_id: "opt_4", value: 4, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 6,
      remove_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0006",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 3 quả dâu trong nhóm 7 quả",
      instruction: "Bé bớt 3 quả dâu xem còn mấy quả?",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 3 quả dâu rồi đếm xem còn mấy quả nhé!",
      remove_count: 3,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "🍓" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "🍓" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "🍓" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "🍓" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "🍓" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "🍓" } },
        { item_id: "it7", asset: { kind: "emoji", ref: "🍓" } },
      ],
      answer_options: [
        { option_id: "opt_3", value: 3, is_correct: false },
        { option_id: "opt_4", value: 4, is_correct: true },
        { option_id: "opt_5", value: 5, is_correct: false },
        { option_id: "opt_6", value: 6, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 7,
      remove_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0007",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 3 ngôi sao trong nhóm 8 ngôi",
      instruction: "Bé bớt 3 ngôi sao xem còn mấy ngôi?",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.05"],
      learning_objective_codes: ["LO-C1.CNT.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 3 ngôi sao rồi xem còn lại mấy ngôi nhé!",
      remove_count: 3,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "⭐" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "⭐" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "⭐" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "⭐" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "⭐" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "⭐" } },
        { item_id: "it7", asset: { kind: "emoji", ref: "⭐" } },
        { item_id: "it8", asset: { kind: "emoji", ref: "⭐" } },
      ],
      answer_options: [
        { option_id: "opt_4", value: 4, is_correct: false },
        { option_id: "opt_5", value: 5, is_correct: true },
        { option_id: "opt_6", value: 6, is_correct: false },
        { option_id: "opt_7", value: 7, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 8,
      remove_count: 3,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0008",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 4 củ cà rốt trong nhóm 9 củ",
      instruction: "Bé bớt 4 củ cà rốt xem còn mấy củ?",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.05"],
      learning_objective_codes: ["LO-C1.CNT.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 4 củ cà rốt rồi đếm xem còn mấy củ nhé!",
      remove_count: 4,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it7", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it8", asset: { kind: "emoji", ref: "🥕" } },
        { item_id: "it9", asset: { kind: "emoji", ref: "🥕" } },
      ],
      answer_options: [
        { option_id: "opt_4", value: 4, is_correct: false },
        { option_id: "opt_5", value: 5, is_correct: true },
        { option_id: "opt_6", value: 6, is_correct: false },
        { option_id: "opt_7", value: 7, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 9,
      remove_count: 4,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0009",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 4 chú cua trong nhóm 8 chú",
      instruction: "Bé bớt 4 chú cua xem còn mấy chú?",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.05"],
      learning_objective_codes: ["LO-C1.CNT.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 4 chú cua rồi xem còn lại mấy chú nhé!",
      remove_count: 4,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "🦀" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "🦀" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "🦀" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "🦀" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "🦀" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "🦀" } },
        { item_id: "it7", asset: { kind: "emoji", ref: "🦀" } },
        { item_id: "it8", asset: { kind: "emoji", ref: "🦀" } },
      ],
      answer_options: [
        { option_id: "opt_2", value: 2, is_correct: false },
        { option_id: "opt_4", value: 4, is_correct: true },
        { option_id: "opt_6", value: 6, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 8,
      remove_count: 4,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C1-REM-SET-0010",
      legacy_v1_ref: "D1-12",
      content_version: 1,
      template_code: "GT-029",
      title: "Bớt 4 quyển sách trong nhóm 10 quyển",
      instruction: "Bé bớt 4 quyển sách xem còn mấy quyển?",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.CNT.05"],
      learning_objective_codes: ["LO-C1.CNT.05-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy bớt 4 quyển sách rồi đếm xem còn mấy quyển nhé!",
      remove_count: 4,
      initial_items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it7", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it8", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it9", asset: { kind: "emoji", ref: "📚" } },
        { item_id: "it10", asset: { kind: "emoji", ref: "📚" } },
      ],
      answer_options: [
        { option_id: "opt_5", value: 5, is_correct: false },
        { option_id: "opt_6", value: 6, is_correct: true },
        { option_id: "opt_7", value: 7, is_correct: false },
        { option_id: "opt_8", value: 8, is_correct: false },
      ],
    },
    difficulty_params: {
      initial_count: 10,
      remove_count: 4,
      allow_retry: true,
      hint_after_ms: 8000,
      shuffle_items: true,
    },
  },
];
