import type { ContentSeed } from "#src/seed-content/types";

/**
 * Batch: SEED-GT034
 * Gõ theo nhịp (beat-sequence)
 * 10 levels, GT-034, legacy_v1_ref: "D3-06", band 5-6, themes: music, farm, nature, festival, school
 */
export const SEED_GT034: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-PAT-BEAT-0001",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Gõ nhịp trống 2 bước A-B-A-B",
      instruction: "Bé nghe mẫu nhịp rồi gõ lại theo nhạc cụ nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "pattern"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nghe mẫu nhịp rồi gõ lại theo đúng nhạc cụ nhé!",
      instruments: [
        {
          instrument_id: "drum",
          asset: { kind: "emoji", ref: "EMJ-drum" },
          freq: 220,
          type: "sine",
          name_vi: "Trống cái",
        },
        {
          instrument_id: "bell",
          asset: { kind: "emoji", ref: "EMJ-bell" },
          freq: 440,
          type: "triangle",
          name_vi: "Chuông nhỏ",
        },
      ],
      target_pattern: ["drum", "bell", "drum", "bell"],
      tempo_bpm: 80,
    },
    difficulty_params: {
      pattern_length: 4,
      instrument_count: 2,
      tempo_bpm: 80,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0002",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Gõ nhịp nông trại kêu A-B-A-B",
      instruction: "Bé nghe tiếng các bạn động vật rồi gõ theo nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "pattern"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nghe tiếng bạn bò và vịt rồi gõ theo nhé!",
      instruments: [
        {
          instrument_id: "cow",
          asset: { kind: "emoji", ref: "EMJ-cow" },
          freq: 180,
          type: "sine",
          name_vi: "Bò sữa",
        },
        {
          instrument_id: "duck",
          asset: { kind: "emoji", ref: "EMJ-duck" },
          freq: 520,
          type: "triangle",
          name_vi: "Vịt con",
        },
      ],
      target_pattern: ["cow", "duck", "cow", "duck"],
      tempo_bpm: 75,
    },
    difficulty_params: {
      pattern_length: 4,
      instrument_count: 2,
      tempo_bpm: 75,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0003",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Nhịp điệu 3 âm thanh A-B-C-A-B-C",
      instruction: "Bé lắng nghe chuỗi 3 âm thanh nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "sequence"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé lắng nghe 3 nhạc cụ hòa tấu rồi gõ lại nhé!",
      instruments: [
        {
          instrument_id: "bell",
          asset: { kind: "emoji", ref: "EMJ-bell" },
          freq: 523,
          type: "sine",
          name_vi: "Chuông",
        },
        {
          instrument_id: "drum",
          asset: { kind: "emoji", ref: "EMJ-drum" },
          freq: 261,
          type: "sine",
          name_vi: "Trống",
        },
        {
          instrument_id: "cymbal",
          asset: { kind: "emoji", ref: "EMJ-musical-score" },
          freq: 784,
          type: "triangle",
          name_vi: "Xèng",
        },
      ],
      target_pattern: ["bell", "drum", "cymbal", "bell", "drum", "cymbal"],
      tempo_bpm: 75,
    },
    difficulty_params: {
      pattern_length: 6,
      instrument_count: 3,
      tempo_bpm: 75,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0004",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Nhịp điệu có quãng nghỉ A-nghỉ-A-nghỉ",
      instruction: "Bé chú ý nhịp nghỉ giữa các tiếng vỗ tay nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "time"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chú ý những chỗ nghỉ trong nhịp điệu nhé!",
      instruments: [
        {
          instrument_id: "clap",
          asset: { kind: "emoji", ref: "EMJ-clapping-hands" },
          freq: 330,
          type: "triangle",
          name_vi: "Vỗ tay",
        },
        {
          instrument_id: "snap",
          asset: { kind: "emoji", ref: "EMJ-sparkles" },
          freq: 660,
          type: "sine",
          name_vi: "Búng tay",
        },
      ],
      target_pattern: ["clap", null, "clap", null],
      tempo_bpm: 70,
    },
    difficulty_params: {
      pattern_length: 4,
      instrument_count: 2,
      tempo_bpm: 70,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0005",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Nhịp rừng xanh A-A-B-A-A-B",
      instruction: "Bé nghe tiếng chim và tiếng gõ kiến nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "pattern"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nghe giai điệu rừng xanh rồi gõ theo nhé!",
      instruments: [
        {
          instrument_id: "bird",
          asset: { kind: "emoji", ref: "EMJ-bird" },
          freq: 600,
          type: "sine",
          name_vi: "Chim hót",
        },
        {
          instrument_id: "frog",
          asset: { kind: "emoji", ref: "EMJ-frog" },
          freq: 240,
          type: "triangle",
          name_vi: "Ếch kêu",
        },
      ],
      target_pattern: ["bird", "bird", "frog", "bird", "bird", "frog"],
      tempo_bpm: 80,
    },
    difficulty_params: {
      pattern_length: 6,
      instrument_count: 2,
      tempo_bpm: 80,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0006",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Lễ hội trống chiêng rộn rã",
      instruction: "Bé nghe tiếng trống hội rồi gõ lại nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "pattern"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé gõ theo nhịp trống chiêng lễ hội nhé!",
      instruments: [
        {
          instrument_id: "drum_low",
          asset: { kind: "emoji", ref: "EMJ-drum" },
          freq: 200,
          type: "sine",
          name_vi: "Trống hội",
        },
        {
          instrument_id: "gong",
          asset: { kind: "emoji", ref: "EMJ-musical-score" },
          freq: 500,
          type: "triangle",
          name_vi: "Chiêng đồng",
        },
      ],
      target_pattern: [
        "drum_low",
        "gong",
        "drum_low",
        "gong",
        "drum_low",
        "gong",
      ],
      tempo_bpm: 85,
    },
    difficulty_params: {
      pattern_length: 6,
      instrument_count: 2,
      tempo_bpm: 85,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0007",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Nhịp đập âm vang 4 bước lặp",
      instruction: "Bé gõ nhịp nhanh 4 bước lặp lại nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "sequence"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy gõ lại mẫu nhịp 4 bước này nhé!",
      instruments: [
        {
          instrument_id: "kick",
          asset: { kind: "emoji", ref: "EMJ-drum" },
          freq: 150,
          type: "sine",
          name_vi: "Trống cái",
        },
        {
          instrument_id: "snare",
          asset: { kind: "emoji", ref: "EMJ-sparkles" },
          freq: 400,
          type: "triangle",
          name_vi: "Trống con",
        },
      ],
      target_pattern: ["kick", "snare", "snare", "kick", "snare", "snare"],
      tempo_bpm: 90,
    },
    difficulty_params: {
      pattern_length: 6,
      instrument_count: 2,
      tempo_bpm: 90,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0008",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Khúc ca đồng cỏ mùa hạ",
      instruction: "Bé nghe khúc nhạc đồng quê nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "pattern"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nghe tiếng sáo và tiếng chuông đồng cỏ nhé!",
      instruments: [
        {
          instrument_id: "flute",
          asset: { kind: "emoji", ref: "EMJ-musical-score" },
          freq: 659,
          type: "sine",
          name_vi: "Tiếng sáo",
        },
        {
          instrument_id: "bell",
          asset: { kind: "emoji", ref: "EMJ-bell" },
          freq: 440,
          type: "triangle",
          name_vi: "Chuông reo",
        },
      ],
      target_pattern: ["flute", "bell", null, "flute", "bell", null],
      tempo_bpm: 75,
    },
    difficulty_params: {
      pattern_length: 6,
      instrument_count: 2,
      tempo_bpm: 75,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0009",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Giai điệu trường mẫu giáo",
      instruction: "Bé nghe nhịp gõ vui nhộn trong lớp học nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "time"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nghe giai điệu vui vẻ rồi gõ theo nhé!",
      instruments: [
        {
          instrument_id: "triangle",
          asset: { kind: "emoji", ref: "EMJ-musical-score" },
          freq: 880,
          type: "triangle",
          name_vi: "Tam giác sắt",
        },
        {
          instrument_id: "woodblock",
          asset: { kind: "emoji", ref: "EMJ-drum" },
          freq: 350,
          type: "sine",
          name_vi: "Mõ gỗ",
        },
      ],
      target_pattern: ["triangle", "woodblock", "triangle", "woodblock"],
      tempo_bpm: 80,
    },
    difficulty_params: {
      pattern_length: 4,
      instrument_count: 2,
      tempo_bpm: 80,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-PAT-BEAT-0010",
      legacy_v1_ref: "D3-06",
      content_version: 1,
      template_code: "GT-034",
      title: "Vũ điệu lễ hội pháo hoa",
      instruction: "Bé cùng hòa nhịp với bài ca lễ hội nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.PAT.01"],
      learning_objective_codes: ["LO-C1.PAT.01-01"],
      what_tags: ["sound", "pattern"],
      thinking_tags: ["observe", "infer", "predict"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé gõ nhịp 3 nhạc cụ chào đón lễ hội nhé!",
      instruments: [
        {
          instrument_id: "drum",
          asset: { kind: "emoji", ref: "EMJ-drum" },
          freq: 220,
          type: "sine",
          name_vi: "Trống",
        },
        {
          instrument_id: "bell",
          asset: { kind: "emoji", ref: "EMJ-bell" },
          freq: 440,
          type: "triangle",
          name_vi: "Chuông",
        },
        {
          instrument_id: "gong",
          asset: { kind: "emoji", ref: "EMJ-musical-score" },
          freq: 660,
          type: "sine",
          name_vi: "Chiêng",
        },
      ],
      target_pattern: ["drum", "bell", "gong", "drum", "bell", "gong"],
      tempo_bpm: 80,
    },
    difficulty_params: {
      pattern_length: 6,
      instrument_count: 3,
      tempo_bpm: 80,
      allow_replay: true,
      replay_limit: 3,
      hint_after_ms: 10_000,
    },
  },
];
