import type { ContentSeed } from "#src/seed-content/types";

/**
 * Batch: SEED-GT031
 * Gộp tiền xu (coin-compose)
 * 10 levels, GT-031, legacy_v1_ref: "D5-10", band 5-6, themes: food, school, farm, home, festival, vehicle
 */
export const SEED_GT031: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-COIN-CMP-0001",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua kẹo mút 3 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 3 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.MEAS.14"],
      learning_objective_codes: ["LO-C1.MEAS.14-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 3 đồng mua kẹo nhé!",
      target_amount: 3,
      item_to_buy: {
        label: "Kẹo mút",
        asset: { kind: "emoji", ref: "EMJ-lollipop" },
      },
      coins: [
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c1_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 2,
      target_amount: 3,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0002",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua quả táo đỏ 4 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 4 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.MEAS.14"],
      learning_objective_codes: ["LO-C1.MEAS.14-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 4 đồng mua quả táo nhé!",
      target_amount: 4,
      item_to_buy: {
        label: "Quả táo",
        asset: { kind: "emoji", ref: "EMJ-red-apple" },
      },
      coins: [
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c2_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 2,
      target_amount: 4,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0003",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua ổ bánh mì 5 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 5 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MEAS.14"],
      learning_objective_codes: ["LO-C1.MEAS.14-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 5 đồng mua bánh mì nhé!",
      target_amount: 5,
      item_to_buy: {
        label: "Bánh mì",
        asset: { kind: "emoji", ref: "EMJ-bread" },
      },
      coins: [
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c2_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c5_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 3,
      target_amount: 5,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0004",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua ly sữa tươi 5 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 5 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MEAS.14"],
      learning_objective_codes: ["LO-C1.MEAS.14-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 5 đồng mua hộp sữa nhé!",
      target_amount: 5,
      item_to_buy: {
        label: "Hộp sữa",
        asset: { kind: "emoji", ref: "EMJ-milk" },
      },
      coins: [
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c1_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c1_3",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 2,
      target_amount: 5,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0005",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua quả dưa hấu 6 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 6 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MEAS.14"],
      learning_objective_codes: ["LO-C1.MEAS.14-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 6 đồng mua dưa hấu nhé!",
      target_amount: 6,
      item_to_buy: {
        label: "Dưa hấu",
        asset: { kind: "emoji", ref: "EMJ-watermelon" },
      },
      coins: [
        {
          coin_id: "c5_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 3,
      target_amount: 6,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0006",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua ô tô đồ chơi 7 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 7 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "login",
      skill_codes: ["C1.MEAS.15"],
      learning_objective_codes: ["LO-C1.MEAS.15-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 7 đồng mua ô tô nhé!",
      target_amount: 7,
      item_to_buy: {
        label: "Ô tô",
        asset: { kind: "emoji", ref: "EMJ-car" },
      },
      coins: [
        {
          coin_id: "c5_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c2_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 3,
      target_amount: 7,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0007",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua bút chì màu 8 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 8 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "login",
      skill_codes: ["C1.MEAS.15"],
      learning_objective_codes: ["LO-C1.MEAS.15-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 8 đồng mua bút chì màu nhé!",
      target_amount: 8,
      item_to_buy: {
        label: "Bút chì",
        asset: { kind: "emoji", ref: "EMJ-crayon" },
      },
      coins: [
        {
          coin_id: "c5_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
        {
          coin_id: "c1_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 3,
      target_amount: 8,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0008",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua gấu bông đáng yêu 9 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 9 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "login",
      skill_codes: ["C1.MEAS.15"],
      learning_objective_codes: ["LO-C1.MEAS.15-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 9 đồng mua gấu bông nhé!",
      target_amount: 9,
      item_to_buy: {
        label: "Gấu bông",
        asset: { kind: "emoji", ref: "EMJ-teddy-bear" },
      },
      coins: [
        {
          coin_id: "c5_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c2_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 3,
      target_amount: 9,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0009",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua quả bóng tròn 10 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 10 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "login",
      skill_codes: ["C1.MEAS.15"],
      learning_objective_codes: ["LO-C1.MEAS.15-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 10 đồng mua quả bóng nhé!",
      target_amount: 10,
      item_to_buy: {
        label: "Quả bóng",
        asset: { kind: "emoji", ref: "EMJ-soccer" },
      },
      coins: [
        {
          coin_id: "c5_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
        {
          coin_id: "c5_2",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 3,
      target_amount: 10,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-COIN-CMP-0010",
      legacy_v1_ref: "D5-10",
      content_version: 1,
      template_code: "GT-031",
      title: "Mua chiếc bánh kem 12 đồng",
      instruction: "Bé chọn các đồng xu trả đúng 12 đồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "login",
      skill_codes: ["C1.MEAS.15"],
      learning_objective_codes: ["LO-C1.MEAS.15-01"],
      what_tags: ["money"],
      thinking_tags: ["count", "plan"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chọn các đồng xu để trả đúng 12 đồng mua bánh kem nhé!",
      target_amount: 12,
      item_to_buy: {
        label: "Bánh kem",
        asset: { kind: "emoji", ref: "EMJ-birthday-cake" },
      },
      coins: [
        {
          coin_id: "c10_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 10,
        },
        {
          coin_id: "c2_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 2,
        },
        {
          coin_id: "c5_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 5,
        },
        {
          coin_id: "c1_1",
          asset: { kind: "emoji", ref: "EMJ-coin" },
          value: 1,
        },
      ],
    },
    difficulty_params: {
      coin_kind_count: 4,
      target_amount: 12,
      exact_change: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
];
