import type { ContentSeed } from "#src/seed-content/types";

/**
 * Batch: SEED-GT028
 * Chạm đếm tích luỹ (tap-count)
 * 10 levels, GT-028, band 4-5 & 5-6, themes: school, farm, nature, food
 */
export const SEED_GT028: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-CNT-TAP-0001",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm chuông theo bước 2",
      instruction: "Bé chạm đếm chuông theo bước 2 cho đủ 6 nhé!",
      age_min: 4,
      age_max: 5,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm chuông theo bước 2 cho đủ 6 nhé!",
      step: 2,
      target_total: 6,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-bell" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-bell" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-bell" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-bell" } },
      ],
    },
    difficulty_params: {
      step: 2,
      target_total: 6,
      item_count: 4,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0002",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm táo theo bước 2",
      instruction: "Bé chạm đếm táo theo bước 2 cho đủ 8 nhé!",
      age_min: 4,
      age_max: 5,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm táo theo bước 2 cho đủ 8 nhé!",
      step: 2,
      target_total: 8,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-red-apple" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-red-apple" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-red-apple" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-red-apple" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "EMJ-red-apple" } },
      ],
    },
    difficulty_params: {
      step: 2,
      target_total: 8,
      item_count: 5,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0003",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm ngôi sao theo bước 5",
      instruction: "Bé chạm đếm sao theo bước 5 cho đủ 15 nhé!",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "free",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm sao theo bước 5 cho đủ 15 nhé!",
      step: 5,
      target_total: 15,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-star" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-star" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-star" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-star" } },
      ],
    },
    difficulty_params: {
      step: 5,
      target_total: 15,
      item_count: 4,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0004",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm dâu tây theo bước 2",
      instruction: "Bé chạm đếm dâu theo bước 2 cho đủ 10 nhé!",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm dâu theo bước 2 cho đủ 10 nhé!",
      step: 2,
      target_total: 10,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-strawberry" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-strawberry" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-strawberry" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-strawberry" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "EMJ-strawberry" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "EMJ-strawberry" } },
      ],
    },
    difficulty_params: {
      step: 2,
      target_total: 10,
      item_count: 6,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0005",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm bút chì theo bước 5",
      instruction: "Bé chạm đếm bút theo bước 5 cho đủ 20 nhé!",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.03"],
      learning_objective_codes: ["LO-C1.CNT.03-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm bút theo bước 5 cho đủ 20 nhé!",
      step: 5,
      target_total: 20,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-pencil" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-pencil" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-pencil" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-pencil" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "EMJ-pencil" } },
      ],
    },
    difficulty_params: {
      step: 5,
      target_total: 20,
      item_count: 5,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0006",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm hoa hướng dương theo bước 5",
      instruction: "Bé chạm đếm hoa theo bước 5 cho đủ 25 nhé!",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.CNT.04"],
      learning_objective_codes: ["LO-C1.CNT.04-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm hoa theo bước 5 cho đủ 25 nhé!",
      step: 5,
      target_total: 25,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "EMJ-sunflower" } },
      ],
    },
    difficulty_params: {
      step: 5,
      target_total: 25,
      item_count: 6,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0007",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm đồng xu theo bước 10",
      instruction: "Bé chạm đếm xu theo bước 10 cho đủ 30 nhé!",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.CNT.04"],
      learning_objective_codes: ["LO-C1.CNT.04-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm xu theo bước 10 cho đủ 30 nhé!",
      step: 10,
      target_total: 30,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-coin" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-coin" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-coin" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-coin" } },
      ],
    },
    difficulty_params: {
      step: 10,
      target_total: 30,
      item_count: 4,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0008",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm cà rốt theo bước 10",
      instruction: "Bé chạm đếm cà rốt theo bước 10 cho đủ 40 nhé!",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.CNT.04"],
      learning_objective_codes: ["LO-C1.CNT.04-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm cà rốt theo bước 10 cho đủ 40 nhé!",
      step: 10,
      target_total: 40,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-carrot" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-carrot" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-carrot" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-carrot" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "EMJ-carrot" } },
      ],
    },
    difficulty_params: {
      step: 10,
      target_total: 40,
      item_count: 5,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0009",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm quả cam theo bước 10",
      instruction: "Bé chạm đếm cam theo bước 10 cho đủ 50 nhé!",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.CNT.04"],
      learning_objective_codes: ["LO-C1.CNT.04-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm cam theo bước 10 cho đủ 50 nhé!",
      step: 10,
      target_total: 50,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-orange" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-orange" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-orange" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-orange" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "EMJ-orange" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "EMJ-orange" } },
      ],
    },
    difficulty_params: {
      step: 10,
      target_total: 50,
      item_count: 6,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
  {
    header: {
      code: "GL-C1-CNT-TAP-0010",
      legacy_v1_ref: "D1-10",
      content_version: 1,
      template_code: "GT-028",
      title: "Chạm đếm cá bơi theo bước 5",
      instruction: "Bé chạm đếm cá theo bước 5 cho đủ 30 nhé!",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.CNT.04"],
      learning_objective_codes: ["LO-C1.CNT.04-01"],
      what_tags: ["cnt"],
      thinking_tags: ["count", "observe"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm đếm cá theo bước 5 cho đủ 30 nhé!",
      step: 5,
      target_total: 30,
      items: [
        { item_id: "it1", asset: { kind: "emoji", ref: "EMJ-tropical-fish" } },
        { item_id: "it2", asset: { kind: "emoji", ref: "EMJ-tropical-fish" } },
        { item_id: "it3", asset: { kind: "emoji", ref: "EMJ-tropical-fish" } },
        { item_id: "it4", asset: { kind: "emoji", ref: "EMJ-tropical-fish" } },
        { item_id: "it5", asset: { kind: "emoji", ref: "EMJ-tropical-fish" } },
        { item_id: "it6", asset: { kind: "emoji", ref: "EMJ-tropical-fish" } },
        { item_id: "it7", asset: { kind: "emoji", ref: "EMJ-tropical-fish" } },
      ],
    },
    difficulty_params: {
      step: 5,
      target_total: 30,
      item_count: 7,
      show_counter_badge: true,
      allow_undo: true,
    },
  },
];
