import type { ContentSeed } from "#src/seed-content/types";

/**
 * Batch: SEED-GT030
 * Đo bằng đơn vị lặp (measure-with-unit)
 * 10 levels, GT-030, legacy_v1_ref: "D5-04", band 5-6, themes: school, farm, food, nature, vehicle, ocean, space
 */
export const SEED_GT030: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-MSR-UNIT-0001",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo cây bút chì bằng kẹp giấy (4 đơn vị)",
      instruction: "Bé xếp kẹp giấy đo chiều dài bút nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "free",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé hãy xếp các chiếc kẹp giấy để đo xem bút chì dài mấy kẹp giấy nhé!",
      object: {
        object_id: "obj_pencil",
        asset: { kind: "emoji", ref: "EMJ-pencil" },
        length_in_units: 4,
      },
      unit: {
        unit_id: "unit_clip",
        asset: { kind: "emoji", ref: "EMJ-paperclip" },
      },
      answer_options: [
        { option_id: "opt_3", value: 3, is_correct: false },
        { option_id: "opt_4", value: 4, is_correct: true },
        { option_id: "opt_5", value: 5, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 4,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0002",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo củ cà rốt bằng cúc áo (4 đơn vị)",
      instruction: "Bé xếp cúc áo đo chiều dài củ cà rốt nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "free",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count", "observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các cúc áo để đo xem củ cà rốt dài mấy cúc áo nhé!",
      object: {
        object_id: "obj_carrot",
        asset: { kind: "emoji", ref: "EMJ-carrot" },
        length_in_units: 4,
      },
      unit: {
        unit_id: "unit_button",
        asset: { kind: "emoji", ref: "EMJ-radio-button" },
      },
      answer_options: [
        { option_id: "opt_3", value: 3, is_correct: false },
        { option_id: "opt_4", value: 4, is_correct: true },
        { option_id: "opt_5", value: 5, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 4,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0003",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo quả dưa chuột bằng quả cherry (5 đơn vị)",
      instruction: "Bé xếp quả cherry đo chiều dài dưa chuột nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các quả cherry để đo chiều dài quả dưa chuột nhé!",
      object: {
        object_id: "obj_cucumber",
        asset: { kind: "emoji", ref: "EMJ-cucumber" },
        length_in_units: 5,
      },
      unit: {
        unit_id: "unit_cherry",
        asset: { kind: "emoji", ref: "EMJ-cherries" },
      },
      answer_options: [
        { option_id: "opt_4", value: 4, is_correct: false },
        { option_id: "opt_5", value: 5, is_correct: true },
        { option_id: "opt_6", value: 6, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 5,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0004",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo thước kẻ bằng bút chì (5 đơn vị)",
      instruction: "Bé xếp bút chì đo chiều dài thước kẻ nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé hãy xếp các cây bút chì để đo xem thước kẻ dài mấy bút chì nhé!",
      object: {
        object_id: "obj_ruler",
        asset: { kind: "emoji", ref: "EMJ-ruler" },
        length_in_units: 5,
      },
      unit: {
        unit_id: "unit_pencil",
        asset: { kind: "emoji", ref: "EMJ-pencil" },
      },
      answer_options: [
        { option_id: "opt_3", value: 3, is_correct: false },
        { option_id: "opt_4", value: 4, is_correct: false },
        { option_id: "opt_5", value: 5, is_correct: true },
        { option_id: "opt_6", value: 6, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 5,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0005",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo đoàn tàu bằng khối vuông (6 đơn vị)",
      instruction: "Bé xếp khối vuông đo chiều dài đoàn tàu nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các khối vuông đo xem đoàn tàu dài mấy khối nhé!",
      object: {
        object_id: "obj_train",
        asset: { kind: "emoji", ref: "EMJ-locomotive" },
        length_in_units: 6,
      },
      unit: {
        unit_id: "unit_block",
        asset: { kind: "emoji", ref: "EMJ-blue-square" },
      },
      answer_options: [
        { option_id: "opt_4", value: 4, is_correct: false },
        { option_id: "opt_5", value: 5, is_correct: false },
        { option_id: "opt_6", value: 6, is_correct: true },
        { option_id: "opt_7", value: 7, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 6,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0006",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo chú cá bằng vỏ sò (6 đơn vị)",
      instruction: "Bé xếp vỏ sò đo chiều dài chú cá nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các vỏ sò đo xem chú cá dài mấy vỏ sò nhé!",
      object: {
        object_id: "obj_fish",
        asset: { kind: "emoji", ref: "EMJ-tropical-fish" },
        length_in_units: 6,
      },
      unit: {
        unit_id: "unit_shell",
        asset: { kind: "emoji", ref: "EMJ-spiral-shell" },
      },
      answer_options: [
        { option_id: "opt_5", value: 5, is_correct: false },
        { option_id: "opt_6", value: 6, is_correct: true },
        { option_id: "opt_7", value: 7, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 6,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0007",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo tên lửa bằng ngôi sao (7 đơn vị)",
      instruction: "Bé xếp ngôi sao đo chiều dài tên lửa nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các ngôi sao đo xem tên lửa dài mấy ngôi sao nhé!",
      object: {
        object_id: "obj_rocket",
        asset: { kind: "emoji", ref: "EMJ-rocket" },
        length_in_units: 7,
      },
      unit: {
        unit_id: "unit_star",
        asset: { kind: "emoji", ref: "EMJ-star" },
      },
      answer_options: [
        { option_id: "opt_5", value: 5, is_correct: false },
        { option_id: "opt_6", value: 6, is_correct: false },
        { option_id: "opt_7", value: 7, is_correct: true },
        { option_id: "opt_8", value: 8, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 7,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0008",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo cây cọ vẽ bằng bút chì (7 đơn vị)",
      instruction: "Bé xếp bút chì đo chiều dài cọ vẽ nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các cây bút chì đo xem cọ vẽ dài mấy bút chì nhé!",
      object: {
        object_id: "obj_brush",
        asset: { kind: "emoji", ref: "EMJ-paintbrush" },
        length_in_units: 7,
      },
      unit: {
        unit_id: "unit_pencil",
        asset: { kind: "emoji", ref: "EMJ-pencil" },
      },
      answer_options: [
        { option_id: "opt_6", value: 6, is_correct: false },
        { option_id: "opt_7", value: 7, is_correct: true },
        { option_id: "opt_8", value: 8, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 7,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0009",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo bắp ngô bằng mầm cây (8 đơn vị)",
      instruction: "Bé xếp mầm cây đo chiều dài bắp ngô nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các mầm cây đo xem bắp ngô dài mấy mầm cây nhé!",
      object: {
        object_id: "obj_corn",
        asset: { kind: "emoji", ref: "EMJ-ear-of-corn" },
        length_in_units: 8,
      },
      unit: {
        unit_id: "unit_sprout",
        asset: { kind: "emoji", ref: "EMJ-seedling" },
      },
      answer_options: [
        { option_id: "opt_6", value: 6, is_correct: false },
        { option_id: "opt_7", value: 7, is_correct: false },
        { option_id: "opt_8", value: 8, is_correct: true },
        { option_id: "opt_9", value: 9, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 8,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-MSR-UNIT-0010",
      legacy_v1_ref: "D5-04",
      content_version: 1,
      template_code: "GT-030",
      title: "Đo bánh mì bằng quả dâu tây (8 đơn vị)",
      instruction: "Bé xếp quả dâu đo chiều dài bánh mì nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C1.MEAS.01"],
      learning_objective_codes: ["LO-C1.MEAS.01-01"],
      what_tags: ["size"],
      thinking_tags: ["count"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các quả dâu tây đo xem bánh mì dài mấy quả dâu nhé!",
      object: {
        object_id: "obj_bread",
        asset: { kind: "emoji", ref: "EMJ-baguette-bread" },
        length_in_units: 8,
      },
      unit: {
        unit_id: "unit_strawberry",
        asset: { kind: "emoji", ref: "EMJ-strawberry" },
      },
      answer_options: [
        { option_id: "opt_7", value: 7, is_correct: false },
        { option_id: "opt_8", value: 8, is_correct: true },
        { option_id: "opt_9", value: 9, is_correct: false },
        { option_id: "opt_10", value: 10, is_correct: false },
      ],
    },
    difficulty_params: {
      length_in_units: 8,
      gap_tolerance_pct: 10,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
];
