import type { ContentSeed } from "#src/seed-content/types";

/**
 * Batch: SEED-GT035
 * Xếp hàng lệnh (command-sequence)
 * 10 levels, GT-035, legacy_v1_ref: "D6-05", band 5-6, themes: space, home, school, farm, nature, ocean, festival
 */
export const SEED_GT035: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-ALG-CMD-0001",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Robot đi thẳng về trạm sạc",
      instruction: "Bé xếp mũi tên để đưa robot về trạm pin nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp mũi tên để đưa robot về trạm sạc pin nhé!",
      grid: { rows: 3, cols: 3 },
      start: { col: 0, row: 0, facing: "right" },
      goal: {
        col: 2,
        row: 0,
        asset: { kind: "emoji", ref: "EMJ-rocket" },
      },
      obstacles: [],
      collectibles: [],
      allowed_commands: ["forward", "turn_left", "turn_right"],
    },
    difficulty_params: {
      max_commands: 4,
      obstacle_count: 0,
      collectible_count: 0,
      allow_loop: false,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0002",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Robot rẽ phải về đích",
      instruction: "Bé lập trình robot đi thẳng và rẽ phải nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé lập trình robot đi thẳng và rẽ phải về trạm pin nhé!",
      grid: { rows: 3, cols: 3 },
      start: { col: 0, row: 0, facing: "right" },
      goal: {
        col: 2,
        row: 2,
        asset: { kind: "emoji", ref: "EMJ-rocket" },
      },
      obstacles: [],
      collectibles: [],
      allowed_commands: ["forward", "turn_left", "turn_right"],
    },
    difficulty_params: {
      max_commands: 6,
      obstacle_count: 0,
      collectible_count: 0,
      allow_loop: false,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0003",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Tàu thám hiểm về trạm",
      instruction: "Bé đưa tàu thám hiểm về trạm vũ trụ nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé đưa tàu thám hiểm về trạm vũ trụ nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 0, row: 3, facing: "up" },
      goal: {
        col: 2,
        row: 0,
        asset: { kind: "emoji", ref: "EMJ-rocket" },
      },
      obstacles: [],
      collectibles: [],
      allowed_commands: ["forward", "turn_left", "turn_right", "loop"],
    },
    difficulty_params: {
      max_commands: 6,
      obstacle_count: 0,
      collectible_count: 0,
      allow_loop: true,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0004",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Vượt chướng ngại vật về nhà",
      instruction: "Bé lập trình robot tránh vật cản về nhà nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé lập trình robot tránh chướng ngại vật về nhà nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 0, row: 0, facing: "right" },
      goal: {
        col: 3,
        row: 0,
        asset: { kind: "emoji", ref: "EMJ-house" },
      },
      obstacles: [{ col: 2, row: 0 }],
      collectibles: [],
      allowed_commands: ["forward", "turn_left", "turn_right"],
    },
    difficulty_params: {
      max_commands: 8,
      obstacle_count: 1,
      collectible_count: 0,
      allow_loop: false,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0005",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Nhặt sách đến trường",
      instruction: "Bé nhặt quyển sách rồi đến lớp học nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.PAT.05"],
      learning_objective_codes: ["LO-C1.PAT.05-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nhặt quyển sách rồi đến lớp học nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 0, row: 0, facing: "right" },
      goal: {
        col: 3,
        row: 0,
        asset: { kind: "emoji", ref: "EMJ-backpack" },
      },
      obstacles: [{ col: 2, row: 0 }],
      collectibles: [
        {
          col: 1,
          row: 1,
          id: "book_1",
          asset: { kind: "emoji", ref: "EMJ-open-book" },
        },
      ],
      allowed_commands: ["forward", "turn_left", "turn_right"],
    },
    difficulty_params: {
      max_commands: 8,
      obstacle_count: 1,
      collectible_count: 1,
      allow_loop: false,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0006",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Thu hoạch táo về chuồng trại",
      instruction: "Bé dẫn robot thu hoạch táo về chuồng nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C1.PAT.07"],
      learning_objective_codes: ["LO-C1.PAT.07-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé dẫn robot thu hoạch quả táo rồi về chuồng trại nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 0, row: 2, facing: "up" },
      goal: {
        col: 3,
        row: 3,
        asset: { kind: "emoji", ref: "EMJ-house" },
      },
      obstacles: [{ col: 1, row: 3 }],
      collectibles: [
        {
          col: 0,
          row: 1,
          id: "apple_1",
          asset: { kind: "emoji", ref: "EMJ-red-apple" },
        },
      ],
      allowed_commands: ["forward", "turn_left", "turn_right", "loop"],
    },
    difficulty_params: {
      max_commands: 8,
      obstacle_count: 1,
      collectible_count: 1,
      allow_loop: true,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0007",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Hái hoa về gốc cây cổ thụ",
      instruction: "Bé hái bông hoa rồi đi đến cây cổ thụ nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "standard",
      skill_codes: ["C1.PAT.07"],
      learning_objective_codes: ["LO-C1.PAT.07-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hái bông hoa rồi đi đến cây cổ thụ nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 0, row: 0, facing: "down" },
      goal: {
        col: 3,
        row: 3,
        asset: { kind: "emoji", ref: "EMJ-deciduous-tree" },
      },
      obstacles: [{ col: 0, row: 2 }],
      collectibles: [
        {
          col: 1,
          row: 1,
          id: "flower_1",
          asset: { kind: "emoji", ref: "EMJ-sunflower" },
        },
      ],
      allowed_commands: ["forward", "turn_left", "turn_right", "loop"],
    },
    difficulty_params: {
      max_commands: 8,
      obstacle_count: 1,
      collectible_count: 1,
      allow_loop: true,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0008",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Thu thập ngọc trai dưới biển",
      instruction: "Bé tìm ngọc trai rồi đưa tàu về mỏ neo nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C1.PAT.07"],
      learning_objective_codes: ["LO-C1.PAT.07-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tìm viên ngọc trai rồi đưa tàu ngầm về mỏ neo nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 0, row: 0, facing: "right" },
      goal: {
        col: 2,
        row: 2,
        asset: { kind: "emoji", ref: "EMJ-anchor" },
      },
      obstacles: [{ col: 1, row: 0 }],
      collectibles: [
        {
          col: 0,
          row: 2,
          id: "gem_1",
          asset: { kind: "emoji", ref: "EMJ-gem-stone" },
        },
      ],
      allowed_commands: ["forward", "turn_left", "turn_right"],
    },
    difficulty_params: {
      max_commands: 8,
      obstacle_count: 1,
      collectible_count: 1,
      allow_loop: false,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0009",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Lượm bóng bay nhận cúp lễ hội",
      instruction: "Bé nhặt bóng bay rồi đến sân khấu nhận cúp nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 5,
      access_tier: "premium",
      skill_codes: ["C1.PAT.07"],
      learning_objective_codes: ["LO-C1.PAT.07-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nhặt bóng bay rồi đến sân khấu nhận cúp nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 0, row: 3, facing: "right" },
      goal: {
        col: 3,
        row: 0,
        asset: { kind: "emoji", ref: "EMJ-trophy" },
      },
      obstacles: [{ col: 2, row: 3 }],
      collectibles: [
        {
          col: 1,
          row: 1,
          id: "balloon_1",
          asset: { kind: "emoji", ref: "EMJ-balloon" },
        },
      ],
      allowed_commands: ["forward", "turn_left", "turn_right", "loop"],
    },
    difficulty_params: {
      max_commands: 8,
      obstacle_count: 1,
      collectible_count: 1,
      allow_loop: true,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
  {
    header: {
      code: "GL-C1-ALG-CMD-0010",
      legacy_v1_ref: "D6-05",
      content_version: 1,
      template_code: "GT-035",
      title: "Nhặt bánh răng về trạm sửa chữa",
      instruction: "Bé nhặt bánh răng sửa chữa rồi về trạm sạc nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 5,
      access_tier: "premium",
      skill_codes: ["C1.PAT.07"],
      learning_objective_codes: ["LO-C1.PAT.07-01"],
      what_tags: ["flw", "space"],
      thinking_tags: ["plan", "observe", "predict"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nhặt bánh răng sửa chữa rồi về trạm sạc pin nhé!",
      grid: { rows: 4, cols: 4 },
      start: { col: 3, row: 3, facing: "left" },
      goal: {
        col: 0,
        row: 0,
        asset: { kind: "emoji", ref: "EMJ-rocket" },
      },
      obstacles: [{ col: 1, row: 1 }],
      collectibles: [
        {
          col: 2,
          row: 0,
          id: "gear_1",
          asset: { kind: "emoji", ref: "EMJ-gear" },
        },
      ],
      allowed_commands: ["forward", "turn_left", "turn_right", "loop"],
    },
    difficulty_params: {
      max_commands: 8,
      obstacle_count: 1,
      collectible_count: 1,
      allow_loop: true,
      allow_retry: true,
      hint_after_ms: 10_000,
    },
  },
];
