import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C2_GEO_01_IDENTITY: SkillIdentity = {
  code: "C2.GEO.01",
  strand_code: "C2.GEO",
  competency_code: "C2",
  name: "Hình tròn",
  age_min: 3,
  age_max: 3,
  difficulty: 1,
  thinking_processes: ["observe"],
  tier: "basic",
  prerequisites: [],
  learning_objectives: [
    {
      code: "LO-C2.GEO.01-01",
      behaviour: "Nhận biết và thực hành Hình tròn ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C2.GEO.01-02",
      behaviour: "Vận dụng Hình tròn trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C2.GEO.01-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Hình tròn",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C2_GEO_01_DATASET: SkillDataset = {
  skill_code: "C2.GEO.01",
  concept_label: "Hình tròn",
  surface: "game",
  items: [
    {
      id: "circle",
      label: "hình tròn",
      image: {
        kind: "emoji",
        ref: "🔴",
      },
      category: {
        type: "shape",
      },
    },
    {
      id: "square",
      label: "hình vuông",
      image: {
        kind: "emoji",
        ref: "🟦",
      },
      category: {
        type: "shape",
      },
    },
    {
      id: "triangle",
      label: "hình tam giác",
      image: {
        kind: "emoji",
        ref: "🔺",
      },
      category: {
        type: "shape",
      },
    },
    {
      id: "rectangle",
      label: "hình chữ nhật",
      image: {
        kind: "emoji",
        ref: "🟧",
      },
      category: {
        type: "shape",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Hình tròn",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Hình tròn",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Hình tròn nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ hình {label} nhé!",
  },
  ordering: ["circle", "square", "triangle", "rectangle"],
};

export const C2_GEO_01_SEED: SkillSeed = {
  identity: C2_GEO_01_IDENTITY,
  dataset: C2_GEO_01_DATASET,
  levels: [
    {
      code: "GL-C2-SHP-CARD-0001",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-SHP-CARD-0002",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-SHP-CARD-0003",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-SORT-SHP-0006",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-SORT-SHP-0007",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-CMP-SIZ-0008",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C2-SEQ-PAT-0011",
      template: "GT-008",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-SEQ-PAT-0012",
      template: "GT-008",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-SUB-FAST-0013",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-SORT-SHP-0015",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-CMP-SIZ-0017",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C2-SEQ-PAT-0018",
      template: "GT-011",
      band: "5-6",
      difficulty: 4,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-MIR-COMP-0024",
      template: "GT-021",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-MIR-COMP-0025",
      template: "GT-021",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-MIR-COMP-0026",
      template: "GT-021",
      band: "5-6",
      difficulty: 4,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-03",
    },
    {
      code: "GL-C2-CON-SHP-0027",
      template: "GT-023",
      band: "4-5",
      difficulty: 1,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D2-07",
    },
    {
      code: "GL-C2-CON-SHP-0028",
      template: "GT-023",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-07",
    },
    {
      code: "GL-C2-CON-SHP-0029",
      template: "GT-023",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D2-07",
    },
    {
      code: "GL-C2-TRC-PTH-0030",
      template: "GT-024",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C2-TRC-PTH-0031",
      template: "GT-024",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C2-TRC-PTH-0032",
      template: "GT-024",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C2-TRC-PTH-0033",
      template: "GT-024",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C2-SHP-FLIP-0030",
      template: "GT-020",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D6-11",
    },
    {
      code: "GL-C2-GEO-MATCH-0101",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      montessori_ref: "WB19-D1",
    },
    {
      code: "GL-C2-GEO-INTRO-0001",
      template: "GT-000",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C2-GEO-PATT-0001",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "food",
      rounds: 3,
    },
  ],
};
