import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C5_ALP_04_IDENTITY: SkillIdentity = {
  code: "C5.ALP.04",
  strand_code: "C5.ALP",
  competency_code: "C5",
  name: "Nhận đủ 29 chữ cái",
  age_min: 6,
  age_max: 7,
  difficulty: 4,
  thinking_processes: ["observe", "recall"],
  tier: "advanced",
  prerequisites: ["C5.ALP.03", "C5.LET.05"],
  learning_objectives: [
    {
      code: "LO-C5.ALP.04-01",
      behaviour: "Nhận biết và thực hành Nhận đủ 29 chữ cái ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C5.ALP.04-02",
      behaviour: "Vận dụng Nhận đủ 29 chữ cái trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C5.ALP.04-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Nhận đủ 29 chữ cái",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C5_ALP_04_DATASET: SkillDataset = {
  skill_code: "C5.ALP.04",
  concept_label: "Nhận đủ 29 chữ cái",
  surface: "game",
  items: [
    {
      id: "let_a",
      label: "chữ a",
      glyph: "a",
      image: { kind: "emoji", ref: "🅰️" },
      contrast_group: "primary",
    },
    {
      id: "let_ă",
      label: "chữ ă",
      glyph: "ă",
      image: { kind: "emoji", ref: "🅰️" },
      contrast_group: "contrast",
    },
    {
      id: "let_â",
      label: "chữ â",
      glyph: "â",
      image: { kind: "emoji", ref: "🅰️" },
      contrast_group: "contrast",
    },
    {
      id: "let_b",
      label: "chữ b",
      glyph: "b",
      image: { kind: "emoji", ref: "🅱️" },
      contrast_group: "primary",
    },
    {
      id: "let_c",
      label: "chữ c",
      glyph: "c",
      image: { kind: "emoji", ref: "🅲" },
      contrast_group: "primary",
    },
    {
      id: "let_d",
      label: "chữ d",
      glyph: "d",
      image: { kind: "emoji", ref: "🅳" },
      contrast_group: "primary",
    },
    {
      id: "let_đ",
      label: "chữ đ",
      glyph: "đ",
      image: { kind: "emoji", ref: "🅳" },
      contrast_group: "contrast",
    },
    {
      id: "let_e",
      label: "chữ e",
      glyph: "e",
      image: { kind: "emoji", ref: "🅴" },
      contrast_group: "primary",
    },
    {
      id: "let_ê",
      label: "chữ ê",
      glyph: "ê",
      image: { kind: "emoji", ref: "🅴" },
      contrast_group: "contrast",
    },
    {
      id: "let_g",
      label: "chữ g",
      glyph: "g",
      image: { kind: "emoji", ref: "🅶" },
      contrast_group: "primary",
    },
    {
      id: "let_h",
      label: "chữ h",
      glyph: "h",
      image: { kind: "emoji", ref: "🅷" },
      contrast_group: "primary",
    },
    {
      id: "let_i",
      label: "chữ i",
      glyph: "i",
      image: { kind: "emoji", ref: "🅸" },
      contrast_group: "primary",
    },
    {
      id: "let_k",
      label: "chữ k",
      glyph: "k",
      image: { kind: "emoji", ref: "🅺" },
      contrast_group: "primary",
    },
    {
      id: "let_l",
      label: "chữ l",
      glyph: "l",
      image: { kind: "emoji", ref: "🅻" },
      contrast_group: "primary",
    },
    {
      id: "let_m",
      label: "chữ m",
      glyph: "m",
      image: { kind: "emoji", ref: "🅼" },
      contrast_group: "primary",
    },
    {
      id: "let_n",
      label: "chữ n",
      glyph: "n",
      image: { kind: "emoji", ref: "🅽" },
      contrast_group: "primary",
    },
    {
      id: "let_o",
      label: "chữ o",
      glyph: "o",
      image: { kind: "emoji", ref: "🅾️" },
      contrast_group: "primary",
    },
    {
      id: "let_ô",
      label: "chữ ô",
      glyph: "ô",
      image: { kind: "emoji", ref: "🅾️" },
      contrast_group: "contrast",
    },
    {
      id: "let_ơ",
      label: "chữ ơ",
      glyph: "ơ",
      image: { kind: "emoji", ref: "🅾️" },
      contrast_group: "contrast",
    },
    {
      id: "let_p",
      label: "chữ p",
      glyph: "p",
      image: { kind: "emoji", ref: "🅿️" },
      contrast_group: "primary",
    },
    {
      id: "let_q",
      label: "chữ q",
      glyph: "q",
      image: { kind: "emoji", ref: "🆀" },
      contrast_group: "primary",
    },
    {
      id: "let_r",
      label: "chữ r",
      glyph: "r",
      image: { kind: "emoji", ref: "🆁" },
      contrast_group: "primary",
    },
    {
      id: "let_s",
      label: "chữ s",
      glyph: "s",
      image: { kind: "emoji", ref: "🆂" },
      contrast_group: "primary",
    },
    {
      id: "let_t",
      label: "chữ t",
      glyph: "t",
      image: { kind: "emoji", ref: "🆃" },
      contrast_group: "primary",
    },
    {
      id: "let_u",
      label: "chữ u",
      glyph: "u",
      image: { kind: "emoji", ref: "🆄" },
      contrast_group: "primary",
    },
    {
      id: "let_ư",
      label: "chữ ư",
      glyph: "ư",
      image: { kind: "emoji", ref: "🆄" },
      contrast_group: "contrast",
    },
    {
      id: "let_v",
      label: "chữ v",
      glyph: "v",
      image: { kind: "emoji", ref: "🆅" },
      contrast_group: "primary",
    },
    {
      id: "let_x",
      label: "chữ x",
      glyph: "x",
      image: { kind: "emoji", ref: "🆇" },
      contrast_group: "primary",
    },
    {
      id: "let_y",
      label: "chữ y",
      glyph: "y",
      image: { kind: "emoji", ref: "🆈" },
      contrast_group: "primary",
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Nhận đủ 29 chữ cái",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Nhận đủ 29 chữ cái",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Nhận đủ 29 chữ cái nhé",
  },
  ordering: [
    "let_a",
    "let_ă",
    "let_â",
    "let_b",
    "let_c",
    "let_d",
    "let_đ",
    "let_e",
    "let_ê",
    "let_g",
    "let_h",
    "let_i",
    "let_k",
    "let_l",
    "let_m",
    "let_n",
    "let_o",
    "let_ô",
    "let_ơ",
    "let_p",
    "let_q",
    "let_r",
    "let_s",
    "let_t",
    "let_u",
    "let_ư",
    "let_v",
    "let_x",
    "let_y",
  ],
};

export const C5_ALP_04_SEED: SkillSeed = {
  identity: C5_ALP_04_IDENTITY,
  dataset: C5_ALP_04_DATASET,
  levels: [
    {
      code: "GL-C5-ALP-TAP-0007",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-TAP-0008",
      template: "GT-001",
      band: "5-6",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-TCNT-0007",
      template: "GT-002",
      band: "5-6",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-TCNT-0008",
      template: "GT-002",
      band: "5-6",
      difficulty: 4,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-TCMP-0007",
      template: "GT-003",
      band: "5-6",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-TCMP-0008",
      template: "GT-003",
      band: "5-6",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-PAIR-0007",
      template: "GT-004",
      band: "5-6",
      difficulty: 3,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-PAIR-0008",
      template: "GT-004",
      band: "5-6",
      difficulty: 4,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-PATT-0007",
      template: "GT-005",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C5-ALP-PATT-0008",
      template: "GT-005",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
  ],
};
