import type { ContentSeed } from "#src/seed-content/types";
import { SEED_GT000_C2 } from "./seed-gt000.js";
import { SEED_MONT_A19 } from "./seed-mont-a19.js";

export const C2_BASE_LEVELS: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C2-SHP-CARD-0001",
      content_version: 1,
      template_code: "GT-012",
      title: "Nhận biết hình vuông",
      instruction: "Em hãy chọn hình vuông màu đỏ.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Em hãy chọn hình vuông màu đỏ.",
      flash_items: [
        {
          item_id: "sq",
          asset: {
            kind: "emoji",
            ref: "🟥",
          },
        },
      ],
      arrangement: "line",
      options: [
        {
          value: 1,
          is_correct: true,
        },
        {
          value: 2,
          is_correct: false,
        },
        {
          value: 3,
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      flash_ms: 3000,
      item_count: 1,
      distractor_count: 2,
      allow_replay: true,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-SHP-CARD-0002",
      content_version: 1,
      template_code: "GT-012",
      title: "Nhận biết hình tròn xanh",
      instruction: "Em hãy chọn quả bóng hình tròn.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Em hãy chọn quả bóng hình tròn.",
      flash_items: [
        {
          item_id: "cr",
          asset: {
            kind: "emoji",
            ref: "🔵",
          },
        },
        {
          item_id: "cr2",
          asset: {
            kind: "emoji",
            ref: "🔵",
          },
        },
      ],
      arrangement: "line",
      options: [
        {
          value: 1,
          is_correct: false,
        },
        {
          value: 2,
          is_correct: true,
        },
        {
          value: 3,
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      flash_ms: 3000,
      item_count: 2,
      distractor_count: 2,
      allow_replay: true,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-SHP-CARD-0003",
      content_version: 1,
      template_code: "GT-012",
      title: "Nhận biết hình tam giác",
      instruction: "Chạm vào hình tam giác màu vàng.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Chạm vào hình tam giác màu vàng.",
      flash_items: [
        {
          item_id: "tr",
          asset: {
            kind: "emoji",
            ref: "🔺",
          },
        },
      ],
      arrangement: "line",
      options: [
        {
          value: 1,
          is_correct: true,
        },
        {
          value: 2,
          is_correct: false,
        },
        {
          value: 3,
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      flash_ms: 3000,
      item_count: 1,
      distractor_count: 2,
      allow_replay: true,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-POS-LOC-0004",
      content_version: 1,
      template_code: "GT-001",
      title: "Vị trí trên và dưới",
      instruction: "Chạm vào đồ vật ở phía trên.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm vào chú gấu bông nhé!",
      target_item: {
        item_id: "teddy",
        asset: {
          kind: "emoji",
          ref: "🧸",
        },
      },
      options: [
        {
          item_id: "teddy",
          asset: {
            kind: "emoji",
            ref: "🧸",
          },
          is_correct: true,
        },
        {
          item_id: "box",
          asset: {
            kind: "emoji",
            ref: "📦",
          },
          is_correct: false,
        },
        {
          item_id: "book",
          asset: {
            kind: "emoji",
            ref: "📘",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 2,
      hint_after_ms: 9000,
      allow_retry: true,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C2-POS-LOC-0005",
      content_version: 1,
      template_code: "GT-001",
      title: "Vị trí trong và ngoài",
      instruction: "Chạm vào chú chó ở trong nhà.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm vào chú chó nhé!",
      target_item: {
        item_id: "dog",
        asset: {
          kind: "emoji",
          ref: "🐶",
        },
      },
      options: [
        {
          item_id: "dog",
          asset: {
            kind: "emoji",
            ref: "🐶",
          },
          is_correct: true,
        },
        {
          item_id: "cat",
          asset: {
            kind: "emoji",
            ref: "🐱",
          },
          is_correct: false,
        },
        {
          item_id: "house",
          asset: {
            kind: "emoji",
            ref: "🏠",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 2,
      hint_after_ms: 9000,
      allow_retry: true,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C2-SORT-SHP-0006",
      content_version: 1,
      template_code: "GT-003",
      title: "Phân loại hình khối",
      instruction: "Kéo hình tròn vào khung tròn.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Kéo hình tròn vào khung tròn.",
      container: {
        container_id: "circle_frame",
        label: "Khung tròn",
        accepts_attribute: "circle",
      },
      items: [
        {
          item_id: "c1",
          attribute: "circle",
          asset: {
            kind: "emoji",
            ref: "🔵",
          },
          is_correct: true,
        },
        {
          item_id: "s1",
          attribute: "square",
          asset: {
            kind: "emoji",
            ref: "🟥",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 1,
      target_count: 1,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-SORT-SHP-0007",
      content_version: 1,
      template_code: "GT-003",
      title: "Phân loại hình tam giác",
      instruction: "Kéo tam giác vào ô tam giác.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Kéo tam giác vào ô tam giác.",
      container: {
        container_id: "tri_frame",
        label: "Khung tam giác",
        accepts_attribute: "triangle",
      },
      items: [
        {
          item_id: "t1",
          attribute: "triangle",
          asset: {
            kind: "emoji",
            ref: "🔺",
          },
          is_correct: true,
        },
        {
          item_id: "c1",
          attribute: "circle",
          asset: {
            kind: "emoji",
            ref: "🟢",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 1,
      target_count: 1,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-CMP-SIZ-0008",
      content_version: 1,
      template_code: "GT-001",
      title: "So sánh to và nhỏ",
      instruction: "Chọn quả bóng to hơn.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm vào quả to hơn nhé!",
      target_item: {
        item_id: "watermelon",
        asset: {
          kind: "emoji",
          ref: "🍉",
        },
      },
      options: [
        {
          item_id: "watermelon",
          asset: {
            kind: "emoji",
            ref: "🍉",
          },
          is_correct: true,
        },
        {
          item_id: "strawberry",
          asset: {
            kind: "emoji",
            ref: "🍓",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 1,
      hint_after_ms: 9000,
      allow_retry: true,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C2-CMP-SIZ-0009",
      content_version: 1,
      template_code: "GT-001",
      title: "Tìm cây cao hơn",
      instruction: "Chọn cái cây cao hơn nhé.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm vào cái cây cao hơn nhé!",
      target_item: {
        item_id: "tall-tree",
        asset: {
          kind: "emoji",
          ref: "🌲",
        },
      },
      options: [
        {
          item_id: "tall-tree",
          asset: {
            kind: "emoji",
            ref: "🌲",
          },
          is_correct: true,
        },
        {
          item_id: "seedling",
          asset: {
            kind: "emoji",
            ref: "🌱",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 1,
      hint_after_ms: 9000,
      allow_retry: true,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C2-DIR-NAV-0010",
      content_version: 1,
      template_code: "GT-022",
      title: "Hướng trái và phải",
      instruction: "Chạm vào chú chim bên phải.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "free",
      skill_codes: ["C2.DIR.05"],
      learning_objective_codes: ["LO-C2.DIR.05-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tìm chú chim ở phía bên phải nhé!",
      target_description: "Chú chim ở bên phải",
      scene_objects: [
        {
          id: "chick",
          asset: {
            kind: "emoji",
            ref: "🐥",
          },
          is_target: false,
          is_hidden: false,
          x: 180,
          y: 270,
        },
        {
          id: "bird",
          asset: {
            kind: "emoji",
            ref: "🐦",
          },
          is_target: true,
          is_hidden: false,
          x: 780,
          y: 270,
        },
        {
          id: "bee",
          asset: {
            kind: "emoji",
            ref: "🐝",
          },
          is_target: false,
          is_hidden: false,
          x: 480,
          y: 420,
        },
      ],
    },
    difficulty_params: {
      hint_after_ms: 9000,
      allow_retry: true,
      show_target_counter: true,
    },
  },
  {
    header: {
      code: "GL-C2-SEQ-PAT-0011",
      content_version: 1,
      template_code: "GT-008",
      title: "Quy luật hình dạng AB",
      instruction: "Chọn hình tiếp theo đúng quy luật.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé kéo hình vào ô cho đúng quy luật nhé!",
      slots: [
        {
          slot_id: "slot-1",
          label: "Ô 1",
          expected_item_id: "s1-1",
        },
        {
          slot_id: "slot-2",
          label: "Ô 2",
          expected_item_id: "s1-2",
        },
        {
          slot_id: "slot-3",
          label: "Ô 3",
          expected_item_id: "s2-1",
        },
        {
          slot_id: "slot-4",
          label: "Ô 4",
          expected_item_id: "s2-2",
        },
      ],
      items: [
        {
          item_id: "s2-2",
          label: "Hình vuông xanh",
          asset: {
            kind: "emoji",
            ref: "🟦",
          },
        },
        {
          item_id: "s2-1",
          label: "Hình tròn đỏ",
          asset: {
            kind: "emoji",
            ref: "🔴",
          },
        },
        {
          item_id: "s1-2",
          label: "Hình vuông xanh",
          asset: {
            kind: "emoji",
            ref: "🟦",
          },
        },
        {
          item_id: "s1-1",
          label: "Hình tròn đỏ",
          asset: {
            kind: "emoji",
            ref: "🔴",
          },
        },
      ],
    },
    difficulty_params: {
      slot_count: 4,
      distractor_count: 0,
      hint_after_ms: 10_000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-SEQ-PAT-0012",
      content_version: 1,
      template_code: "GT-008",
      title: "Quy luật kích thước to nhỏ",
      instruction: "Chọn ngôi sao tiếp theo.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé kéo ngôi sao vào ô cho đúng quy luật nhé!",
      slots: [
        {
          slot_id: "slot-1",
          label: "Ô 1",
          expected_item_id: "s1-1",
        },
        {
          slot_id: "slot-2",
          label: "Ô 2",
          expected_item_id: "s1-2",
        },
        {
          slot_id: "slot-3",
          label: "Ô 3",
          expected_item_id: "s2-1",
        },
        {
          slot_id: "slot-4",
          label: "Ô 4",
          expected_item_id: "s2-2",
        },
      ],
      items: [
        {
          item_id: "s2-2",
          label: "Sao nhỏ",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
        },
        {
          item_id: "s2-1",
          label: "Sao lớn",
          asset: {
            kind: "emoji",
            ref: "🌟",
          },
        },
        {
          item_id: "s1-2",
          label: "Sao nhỏ",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
        },
        {
          item_id: "s1-1",
          label: "Sao lớn",
          asset: {
            kind: "emoji",
            ref: "🌟",
          },
        },
      ],
    },
    difficulty_params: {
      slot_count: 4,
      distractor_count: 0,
      hint_after_ms: 10_000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-SUB-FAST-0013",
      content_version: 1,
      template_code: "GT-004",
      title: "Phân loại hình tròn và hình có góc",
      instruction: "Bé xếp hình vào đúng rổ theo hình dạng nhé!",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp hình vào đúng rổ theo hình dạng nhé!",
      groups: [
        {
          group_id: "g0",
          label: "Rổ hình tròn",
          label_emoji: "🔴",
        },
        {
          group_id: "g1",
          label: "Rổ hình có góc",
          label_emoji: "🟦",
        },
      ],
      items: [
        {
          item_id: "circle-red",
          asset: {
            kind: "emoji",
            ref: "🔴",
          },
          correct_group_id: "g0",
        },
        {
          item_id: "circle-blue",
          asset: {
            kind: "emoji",
            ref: "🔵",
          },
          correct_group_id: "g0",
        },
        {
          item_id: "square",
          asset: {
            kind: "emoji",
            ref: "🟦",
          },
          correct_group_id: "g1",
        },
        {
          item_id: "triangle",
          asset: {
            kind: "emoji",
            ref: "🔺",
          },
          correct_group_id: "g1",
        },
      ],
    },
    difficulty_params: {
      distractor_count: 0,
      hint_after_ms: 10_000,
      allow_retry: true,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C2-POS-LOC-0014",
      content_version: 1,
      template_code: "GT-022",
      title: "Vị trí trước và sau",
      instruction: "Chạm vào ô tô ở đằng trước.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tìm chiếc xe đi đằng trước nhé!",
      target_description: "Chiếc xe đi đằng trước",
      scene_objects: [
        {
          id: "front",
          asset: {
            kind: "emoji",
            ref: "🚘",
          },
          is_target: true,
          is_hidden: false,
          x: 480,
          y: 120,
        },
        {
          id: "back",
          asset: {
            kind: "emoji",
            ref: "🚕",
          },
          is_target: false,
          is_hidden: false,
          x: 480,
          y: 420,
        },
        {
          id: "bus",
          asset: {
            kind: "emoji",
            ref: "🚙",
          },
          is_target: false,
          is_hidden: false,
          x: 180,
          y: 270,
        },
      ],
    },
    difficulty_params: {
      hint_after_ms: 9000,
      allow_retry: true,
      show_target_counter: true,
    },
  },
  {
    header: {
      code: "GL-C2-SORT-SHP-0015",
      content_version: 1,
      template_code: "GT-003",
      title: "Phân loại khối vuông và tròn",
      instruction: "Bỏ khối vuông vào hộp vuông.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bỏ khối vuông vào hộp vuông.",
      container: {
        container_id: "sq_box",
        label: "Hộp vuông",
        accepts_attribute: "square",
      },
      items: [
        {
          item_id: "s1",
          attribute: "square",
          asset: {
            kind: "emoji",
            ref: "🟨",
          },
          is_correct: true,
        },
        {
          item_id: "c1",
          attribute: "circle",
          asset: {
            kind: "emoji",
            ref: "🟢",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 1,
      target_count: 1,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-DIR-NAV-0016",
      content_version: 1,
      template_code: "GT-022",
      title: "Đi tìm kho báu ngôi sao",
      instruction: "Chọn đường đi sang bên trái.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.DIR.05"],
      learning_objective_codes: ["LO-C2.DIR.05-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tìm ngôi sao ở phía bên trái nhé!",
      target_description: "Ngôi sao ở bên trái",
      scene_objects: [
        {
          id: "star",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
          is_target: true,
          is_hidden: false,
          x: 180,
          y: 270,
        },
        {
          id: "moon",
          asset: {
            kind: "emoji",
            ref: "🌙",
          },
          is_target: false,
          is_hidden: false,
          x: 780,
          y: 270,
        },
        {
          id: "sun",
          asset: {
            kind: "emoji",
            ref: "☀️",
          },
          is_target: false,
          is_hidden: false,
          x: 480,
          y: 120,
        },
      ],
    },
    difficulty_params: {
      hint_after_ms: 9000,
      allow_retry: true,
      show_target_counter: true,
    },
  },
  {
    header: {
      code: "GL-C2-CMP-SIZ-0017",
      content_version: 1,
      template_code: "GT-001",
      title: "So sánh con vật to nhỏ",
      instruction: "Chọn con vật to lớn hơn.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "animal",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chạm vào con vật to hơn nhé!",
      target_item: {
        item_id: "elephant",
        asset: {
          kind: "emoji",
          ref: "🐘",
        },
      },
      options: [
        {
          item_id: "elephant",
          asset: {
            kind: "emoji",
            ref: "🐘",
          },
          is_correct: true,
        },
        {
          item_id: "mouse",
          asset: {
            kind: "emoji",
            ref: "🐭",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      distractor_count: 1,
      hint_after_ms: 9000,
      allow_retry: true,
      shuffle_items: true,
    },
  },
  {
    header: {
      code: "GL-C2-SEQ-PAT-0018",
      content_version: 1,
      template_code: "GT-011",
      title: "Chuỗi quy luật hình khối ABC",
      instruction: "Chọn hình tiếp theo trong chuỗi.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chọn hình điền vào ô trống cho đủ ba màu!",
      matrix: {
        rows: 3,
        cols: 3,
        cells: [
          {
            row: 0,
            col: 0,
            asset: {
              kind: "emoji",
              ref: "🔴",
            },
          },
          {
            row: 0,
            col: 1,
            asset: {
              kind: "emoji",
              ref: "🟢",
            },
          },
          {
            row: 0,
            col: 2,
            asset: {
              kind: "emoji",
              ref: "🟡",
            },
          },
          {
            row: 1,
            col: 0,
            asset: {
              kind: "emoji",
              ref: "🟢",
            },
          },
          {
            row: 1,
            col: 1,
            asset: {
              kind: "emoji",
              ref: "🟡",
            },
          },
          {
            row: 1,
            col: 2,
            asset: {
              kind: "emoji",
              ref: "🔴",
            },
          },
          {
            row: 2,
            col: 0,
            asset: {
              kind: "emoji",
              ref: "🟡",
            },
          },
          {
            row: 2,
            col: 1,
            asset: {
              kind: "emoji",
              ref: "🔴",
            },
          },
          {
            row: 2,
            col: 2,
            asset: null,
          },
        ],
      },
      options: [
        {
          option_id: "op-1",
          asset: {
            kind: "emoji",
            ref: "🟢",
          },
          is_correct: true,
        },
        {
          option_id: "op-2",
          asset: {
            kind: "emoji",
            ref: "🔴",
          },
          is_correct: false,
        },
        {
          option_id: "op-3",
          asset: {
            kind: "emoji",
            ref: "🟡",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      grid_size: 3,
      distractor_count: 2,
      hint_after_ms: 10_000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-SUB-FAST-0019",
      content_version: 1,
      template_code: "GT-012",
      title: "Nhìn nhanh đếm ngôi sao",
      instruction: "Bé nhìn nhanh xem có mấy ngôi sao nhé!",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé nhìn nhanh xem có mấy ngôi sao nhé!",
      flash_items: [
        {
          item_id: "it-1",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
        },
        {
          item_id: "it-2",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
        },
      ],
      arrangement: "dice",
      options: [
        {
          value: 1,
          is_correct: false,
        },
        {
          value: 2,
          is_correct: true,
        },
        {
          value: 3,
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      flash_ms: 1200,
      item_count: 2,
      distractor_count: 2,
      allow_replay: true,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-POS-LOC-0020",
      content_version: 1,
      template_code: "GT-022",
      title: "Tìm ô góc trên bên trái",
      instruction: "Chạm vào ô góc trên bên trái.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Chạm vào ô góc trên bên trái.",
      target_description: "Tìm ô góc trên bên trái",
      scene_objects: [
        {
          id: "tl",
          asset: {
            kind: "emoji",
            ref: "🎁",
          },
          is_target: true,
          is_hidden: false,
        },
        {
          id: "tr",
          asset: {
            kind: "emoji",
            ref: "🎈",
          },
          is_target: false,
          is_hidden: false,
        },
        {
          id: "bl",
          asset: {
            kind: "emoji",
            ref: "🧸",
          },
          is_target: false,
          is_hidden: false,
        },
        {
          id: "br",
          asset: {
            kind: "emoji",
            ref: "⚽",
          },
          is_target: false,
          is_hidden: false,
        },
      ],
    },
    difficulty_params: {
      hint_after_ms: 9000,
      allow_retry: true,
      show_target_counter: true,
    },
  },
  {
    header: {
      code: "GL-C2-ROT-TRANS-0021",
      legacy_v1_ref: "D2-04",
      content_version: 1,
      template_code: "GT-019",
      title: "Xoay mũi tên lên trên",
      instruction: "Bé xoay mũi tên hướng lên trên.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xoay mũi tên hướng lên trên rồi đặt vào ô nhé!",
      target_slots: [
        {
          slot_id: "slot-1",
          target_rotation: 0,
          target_flip: "none",
          asset: {
            kind: "emoji",
            ref: "⬆️",
          },
        },
      ],
      pieces: [
        {
          piece_id: "arrow-1",
          initial_rotation: 90,
          initial_flip: "none",
          target_slot_id: "slot-1",
          asset: {
            kind: "emoji",
            ref: "⬆️",
          },
        },
      ],
    },
    difficulty_params: {
      allow_flip: false,
      rotation_step: 90,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-ROT-TRANS-0022",
      legacy_v1_ref: "D2-04",
      content_version: 1,
      template_code: "GT-019",
      title: "Xoay hai mảnh ghép đúng chiều",
      instruction: "Bé xoay các mảnh ghép thẳng đứng.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xoay các mảnh ghép cho thẳng đứng rồi đặt vào khung nhé!",
      target_slots: [
        {
          slot_id: "slot-triangle",
          target_rotation: 0,
          target_flip: "none",
          asset: {
            kind: "emoji",
            ref: "🔺",
          },
        },
        {
          slot_id: "slot-star",
          target_rotation: 180,
          target_flip: "none",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
        },
      ],
      pieces: [
        {
          piece_id: "piece-triangle",
          initial_rotation: 270,
          initial_flip: "none",
          target_slot_id: "slot-triangle",
          asset: {
            kind: "emoji",
            ref: "🔺",
          },
        },
        {
          piece_id: "piece-star",
          initial_rotation: 90,
          initial_flip: "none",
          target_slot_id: "slot-star",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
        },
      ],
    },
    difficulty_params: {
      allow_flip: false,
      rotation_step: 90,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-ROT-TRANS-0023",
      legacy_v1_ref: "D2-04",
      content_version: 1,
      template_code: "GT-019",
      title: "Xoay và lật hình cá bơi lội",
      instruction: "Bé xoay chú cá nhỏ bơi về bên phải.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xoay chú cá nhỏ bơi về bên phải vào hồ nước nhé.",
      target_slots: [
        {
          slot_id: "slot-fish",
          target_rotation: 0,
          target_flip: "none",
          asset: {
            kind: "emoji",
            ref: "🐠",
          },
        },
      ],
      pieces: [
        {
          piece_id: "piece-fish",
          initial_rotation: 180,
          initial_flip: "horizontal",
          target_slot_id: "slot-fish",
          asset: {
            kind: "emoji",
            ref: "🐠",
          },
        },
      ],
    },
    difficulty_params: {
      allow_flip: true,
      rotation_step: 90,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-MIR-COMP-0024",
      legacy_v1_ref: "D2-03",
      content_version: 1,
      template_code: "GT-021",
      title: "Hoàn thiện cánh bướm đối xứng",
      instruction: "Bé chọn cánh bướm ghép bên phải.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé hãy hoàn thiện cánh bướm bên phải cho giống cánh bên trái nhé!",
      axis: "vertical",
      reference_pattern: [
        {
          slot_id: "left-wing",
          asset: {
            kind: "emoji",
            ref: "🦋",
          },
        },
      ],
      target_slots: [
        {
          slot_id: "right-wing",
          expected_asset_ref: "butterfly-wing",
        },
      ],
      options: [
        {
          item_id: "opt-wing",
          asset: {
            kind: "emoji",
            ref: "🦋",
          },
          asset_ref: "butterfly-wing",
        },
        {
          item_id: "opt-flower",
          asset: {
            kind: "emoji",
            ref: "🌸",
          },
          asset_ref: "flower",
        },
      ],
    },
    difficulty_params: {
      show_axis_guide: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-MIR-COMP-0025",
      legacy_v1_ref: "D2-03",
      content_version: 1,
      template_code: "GT-021",
      title: "Xếp khối màu đối xứng trục dọc",
      instruction: "Bé xếp các khối màu đối xứng.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy xếp các khối màu bên phải đối xứng với bên trái nhé!",
      axis: "vertical",
      reference_pattern: [
        {
          slot_id: "top-left",
          asset: {
            kind: "emoji",
            ref: "🔴",
          },
        },
        {
          slot_id: "bottom-left",
          asset: {
            kind: "emoji",
            ref: "🟦",
          },
        },
      ],
      target_slots: [
        {
          slot_id: "top-right",
          expected_asset_ref: "red-circle",
        },
        {
          slot_id: "bottom-right",
          expected_asset_ref: "blue-square",
        },
      ],
      options: [
        {
          item_id: "opt-red",
          asset: {
            kind: "emoji",
            ref: "🔴",
          },
          asset_ref: "red-circle",
        },
        {
          item_id: "opt-blue",
          asset: {
            kind: "emoji",
            ref: "🟦",
          },
          asset_ref: "blue-square",
        },
        {
          item_id: "opt-yellow",
          asset: {
            kind: "emoji",
            ref: "🟡",
          },
          asset_ref: "yellow-circle",
        },
      ],
    },
    difficulty_params: {
      show_axis_guide: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-MIR-COMP-0026",
      legacy_v1_ref: "D2-03",
      content_version: 1,
      template_code: "GT-021",
      title: "Đối xứng trục ngang bốn ô",
      instruction: "Bé tìm hình ghép đối xứng gương phía dưới.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp các hình đối xứng qua gương bên dưới nhé.",
      axis: "horizontal",
      reference_pattern: [
        {
          slot_id: "r1",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
        },
        {
          slot_id: "r2",
          asset: {
            kind: "emoji",
            ref: "💎",
          },
        },
      ],
      target_slots: [
        {
          slot_id: "t1",
          expected_asset_ref: "star",
        },
        {
          slot_id: "t2",
          expected_asset_ref: "diamond",
        },
      ],
      options: [
        {
          item_id: "opt-star",
          asset: {
            kind: "emoji",
            ref: "⭐",
          },
          asset_ref: "star",
        },
        {
          item_id: "opt-diamond",
          asset: {
            kind: "emoji",
            ref: "💎",
          },
          asset_ref: "diamond",
        },
      ],
    },
    difficulty_params: {
      show_axis_guide: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-CON-SHP-0027",
      legacy_v1_ref: "D2-07",
      content_version: 1,
      template_code: "GT-023",
      title: "Lắp ráp ngôi nhà đơn giản",
      instruction: "Bé ghép mái nhà và thân nhà.",
      age_min: 4,
      age_max: 5,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy ghép mái nhà và thân nhà để tạo thành ngôi nhà nhé!",
      target_model: {
        name: "Ngôi nhà",
        asset: {
          kind: "emoji",
          ref: "🏠",
        },
      },
      anchors: [
        {
          anchor_id: "anchor-roof",
          x: 480,
          y: 180,
          accepted_part_id: "part-roof",
          label: "Mái nhà",
        },
        {
          anchor_id: "anchor-wall",
          x: 480,
          y: 320,
          accepted_part_id: "part-wall",
          label: "Thân nhà",
        },
      ],
      parts: [
        {
          part_id: "part-roof",
          target_anchor_id: "anchor-roof",
          asset: {
            kind: "emoji",
            ref: "🔺",
          },
          name: "Mái tam giác",
        },
        {
          part_id: "part-wall",
          target_anchor_id: "anchor-wall",
          asset: {
            kind: "emoji",
            ref: "🟦",
          },
          name: "Tường vuông",
        },
      ],
    },
    difficulty_params: {
      snap_radius_px: 60,
      show_anchor_outline: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-CON-SHP-0028",
      legacy_v1_ref: "D2-07",
      content_version: 1,
      template_code: "GT-023",
      title: "Lắp ráp xe ô tô nhỏ",
      instruction: "Bé hãy lắp hai bánh vào ô tô.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy lắp 2 bánh xe vào thân xe ô tô nhé!",
      target_model: {
        name: "Xe ô tô",
        asset: {
          kind: "emoji",
          ref: "🚗",
        },
      },
      anchors: [
        {
          anchor_id: "anchor-body",
          x: 480,
          y: 220,
          accepted_part_id: "part-body",
          label: "Thân xe",
        },
        {
          anchor_id: "anchor-w1",
          x: 400,
          y: 330,
          accepted_part_id: "part-w1",
          label: "Bánh trước",
        },
        {
          anchor_id: "anchor-w2",
          x: 560,
          y: 330,
          accepted_part_id: "part-w2",
          label: "Bánh sau",
        },
      ],
      parts: [
        {
          part_id: "part-body",
          target_anchor_id: "anchor-body",
          asset: {
            kind: "emoji",
            ref: "🚙",
          },
          name: "Thân xe",
        },
        {
          part_id: "part-w1",
          target_anchor_id: "anchor-w1",
          asset: {
            kind: "emoji",
            ref: "⚫",
          },
          name: "Bánh xe 1",
        },
        {
          part_id: "part-w2",
          target_anchor_id: "anchor-w2",
          asset: {
            kind: "emoji",
            ref: "⚫",
          },
          name: "Bánh xe 2",
        },
      ],
    },
    difficulty_params: {
      snap_radius_px: 50,
      show_anchor_outline: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-CON-SHP-0029",
      legacy_v1_ref: "D2-07",
      content_version: 1,
      template_code: "GT-023",
      title: "Lắp ráp tên lửa vũ trụ",
      instruction: "Bé ghép các bộ phận tạo tên lửa vũ trụ.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy ghép 3 bộ phận để tạo thành chiếc tên lửa nhé!",
      target_model: {
        name: "Tên lửa",
        asset: {
          kind: "emoji",
          ref: "🚀",
        },
      },
      anchors: [
        {
          anchor_id: "a-tip",
          x: 480,
          y: 150,
          accepted_part_id: "p-tip",
          label: "Mũi tên lửa",
        },
        {
          anchor_id: "a-body",
          x: 480,
          y: 260,
          accepted_part_id: "p-body",
          label: "Thân tên lửa",
        },
        {
          anchor_id: "a-booster",
          x: 480,
          y: 370,
          accepted_part_id: "p-booster",
          label: "Động cơ đẩy",
        },
      ],
      parts: [
        {
          part_id: "p-tip",
          target_anchor_id: "a-tip",
          asset: {
            kind: "emoji",
            ref: "🔺",
          },
          name: "Mũi tên lửa",
        },
        {
          part_id: "p-body",
          target_anchor_id: "a-body",
          asset: {
            kind: "emoji",
            ref: "⬜",
          },
          name: "Thân tên lửa",
        },
        {
          part_id: "p-booster",
          target_anchor_id: "a-booster",
          asset: {
            kind: "emoji",
            ref: "🔥",
          },
          name: "Động cơ đẩy",
        },
      ],
    },
    difficulty_params: {
      snap_radius_px: 50,
      show_anchor_outline: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-TRC-PTH-0030",
      legacy_v1_ref: "D2-09",
      content_version: 1,
      template_code: "GT-024",
      title: "Vẽ theo nét hình tam giác",
      instruction: "Bé nối các điểm vẽ hình tam giác.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy nối các điểm theo thứ tự 1-2-3 để vẽ hình tam giác nhé!",
      shape_name: "Hình tam giác",
      guide_asset: {
        kind: "emoji",
        ref: "🔺",
      },
      waypoints: [
        {
          id: "wp-top",
          x: 480,
          y: 150,
          order: 0,
          label: "1",
        },
        {
          id: "wp-right",
          x: 650,
          y: 380,
          order: 1,
          label: "2",
        },
        {
          id: "wp-left",
          x: 310,
          y: 380,
          order: 2,
          label: "3",
        },
        {
          id: "wp-top-close",
          x: 480,
          y: 150,
          order: 3,
          label: "1",
        },
      ],
    },
    difficulty_params: {
      tolerance_px: 50,
      show_numbered_dots: true,
      show_guide_lines: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-TRC-PTH-0031",
      legacy_v1_ref: "D2-09",
      content_version: 1,
      template_code: "GT-024",
      title: "Vẽ theo nét hình vuông",
      instruction: "Bé nối các điểm vẽ hình vuông.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy nối 4 điểm theo thứ tự để tạo thành hình vuông nhé!",
      shape_name: "Hình vuông",
      guide_asset: {
        kind: "emoji",
        ref: "🟦",
      },
      waypoints: [
        {
          id: "wp-tl",
          x: 340,
          y: 180,
          order: 0,
          label: "1",
        },
        {
          id: "wp-tr",
          x: 620,
          y: 180,
          order: 1,
          label: "2",
        },
        {
          id: "wp-br",
          x: 620,
          y: 420,
          order: 2,
          label: "3",
        },
        {
          id: "wp-bl",
          x: 340,
          y: 420,
          order: 3,
          label: "4",
        },
        {
          id: "wp-tl-close",
          x: 340,
          y: 180,
          order: 4,
          label: "1",
        },
      ],
    },
    difficulty_params: {
      tolerance_px: 50,
      show_numbered_dots: true,
      show_guide_lines: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-TRC-PTH-0032",
      legacy_v1_ref: "D2-09",
      content_version: 1,
      template_code: "GT-024",
      title: "Nối điểm vẽ ngôi sao năm cánh",
      instruction: "Bé nối điểm từ một đến năm vẽ ngôi sao.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé hãy nối các điểm theo thứ tự từ 1 đến 5 để vẽ ngôi sao sáng nhé!",
      shape_name: "Ngôi sao",
      guide_asset: {
        kind: "emoji",
        ref: "⭐",
      },
      waypoints: [
        {
          id: "wp-1",
          x: 480,
          y: 120,
          order: 0,
          label: "1",
        },
        {
          id: "wp-2",
          x: 530,
          y: 270,
          order: 1,
          label: "2",
        },
        {
          id: "wp-3",
          x: 680,
          y: 270,
          order: 2,
          label: "3",
        },
        {
          id: "wp-4",
          x: 560,
          y: 360,
          order: 3,
          label: "4",
        },
        {
          id: "wp-5",
          x: 600,
          y: 500,
          order: 4,
          label: "5",
        },
        {
          id: "wp-6",
          x: 480,
          y: 410,
          order: 5,
          label: "6",
        },
        {
          id: "wp-7",
          x: 360,
          y: 500,
          order: 6,
          label: "7",
        },
        {
          id: "wp-8",
          x: 400,
          y: 360,
          order: 7,
          label: "8",
        },
        {
          id: "wp-9",
          x: 280,
          y: 270,
          order: 8,
          label: "9",
        },
        {
          id: "wp-10",
          x: 430,
          y: 270,
          order: 9,
          label: "10",
        },
        {
          id: "wp-close",
          x: 480,
          y: 120,
          order: 10,
          label: "1",
        },
      ],
    },
    difficulty_params: {
      tolerance_px: 45,
      show_numbered_dots: true,
      show_guide_lines: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-TRC-PTH-0033",
      legacy_v1_ref: "D2-09",
      content_version: 1,
      template_code: "GT-024",
      title: "Vẽ theo nét hình thoi",
      instruction: "Bé nối các điểm vẽ hình thoi nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["match"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy nối các điểm theo thứ tự để tạo thành hình thoi nhé!",
      shape_name: "Hình thoi",
      guide_asset: {
        kind: "emoji",
        ref: "✨",
      },
      waypoints: [
        {
          id: "p1",
          x: 480,
          y: 110,
          order: 0,
          label: "1",
        },
        {
          id: "p2",
          x: 680,
          y: 270,
          order: 1,
          label: "2",
        },
        {
          id: "p3",
          x: 480,
          y: 430,
          order: 2,
          label: "3",
        },
        {
          id: "p4",
          x: 280,
          y: 270,
          order: 3,
          label: "4",
        },
        {
          id: "p5",
          x: 480,
          y: 110,
          order: 4,
          label: "5",
        },
      ],
    },
    difficulty_params: {
      tolerance_px: 45,
      show_numbered_dots: true,
      show_guide_lines: true,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-BLK-STK-0033",
      legacy_v1_ref: "D6-10",
      content_version: 1,
      template_code: "GT-017",
      title: "Đếm số khối lập phương đơn giản",
      instruction: "Bé hãy đếm xem có bao nhiêu khối nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe", "count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy đếm xem có tất cả bao nhiêu khối lập phương nhé!",
      question: "count_cubes",
      model: [
        {
          x: 0,
          y: 0,
          z: 0,
        },
        {
          x: 1,
          y: 0,
          z: 0,
        },
        {
          x: 0,
          y: 1,
          z: 0,
        },
        {
          x: 0,
          y: 0,
          z: 1,
        },
      ],
      options: [
        {
          option_id: "opt_3",
          asset: {
            kind: "emoji",
            ref: "3️⃣",
          },
          is_correct: false,
        },
        {
          option_id: "opt_4",
          asset: {
            kind: "emoji",
            ref: "4️⃣",
          },
          is_correct: true,
        },
        {
          option_id: "opt_5",
          asset: {
            kind: "emoji",
            ref: "5️⃣",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      hidden_cube_count: 0,
      allow_rotate: true,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-BLK-STK-0034",
      legacy_v1_ref: "D6-10",
      content_version: 1,
      template_code: "GT-017",
      title: "Xếp tháp năm khối lập phương",
      instruction: "Bé đếm các khối gạch xây tháp.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe", "count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy đếm xem chiếc tháp có bao nhiêu khối gạch nhé!",
      question: "count_cubes",
      model: [
        {
          x: 0,
          y: 0,
          z: 0,
        },
        {
          x: 1,
          y: 0,
          z: 0,
        },
        {
          x: 0,
          y: 1,
          z: 0,
        },
        {
          x: 1,
          y: 1,
          z: 0,
        },
        {
          x: 0,
          y: 0,
          z: 1,
        },
      ],
      options: [
        {
          option_id: "o4",
          asset: {
            kind: "emoji",
            ref: "4️⃣",
          },
          is_correct: false,
        },
        {
          option_id: "o5",
          asset: {
            kind: "emoji",
            ref: "5️⃣",
          },
          is_correct: true,
        },
        {
          option_id: "o6",
          asset: {
            kind: "emoji",
            ref: "6️⃣",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      hidden_cube_count: 0,
      allow_rotate: true,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-BLK-STK-0035",
      legacy_v1_ref: "D6-10",
      content_version: 1,
      template_code: "GT-017",
      title: "Đếm khối lập phương có phần bị che",
      instruction: "Xoay hình quan sát và đếm đủ các khối.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe", "count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé xoay hình để đếm xem có tất cả bao nhiêu khối lập phương nhé!",
      question: "count_cubes",
      model: [
        {
          x: 0,
          y: 0,
          z: 0,
        },
        {
          x: 1,
          y: 0,
          z: 0,
        },
        {
          x: 0,
          y: 1,
          z: 0,
        },
        {
          x: 1,
          y: 1,
          z: 0,
        },
        {
          x: 0,
          y: 0,
          z: 1,
        },
        {
          x: 1,
          y: 1,
          z: 1,
        },
      ],
      options: [
        {
          option_id: "o5",
          asset: {
            kind: "emoji",
            ref: "5️⃣",
          },
          is_correct: false,
        },
        {
          option_id: "o6",
          asset: {
            kind: "emoji",
            ref: "6️⃣",
          },
          is_correct: true,
        },
        {
          option_id: "o7",
          asset: {
            kind: "emoji",
            ref: "7️⃣",
          },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      hidden_cube_count: 1,
      allow_rotate: true,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  {
    header: {
      code: "GL-C2-SHP-FLIP-0030",
      legacy_v1_ref: "D6-11",
      content_version: 1,
      template_code: "GT-020",
      title: "Lật thẻ tìm cặp hình giống nhau",
      instruction: "Bé lật thẻ và tìm hai hình giống hệt nhau nhé!",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé lật thẻ tìm hai hình giống nhau nhé!",
      pairs: [
        {
          pair_key: "circle",
          card_a: {
            card_id: "circle-1",
            asset: {
              kind: "emoji",
              ref: "🔴",
            },
          },
          card_b: {
            card_id: "circle-2",
            asset: {
              kind: "emoji",
              ref: "🔴",
            },
          },
        },
        {
          pair_key: "square",
          card_a: {
            card_id: "square-1",
            asset: {
              kind: "emoji",
              ref: "🟦",
            },
          },
          card_b: {
            card_id: "square-2",
            asset: {
              kind: "emoji",
              ref: "🟦",
            },
          },
        },
      ],
    },
    difficulty_params: {
      flip_back_delay_ms: 1800,
      peek_all_initial_ms: 2500,
      hint_after_ms: 9000,
      allow_retry: true,
    },
  },
];

export const C2_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  ...C2_BASE_LEVELS,
  ...SEED_MONT_A19,
  ...SEED_GT000_C2,
];
