import type { ContentSeed } from "../types.js";
import { SEED_MONT_A19 } from "./seed-mont-a19.js";

export const C2_BASE_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C2-SHP-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title: "Nhận biết hình vuông",
      instruction: "Em hãy chọn hình vuông màu đỏ.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "sq", emoji: "🟥" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C2-SHP-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title: "Nhận biết hình tròn xanh",
      instruction: "Em hãy chọn quả bóng hình tròn.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "cr", emoji: "🔵" },
        { id: "cr2", emoji: "🔵" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 3 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C2-SHP-CARD-0003",
      content_version: 1,
      template_code: "GT-001",
      title: "Nhận biết hình tam giác",
      instruction: "Chạm vào hình tam giác màu vàng.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "tr", emoji: "🔺" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C2-POS-LOC-0004",
      content_version: 1,
      template_code: "GT-005",
      title: "Vị trí trên và dưới",
      instruction: "Chạm vào đồ vật ở phía trên.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["spatial"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [{ id: "top_item", emoji: "🧸", position: "top" }],
        [{ id: "bot_item", emoji: "📦", position: "bottom" }],
      ],
      target_id: "top_item",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C2-POS-LOC-0005",
      content_version: 1,
      template_code: "GT-005",
      title: "Vị trí trong và ngoài",
      instruction: "Chạm vào chú chó ở trong nhà.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["spatial"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "inside_dog", emoji: "🐶", position: "inside" },
          { id: "outside_cat", emoji: "🐱", position: "outside" },
        ],
      ],
      target_id: "inside_dog",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C2-SORT-SHP-0006",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại hình khối",
      instruction: "Kéo hình tròn vào khung tròn.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "circle_frame", label: "Khung tròn", target_shape: "circle" },
      ],
      drag_items: [
        { id: "c1", emoji: "🔵", shape: "circle" },
        { id: "s1", emoji: "🟥", shape: "square" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C2-SORT-SHP-0007",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại hình tam giác",
      instruction: "Kéo tam giác vào ô tam giác.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "tri_frame", label: "Khung tam giác", target_shape: "triangle" },
      ],
      drag_items: [
        { id: "t1", emoji: "🔺", shape: "triangle" },
        { id: "c1", emoji: "🟢", shape: "circle" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C2-CMP-SIZ-0008",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh to và nhỏ",
      instruction: "Chọn quả bóng to hơn.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "⚽", size: "big" }],
      right_group: [{ emoji: "⚽", size: "small" }],
      target: "big",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C2-CMP-SIZ-0009",
      content_version: 1,
      template_code: "GT-003",
      title: "Tìm cây cao hơn",
      instruction: "Chọn cái cây cao hơn nhé.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["spatial"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🌲", height: "tall" }],
      right_group: [{ emoji: "🌱", height: "short" }],
      target: "tall",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C2-DIR-NAV-0010",
      content_version: 1,
      template_code: "GT-005",
      title: "Hướng trái và phải",
      instruction: "Chạm vào chú chim bên phải.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.DIR.05"],
      learning_objective_codes: ["LO-C2.DIR.05-01"],
      what_tags: ["spt"],
      thinking_tags: ["spatial"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "b_left", emoji: "🐥", position: "left" },
          { id: "b_right", emoji: "🐦", position: "right" },
        ],
      ],
      target_id: "b_right",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C2-SEQ-PAT-0011",
      content_version: 1,
      template_code: "GT-004",
      title: "Quy luật hình dạng AB",
      instruction: "Chọn hình tiếp theo đúng quy luật.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🔴", "🟦", "🔴", "🟦"],
      options: ["🔴", "🟦", "🟢"],
      correct_option: "🔴",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C2-SEQ-PAT-0012",
      content_version: 1,
      template_code: "GT-004",
      title: "Quy luật kích thước to nhỏ",
      instruction: "Chọn ngôi sao tiếp theo.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🌟", "⭐️", "🌟", "⭐️"],
      options: ["🌟", "⭐️", "✨"],
      correct_option: "🌟",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C2-SUB-FAST-0013",
      content_version: 1,
      template_code: "GT-006",
      title: "Nhận biết hình khối nhanh",
      instruction: "Hình gì vừa xuất hiện vậy em.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🔺" }],
      flash_duration_ms: 1500,
      options: ["Tam giác", "Hình tròn", "Hình vuông"],
      correct_answer: "Tam giác",
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C2-POS-LOC-0014",
      content_version: 1,
      template_code: "GT-005",
      title: "Vị trí trước và sau",
      instruction: "Chạm vào ô tô ở đằng trước.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [{ id: "car_front", emoji: "🚘", position: "front" }],
        [{ id: "car_back", emoji: "🚖", position: "back" }],
      ],
      target_id: "car_front",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C2-SORT-SHP-0015",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại khối vuông và tròn",
      instruction: "Bỏ khối vuông vào hộp vuông.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "sq_box", label: "Hộp vuông", target_shape: "square" },
      ],
      drag_items: [
        { id: "s1", emoji: "🟨", shape: "square" },
        { id: "c1", emoji: "🟢", shape: "circle" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C2-DIR-NAV-0016",
      content_version: 1,
      template_code: "GT-005",
      title: "Đi tìm kho báu ngôi sao",
      instruction: "Chọn đường đi sang bên trái.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.DIR.05"],
      learning_objective_codes: ["LO-C2.DIR.05-01"],
      what_tags: ["spt"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "star_left", emoji: "⭐", position: "left" },
          { id: "moon_right", emoji: "🌙", position: "right" },
        ],
      ],
      target_id: "star_left",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C2-CMP-SIZ-0017",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh con vật to nhỏ",
      instruction: "Chọn con vật to lớn hơn.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["spatial"],
      theme_tag: "zoo",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🐘", size: "big" }],
      right_group: [{ emoji: "🐭", size: "small" }],
      target: "big",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C2-SEQ-PAT-0018",
      content_version: 1,
      template_code: "GT-004",
      title: "Chuỗi quy luật hình khối ABC",
      instruction: "Chọn hình tiếp theo trong chuỗi.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shp"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🔴", "🟢", "🟡", "🔴", "🟢"],
      options: ["🔴", "🟢", "🟡"],
      correct_option: "🟡",
    },
    difficulty_params: { pattern_length: 3 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C2-SUB-FAST-0019",
      content_version: 1,
      template_code: "GT-006",
      title: "Nhìn nhanh vị trí ngôi sao",
      instruction: "Ngôi sao nằm ở phía nào vậy em.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "⭐", position: "top" }],
      flash_duration_ms: 1200,
      options: ["Phía trên", "Phía dưới"],
      correct_answer: "Phía trên",
    },
    difficulty_params: { flash_duration_ms: 1200 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C2-POS-LOC-0020",
      content_version: 1,
      template_code: "GT-005",
      title: "Tìm ô góc trên bên trái",
      instruction: "Chạm vào ô góc trên bên trái.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C2.ORI.07"],
      learning_objective_codes: ["LO-C2.ORI.07-01"],
      what_tags: ["spt"],
      thinking_tags: ["spatial"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "tl", emoji: "🎁", position: "top_left" },
          { id: "tr", emoji: "🎈", position: "top_right" },
        ],
        [
          { id: "bl", emoji: "🧸", position: "bottom_left" },
          { id: "br", emoji: "⚽", position: "bottom_right" },
        ],
      ],
      target_id: "tl",
    },
    difficulty_params: { grid_size: 2 },
  },
];

export const C2_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  ...C2_BASE_LEVELS,
  ...SEED_MONT_A19,
];
