import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_NREC_09_IDENTITY: SkillIdentity = {
  code: "C1.NREC.09",
  strand_code: "C1.NREC",
  competency_code: "C1",
  name: "Thứ tự số",
  age_min: 4,
  age_max: 4,
  difficulty: 2,
  thinking_processes: ["sequence"],
  tier: "basic",
  prerequisites: ["C1.NREC.03"],
  learning_objectives: [
    {
      code: "LO-C1.NREC.09-01",
      behaviour: "Nhận biết và thực hành Thứ tự số ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.NREC.09-02",
      behaviour: "Vận dụng Thứ tự số trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.NREC.09-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Thứ tự số",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_NREC_09_DATASET: SkillDataset = {
  skill_code: "C1.NREC.09",
  concept_label: "Thứ tự số",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "số không",
      glyph: "0",
      value: 0,
      audio_path: "/audio/voice/common/numbers/0.mp3",
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "số một",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "số hai",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "số ba",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n4",
      label: "số bốn",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n5",
      label: "số năm",
      glyph: "5",
      value: 5,
      audio_path: "/audio/voice/common/numbers/5.mp3",
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "n0",
      target_id: "n1",
    },
    {
      type: "sequence",
      source_id: "n1",
      target_id: "n2",
    },
    {
      type: "sequence",
      source_id: "n2",
      target_id: "n3",
    },
    {
      type: "sequence",
      source_id: "n3",
      target_id: "n4",
    },
    {
      type: "sequence",
      source_id: "n4",
      target_id: "n5",
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với thứ tự số",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng thứ tự số",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt thứ tự số với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi thứ tự số",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục thứ tự số và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Bé xếp các số theo đúng thứ tự nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Thứ tự số nhé",
  },
  ordering: ["n0", "n1", "n2", "n3", "n4", "n5"],
};

export const C1_NREC_09_SEED: SkillSeed = {
  identity: C1_NREC_09_IDENTITY,
  dataset: C1_NREC_09_DATASET,
  levels: [
    {
      code: "GL-C1-SEQ-PAT-0014",
      template: "GT-008",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-SEQ-PAT-0015",
      template: "GT-008",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-SEQ-PAT-0016",
      template: "GT-011",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-CARD-0107",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      montessori_ref: "WB02-D1",
    },
    {
      code: "GL-C1-NREC-CARD-0108",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
      montessori_ref: "WB02-D1",
    },
    {
      code: "GL-C1-SEQ-PAT-0109",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      montessori_ref: "WB02-D3",
    },
    {
      code: "GL-C1-SEQ-PAT-0110",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
      montessori_ref: "WB02-D3",
    },
    {
      code: "GL-C1-SEQ-SLOT-0131",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
      montessori_ref: "WB02-D2",
    },
    {
      code: "GL-C1-SEQ-SLOT-0132",
      template: "GT-008",
      band: "3-4",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
      montessori_ref: "WB02-D2",
    },
    {
      code: "GL-C1-NRC-BSK-0003",
      template: "GT-003",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-04",
    },
    {
      code: "GL-C1-NRC-BSK-0004",
      template: "GT-003",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D1-04",
    },
    {
      code: "GL-C1-TIM-ORD-0005",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D5-07",
    },
    {
      code: "GL-C1-TIM-ORD-0006",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D5-07",
    },
    {
      code: "GL-C1-TIM-ORD-0007",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D5-07",
    },
    {
      code: "GL-C1-DOT-TRC-0006",
      template: "GT-024",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C1-DOT-TRC-0007",
      template: "GT-024",
      band: "5-6",
      difficulty: 1,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C1-DOT-TRC-0008",
      template: "GT-024",
      band: "5-6",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C1-DOT-TRC-0009",
      template: "GT-024",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C1-DOT-TRC-0010",
      template: "GT-024",
      band: "5-6",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D2-09",
    },
    {
      code: "GL-C1-NREC-SLOT-0011",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MAZE-0001",
      template: "GT-013",
      band: "4-5",
      difficulty: 1,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MAZE-0002",
      template: "GT-013",
      band: "4-5",
      difficulty: 2,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MAZE-0003",
      template: "GT-013",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MAZE-0004",
      template: "GT-013",
      band: "4-5",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MAZE-0005",
      template: "GT-013",
      band: "4-5",
      difficulty: 2,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-BOND-0001",
      template: "GT-018",
      band: "4-5",
      difficulty: 1,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-BOND-0002",
      template: "GT-018",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-BOND-0003",
      template: "GT-018",
      band: "4-5",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-BOND-0004",
      template: "GT-018",
      band: "4-5",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-BOND-0005",
      template: "GT-018",
      band: "4-5",
      difficulty: 2,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MTRX-0001",
      template: "GT-023",
      band: "4-5",
      difficulty: 1,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MTRX-0002",
      template: "GT-023",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MTRX-0003",
      template: "GT-023",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MTRX-0004",
      template: "GT-023",
      band: "4-5",
      difficulty: 1,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-MTRX-0005",
      template: "GT-023",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
  ],
};
