import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_NREC_04_IDENTITY: SkillIdentity = {
  code: "C1.NREC.04",
  strand_code: "C1.NREC",
  competency_code: "C1",
  name: "Nhận biết số 11–20",
  age_min: 5,
  age_max: 5,
  difficulty: 3,
  thinking_processes: ["observe"],
  tier: "core",
  prerequisites: ["C1.NREC.03"],
  learning_objectives: [
    {
      code: "LO-C1.NREC.04-01",
      behaviour: "Nhận biết và thực hành Nhận biết số 11–20 ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.NREC.04-02",
      behaviour: "Vận dụng Nhận biết số 11–20 trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.NREC.04-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Nhận biết số 11–20",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_NREC_04_DATASET: SkillDataset = {
  skill_code: "C1.NREC.04",
  concept_label: "Nhận biết số 11–20",
  surface: "game",
  items: [
    {
      id: "n11",
      label: "mười một",
      glyph: "11",
      value: 11,
      audio_path: "/audio/voice/common/numbers/11.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n12",
      label: "mười hai",
      glyph: "12",
      value: 12,
      audio_path: "/audio/voice/common/numbers/12.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n13",
      label: "mười ba",
      glyph: "13",
      value: 13,
      audio_path: "/audio/voice/common/numbers/13.mp3",
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n14",
      label: "mười bốn",
      glyph: "14",
      value: 14,
      audio_path: "/audio/voice/common/numbers/14.mp3",
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n15",
      label: "mười lăm",
      glyph: "15",
      value: 15,
      audio_path: "/audio/voice/common/numbers/15.mp3",
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n16",
      label: "mười sáu",
      glyph: "16",
      value: 16,
      audio_path: "/audio/voice/common/numbers/16.mp3",
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n17",
      label: "mười bảy",
      glyph: "17",
      value: 17,
      audio_path: "/audio/voice/common/numbers/17.mp3",
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n18",
      label: "mười tám",
      glyph: "18",
      value: 18,
      audio_path: "/audio/voice/common/numbers/18.mp3",
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n19",
      label: "mười chín",
      glyph: "19",
      value: 19,
      audio_path: "/audio/voice/common/numbers/19.mp3",
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n20",
      label: "hai mươi",
      glyph: "20",
      value: 20,
      audio_path: "/audio/voice/common/numbers/20.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Nhận biết số 11–20",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Nhận biết số 11–20",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Nhận biết số 11–20 nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ hình {label} nhé!",
  },
  ordering: [
    "n0",
    "n1",
    "n2",
    "n3",
    "n4",
    "n5",
    "n6",
    "n7",
    "n8",
    "n9",
    "n10",
    "n11",
    "n12",
    "n13",
    "n14",
    "n15",
    "n16",
    "n17",
    "n18",
    "n19",
    "n20",
  ],
};

/**
 * Chủ đề làm quen — dataset của bài học mở đầu GL-C1-NREC-INTRO-0003.
 *
 * Chủ đề không có hàng `skills` riêng (`BR-CTM-01`): nó sống trên chính level dạy
 * qua `SkillLevelPlan.dataset`. Trước 2026-09-06 dataset này treo ở kỹ năng bậc
 * `pre` C1.NREC.15, kỹ năng đó đã bị gỡ.
 */
const TOPIC_NUMBER_11_20_DATASET: SkillDataset = {
  skill_code: "C1.NREC.04",
  concept_label: "Làm quen số 11–20",
  surface: "game",
  items: [
    {
      id: "n11",
      label: "mười một",
      glyph: "11",
      value: 11,
      audio_path: "/audio/voice/common/numbers/11.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n12",
      label: "mười hai",
      glyph: "12",
      value: 12,
      audio_path: "/audio/voice/common/numbers/12.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n13",
      label: "mười ba",
      glyph: "13",
      value: 13,
      audio_path: "/audio/voice/common/numbers/13.mp3",
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n14",
      label: "mười bốn",
      glyph: "14",
      value: 14,
      audio_path: "/audio/voice/common/numbers/14.mp3",
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n15",
      label: "mười lăm",
      glyph: "15",
      value: 15,
      audio_path: "/audio/voice/common/numbers/15.mp3",
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n16",
      label: "mười sáu",
      glyph: "16",
      value: 16,
      audio_path: "/audio/voice/common/numbers/16.mp3",
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n17",
      label: "mười bảy",
      glyph: "17",
      value: 17,
      audio_path: "/audio/voice/common/numbers/17.mp3",
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n18",
      label: "mười tám",
      glyph: "18",
      value: 18,
      audio_path: "/audio/voice/common/numbers/18.mp3",
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n19",
      label: "mười chín",
      glyph: "19",
      value: 19,
      audio_path: "/audio/voice/common/numbers/19.mp3",
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n20",
      label: "hai mươi",
      glyph: "20",
      value: 20,
      audio_path: "/audio/voice/common/numbers/20.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Giới thiệu chữ số 11 đến 20 qua tai và mắt",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết chữ số 11 đến 20 giữa các phương án",
    },
    {
      rung: 3,
      dimension: "range",
      description: "Gọi tên và củng cố chữ số 11 đến 20",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy làm quen với chữ số nhé!",
    narration_template: "Chúng mình cùng làm quen với các số từ 11 đến 20 nhé",
    success_message: "Hoan hô, bé đã nhận biết rất tốt!",
    hint_message: "Bé hãy lắng nghe và nhìn kỹ chữ số nhé!",
  },
  ordering: [
    "n11",
    "n12",
    "n13",
    "n14",
    "n15",
    "n16",
    "n17",
    "n18",
    "n19",
    "n20",
  ],
};

export const C1_NREC_04_SEED: SkillSeed = {
  identity: C1_NREC_04_IDENTITY,
  dataset: C1_NREC_04_DATASET,
  levels: [
    {
      code: "GL-C1-NREC-INTRO-0003",
      template: "GT-000",
      band: "5-6",
      difficulty: 1,
      theme: "space",
      rounds: 1,
      dataset: TOPIC_NUMBER_11_20_DATASET,
      sequence_no: 1,
      skill_codes: ["C1.NREC.04"],
    },
    {
      code: "GL-C1-NREC-TAP-0008",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TAP-0009",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TAP-0010",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TAP-0011",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCNT-0005",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCNT-0006",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCNT-0007",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCNT-0008",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCMP-0011",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCMP-0012",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCMP-0013",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-TCMP-0014",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PAIR-0005",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PAIR-0006",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PAIR-0007",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PAIR-0008",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PATT-0011",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PATT-0012",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PATT-0013",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-NREC-PATT-0014",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
