import type { ContentSeed } from "../types.js";
import { SEED_MONT_A03 } from "./seed-mont-a03.js";
import { SEED_MONT_A10 } from "./seed-mont-a10.js";

export const C4_BASE_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C4-OBS-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title: "Quan sát tìm quả dâu",
      instruction: "Em hãy tìm và chọn quả dâu tây.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "sb1", emoji: "🍓" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C4-OBS-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title: "Quan sát tìm chú thỏ",
      instruction: "Em tìm chú thỏ bông trong tranh.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "r1", emoji: "🐰" },
        { id: "r2", emoji: "🐰" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 3 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C4-OBS-CARD-0003",
      content_version: 1,
      template_code: "GT-003",
      title: "Tìm điểm khác biệt đơn giản",
      instruction: "Chọn hình khác loại với các hình còn lại.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C4.VIS.04"],
      learning_objective_codes: ["LO-C4.VIS.04-01"],
      what_tags: ["cmp"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🍎" }, { emoji: "🍎" }],
      right_group: [{ emoji: "🍌" }],
      target: "different",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C4-DIF-BOX-0004",
      content_version: 1,
      template_code: "GT-002",
      title: "Nhặt rác giữ sạch công viên",
      instruction: "Kéo vỏ chai vào thùng rác.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "trash_bin", label: "Thùng rác", target_category: "waste" },
      ],
      drag_items: [
        { id: "b1", emoji: "🍾", category: "waste" },
        { id: "f1", emoji: "🌻", category: "flower" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C4-OBS-LOC-0005",
      content_version: 1,
      template_code: "GT-005",
      title: "Quan sát ô ly ẩn nấp",
      instruction: "Chạm vào chú bướm trên cành cây.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "bf", emoji: "🦋", position: "tree" },
          { id: "lf", emoji: "🍃", position: "ground" },
        ],
      ],
      target_id: "bf",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C4-SEQ-OBS-0006",
      content_version: 1,
      template_code: "GT-004",
      title: "Theo dõi quy luật màu sắc",
      instruction: "Chọn màu tiếp theo đúng dãy.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🟢", "🟡", "🟢", "🟡"],
      options: ["🟢", "🟡", "🔴"],
      correct_option: "🟢",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C4-DIF-CMP-0007",
      content_version: 1,
      template_code: "GT-003",
      title: "Tìm con vật khác nhóm",
      instruction: "Chọn chú chim giữa đàn cá.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C4.VIS.04"],
      learning_objective_codes: ["LO-C4.VIS.04-01"],
      what_tags: ["cmp"],
      thinking_tags: ["visual"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🐠" }, { emoji: "🐠" }],
      right_group: [{ emoji: "🐥" }],
      target: "different",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C4-OBS-BOX-0008",
      content_version: 1,
      template_code: "GT-002",
      title: "Gom lá cây khô",
      instruction: "Kéo chiếc lá vàng vào bao.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "leaf_sack", label: "Bao lá khô", target_type: "yellow_leaf" },
      ],
      drag_items: [
        { id: "yl", emoji: "🍂", type: "yellow_leaf" },
        { id: "gl", emoji: "🌿", type: "green_leaf" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C4-OBS-LOC-0009",
      content_version: 1,
      template_code: "GT-005",
      title: "Quan sát bóng râm",
      instruction: "Chạm vào bóng cây dừa.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["spatial"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [{ id: "coconut_tree", emoji: "🌴", shadow: true }],
        [{ id: "stone", emoji: "🪨", shadow: false }],
      ],
      target_id: "coconut_tree",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C4-SUB-FAST-0010",
      content_version: 1,
      template_code: "GT-006",
      title: "Quan sát hình ảnh chớp nhoáng",
      instruction: "Vật thể nào vừa chớp mắt qua.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🚗" }],
      flash_duration_ms: 1500,
      options: ["Xe ô tô", "Xe đạp"],
      correct_answer: "Xe ô tô",
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C4-OBS-CARD-0011",
      content_version: 1,
      template_code: "GT-001",
      title: "Quan sát đếm cá heo",
      instruction: "Đếm xem có bao nhiêu cá heo.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "d1", emoji: "🐬" },
        { id: "d2", emoji: "🐬" },
        { id: "d3", emoji: "🐬" },
      ],
      target_count: 3,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C4-SEQ-OBS-0012",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy hình ảnh động vật lặp lại",
      instruction: "Chọn con vật tiếp theo đúng dãy.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["sequential"],
      theme_tag: "zoo",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🐶", "🐱", "🐶", "🐱"],
      options: ["🐶", "🐱", "🐭"],
      correct_option: "🐶",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C4-DIF-CMP-0013",
      content_version: 1,
      template_code: "GT-003",
      title: "Tìm chi tiết khác màu sắc",
      instruction: "Chọn bông hoa có màu khác.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C4.VIS.04"],
      learning_objective_codes: ["LO-C4.VIS.04-01"],
      what_tags: ["cmp"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🌹" }, { emoji: "🌹" }],
      right_group: [{ emoji: "🌻" }],
      target: "different",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C4-OBS-BOX-0014",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại dụng cụ nấu ăn",
      instruction: "Bỏ dụng cụ làm bếp vào tủ.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "kitchen_cupboard", label: "Tủ bếp", target_category: "kitchen" },
      ],
      drag_items: [
        { id: "k1", emoji: "🍳", category: "kitchen" },
        { id: "t1", emoji: "🧸", category: "toy" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C4-SUB-FAST-0015",
      content_version: 1,
      template_code: "GT-006",
      title: "Nhìn tinh mắt tìm đồ chơi",
      instruction: "Đồ chơi nào vừa ẩn sau màn.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🧸" }],
      flash_duration_ms: 1200,
      options: ["Gấu bông", "Búp bê"],
      correct_answer: "Gấu bông",
    },
    difficulty_params: { flash_duration_ms: 1200 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C4-OBS-LOC-0016",
      content_version: 1,
      template_code: "GT-005",
      title: "Quan sát chi tiết bị che khuất",
      instruction: "Chạm vào ô có chú rùa xanh.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "turtle", emoji: "🐢", hidden: false },
          { id: "rock", emoji: "🪨", hidden: false },
        ],
      ],
      target_id: "turtle",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C4-DIF-CMP-0017",
      content_version: 1,
      template_code: "GT-003",
      title: "Tìm chi tiết quay ngược hướng",
      instruction: "Chọn chiếc xe quay sang trái.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C4.VIS.04"],
      learning_objective_codes: ["LO-C4.VIS.04-01"],
      what_tags: ["cmp"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🚘", dir: "left" }],
      right_group: [{ emoji: "🚖", dir: "right" }],
      target: "left",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C4-SEQ-OBS-0018",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy hình ảnh có chi tiết thay đổi",
      instruction: "Chọn hình tiếp theo trong chuỗi.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🌕", "🌖", "🌗", "🌘"],
      options: ["🌑", "🌕", "🌔"],
      correct_option: "🌑",
    },
    difficulty_params: { pattern_length: 4 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C4-SUB-FAST-0019",
      content_version: 1,
      template_code: "GT-006",
      title: "Thử thách tinh mắt 1 giây",
      instruction: "Quả bóng vừa hiện có màu gì.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🔴" }],
      flash_duration_ms: 1000,
      options: ["Màu đỏ", "Màu xanh"],
      correct_answer: "Màu đỏ",
    },
    difficulty_params: { flash_duration_ms: 1000 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C4-OBS-BOX-0020",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại động vật và thực vật",
      instruction: "Kéo cây xanh vào mảnh vườn.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C4.VIS.03"],
      learning_objective_codes: ["LO-C4.VIS.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "garden", label: "Mảnh vườn", target_type: "plant" }],
      drag_items: [
        { id: "p1", emoji: "🌳", type: "plant" },
        { id: "a1", emoji: "🐶", type: "animal" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
];

export const C4_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  ...C4_BASE_LEVELS,
  ...SEED_MONT_A03,
  ...SEED_MONT_A10,
];
