import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_OTO_07_IDENTITY: SkillIdentity = {
  code: "C1.OTO.07",
  strand_code: "C1.OTO",
  competency_code: "C1",
  name: "Ghép theo quy luật",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["match", "infer"],
  tier: "advanced",
  prerequisites: ["C1.OTO.01", "C1.PAT.01"],
  learning_objectives: [
    {
      code: "LO-C1.OTO.07-01",
      behaviour: "Nhận biết và thực hành Ghép theo quy luật ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.OTO.07-02",
      behaviour: "Vận dụng Ghép theo quy luật trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.OTO.07-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Ghép theo quy luật",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_OTO_07_DATASET: SkillDataset = {
  skill_code: "C1.OTO.07",
  concept_label: "Ghép theo quy luật",
  surface: "game",
  items: [
    {
      id: "shape_red_circle",
      label: "hình tròn đỏ",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🔴",
      },
      contrast_group: "circle",
    },
    {
      id: "shape_blue_circle",
      label: "hình tròn xanh",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🔵",
      },
      contrast_group: "circle",
    },
    {
      id: "shape_red_square",
      label: "hình vuông đỏ",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🟥",
      },
      contrast_group: "square",
    },
    {
      id: "shape_blue_square",
      label: "hình vuông xanh",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🟦",
      },
      contrast_group: "square",
    },
    {
      id: "shape_red_triangle",
      label: "hình tam giác đỏ",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🔺",
      },
      contrast_group: "triangle",
    },
    {
      id: "shape_blue_triangle",
      label: "hình tam giác xanh",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🔷",
      },
      contrast_group: "triangle",
    },
  ],
  relations: [
    {
      type: "pair",
      source_id: "shape_red_circle",
      target_id: "shape_blue_circle",
    },
    {
      type: "pair",
      source_id: "shape_red_square",
      target_id: "shape_blue_square",
    },
    {
      type: "pair",
      source_id: "shape_red_triangle",
      target_id: "shape_blue_triangle",
    },
    {
      type: "subset",
      source_id: "shape_red_circle",
      target_id: "shape_red_square",
      metadata: {
        rule: "shape_transformation",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với ghép theo quy luật",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng ghép theo quy luật",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt ghép theo quy luật với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi ghép theo quy luật",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục ghép theo quy luật và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy ghép đôi từng {label} tương ứng nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Ghép theo quy luật nhé",
  },
};

export const C1_OTO_07_SEED: SkillSeed = {
  identity: C1_OTO_07_IDENTITY,
  dataset: C1_OTO_07_DATASET,
  levels: [
    {
      code: "GL-C1-OTO-TAP-0025",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0026",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0027",
      template: "GT-001",
      band: "4-5",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0028",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0025",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0026",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0027",
      template: "GT-003",
      band: "4-5",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0028",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PAIR-0009",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PAIR-0010",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PAIR-0011",
      template: "GT-004",
      band: "4-5",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PAIR-0012",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0025",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0026",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0027",
      template: "GT-005",
      band: "4-5",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0028",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SORT-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SORT-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SORT-0003",
      template: "GT-006",
      band: "5-6",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SORT-0004",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-MIR-0003",
      template: "GT-021",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-MIR-0004",
      template: "GT-021",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
  ],
};
