import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_OTO_01_IDENTITY: SkillIdentity = {
  code: "C1.OTO.01",
  strand_code: "C1.OTO",
  competency_code: "C1",
  name: "Ghép 1-1",
  age_min: 3,
  age_max: 3,
  difficulty: 1,
  thinking_processes: ["match"],
  tier: "basic",
  prerequisites: [],
  learning_objectives: [
    {
      code: "LO-C1.OTO.01-01",
      behaviour: "Nhận biết và thực hành Ghép 1-1 ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.OTO.01-02",
      behaviour: "Vận dụng Ghép 1-1 trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.OTO.01-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Ghép 1-1",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_OTO_01_DATASET: SkillDataset = {
  skill_code: "C1.OTO.01",
  concept_label: "Ghép 1-1",
  surface: "game",
  items: [
    {
      id: "rabbit",
      label: "chú thỏ",
      glyph: "🐇",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🐇",
      },
      contrast_group: "animal",
    },
    {
      id: "carrot",
      label: "củ cà rốt",
      glyph: "🥕",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🥕",
      },
      contrast_group: "food",
    },
    {
      id: "cat",
      label: "chú mèo",
      glyph: "🐱",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🐱",
      },
      contrast_group: "animal",
    },
    {
      id: "fish",
      label: "con cá",
      glyph: "🐟",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🐟",
      },
      contrast_group: "food",
    },
    {
      id: "dog",
      label: "chú chó",
      glyph: "🐕",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🐕",
      },
      contrast_group: "animal",
    },
    {
      id: "bone",
      label: "khúc xương",
      glyph: "🦴",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🦴",
      },
      contrast_group: "food",
    },
  ],
  relations: [
    {
      type: "pair",
      source_id: "rabbit",
      target_id: "carrot",
      metadata: {
        relation: "one_to_one",
      },
    },
    {
      type: "pair",
      source_id: "cat",
      target_id: "fish",
      metadata: {
        relation: "one_to_one",
      },
    },
    {
      type: "pair",
      source_id: "dog",
      target_id: "bone",
      metadata: {
        relation: "one_to_one",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "discrete-object",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "discrete-object",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "discrete-object",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy ghép đôi từng {label} tương ứng nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Ghép 1-1 nhé",
  },
};

export const C1_OTO_01_SEED: SkillSeed = {
  identity: C1_OTO_01_IDENTITY,
  dataset: C1_OTO_01_DATASET,
  levels: [
    {
      code: "GL-C1-OTO-CARD-0103",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB01-D2",
    },
    {
      code: "GL-C1-OTO-TAP-0001",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0002",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0003",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0004",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0001",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0002",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0003",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0004",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0001",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0002",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0003",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0004",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0001",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0002",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0003",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0004",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-GRID-0001",
      template: "GT-020",
      band: "3-4",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-GRID-0002",
      template: "GT-020",
      band: "3-4",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-GRID-0003",
      template: "GT-020",
      band: "3-4",
      difficulty: 1,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-GRID-0004",
      template: "GT-020",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
