import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_OTO_04_IDENTITY: SkillIdentity = {
  code: "C1.OTO.04",
  strand_code: "C1.OTO",
  competency_code: "C1",
  name: "Ghép đồ vật với số",
  age_min: 4,
  age_max: 4,
  difficulty: 2,
  thinking_processes: ["match"],
  tier: "basic",
  prerequisites: ["C1.OTO.01", "C1.NREC.02"],
  learning_objectives: [
    {
      code: "LO-C1.OTO.04-01",
      behaviour: "Nhận biết và thực hành Ghép đồ vật với số ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.OTO.04-02",
      behaviour: "Vận dụng Ghép đồ vật với số trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.OTO.04-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Ghép đồ vật với số",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_OTO_04_DATASET: SkillDataset = {
  skill_code: "C1.OTO.04",
  concept_label: "Ghép đồ vật với số",
  surface: "game",
  items: [
    {
      id: "one_star",
      label: "một ngôi sao",
      glyph: "⭐",
      value: 1,
      image: {
        kind: "emoji",
        ref: "⭐",
      },
      contrast_group: "object",
    },
    {
      id: "num_1",
      label: "số một",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
      contrast_group: "numeral",
    },
    {
      id: "two_hearts",
      label: "hai trái tim",
      glyph: "💖",
      value: 2,
      image: {
        kind: "emoji",
        ref: "💖",
      },
      contrast_group: "object",
    },
    {
      id: "num_2",
      label: "số hai",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
      contrast_group: "numeral",
    },
    {
      id: "three_flowers",
      label: "ba bông hoa",
      glyph: "🌸",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🌸",
      },
      contrast_group: "object",
    },
    {
      id: "num_3",
      label: "số ba",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
      contrast_group: "numeral",
    },
  ],
  relations: [
    {
      type: "pair",
      source_id: "one_star",
      target_id: "num_1",
    },
    {
      type: "pair",
      source_id: "two_hearts",
      target_id: "num_2",
    },
    {
      type: "pair",
      source_id: "three_flowers",
      target_id: "num_3",
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với ghép đồ vật với số",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng ghép đồ vật với số",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt ghép đồ vật với số với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi ghép đồ vật với số",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục ghép đồ vật với số và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy ghép đôi từng {label} tương ứng nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Ghép đồ vật với số nhé",
  },
};

export const C1_OTO_04_SEED: SkillSeed = {
  identity: C1_OTO_04_IDENTITY,
  dataset: C1_OTO_04_DATASET,
  levels: [
    {
      code: "GL-C1-OTO-CARD-0104",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB01-D2",
    },
    {
      code: "GL-C1-OTO-TAP-0013",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0014",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0015",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TAP-0016",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0013",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0014",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0015",
      template: "GT-003",
      band: "3-4",
      difficulty: 3,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-TCMP-0016",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0013",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0014",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0015",
      template: "GT-005",
      band: "3-4",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PATT-0016",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0009",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0010",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0011",
      template: "GT-008",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-SLOT-0012",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PUZZ-0001",
      template: "GT-010",
      band: "4-5",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PUZZ-0002",
      template: "GT-010",
      band: "4-5",
      difficulty: 2,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PUZZ-0003",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-PUZZ-0004",
      template: "GT-010",
      band: "4-5",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-FLIP-0001",
      template: "GT-020",
      band: "4-5",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-FLIP-0002",
      template: "GT-020",
      band: "4-5",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
  ],
};
