import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_CNT_04_IDENTITY: SkillIdentity = {
  code: "C1.CNT.04",
  strand_code: "C1.CNT",
  competency_code: "C1",
  name: "Đếm ngược",
  age_min: 4,
  age_max: 4,
  difficulty: 3,
  thinking_processes: ["count", "sequence"],
  tier: "core",
  prerequisites: ["C1.CNT.01", "C1.NREC.09"],
  learning_objectives: [
    {
      code: "LO-C1.CNT.04-01",
      behaviour: "Nhận biết và thực hành Đếm ngược ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.CNT.04-02",
      behaviour: "Vận dụng Đếm ngược trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.CNT.04-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đếm ngược",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_CNT_04_DATASET: SkillDataset = {
  skill_code: "C1.CNT.04",
  concept_label: "Đếm ngược",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "số không",
      glyph: "0",
      value: 0,
      audio_path: "/audio/voice/common/numbers/0.mp3",
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "số một",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "số hai",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "số ba",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n4",
      label: "số bốn",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n5",
      label: "số năm",
      glyph: "5",
      value: 5,
      audio_path: "/audio/voice/common/numbers/5.mp3",
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n6",
      label: "số sáu",
      glyph: "6",
      value: 6,
      audio_path: "/audio/voice/common/numbers/6.mp3",
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n7",
      label: "số bảy",
      glyph: "7",
      value: 7,
      audio_path: "/audio/voice/common/numbers/7.mp3",
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n8",
      label: "số tám",
      glyph: "8",
      value: 8,
      audio_path: "/audio/voice/common/numbers/8.mp3",
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n9",
      label: "số chín",
      glyph: "9",
      value: 9,
      audio_path: "/audio/voice/common/numbers/9.mp3",
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n10",
      label: "số mười",
      glyph: "10",
      value: 10,
      audio_path: "/audio/voice/common/numbers/10.mp3",
      image: {
        kind: "emoji",
        ref: "🔟",
      },
    },
    {
      id: "n11",
      label: "số mười một",
      glyph: "11",
      value: 11,
      audio_path: "/audio/voice/common/numbers/11.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣1️⃣",
      },
    },
    {
      id: "n12",
      label: "số mười hai",
      glyph: "12",
      value: 12,
      audio_path: "/audio/voice/common/numbers/12.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣2️⃣",
      },
    },
    {
      id: "n13",
      label: "số mười ba",
      glyph: "13",
      value: 13,
      audio_path: "/audio/voice/common/numbers/13.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣3️⃣",
      },
    },
    {
      id: "n14",
      label: "số mười bốn",
      glyph: "14",
      value: 14,
      audio_path: "/audio/voice/common/numbers/14.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣4️⃣",
      },
    },
    {
      id: "n15",
      label: "số mười lăm",
      glyph: "15",
      value: 15,
      audio_path: "/audio/voice/common/numbers/15.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣5️⃣",
      },
    },
    {
      id: "n16",
      label: "số mười sáu",
      glyph: "16",
      value: 16,
      audio_path: "/audio/voice/common/numbers/16.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣6️⃣",
      },
    },
    {
      id: "n17",
      label: "số mười bảy",
      glyph: "17",
      value: 17,
      audio_path: "/audio/voice/common/numbers/17.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣7️⃣",
      },
    },
    {
      id: "n18",
      label: "số mười tám",
      glyph: "18",
      value: 18,
      audio_path: "/audio/voice/common/numbers/18.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣8️⃣",
      },
    },
    {
      id: "n19",
      label: "số mười chín",
      glyph: "19",
      value: 19,
      audio_path: "/audio/voice/common/numbers/19.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣9️⃣",
      },
    },
    {
      id: "n20",
      label: "số hai mươi",
      glyph: "20",
      value: 20,
      audio_path: "/audio/voice/common/numbers/20.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣0️⃣",
      },
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "n0",
      target_id: "n1",
    },
    {
      type: "sequence",
      source_id: "n1",
      target_id: "n2",
    },
    {
      type: "sequence",
      source_id: "n2",
      target_id: "n3",
    },
    {
      type: "sequence",
      source_id: "n3",
      target_id: "n4",
    },
    {
      type: "sequence",
      source_id: "n4",
      target_id: "n5",
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với đếm ngược",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng đếm ngược",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt đếm ngược với phương án nhiễu",
      representation: "ten-frame",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi đếm ngược",
      representation: "ten-frame",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục đếm ngược và tự làm một mình",
      representation: "ten-frame",
    },
  ],
  phrasing: {
    prompt_template: "Bé đếm ngược xem còn mấy nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Đếm ngược nhé",
  },
  ordering: [
    "n20",
    "n19",
    "n18",
    "n17",
    "n16",
    "n15",
    "n14",
    "n13",
    "n12",
    "n11",
    "n10",
    "n9",
    "n8",
    "n7",
    "n6",
    "n5",
    "n4",
    "n3",
    "n2",
    "n1",
    "n0",
  ],
};

export const C1_CNT_04_SEED: SkillSeed = {
  identity: C1_CNT_04_IDENTITY,
  dataset: C1_CNT_04_DATASET,
  levels: [
    {
      code: "GL-C1-CNT-TAP-0006",
      template: "GT-028",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0007",
      template: "GT-028",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0008",
      template: "GT-028",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0009",
      template: "GT-028",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0010",
      template: "GT-028",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-BCK-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-BCK-0002",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-CDW-ORD-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-CDW-ORD-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-CDW-ORD-0003",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-CDW-ORD-0004",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-SUB-FLS-0001",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0002",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0003",
      template: "GT-012",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0004",
      template: "GT-012",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0005",
      template: "GT-012",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-CNT-TAP-0022",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0023",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0024",
      template: "GT-001",
      band: "3-4",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0004",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0005",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0006",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0007",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0006",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0007",
      template: "GT-003",
      band: "3-4",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0008",
      template: "GT-003",
      band: "3-4",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0009",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0011",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0012",
      template: "GT-007",
      band: "3-4",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0013",
      template: "GT-007",
      band: "3-4",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0014",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0001",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0002",
      template: "GT-008",
      band: "3-4",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0003",
      template: "GT-008",
      band: "3-4",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0004",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
