import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_CNT_03_IDENTITY: SkillIdentity = {
  code: "C1.CNT.03",
  strand_code: "C1.CNT",
  competency_code: "C1",
  name: "Đếm không bỏ sót",
  age_min: 3,
  age_max: 3,
  difficulty: 2,
  thinking_processes: ["count", "verify"],
  tier: "basic",
  prerequisites: ["C1.CNT.01"],
  learning_objectives: [
    {
      code: "LO-C1.CNT.03-01",
      behaviour: "Nhận biết và thực hành Đếm không bỏ sót ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.CNT.03-02",
      behaviour: "Vận dụng Đếm không bỏ sót trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.CNT.03-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đếm không bỏ sót",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_CNT_03_DATASET: SkillDataset = {
  skill_code: "C1.CNT.03",
  concept_label: "Đếm không bỏ sót",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "Số không",
      glyph: "0",
      value: 0,
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "Số một",
      glyph: "1",
      value: 1,
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "Số hai",
      glyph: "2",
      value: 2,
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "Số ba",
      glyph: "3",
      value: 3,
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n4",
      label: "Số bốn",
      glyph: "4",
      value: 4,
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n5",
      label: "Số năm",
      glyph: "5",
      value: 5,
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n6",
      label: "Số sáu",
      glyph: "6",
      value: 6,
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n7",
      label: "Số bảy",
      glyph: "7",
      value: 7,
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n8",
      label: "Số tám",
      glyph: "8",
      value: 8,
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n9",
      label: "Số chín",
      glyph: "9",
      value: 9,
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n10",
      label: "Số mười",
      glyph: "10",
      value: 10,
      image: {
        kind: "emoji",
        ref: "🔟",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Đếm không bỏ sót",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Đếm không bỏ sót",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Đếm không bỏ sót nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ {label} nhé!",
  },
  ordering: ["n0", "n1", "n2", "n3", "n4", "n5", "n6", "n7", "n8", "n9", "n10"],
};

export const C1_CNT_03_SEED: SkillSeed = {
  identity: C1_CNT_03_IDENTITY,
  dataset: C1_CNT_03_DATASET,
  levels: [
    {
      code: "GL-C1-CNT-CARD-0005",
      template: "GT-012",
      band: "4-5",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-SORT-BOX-0008",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-SORT-BOX-0009",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-POS-LOC-0018",
      template: "GT-022",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-CONT-0106",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      montessori_ref: "WB01-D3",
    },
    {
      code: "GL-C1-CNT-PAIR-0112",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB05-D1",
    },
    {
      code: "GL-C1-CNT-CONT-0114",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB05-D2",
    },
    {
      code: "GL-C1-CNT-TAP-0001",
      template: "GT-028",
      band: "4-5",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0002",
      template: "GT-028",
      band: "4-5",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0003",
      template: "GT-028",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0004",
      template: "GT-028",
      band: "4-5",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0005",
      template: "GT-028",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-REM-SET-0003",
      template: "GT-029",
      band: "4-5",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-REM-SET-0005",
      template: "GT-029",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-REM-SET-0006",
      template: "GT-029",
      band: "5-6",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-OTO-MATCH-0005",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
    {
      code: "GL-C1-OTO-MATCH-0006",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
    {
      code: "GL-C1-OTO-MATCH-0007",
      template: "GT-005",
      band: "4-5",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
    {
      code: "GL-C1-OTO-MATCH-0008",
      template: "GT-005",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
    {
      code: "GL-C1-CNT-TAP-0017",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0018",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0019",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0020",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0021",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0005",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0006",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0007",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0008",
      template: "GT-007",
      band: "3-4",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0009",
      template: "GT-007",
      band: "3-4",
      difficulty: 1,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0010",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-MEMO-0002",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-MEMO-0003",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-MEMO-0004",
      template: "GT-012",
      band: "3-4",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-MEMO-0005",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "family",
      rounds: 3,
    },
  ],
};
