import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_CNT_01_IDENTITY: SkillIdentity = {
  code: "C1.CNT.01",
  strand_code: "C1.CNT",
  competency_code: "C1",
  name: "Đếm đồ vật",
  age_min: 3,
  age_max: 3,
  difficulty: 1,
  thinking_processes: ["count"],
  tier: "basic",
  prerequisites: [],
  learning_objectives: [
    {
      code: "LO-C1.CNT.01-01",
      behaviour: "Nhận biết và thực hành Đếm đồ vật ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.CNT.01-02",
      behaviour: "Vận dụng Đếm đồ vật trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.CNT.01-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đếm đồ vật",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_CNT_01_DATASET: SkillDataset = {
  skill_code: "C1.CNT.01",
  concept_label: "Đếm đồ vật",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "không",
      glyph: "0",
      value: 0,
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "một",
      glyph: "1",
      value: 1,
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "hai",
      glyph: "2",
      value: 2,
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "ba",
      glyph: "3",
      value: 3,
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Đếm đồ vật",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Đếm đồ vật",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Đếm đồ vật nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ hình {label} nhé!",
  },
  ordering: ["n0", "n1", "n2", "n3"],
};

export const C1_CNT_01_SEED: SkillSeed = {
  identity: C1_CNT_01_IDENTITY,
  dataset: C1_CNT_01_DATASET,
  levels: [
    {
      code: "GL-C1-CNT-CARD-0001",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-CARD-0002",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-CARD-0003",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-SORT-BOX-0006",
      template: "GT-003",
      band: "4-5",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-SORT-BOX-0007",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-POS-LOC-0017",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-MEM-FLASH-0040",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-CONT-0105",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "food",
      rounds: 3,
      montessori_ref: "WB01-D3",
    },
    {
      code: "GL-C1-CNT-PAIR-0111",
      template: "GT-005",
      band: "4-5",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB05-D1",
    },
    {
      code: "GL-C1-CNT-CONT-0113",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      montessori_ref: "WB05-D2",
    },
    {
      code: "GL-C1-REM-SET-0001",
      template: "GT-029",
      band: "4-5",
      difficulty: 1,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-REM-SET-0002",
      template: "GT-029",
      band: "4-5",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-REM-SET-0004",
      template: "GT-029",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-CNT-INTRO-0001",
      template: "GT-000",
      band: "3-4",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-OTO-MATCH-0001",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
    {
      code: "GL-C1-OTO-MATCH-0002",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
    {
      code: "GL-C1-OTO-MATCH-0003",
      template: "GT-005",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
    {
      code: "GL-C1-OTO-MATCH-0004",
      template: "GT-005",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D1-02",
    },
  ],
};
