import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_CNT_05_IDENTITY: SkillIdentity = {
  code: "C1.CNT.05",
  strand_code: "C1.CNT",
  competency_code: "C1",
  name: "Đếm cách 2",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["count", "infer"],
  tier: "advanced",
  prerequisites: ["C1.CNT.04"],
  learning_objectives: [
    {
      code: "LO-C1.CNT.05-01",
      behaviour: "Nhận biết và thực hành Đếm cách 2 ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.CNT.05-02",
      behaviour: "Vận dụng Đếm cách 2 trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.CNT.05-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đếm cách 2",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_CNT_05_DATASET: SkillDataset = {
  skill_code: "C1.CNT.05",
  concept_label: "Đếm cách 2",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "không",
      glyph: "0",
      value: 0,
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "một",
      glyph: "1",
      value: 1,
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "hai",
      glyph: "2",
      value: 2,
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "ba",
      glyph: "3",
      value: 3,
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n4",
      label: "bốn",
      glyph: "4",
      value: 4,
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n5",
      label: "năm",
      glyph: "5",
      value: 5,
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n6",
      label: "sáu",
      glyph: "6",
      value: 6,
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n7",
      label: "bảy",
      glyph: "7",
      value: 7,
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n8",
      label: "tám",
      glyph: "8",
      value: 8,
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n9",
      label: "chín",
      glyph: "9",
      value: 9,
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n10",
      label: "mười",
      glyph: "10",
      value: 10,
      image: {
        kind: "emoji",
        ref: "🔟",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Đếm cách 2",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Đếm cách 2",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Đếm cách 2 nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ hình {label} nhé!",
  },
  ordering: ["n0", "n1", "n2", "n3", "n4", "n5", "n6", "n7", "n8", "n9", "n10"],
};

export const C1_CNT_05_SEED: SkillSeed = {
  identity: C1_CNT_05_IDENTITY,
  dataset: C1_CNT_05_DATASET,
  levels: [
    {
      code: "GL-C1-CNT-CARD-0119",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB11-D1",
    },
    {
      code: "GL-C1-CNT-CARD-0120",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB11-D1",
    },
    {
      code: "GL-C1-CNT-SLOT-0133",
      template: "GT-008",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB11-D2",
    },
    {
      code: "GL-C1-CNT-SLOT-0134",
      template: "GT-008",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
      montessori_ref: "WB11-D2",
    },
    {
      code: "GL-C1-REM-SET-0007",
      template: "GT-029",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-REM-SET-0008",
      template: "GT-029",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-REM-SET-0009",
      template: "GT-029",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-REM-SET-0010",
      template: "GT-029",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-12",
    },
    {
      code: "GL-C1-SUB-FLS-0006",
      template: "GT-012",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0007",
      template: "GT-012",
      band: "4-5",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0008",
      template: "GT-012",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0009",
      template: "GT-012",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0010",
      template: "GT-012",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
  ],
};
