import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_CNT_04_IDENTITY: SkillIdentity = {
  code: "C1.CNT.04",
  strand_code: "C1.CNT",
  competency_code: "C1",
  name: "Đếm ngược",
  age_min: 4,
  age_max: 4,
  difficulty: 3,
  thinking_processes: ["count", "sequence"],
  tier: "core",
  prerequisites: ["C1.CNT.01", "C1.NREC.09"],
  learning_objectives: [
    {
      code: "LO-C1.CNT.04-01",
      behaviour: "Nhận biết và thực hành Đếm ngược ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.CNT.04-02",
      behaviour: "Vận dụng Đếm ngược trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.CNT.04-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Đếm ngược",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_CNT_04_DATASET: SkillDataset = {
  skill_code: "C1.CNT.04",
  concept_label: "Đếm ngược",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "Số không",
      glyph: "0",
      value: 0,
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "Số một",
      glyph: "1",
      value: 1,
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "Số hai",
      glyph: "2",
      value: 2,
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "Số ba",
      glyph: "3",
      value: 3,
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n4",
      label: "Số bốn",
      glyph: "4",
      value: 4,
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n5",
      label: "Số năm",
      glyph: "5",
      value: 5,
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n6",
      label: "Số sáu",
      glyph: "6",
      value: 6,
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n7",
      label: "Số bảy",
      glyph: "7",
      value: 7,
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n8",
      label: "Số tám",
      glyph: "8",
      value: 8,
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n9",
      label: "Số chín",
      glyph: "9",
      value: 9,
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n10",
      label: "Số mười",
      glyph: "10",
      value: 10,
      image: {
        kind: "emoji",
        ref: "🔟",
      },
    },
    {
      id: "n11",
      label: "Số mười một",
      glyph: "11",
      value: 11,
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n12",
      label: "Số mười hai",
      glyph: "12",
      value: 12,
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n13",
      label: "Số mười ba",
      glyph: "13",
      value: 13,
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n14",
      label: "Số mười bốn",
      glyph: "14",
      value: 14,
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n15",
      label: "Số mười lăm",
      glyph: "15",
      value: 15,
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n16",
      label: "Số mười sáu",
      glyph: "16",
      value: 16,
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n17",
      label: "Số mười bảy",
      glyph: "17",
      value: 17,
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n18",
      label: "Số mười tám",
      glyph: "18",
      value: 18,
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n19",
      label: "Số mười chín",
      glyph: "19",
      value: 19,
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n20",
      label: "Số hai mươi",
      glyph: "20",
      value: 20,
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Đếm ngược",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Đếm ngược",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Đếm ngược nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ {label} nhé!",
  },
  ordering: [
    "n0",
    "n1",
    "n2",
    "n3",
    "n4",
    "n5",
    "n6",
    "n7",
    "n8",
    "n9",
    "n10",
    "n11",
    "n12",
    "n13",
    "n14",
    "n15",
    "n16",
    "n17",
    "n18",
    "n19",
    "n20",
  ],
};

export const C1_CNT_04_SEED: SkillSeed = {
  identity: C1_CNT_04_IDENTITY,
  dataset: C1_CNT_04_DATASET,
  levels: [
    {
      code: "GL-C1-CNT-TAP-0006",
      template: "GT-028",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0007",
      template: "GT-028",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0008",
      template: "GT-028",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0009",
      template: "GT-028",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-TAP-0010",
      template: "GT-028",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-10",
    },
    {
      code: "GL-C1-CNT-BCK-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-BCK-0002",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-CDW-ORD-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-CDW-ORD-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-CDW-ORD-0003",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-CDW-ORD-0004",
      template: "GT-006",
      band: "5-6",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D1-09",
    },
    {
      code: "GL-C1-SUB-FLS-0001",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0002",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0003",
      template: "GT-012",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0004",
      template: "GT-012",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-SUB-FLS-0005",
      template: "GT-012",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D1-06",
    },
    {
      code: "GL-C1-CNT-TAP-0022",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0023",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TAP-0024",
      template: "GT-001",
      band: "3-4",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0004",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0005",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0006",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCNT-0007",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0006",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0007",
      template: "GT-003",
      band: "3-4",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0008",
      template: "GT-003",
      band: "3-4",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-TCMP-0009",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0011",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0012",
      template: "GT-007",
      band: "3-4",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0013",
      template: "GT-007",
      band: "3-4",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SHAD-0014",
      template: "GT-007",
      band: "3-4",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0001",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0002",
      template: "GT-008",
      band: "3-4",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0003",
      template: "GT-008",
      band: "3-4",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-CNT-SLOT-0004",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
