import type { ContentSeed } from "../types.js";

export const C3_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C3-PAT-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Tìm thẻ theo quy luật",
      instruction_vi: "Em hãy chọn hình hoa hồng màu đỏ.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "r1", emoji: "🌹" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C3-PAT-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Tìm hoa hướng dương",
      instruction_vi: "Chạm vào bông hoa hướng dương vàng.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["analytical"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "sf1", emoji: "🌻" },
        { id: "sf2", emoji: "🌻" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 3 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C3-CLS-CARD-0003",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Chọn con vật nuôi",
      instruction_vi: "Chạm vào chú mèo con xinh xắn.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["analytical"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "cat", emoji: "🐱" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C3-CLS-BOX-0004",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại hoa và quả",
      instruction_vi: "Kéo bông hoa vào chậu cây.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["analytical"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "flower_pot", label: "Chậu hoa", target_category: "flower" },
      ],
      drag_items: [
        { id: "f1", emoji: "🌸", category: "flower" },
        { id: "a1", emoji: "🍎", category: "fruit" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C3-CLS-BOX-0005",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại phương tiện giao thông",
      instruction_vi: "Kéo xe ô tô vào garage.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "garage", label: "Nhà xe", target_category: "vehicle" },
      ],
      drag_items: [
        { id: "v1", emoji: "🚗", category: "vehicle" },
        { id: "a1", emoji: "🐶", category: "animal" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0006",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Dãy quy luật mặt cười AB",
      instruction_vi: "Chọn biểu cảm tiếp theo đúng chuỗi.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["😀", "😍", "😀", "😍"],
      options: ["😀", "😍", "😎"],
      correct_option: "😀",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0007",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Dãy quy luật thời tiết AABB",
      instruction_vi: "Chọn biểu tượng thời tiết tiếp theo.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["☀️", "☀️", "🌧️", "🌧️", "☀️"],
      options: ["☀️", "🌧️", "❄️"],
      correct_option: "☀️",
    },
    difficulty_params: { pattern_length: 4 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C3-LOG-CMP-0008",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "So sánh nặng và nhẹ",
      instruction_vi: "Chọn con vật nặng hơn nhé.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["analytical"],
      theme_tag: "zoo",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🦛", weight: "heavy" }],
      right_group: [{ emoji: "🪶", weight: "light" }],
      target: "heavy",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C3-LOG-CMP-0009",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "So sánh nhanh và chậm",
      instruction_vi: "Chọn phương tiện chạy nhanh hơn.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🚀", speed: "fast" }],
      right_group: [{ emoji: "🐌", speed: "slow" }],
      target: "fast",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C3-CLS-BOX-0010",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại động vật sống dưới nước",
      instruction_vi: "Kéo sinh vật biển vào đại dương.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["analytical"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "ocean_box", label: "Đại dương", target_habitat: "water" },
      ],
      drag_items: [
        { id: "fish", emoji: "🐟", habitat: "water" },
        { id: "bird", emoji: "🐦", habitat: "air" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C3-LOG-POS-0011",
      content_version: 1,
      template_code: "GT-005",
      title_vi: "Suy luận ai đứng đầu hàng",
      instruction_vi: "Chạm vào bạn nhỏ ở vị trí đầu tiên.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "p1", emoji: "👧", rank: 1 },
          { id: "p2", emoji: "👦", rank: 2 },
        ],
      ],
      target_id: "p1",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0012",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Quy luật đồ dùng học tập ABC",
      instruction_vi: "Chọn dụng cụ tiếp theo trong hàng.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["✏️", "📏", "✂️", "✏️", "📏"],
      options: ["✏️", "📏", "✂️"],
      correct_option: "✂️",
    },
    difficulty_params: { pattern_length: 3 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C3-SUB-FAST-0013",
      content_version: 1,
      template_code: "GT-006",
      title_vi: "Nhận biết quy luật nhanh",
      instruction_vi: "Hình nào vừa ẩn đi vậy em.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["visual"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🍎" }, { emoji: "🍌" }],
      flash_duration_ms: 1500,
      options: ["Quả táo", "Quả dưa"],
      correct_answer: "Quả táo",
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C3-CLS-BOX-0014",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại dụng cụ thể thao",
      instruction_vi: "Bỏ bóng thể thao vào rổ.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "sports_basket", label: "Rổ bóng", target_category: "sports" },
      ],
      drag_items: [
        { id: "b1", emoji: "🏀", category: "sports" },
        { id: "p1", emoji: "✏️", category: "stationery" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C3-LOG-CMP-0015",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "Suy luận dung tích chứa",
      instruction_vi: "Chọn vại chứa được nhiều nước hơn.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["analytical"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🫙", capacity: "large" }],
      right_group: [{ emoji: "🥤", capacity: "small" }],
      target: "large",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0016",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Dãy quy luật xen kẽ 4 yếu tố",
      instruction_vi: "Chọn đối tượng tiếp theo đúng luật.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🔴", "🟡", "🔵", "🔴", "🟡"],
      options: ["🔴", "🟡", "🔵"],
      correct_option: "🔵",
    },
    difficulty_params: { pattern_length: 3 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C3-LOG-POS-0017",
      content_version: 1,
      template_code: "GT-005",
      title_vi: "Vị trí nằm giữa hai đối tượng",
      instruction_vi: "Chạm vào món quà nằm ở giữa.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["analytical"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "g1", emoji: "🎈" },
          { id: "g2", emoji: "🎁", position: "middle" },
          { id: "g3", emoji: "🎈" },
        ],
      ],
      target_id: "g2",
    },
    difficulty_params: { grid_size: 3 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C3-SUB-FAST-0018",
      content_version: 1,
      template_code: "GT-006",
      title_vi: "Phản xạ phân loại siêu nhanh",
      instruction_vi: "Đó là trái cây hay động vật.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["visual"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🐱" }],
      flash_duration_ms: 1000,
      options: ["Động vật", "Trái cây"],
      correct_answer: "Động vật",
    },
    difficulty_params: { flash_duration_ms: 1000 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C3-CLS-BOX-0019",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại nhạc cụ âm nhạc",
      instruction_vi: "Kéo nhạc cụ vào sân khấu.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "stage", label: "Sân khấu", target_category: "music" },
      ],
      drag_items: [
        { id: "m1", emoji: "🎸", category: "music" },
        { id: "f1", emoji: "⚽", category: "sports" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C3-LOG-CMP-0020",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "So sánh chiều dài đoạn thẳng",
      instruction_vi: "Chọn cây bút dài hơn.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["analytical"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "✏️", length: "long" }],
      right_group: [{ emoji: "✏️", length: "short" }],
      target: "long",
    },
    difficulty_params: { max_difference: 1 },
  },
];
