import type { ContentSeed } from "#src/seed-content/types";

export const C3_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C3-PAT-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title: "Tìm thẻ theo quy luật",
      instruction: "Em hãy chọn hình hoa hồng màu đỏ.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "r1", emoji: "🌹" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C3-PAT-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title: "Tìm hoa hướng dương",
      instruction: "Chạm vào bông hoa hướng dương vàng.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["compare"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "sf1", emoji: "🌻" },
        { id: "sf2", emoji: "🌻" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 3 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C3-CLS-CARD-0003",
      content_version: 1,
      template_code: "GT-001",
      title: "Chọn con vật nuôi",
      instruction: "Chạm vào chú mèo con xinh xắn.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["compare"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "cat", emoji: "🐱" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C3-CLS-BOX-0004",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại hoa và quả",
      instruction: "Kéo bông hoa vào chậu cây.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["compare"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "flower_pot", label: "Chậu hoa", target_category: "flower" },
      ],
      drag_items: [
        { id: "f1", emoji: "🌸", category: "flower" },
        { id: "a1", emoji: "🍎", category: "fruit" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C3-CLS-BOX-0005",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại phương tiện giao thông",
      instruction: "Kéo xe ô tô vào garage.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "garage", label: "Nhà xe", target_category: "vehicle" },
      ],
      drag_items: [
        { id: "v1", emoji: "🚗", category: "vehicle" },
        { id: "a1", emoji: "🐶", category: "animal" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0006",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy quy luật mặt cười AB",
      instruction: "Chọn biểu cảm tiếp theo đúng chuỗi.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["😀", "😍", "😀", "😍"],
      options: ["😀", "😍", "😎"],
      correct_option: "😀",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0007",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy quy luật thời tiết AABB",
      instruction: "Chọn biểu tượng thời tiết tiếp theo.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["☀️", "☀️", "🌧️", "🌧️", "☀️"],
      options: ["☀️", "🌧️", "❄️"],
      correct_option: "☀️",
    },
    difficulty_params: { pattern_length: 4 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C3-LOG-CMP-0008",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh nặng và nhẹ",
      instruction: "Chọn con vật nặng hơn nhé.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["compare"],
      theme_tag: "animal",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🦛", weight: "heavy" }],
      right_group: [{ emoji: "🪶", weight: "light" }],
      target: "heavy",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C3-LOG-CMP-0009",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh nhanh và chậm",
      instruction: "Chọn phương tiện chạy nhanh hơn.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🚀", speed: "fast" }],
      right_group: [{ emoji: "🐌", speed: "slow" }],
      target: "fast",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C3-CLS-BOX-0010",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại động vật sống dưới nước",
      instruction: "Kéo sinh vật biển vào đại dương.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["compare"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "ocean_box", label: "Đại dương", target_habitat: "water" },
      ],
      drag_items: [
        { id: "fish", emoji: "🐟", habitat: "water" },
        { id: "bird", emoji: "🐦", habitat: "air" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C3-LOG-POS-0011",
      content_version: 1,
      template_code: "GT-005",
      title: "Suy luận ai đứng đầu hàng",
      instruction: "Chạm vào bạn nhỏ ở vị trí đầu tiên.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "p1", emoji: "👧", rank: 1 },
          { id: "p2", emoji: "👦", rank: 2 },
        ],
      ],
      target_id: "p1",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0012",
      content_version: 1,
      template_code: "GT-004",
      title: "Quy luật đồ dùng học tập ABC",
      instruction: "Chọn dụng cụ tiếp theo trong hàng.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["✏️", "📏", "✂️", "✏️", "📏"],
      options: ["✏️", "📏", "✂️"],
      correct_option: "✂️",
    },
    difficulty_params: { pattern_length: 3 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C3-SUB-FAST-0013",
      content_version: 1,
      template_code: "GT-006",
      title: "Nhận biết quy luật nhanh",
      instruction: "Hình nào vừa ẩn đi vậy em.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["count"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🍎" }, { emoji: "🍌" }],
      flash_duration_ms: 1500,
      options: ["Quả táo", "Quả dưa"],
      correct_answer: "Quả táo",
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C3-CLS-BOX-0014",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại dụng cụ thể thao",
      instruction: "Bỏ bóng thể thao vào rổ.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "sports_basket", label: "Rổ bóng", target_category: "sports" },
      ],
      drag_items: [
        { id: "b1", emoji: "🏀", category: "sports" },
        { id: "p1", emoji: "✏️", category: "stationery" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C3-LOG-CMP-0015",
      content_version: 1,
      template_code: "GT-003",
      title: "Suy luận dung tích chứa",
      instruction: "Chọn vại chứa được nhiều nước hơn.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["compare"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🫙", capacity: "large" }],
      right_group: [{ emoji: "🥤", capacity: "small" }],
      target: "large",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C3-PAT-SEQ-0016",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy quy luật xen kẽ 4 yếu tố",
      instruction: "Chọn đối tượng tiếp theo đúng luật.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🔴", "🟡", "🔵", "🔴", "🟡"],
      options: ["🔴", "🟡", "🔵"],
      correct_option: "🔵",
    },
    difficulty_params: { pattern_length: 3 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C3-LOG-POS-0017",
      content_version: 1,
      template_code: "GT-005",
      title: "Vị trí nằm giữa hai đối tượng",
      instruction: "Chạm vào món quà nằm ở giữa.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["compare"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "g1", emoji: "🎈" },
          { id: "g2", emoji: "🎁", position: "middle" },
          { id: "g3", emoji: "🎈" },
        ],
      ],
      target_id: "g2",
    },
    difficulty_params: { grid_size: 3 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C3-SUB-FAST-0018",
      content_version: 1,
      template_code: "GT-006",
      title: "Phản xạ phân loại siêu nhanh",
      instruction: "Đó là trái cây hay động vật.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["count"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🐱" }],
      flash_duration_ms: 1000,
      options: ["Động vật", "Trái cây"],
      correct_answer: "Động vật",
    },
    difficulty_params: { flash_duration_ms: 1000 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C3-CLS-BOX-0019",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại nhạc cụ âm nhạc",
      instruction: "Kéo nhạc cụ vào sân khấu.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.CLS.01"],
      learning_objective_codes: ["LO-C3.CLS.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "stage", label: "Sân khấu", target_category: "music" },
      ],
      drag_items: [
        { id: "m1", emoji: "🎸", category: "music" },
        { id: "f1", emoji: "⚽", category: "sports" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C3-LOG-CMP-0020",
      content_version: 1,
      template_code: "GT-003",
      title: "So sánh chiều dài đoạn thẳng",
      instruction: "Chọn cây bút dài hơn.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log"],
      thinking_tags: ["compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "✏️", length: "long" }],
      right_group: [{ emoji: "✏️", length: "short" }],
      target: "long",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 21 (GT-009 - Clue Deduction)
  {
    header: {
      code: "GL-C3-CLU-DED-0021",
      content_version: 1,
      template_code: "GT-009",
      title: "Tìm số bí ẩn lớn hơn bốn",
      instruction: "Bé tìm số bí ẩn theo manh mối.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C3.LOG.01"],
      learning_objective_codes: ["LO-C3.LOG.01-01"],
      what_tags: ["rule"],
      thinking_tags: ["infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Số bí ẩn lớn hơn 4. Bé tìm xem là số nào?",
      candidates: [
        { candidate_id: "c1", value: 1 },
        { candidate_id: "c2", value: 2 },
        { candidate_id: "c3", value: 3 },
        { candidate_id: "c5", value: 5 },
      ],
      clues: [
        {
          clue_id: "k1",
          text: "Số này lớn hơn 4",
          predicate: { kind: "greater_than", value: 4 },
        },
      ],
      answer_candidate_id: "c5",
    },
    difficulty_params: {
      clue_count: 1,
      candidate_count: 4,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 22 (GT-009 - Clue Deduction)
  {
    header: {
      code: "GL-C3-CLU-DED-0022",
      content_version: 1,
      template_code: "GT-009",
      title: "Tìm số bé hơn năm và khác hai",
      instruction: "Bé đọc hai manh mối tìm số đúng.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C3.LOG.01"],
      learning_objective_codes: ["LO-C3.LOG.01-01"],
      what_tags: ["rule"],
      thinking_tags: ["infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Số bí ẩn bé hơn 5 và khác 2. Là số nào?",
      candidates: [
        { candidate_id: "c1", value: 1 },
        { candidate_id: "c2", value: 2 },
        { candidate_id: "c4", value: 4 },
        { candidate_id: "c5", value: 5 },
        { candidate_id: "c6", value: 6 },
      ],
      clues: [
        {
          clue_id: "k1",
          text: "Số này bé hơn 5",
          predicate: { kind: "less_than", value: 5 },
        },
        {
          clue_id: "k2",
          text: "Số này khác 2",
          predicate: { kind: "not_equal", value: 2 },
        },
        {
          clue_id: "k3",
          text: "Số này lớn hơn 3",
          predicate: { kind: "greater_than", value: 3 },
        },
      ],
      answer_candidate_id: "c4",
    },
    difficulty_params: {
      clue_count: 3,
      candidate_count: 5,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 23 (GT-009 - Clue Deduction)
  {
    header: {
      code: "GL-C3-CLU-DED-0023",
      content_version: 1,
      template_code: "GT-009",
      title: "Tìm số chẵn nằm giữa ba và bảy",
      instruction: "Bé tìm số chẵn theo các manh mối.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.LOG.01"],
      learning_objective_codes: ["LO-C3.LOG.01-01"],
      what_tags: ["rule"],
      thinking_tags: ["infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Số này lớn hơn 3, nhỏ hơn 7, và lớn hơn 5. Là số mấy?",
      candidates: [
        { candidate_id: "c2", value: 2 },
        { candidate_id: "c4", value: 4 },
        { candidate_id: "c6", value: 6 },
        { candidate_id: "c8", value: 8 },
      ],
      clues: [
        {
          clue_id: "cl-1",
          text: "Số này lớn hơn 3",
          predicate: { kind: "greater_than", value: 3 },
        },
        {
          clue_id: "cl-2",
          text: "Số này nhỏ hơn 7",
          predicate: { kind: "less_than", value: 7 },
        },
        {
          clue_id: "cl-3",
          text: "Số này lớn hơn 5",
          predicate: { kind: "greater_than", value: 5 },
        },
      ],
      answer_candidate_id: "c6",
    },
    difficulty_params: {
      clue_count: 3,
      candidate_count: 4,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 24 (GT-011 - Matrix Choice)
  {
    header: {
      code: "GL-C3-MAT-CHO-0024",
      content_version: 1,
      template_code: "GT-011",
      title: "Ma trận hai hàng hai cột trái cây",
      instruction: "Bé chọn hình cho ô còn trống.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["infer"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé chọn hình cho ô còn trống của bảng hai hàng.",
      matrix: {
        rows: 2,
        cols: 2,
        cells: [
          { row: 0, col: 0, asset: { kind: "emoji", ref: "🍎" } },
          { row: 0, col: 1, asset: { kind: "emoji", ref: "🍌" } },
          { row: 1, col: 0, asset: { kind: "emoji", ref: "🍌" } },
          { row: 1, col: 1, asset: null },
        ],
      },
      options: [
        {
          option_id: "o1",
          asset: { kind: "emoji", ref: "🍎" },
          is_correct: true,
        },
        {
          option_id: "o2",
          asset: { kind: "emoji", ref: "🍌" },
          is_correct: false,
        },
        {
          option_id: "o3",
          asset: { kind: "emoji", ref: "🍇" },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      grid_size: 2,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 25 (GT-011 - Matrix Choice)
  {
    header: {
      code: "GL-C3-MAT-CHO-0025",
      content_version: 1,
      template_code: "GT-011",
      title: "Ma trận ba nhân ba hình học",
      instruction: "Bé tìm hình còn thiếu trong bảng.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Ô trống thiếu hình nào để hàng và cột đủ ba hình?",
      matrix: {
        rows: 3,
        cols: 3,
        cells: [
          { row: 0, col: 0, asset: { kind: "emoji", ref: "🔺" } },
          { row: 0, col: 1, asset: { kind: "emoji", ref: "⚫" } },
          { row: 0, col: 2, asset: { kind: "emoji", ref: "⭐" } },
          { row: 1, col: 0, asset: { kind: "emoji", ref: "⚫" } },
          { row: 1, col: 1, asset: { kind: "emoji", ref: "⭐" } },
          { row: 1, col: 2, asset: { kind: "emoji", ref: "🔺" } },
          { row: 2, col: 0, asset: { kind: "emoji", ref: "⭐" } },
          { row: 2, col: 1, asset: { kind: "emoji", ref: "🔺" } },
          { row: 2, col: 2, asset: null },
        ],
      },
      options: [
        {
          option_id: "o1",
          asset: { kind: "emoji", ref: "⚫" },
          is_correct: true,
        },
        {
          option_id: "o2",
          asset: { kind: "emoji", ref: "⭐" },
          is_correct: false,
        },
        {
          option_id: "o3",
          asset: { kind: "emoji", ref: "🔺" },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      grid_size: 3,
      distractor_count: 2,
      hint_after_ms: 10_000,
      allow_retry: true,
    },
  },
  // Level 26 (GT-011 - Matrix Choice)
  {
    header: {
      code: "GL-C3-MAT-CHO-0026",
      content_version: 1,
      template_code: "GT-011",
      title: "Ma trận xoay theo quy luật",
      instruction: "Bé quan sát quy luật xoay điền hình.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tìm hình đúng quy luật điền vào ô trống nhé.",
      matrix: {
        rows: 2,
        cols: 2,
        cells: [
          { row: 0, col: 0, asset: { kind: "emoji", ref: "⬆️" } },
          { row: 0, col: 1, asset: { kind: "emoji", ref: "➡️" } },
          { row: 1, col: 0, asset: { kind: "emoji", ref: "⬅️" } },
          { row: 1, col: 1, asset: null },
        ],
      },
      options: [
        {
          option_id: "op-down",
          asset: { kind: "emoji", ref: "⬇️" },
          is_correct: true,
        },
        {
          option_id: "op-up",
          asset: { kind: "emoji", ref: "⬆️" },
          is_correct: false,
        },
        {
          option_id: "op-left",
          asset: { kind: "emoji", ref: "⬅️" },
          is_correct: false,
        },
      ],
    },
    difficulty_params: {
      grid_size: 2,
      distractor_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 27 (GT-015 - Sudoku Mini)
  {
    header: {
      code: "GL-C3-SUD-MIN-0027",
      content_version: 1,
      template_code: "GT-015",
      title: "Sudoku mini hai nhân hai động vật",
      instruction: "Bé xếp các bạn động vật vào ô.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C3.LOG.01"],
      learning_objective_codes: ["LO-C3.LOG.01-01"],
      what_tags: ["rule"],
      thinking_tags: ["infer"],
      theme_tag: "animal",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt:
        "Bé hãy xếp các bạn động vật sao cho mỗi hàng và cột không bị trùng nhé!",
      grid_size: 2,
      regions: "row_col",
      symbols: [
        { symbol_id: "cat", asset: { kind: "emoji", ref: "🐱" } },
        { symbol_id: "dog", asset: { kind: "emoji", ref: "🐶" } },
      ],
      cells: [
        { row: 0, col: 0, symbol_id: "cat" },
        { row: 0, col: 1, symbol_id: null },
        { row: 1, col: 0, symbol_id: null },
        { row: 1, col: 1, symbol_id: "cat" },
      ],
    },
    difficulty_params: {
      blank_count: 2,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 28 (GT-015 - Sudoku Mini)
  {
    header: {
      code: "GL-C3-SUD-MIN-0028",
      content_version: 1,
      template_code: "GT-015",
      title: "Sudoku mini ba nhân ba trái cây",
      instruction: "Bé xếp đủ trái cây vào hàng cột.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C3.LOG.01"],
      learning_objective_codes: ["LO-C3.LOG.01-01"],
      what_tags: ["rule"],
      thinking_tags: ["infer"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Mỗi hàng và mỗi cột cần có đủ Táo, Chuối, Nho nhé!",
      grid_size: 3,
      regions: "row_col",
      symbols: [
        { symbol_id: "apple", asset: { kind: "emoji", ref: "🍎" } },
        { symbol_id: "banana", asset: { kind: "emoji", ref: "🍌" } },
        { symbol_id: "grape", asset: { kind: "emoji", ref: "🍇" } },
      ],
      cells: [
        { row: 0, col: 0, symbol_id: "apple" },
        { row: 0, col: 1, symbol_id: "banana" },
        { row: 0, col: 2, symbol_id: null },
        { row: 1, col: 0, symbol_id: "banana" },
        { row: 1, col: 1, symbol_id: null },
        { row: 1, col: 2, symbol_id: "apple" },
        { row: 2, col: 0, symbol_id: null },
        { row: 2, col: 1, symbol_id: "apple" },
        { row: 2, col: 2, symbol_id: "banana" },
      ],
    },
    difficulty_params: {
      blank_count: 3,
      hint_after_ms: 8000,
      allow_retry: true,
    },
  },
  // Level 29 (GT-015 - Sudoku Mini)
  {
    header: {
      code: "GL-C3-SUD-MIN-0029",
      content_version: 1,
      template_code: "GT-015",
      title: "Sudoku bốn nhân bốn hình khối",
      instruction: "Điền hình khối vào bảng bốn ô vuông.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C3.LOG.01"],
      learning_objective_codes: ["LO-C3.LOG.01-01"],
      what_tags: ["rule"],
      thinking_tags: ["infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé xếp các khối hình vào bảng Sudoku 4x4 nhé!",
      grid_size: 4,
      regions: "blocks_2x2",
      symbols: [
        { symbol_id: "circle", asset: { kind: "emoji", ref: "🔴" } },
        { symbol_id: "square", asset: { kind: "emoji", ref: "🟦" } },
        { symbol_id: "triangle", asset: { kind: "emoji", ref: "🔺" } },
        { symbol_id: "star", asset: { kind: "emoji", ref: "⭐" } },
      ],
      cells: [
        { row: 0, col: 0, symbol_id: "circle" },
        { row: 0, col: 1, symbol_id: "square" },
        { row: 0, col: 2, symbol_id: "triangle" },
        { row: 0, col: 3, symbol_id: "star" },
        { row: 1, col: 0, symbol_id: "triangle" },
        { row: 1, col: 1, symbol_id: "star" },
        { row: 1, col: 2, symbol_id: "circle" },
        { row: 1, col: 3, symbol_id: "square" },
        { row: 2, col: 0, symbol_id: "square" },
        { row: 2, col: 1, symbol_id: "circle" },
        { row: 2, col: 2, symbol_id: "star" },
        { row: 2, col: 3, symbol_id: "triangle" },
        { row: 3, col: 0, symbol_id: null },
        { row: 3, col: 1, symbol_id: "triangle" },
        { row: 3, col: 2, symbol_id: "square" },
        { row: 3, col: 3, symbol_id: null },
      ],
    },
    difficulty_params: {
      blank_count: 2,
      hint_after_ms: 10_000,
      allow_retry: true,
    },
  },
  // Level 30 (GT-025 - Spot Difference for C3)
  {
    header: {
      code: "GL-C3-VIS-SPOT-0030",
      content_version: 1,
      template_code: "GT-025",
      title: "Tìm điểm khác nhau trong dãy quy luật",
      instruction: "Bé tìm điểm khác nhau giữa hai dãy hình.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["pat", "cmp"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé tìm 1 điểm khác biệt giữa hai hàng hình nhé.",
      target_count: 1,
      left_objects: [
        { id: "l-r1", asset: { kind: "emoji", ref: "🔴" }, x: 100, y: 200 },
        { id: "l-b1", asset: { kind: "emoji", ref: "🔵" }, x: 200, y: 200 },
        { id: "l-r2", asset: { kind: "emoji", ref: "🔴" }, x: 300, y: 200 },
      ],
      right_objects: [
        { id: "r-r1", asset: { kind: "emoji", ref: "🔴" }, x: 100, y: 200 },
        { id: "r-y1", asset: { kind: "emoji", ref: "🟡" }, x: 200, y: 200 },
        { id: "r-r2", asset: { kind: "emoji", ref: "🔴" }, x: 300, y: 200 },
      ],
      differences: [
        {
          id: "diff-1",
          left_id: "l-b1",
          right_id: "r-y1",
          description: "Bóng xanh và bóng vàng",
        },
      ],
    },
    difficulty_params: {
      hint_after_ms: 8000,
      allow_retry: true,
      show_counter: true,
    },
  },
];
