import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_PAT_02_IDENTITY: SkillIdentity = {
  code: "C1.PAT.02",
  strand_code: "C1.PAT",
  competency_code: "C1",
  name: "Quy luật ABB",
  age_min: 4,
  age_max: 4,
  difficulty: 2,
  thinking_processes: ["observe", "predict"],
  tier: "basic",
  prerequisites: ["C1.PAT.01"],
  learning_objectives: [
    {
      code: "LO-C1.PAT.02-01",
      behaviour: "Nhận biết và thực hành Quy luật ABB ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.PAT.02-02",
      behaviour: "Vận dụng Quy luật ABB trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.PAT.02-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Quy luật ABB",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_PAT_02_DATASET: SkillDataset = {
  skill_code: "C1.PAT.02",
  concept_label: "Quy luật ABB",
  surface: "game",
  items: [
    {
      id: "pat_circle_1",
      label: "hình tròn xanh một",
      glyph: "🔵",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🔵",
      },
      contrast_group: "b",
      category: {
        cycle: "B1",
      },
    },
    {
      id: "pat_circle_2",
      label: "hình tròn xanh hai",
      glyph: "🔵",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🔵",
      },
      contrast_group: "b",
      category: {
        cycle: "B2",
      },
    },
    {
      id: "pat_star_repeat",
      label: "ngôi sao vàng lặp lại",
      glyph: "⭐",
      value: 4,
      image: {
        kind: "emoji",
        ref: "⭐",
      },
      contrast_group: "a",
      category: {
        cycle: "A2",
      },
    },
    {
      id: "pat_star",
      label: "ngôi sao vàng",
      glyph: "⭐",
      value: 1,
      image: {
        kind: "emoji",
        ref: "⭐",
      },
      contrast_group: "a",
      category: {
        cycle: "A",
      },
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "pat_star",
      target_id: "pat_circle_1",
      metadata: {
        rule: "ABB",
        period: 3,
      },
    },
    {
      type: "sequence",
      source_id: "pat_circle_1",
      target_id: "pat_circle_2",
      metadata: {
        rule: "ABB",
        period: 3,
      },
    },
    {
      type: "sequence",
      source_id: "pat_circle_2",
      target_id: "pat_star_repeat",
      metadata: {
        rule: "ABB",
        period: 3,
      },
    },
  ],
  axes: {
    cycle: {
      values: ["A", "B1", "B2", "A2"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với quy luật ABB",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng quy luật ABB",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt quy luật ABB với phương án nhiễu",
      representation: "ten-frame",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi quy luật ABB",
      representation: "ten-frame",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục quy luật ABB và tự làm một mình",
      representation: "ten-frame",
    },
  ],
  phrasing: {
    prompt_template: "Hình tiếp theo theo đúng quy luật là gì hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Quy luật ABB nhé",
  },
  ordering: ["pat_star", "pat_circle_1", "pat_circle_2", "pat_star_repeat"],
};

export const C1_PAT_02_SEED: SkillSeed = {
  identity: C1_PAT_02_IDENTITY,
  dataset: C1_PAT_02_DATASET,
  levels: [
    {
      code: "GL-C1-PAT-BEAT-0006",
      template: "GT-034",
      band: "5-6",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0007",
      template: "GT-034",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0008",
      template: "GT-034",
      band: "5-6",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0009",
      template: "GT-034",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0010",
      template: "GT-034",
      band: "5-6",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C3-PXT-SLOT-0001",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D3-01",
    },
    {
      code: "GL-C3-PXT-SLOT-0002",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D3-01",
    },
    {
      code: "GL-C1-SND-PAT-0006",
      template: "GT-018",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0007",
      template: "GT-018",
      band: "5-6",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0008",
      template: "GT-018",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0009",
      template: "GT-018",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0010",
      template: "GT-018",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-PAT-TAP-0005",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0006",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0007",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0008",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0001",
      template: "GT-002",
      band: "4-5",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0002",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0003",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0004",
      template: "GT-002",
      band: "4-5",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0005",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0006",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0007",
      template: "GT-003",
      band: "3-4",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0008",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0001",
      template: "GT-004",
      band: "4-5",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0002",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0003",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0004",
      template: "GT-004",
      band: "4-5",
      difficulty: 1,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0005",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0006",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0007",
      template: "GT-005",
      band: "3-4",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0008",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
    },
  ],
};
