import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_PAT_01_IDENTITY: SkillIdentity = {
  code: "C1.PAT.01",
  strand_code: "C1.PAT",
  competency_code: "C1",
  name: "Quy luật AB",
  age_min: 3,
  age_max: 3,
  difficulty: 1,
  thinking_processes: ["observe", "predict"],
  tier: "basic",
  prerequisites: [],
  learning_objectives: [
    {
      code: "LO-C1.PAT.01-01",
      behaviour: "Nhận biết và thực hành Quy luật AB ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.PAT.01-02",
      behaviour: "Vận dụng Quy luật AB trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.PAT.01-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Quy luật AB",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_PAT_01_DATASET: SkillDataset = {
  skill_code: "C1.PAT.01",
  concept_label: "Quy luật AB",
  surface: "game",
  items: [
    {
      id: "pat_apple",
      label: "quả táo đỏ",
      glyph: "🍎",
      value: 1,
      audio_path: "/audio/voice/c1/pat/apple.mp3",
      image: {
        kind: "emoji",
        ref: "🍎",
      },
      contrast_group: "a",
    },
    {
      id: "pat_banana",
      label: "quả chuối vàng",
      glyph: "🍌",
      value: 2,
      audio_path: "/audio/voice/c1/pat/banana.mp3",
      image: {
        kind: "emoji",
        ref: "🍌",
      },
      contrast_group: "b",
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "pat_apple",
      target_id: "pat_banana",
      metadata: {
        rule: "AB",
        period: 2,
      },
    },
    {
      type: "sequence",
      source_id: "pat_banana",
      target_id: "pat_apple",
      metadata: {
        rule: "AB",
        period: 2,
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "discrete-object",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "discrete-object",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "discrete-object",
    },
  ],
  phrasing: {
    prompt_template: "Hình tiếp theo theo đúng quy luật là gì hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Quy luật AB nhé",
  },
  ordering: ["pat_banana", "pat_apple"],
};

export const C1_PAT_01_SEED: SkillSeed = {
  identity: C1_PAT_01_IDENTITY,
  dataset: C1_PAT_01_DATASET,
  levels: [
    {
      code: "GL-C1-PAT-SEQ-0121",
      template: "GT-011",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      montessori_ref: "WB15-D1",
    },
    {
      code: "GL-C1-PAT-SLOT-0135",
      template: "GT-008",
      band: "5-6",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      montessori_ref: "WB15-D2",
    },
    {
      code: "GL-C1-PAT-BEAT-0001",
      template: "GT-034",
      band: "5-6",
      difficulty: 1,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0002",
      template: "GT-034",
      band: "5-6",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0003",
      template: "GT-034",
      band: "5-6",
      difficulty: 2,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0004",
      template: "GT-034",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-PAT-BEAT-0005",
      template: "GT-034",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-06",
    },
    {
      code: "GL-C1-SND-PAT-0001",
      template: "GT-018",
      band: "4-5",
      difficulty: 1,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0002",
      template: "GT-018",
      band: "4-5",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0003",
      template: "GT-018",
      band: "4-5",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0004",
      template: "GT-018",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-SND-PAT-0005",
      template: "GT-018",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-04",
    },
    {
      code: "GL-C1-PAT-TAP-0001",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0002",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0003",
      template: "GT-001",
      band: "3-4",
      difficulty: 1,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0004",
      template: "GT-001",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0001",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0002",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0003",
      template: "GT-003",
      band: "3-4",
      difficulty: 1,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0004",
      template: "GT-003",
      band: "3-4",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0001",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0002",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0003",
      template: "GT-005",
      band: "3-4",
      difficulty: 1,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0004",
      template: "GT-005",
      band: "3-4",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SLOT-0001",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SLOT-0002",
      template: "GT-008",
      band: "3-4",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SLOT-0003",
      template: "GT-008",
      band: "3-4",
      difficulty: 1,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-MEMO-0001",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-MEMO-0002",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-MEMO-0003",
      template: "GT-012",
      band: "3-4",
      difficulty: 1,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-MEMO-0004",
      template: "GT-012",
      band: "3-4",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
