import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_PAT_05_IDENTITY: SkillIdentity = {
  code: "C1.PAT.05",
  strand_code: "C1.PAT",
  competency_code: "C1",
  name: "Quy luật AABB",
  age_min: 5,
  age_max: 5,
  difficulty: 3,
  thinking_processes: ["observe", "predict"],
  tier: "core",
  prerequisites: ["C1.PAT.02", "C1.PAT.03"],
  learning_objectives: [
    {
      code: "LO-C1.PAT.05-01",
      behaviour: "Nhận biết và thực hành Quy luật AABB ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.PAT.05-02",
      behaviour: "Vận dụng Quy luật AABB trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.PAT.05-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Quy luật AABB",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_PAT_05_DATASET: SkillDataset = {
  skill_code: "C1.PAT.05",
  concept_label: "Quy luật AABB",
  surface: "game",
  items: [
    {
      id: "pat_car_2",
      label: "xe đỏ hai",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🚗",
      },
      contrast_group: "a",
    },
    {
      id: "pat_bus_1",
      label: "xe buýt vàng một",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🚌",
      },
      contrast_group: "b",
    },
    {
      id: "pat_bus_2",
      label: "xe buýt vàng hai",
      value: 4,
      image: {
        kind: "emoji",
        ref: "b",
      },
      contrast_group: "b",
    },
    {
      id: "pat_car_1",
      label: "xe đỏ một",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🚗",
      },
      contrast_group: "a",
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "pat_car_1",
      target_id: "pat_car_2",
      metadata: {
        rule: "AABB",
        period: 4,
      },
    },
    {
      type: "sequence",
      source_id: "pat_car_2",
      target_id: "pat_bus_1",
      metadata: {
        rule: "AABB",
        period: 4,
      },
    },
    {
      type: "sequence",
      source_id: "pat_bus_1",
      target_id: "pat_bus_2",
      metadata: {
        rule: "AABB",
        period: 4,
      },
    },
    {
      type: "sequence",
      source_id: "pat_bus_2",
      target_id: "pat_car_1",
      metadata: {
        rule: "AABB",
        period: 4,
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với quy luật AABB",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng quy luật AABB",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt quy luật AABB với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi quy luật AABB",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục quy luật AABB và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Hình tiếp theo theo đúng quy luật là gì hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Quy luật AABB nhé",
  },
  ordering: ["pat_car_1", "pat_car_2", "pat_bus_1", "pat_bus_2"],
};

export const C1_PAT_05_SEED: SkillSeed = {
  identity: C1_PAT_05_IDENTITY,
  dataset: C1_PAT_05_DATASET,
  levels: [
    {
      code: "GL-C1-PAT-WEAVE-0001",
      template: "GT-033",
      band: "5-6",
      difficulty: 1,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D3-07",
    },
    {
      code: "GL-C1-PAT-WEAVE-0002",
      template: "GT-033",
      band: "5-6",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-07",
    },
    {
      code: "GL-C1-PAT-WEAVE-0003",
      template: "GT-033",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D3-07",
    },
    {
      code: "GL-C1-PAT-WEAVE-0004",
      template: "GT-033",
      band: "5-6",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D3-07",
    },
    {
      code: "GL-C1-PAT-WEAVE-0005",
      template: "GT-033",
      band: "5-6",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D3-07",
    },
    {
      code: "GL-C1-ALG-CMD-0001",
      template: "GT-035",
      band: "5-6",
      difficulty: 1,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0002",
      template: "GT-035",
      band: "5-6",
      difficulty: 1,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0003",
      template: "GT-035",
      band: "5-6",
      difficulty: 2,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0004",
      template: "GT-035",
      band: "5-6",
      difficulty: 2,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0005",
      template: "GT-035",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-PAT-FCR-0001",
      template: "GT-036",
      band: "5-6",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0002",
      template: "GT-036",
      band: "5-6",
      difficulty: 1,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0003",
      template: "GT-036",
      band: "5-6",
      difficulty: 2,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0004",
      template: "GT-036",
      band: "5-6",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0005",
      template: "GT-036",
      band: "5-6",
      difficulty: 2,
      theme: "school",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C3-PXT-SLOT-0005",
      template: "GT-008",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-01",
    },
    {
      code: "GL-C3-PXT-SLOT-0006",
      template: "GT-008",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D3-01",
    },
    {
      code: "GL-C1-PAT-TAP-0017",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0018",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0019",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TAP-0020",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0013",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0014",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0015",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCNT-0016",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0017",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0018",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0019",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-TCMP-0020",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0013",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0014",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0015",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0016",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0017",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0018",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0019",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PATT-0020",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
