import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_PAT_08_IDENTITY: SkillIdentity = {
  code: "C1.PAT.08",
  strand_code: "C1.PAT",
  competency_code: "C1",
  name: "Pattern số",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["infer"],
  tier: "advanced",
  prerequisites: ["C1.NREC.09", "C1.PAT.01"],
  learning_objectives: [
    {
      code: "LO-C1.PAT.08-01",
      behaviour: "Nhận biết và thực hành Pattern số ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.PAT.08-02",
      behaviour: "Vận dụng Pattern số trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.PAT.08-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Pattern số",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_PAT_08_DATASET: SkillDataset = {
  skill_code: "C1.PAT.08",
  concept_label: "Pattern số",
  surface: "game",
  items: [
    {
      id: "pat_n2",
      label: "số hai",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
      contrast_group: "num",
    },
    {
      id: "pat_n4",
      label: "số bốn",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
      contrast_group: "num",
    },
    {
      id: "pat_n6",
      label: "số sáu",
      glyph: "6",
      value: 6,
      audio_path: "/audio/voice/common/numbers/6.mp3",
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
      contrast_group: "num",
    },
    {
      id: "pat_n8",
      label: "số tám",
      glyph: "8",
      value: 8,
      audio_path: "/audio/voice/common/numbers/8.mp3",
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
      contrast_group: "num",
    },
  ],
  relations: [
    {
      type: "subset",
      source_id: "pat_n2",
      target_id: "pat_n4",
      metadata: {
        rule: "plus_two",
      },
    },
    {
      type: "subset",
      source_id: "pat_n4",
      target_id: "pat_n6",
      metadata: {
        rule: "plus_two",
      },
    },
    {
      type: "subset",
      source_id: "pat_n6",
      target_id: "pat_n8",
      metadata: {
        rule: "plus_two",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với pattern số",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng pattern số",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt pattern số với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi pattern số",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục pattern số và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Số tiếp theo theo đúng quy luật là số mấy hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Pattern số nhé",
  },
};

export const C1_PAT_08_SEED: SkillSeed = {
  identity: C1_PAT_08_IDENTITY,
  dataset: C1_PAT_08_DATASET,
  levels: [
    {
      code: "GL-C1-PAT-FCR-0006",
      template: "GT-036",
      band: "5-6",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0007",
      template: "GT-036",
      band: "5-6",
      difficulty: 3,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0008",
      template: "GT-036",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0009",
      template: "GT-036",
      band: "5-6",
      difficulty: 4,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C1-PAT-FCR-0010",
      template: "GT-036",
      band: "5-6",
      difficulty: 4,
      theme: "art",
      rounds: 3,
      legacy_v1_ref: "D3-05",
    },
    {
      code: "GL-C3-GAP-SLOT-0005",
      template: "GT-008",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D3-02",
    },
    {
      code: "GL-C3-GAP-SLOT-0006",
      template: "GT-008",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D3-02",
    },
    {
      code: "GL-C1-PAT-PAIR-0025",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0026",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0027",
      template: "GT-004",
      band: "4-5",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0028",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0009",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0010",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0011",
      template: "GT-006",
      band: "5-6",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0012",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0009",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0010",
      template: "GT-007",
      band: "4-5",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0011",
      template: "GT-007",
      band: "4-5",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0012",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0009",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0010",
      template: "GT-009",
      band: "4-5",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0011",
      template: "GT-009",
      band: "4-5",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0012",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0009",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0010",
      template: "GT-010",
      band: "4-5",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0011",
      template: "GT-010",
      band: "4-5",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0012",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
  ],
};
