import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_PAT_07_IDENTITY: SkillIdentity = {
  code: "C1.PAT.07",
  strand_code: "C1.PAT",
  competency_code: "C1",
  name: "Pattern giảm dần",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["infer"],
  tier: "advanced",
  prerequisites: ["C1.PAT.06"],
  learning_objectives: [
    {
      code: "LO-C1.PAT.07-01",
      behaviour: "Nhận biết và thực hành Pattern giảm dần ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.PAT.07-02",
      behaviour: "Vận dụng Pattern giảm dần trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.PAT.07-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Pattern giảm dần",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_PAT_07_DATASET: SkillDataset = {
  skill_code: "C1.PAT.07",
  concept_label: "Pattern giảm dần",
  surface: "game",
  items: [
    {
      id: "spoon",
      label: "cái thìa",
      image: {
        kind: "emoji",
        ref: "🥄",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "cup",
      label: "cái cốc",
      image: {
        kind: "emoji",
        ref: "🥤",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "bed",
      label: "cái giường",
      image: {
        kind: "emoji",
        ref: "🛏️",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "chair",
      label: "cái ghế",
      image: {
        kind: "emoji",
        ref: "🪑",
      },
      category: {
        type: "đồ dùng",
      },
    },
    {
      id: "apple",
      label: "quả táo",
      image: {
        kind: "emoji",
        ref: "🍎",
      },
      category: {
        type: "hoa quả",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với Pattern giảm dần",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng Pattern giảm dần",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy chọn đúng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Pattern giảm dần nhé",
    success_message: "Hoan hô, bé đã chọn đúng rồi!",
    hint_message: "Bé hãy nhìn kỹ hình {label} nhé!",
  },
  ordering: ["spoon", "cup", "bed", "chair", "apple"],
};

export const C1_PAT_07_SEED: SkillSeed = {
  identity: C1_PAT_07_IDENTITY,
  dataset: C1_PAT_07_DATASET,
  levels: [
    {
      code: "GL-C1-ALG-CMD-0006",
      template: "GT-035",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0007",
      template: "GT-035",
      band: "5-6",
      difficulty: 4,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0008",
      template: "GT-035",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0009",
      template: "GT-035",
      band: "5-6",
      difficulty: 5,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0010",
      template: "GT-035",
      band: "5-6",
      difficulty: 5,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-HGT-TAP-0009",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-02",
    },
    {
      code: "GL-C1-HGT-TAP-0010",
      template: "GT-001",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-02",
    },
    {
      code: "GL-C3-GAP-SLOT-0003",
      template: "GT-008",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D3-02",
    },
    {
      code: "GL-C3-GAP-SLOT-0004",
      template: "GT-008",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D3-02",
    },
    {
      code: "GL-C1-PAT-PAIR-0021",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0022",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0023",
      template: "GT-004",
      band: "4-5",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0024",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0005",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0006",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0007",
      template: "GT-006",
      band: "5-6",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0008",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0005",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0006",
      template: "GT-007",
      band: "4-5",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0007",
      template: "GT-007",
      band: "4-5",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0008",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0005",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0006",
      template: "GT-009",
      band: "4-5",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0007",
      template: "GT-009",
      band: "4-5",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0008",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0005",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0006",
      template: "GT-010",
      band: "4-5",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0007",
      template: "GT-010",
      band: "4-5",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0008",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
  ],
};
