import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_PAT_07_IDENTITY: SkillIdentity = {
  code: "C1.PAT.07",
  strand_code: "C1.PAT",
  competency_code: "C1",
  name: "Pattern giảm dần",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["infer"],
  tier: "advanced",
  prerequisites: ["C1.PAT.06"],
  learning_objectives: [
    {
      code: "LO-C1.PAT.07-01",
      behaviour: "Nhận biết và thực hành Pattern giảm dần ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.PAT.07-02",
      behaviour: "Vận dụng Pattern giảm dần trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.PAT.07-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Pattern giảm dần",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_PAT_07_DATASET: SkillDataset = {
  skill_code: "C1.PAT.07",
  concept_label: "Pattern giảm dần",
  surface: "game",
  items: [
    {
      id: "dec_4",
      label: "bốn khối vuông",
      glyph: "🟪",
      value: 4,
      image: {
        kind: "emoji",
        ref: "🟪",
      },
      contrast_group: "step_1",
    },
    {
      id: "dec_3",
      label: "ba khối vuông",
      glyph: "🟪",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🟪",
      },
      contrast_group: "step_2",
    },
    {
      id: "dec_2",
      label: "hai khối vuông",
      glyph: "🟪",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🟪",
      },
      contrast_group: "step_3",
    },
    {
      id: "dec_1",
      label: "một khối vuông",
      glyph: "🟪",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🟪",
      },
      contrast_group: "step_4",
    },
  ],
  relations: [
    {
      type: "subset",
      source_id: "dec_3",
      target_id: "dec_4",
      metadata: {
        rule: "minus_one",
      },
    },
    {
      type: "subset",
      source_id: "dec_2",
      target_id: "dec_3",
      metadata: {
        rule: "minus_one",
      },
    },
    {
      type: "subset",
      source_id: "dec_1",
      target_id: "dec_2",
      metadata: {
        rule: "minus_one",
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với pattern giảm dần",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng pattern giảm dần",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt pattern giảm dần với phương án nhiễu",
      representation: "ten-frame",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi pattern giảm dần",
      representation: "ten-frame",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục pattern giảm dần và tự làm một mình",
      representation: "numeral",
    },
  ],
  phrasing: {
    prompt_template: "Số tiếp theo theo đúng quy luật là số mấy hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Pattern giảm dần nhé",
  },
};

export const C1_PAT_07_SEED: SkillSeed = {
  identity: C1_PAT_07_IDENTITY,
  dataset: C1_PAT_07_DATASET,
  levels: [
    {
      code: "GL-C1-ALG-CMD-0006",
      template: "GT-035",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0007",
      template: "GT-035",
      band: "5-6",
      difficulty: 4,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0008",
      template: "GT-035",
      band: "5-6",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0009",
      template: "GT-035",
      band: "5-6",
      difficulty: 5,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-ALG-CMD-0010",
      template: "GT-035",
      band: "5-6",
      difficulty: 5,
      theme: "space",
      rounds: 3,
      legacy_v1_ref: "D6-05",
    },
    {
      code: "GL-C1-HGT-TAP-0009",
      template: "GT-001",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
      legacy_v1_ref: "D5-02",
    },
    {
      code: "GL-C1-HGT-TAP-0010",
      template: "GT-001",
      band: "5-6",
      difficulty: 1,
      theme: "festival",
      rounds: 3,
      legacy_v1_ref: "D5-02",
    },
    {
      code: "GL-C3-GAP-SLOT-0003",
      template: "GT-008",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D3-02",
    },
    {
      code: "GL-C3-GAP-SLOT-0004",
      template: "GT-008",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D3-02",
    },
    {
      code: "GL-C1-PAT-PAIR-0021",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0022",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0023",
      template: "GT-004",
      band: "4-5",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PAIR-0024",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0005",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0006",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0007",
      template: "GT-006",
      band: "5-6",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SORT-0008",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0005",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0006",
      template: "GT-007",
      band: "4-5",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0007",
      template: "GT-007",
      band: "4-5",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SHAD-0008",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0005",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0006",
      template: "GT-009",
      band: "4-5",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0007",
      template: "GT-009",
      band: "4-5",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-SIZE-0008",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0005",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0006",
      template: "GT-010",
      band: "4-5",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0007",
      template: "GT-010",
      band: "4-5",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PAT-PUZZ-0008",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
  ],
};
