#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {
  type AgeBand,
  ALL_TEMPLATES,
  createRng,
  deriveStream,
  getLevelGenerator,
} from "@mindkid/game-engine";
import { getThemeVocabulary } from "../vocab/themes.js";

export interface GenOptions {
  engine: string;
  count: number;
  seed: number;
  theme: string;
  band?: AgeBand;
  out?: string;
  silent?: boolean;
}

export interface GenResult {
  engine: string;
  countRequested: number;
  candidatesGenerated: number;
  contractRejectedCount: number;
  duplicatesCount: number;
  writtenCount: number;
  outputPath?: string;
  items: unknown[];
}

function resolveTargetBand(
  engine: string,
  band: AgeBand | undefined,
  allowedBands: AgeBand[]
): AgeBand {
  if (band && allowedBands.includes(band)) {
    return band;
  }
  const first = allowedBands[0];
  if (!first) {
    throw new Error(`Engine ${engine} không có age_band hợp lệ.`);
  }
  return first;
}

function getAgeRange(band: AgeBand): { min: number; max: number } {
  if (band === "3-4") {
    return { min: 3, max: 4 };
  }
  if (band === "4-5") {
    return { min: 4, max: 5 };
  }
  return { min: 5, max: 6 };
}

function writeGeneratedFile(
  engine: string,
  seed: number,
  theme: string,
  targetBand: AgeBand,
  candidates: unknown[],
  out?: string
): string {
  const defaultOutDir = path.resolve(import.meta.dirname, "../generated");
  const sanitizedEngine = engine.toLowerCase().replace(/[^a-z0-9]/g, "");
  const filePath =
    out || path.join(defaultOutDir, `gen-${sanitizedEngine}-${seed}.ts`);

  fs.mkdirSync(path.dirname(filePath), { recursive: true });

  const fileContent = `/**
 * @generated by gen:levels
 * Engine: ${engine}
 * Seed: ${seed}
 * Theme: ${theme}
 * Band: ${targetBand}
 * Total generated: ${candidates.length}
 */
import type { ContentSeed } from "#src/seed-content/types";

export const GEN_${sanitizedEngine.toUpperCase()}_${seed}: ContentSeed<unknown, unknown>[] = ${JSON.stringify(
    candidates,
    null,
    2
  )};
`;
  fs.writeFileSync(filePath, fileContent, "utf-8");
  return filePath;
}

export function generateLevelsCore(options: GenOptions): GenResult {
  const { engine, count, seed, theme, band, out } = options;

  const template = ALL_TEMPLATES[engine];
  if (!template) {
    throw new Error(`Engine ${engine} không tồn tại trong ALL_TEMPLATES.`);
  }

  const generator = getLevelGenerator(engine);
  if (!generator) {
    throw new Error(`Engine ${engine} chưa có generator được đăng ký.`);
  }

  const allowedBands = generator.axes.age_band.filter(
    (b) => !template.banned_age_bands?.includes(b)
  );
  const targetBand = resolveTargetBand(engine, band, allowedBands);
  const vocab = getThemeVocabulary(theme);
  const ageRange = getAgeRange(targetBand);

  deriveStream(seed, "items");
  const candidates: unknown[] = [];
  let contractRejectedCount = 0;
  let duplicatesCount = 0;
  const seenHashes = new Set<string>();

  for (let i = 0; i < count; i++) {
    const itemRng = createRng(seed * 1000 + i);
    const generated = generator.generate({
      rng: itemRng,
      age_band: targetBand,
      theme,
      vocabulary: vocab,
    });

    const parseResult = template.content_contract.safeParse(
      generated.content_pack
    );
    if (!parseResult.success) {
      contractRejectedCount++;
      continue;
    }

    const contentHash = JSON.stringify(parseResult.data);
    if (seenHashes.has(contentHash)) {
      duplicatesCount++;
      continue;
    }
    seenHashes.add(contentHash);

    const levelSeed = {
      header: {
        code: `GL-GEN-${engine}-${seed}-${String(candidates.length + 1).padStart(2, "0")}`,
        content_version: 1,
        template_code: engine,
        title: "",
        instruction: "",
        age_min: ageRange.min,
        age_max: ageRange.max,
        difficulty: 1,
        access_tier: "free",
        skill_codes: [],
        learning_objective_codes: [],
        what_tags: [],
        thinking_tags: [],
        theme_tag: theme,
        origin: "generator",
        authored_in: "repo_seed",
      },
      content_pack: parseResult.data,
      difficulty_params: generated.difficulty_params,
    };

    candidates.push(levelSeed);
  }

  let finalOutputPath: string | undefined = out;
  if (out || candidates.length > 0) {
    finalOutputPath = writeGeneratedFile(
      engine,
      seed,
      theme,
      targetBand,
      candidates,
      out
    );
  }

  return {
    engine,
    countRequested: count,
    candidatesGenerated: count,
    contractRejectedCount,
    duplicatesCount,
    writtenCount: candidates.length,
    outputPath: finalOutputPath,
    items: candidates,
  };
}

export function parseArgs(args: string[]): GenOptions {
  let engine = "GT-001";
  let count = 9;
  let seed = 20_260_829;
  let theme = "school";
  let band: AgeBand | undefined;
  let out: string | undefined;

  for (const arg of args) {
    if (arg.startsWith("--engine=")) {
      engine = arg.slice("--engine=".length);
    } else if (arg.startsWith("--count=")) {
      count = Number.parseInt(arg.slice("--count=".length), 10);
    } else if (arg.startsWith("--seed=")) {
      seed = Number.parseInt(arg.slice("--seed=".length), 10);
    } else if (arg.startsWith("--theme=")) {
      theme = arg.slice("--theme=".length);
    } else if (arg.startsWith("--band=")) {
      band = arg.slice("--band=".length) as AgeBand;
    } else if (arg.startsWith("--out=")) {
      out = arg.slice("--out=".length);
    }
  }

  return { engine, count, seed, theme, band, out };
}

// CLI execution
if (import.meta.url === `file://${process.argv[1]}`) {
  const options = parseArgs(process.argv.slice(2));
  const res = generateLevelsCore(options);

  console.log(
    `gen:levels --engine=${res.engine} --count=${res.countRequested} --seed=${options.seed}`
  );
  console.log(`  ứng viên dựng            ${res.candidatesGenerated}`);
  console.log(`  trượt content_contract   ${res.contractRejectedCount}`);
  console.log(`  trùng ứng viên đã có     ${res.duplicatesCount}`);
  console.log(
    `  ghi ra                   ${res.writtenCount}   ${res.outputPath || ""}`
  );
  console.log(
    "  chưa đặt mã, chưa đặt tag, chưa có instruction — bước 6 thuộc về người"
  );
}
