import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_NCOMP_11_IDENTITY: SkillIdentity = {
  code: "C1.NCOMP.11",
  strand_code: "C1.NCOMP",
  competency_code: "C1",
  name: "Thành phần số",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["infer"],
  tier: "advanced",
  prerequisites: ["C1.NCOMP.09", "C1.NCOMP.10"],
  learning_objectives: [
    {
      code: "LO-C1.NCOMP.11-01",
      behaviour: "Nhận biết và thực hành Thành phần số ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.NCOMP.11-02",
      behaviour: "Vận dụng Thành phần số trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.NCOMP.11-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Thành phần số",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_NCOMP_11_DATASET: SkillDataset = {
  skill_code: "C1.NCOMP.11",
  concept_label: "Thành phần số",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "số không",
      glyph: "0",
      value: 0,
      audio_path: "/audio/voice/common/numbers/0.mp3",
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "số một",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "số hai",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "số ba",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n4",
      label: "số bốn",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n5",
      label: "số năm",
      glyph: "5",
      value: 5,
      audio_path: "/audio/voice/common/numbers/5.mp3",
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n6",
      label: "số sáu",
      glyph: "6",
      value: 6,
      audio_path: "/audio/voice/common/numbers/6.mp3",
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n7",
      label: "số bảy",
      glyph: "7",
      value: 7,
      audio_path: "/audio/voice/common/numbers/7.mp3",
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n8",
      label: "số tám",
      glyph: "8",
      value: 8,
      audio_path: "/audio/voice/common/numbers/8.mp3",
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n9",
      label: "số chín",
      glyph: "9",
      value: 9,
      audio_path: "/audio/voice/common/numbers/9.mp3",
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "n10",
      label: "số mười",
      glyph: "10",
      value: 10,
      audio_path: "/audio/voice/common/numbers/10.mp3",
      image: {
        kind: "emoji",
        ref: "🔟",
      },
    },
  ],
  relations: [
    {
      type: "subset",
      source_id: "n0",
      target_id: "n6",
      metadata: {
        bond_id: "bond_6_0_6",
        part_a: 0,
        part_b: 6,
        whole: 6,
      },
    },
    {
      type: "subset",
      source_id: "n1",
      target_id: "n6",
      metadata: {
        bond_id: "bond_6_1_5",
        part_a: 1,
        part_b: 5,
        whole: 6,
      },
    },
    {
      type: "subset",
      source_id: "n2",
      target_id: "n6",
      metadata: {
        bond_id: "bond_6_2_4",
        part_a: 2,
        part_b: 4,
        whole: 6,
      },
    },
    {
      type: "subset",
      source_id: "n3",
      target_id: "n6",
      metadata: {
        bond_id: "bond_6_3_3",
        part_a: 3,
        part_b: 3,
        whole: 6,
      },
    },
    {
      type: "subset",
      source_id: "n4",
      target_id: "n6",
      metadata: {
        bond_id: "bond_6_4_2",
        part_a: 4,
        part_b: 2,
        whole: 6,
      },
    },
    {
      type: "subset",
      source_id: "n5",
      target_id: "n6",
      metadata: {
        bond_id: "bond_6_5_1",
        part_a: 5,
        part_b: 1,
        whole: 6,
      },
    },
    {
      type: "subset",
      source_id: "n0",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_0_8",
        part_a: 0,
        part_b: 8,
        whole: 8,
      },
    },
    {
      type: "subset",
      source_id: "n1",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_1_7",
        part_a: 1,
        part_b: 7,
        whole: 8,
      },
    },
    {
      type: "subset",
      source_id: "n2",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_2_6",
        part_a: 2,
        part_b: 6,
        whole: 8,
      },
    },
    {
      type: "subset",
      source_id: "n3",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_3_5",
        part_a: 3,
        part_b: 5,
        whole: 8,
      },
    },
    {
      type: "subset",
      source_id: "n4",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_4_4",
        part_a: 4,
        part_b: 4,
        whole: 8,
      },
    },
    {
      type: "subset",
      source_id: "n5",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_5_3",
        part_a: 5,
        part_b: 3,
        whole: 8,
      },
    },
    {
      type: "subset",
      source_id: "n6",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_6_2",
        part_a: 6,
        part_b: 2,
        whole: 8,
      },
    },
    {
      type: "subset",
      source_id: "n7",
      target_id: "n8",
      metadata: {
        bond_id: "bond_8_7_1",
        part_a: 7,
        part_b: 1,
        whole: 8,
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản với thành phần số",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng thành phần số",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt thành phần số với phương án nhiễu",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi thành phần số",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục thành phần số và tự làm một mình",
    },
  ],
  phrasing: {
    prompt_template: "Số này gồm những số nào cộng lại hả bé?",
    narration_template: "Chúng mình cùng tìm hiểu về Thành phần số nhé",
  },
  ordering: ["n0", "n1", "n2", "n3", "n4", "n5", "n6", "n7", "n8", "n9", "n10"],
};

export const C1_NCOMP_11_SEED: SkillSeed = {
  identity: C1_NCOMP_11_IDENTITY,
  dataset: C1_NCOMP_11_DATASET,
  levels: [
    {
      code: "GL-C1-QNT-TAP-0003",
      template: "GT-001",
      band: "3-4",
      difficulty: 3,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D1-03",
    },
    {
      code: "GL-C1-QNT-TAP-0004",
      template: "GT-001",
      band: "4-5",
      difficulty: 1,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D1-03",
    },
    {
      code: "GL-C1-CNT-BSK-0006",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D1-01",
    },
    {
      code: "GL-C1-CNT-BSK-0007",
      template: "GT-003",
      band: "4-5",
      difficulty: 1,
      theme: "vehicle",
      rounds: 3,
      legacy_v1_ref: "D1-01",
    },
    {
      code: "GL-C1-BAL-EQN-0001",
      template: "GT-014",
      band: "5-6",
      difficulty: 1,
      theme: "farm",
      rounds: 3,
      legacy_v1_ref: "D6-08",
    },
    {
      code: "GL-C1-BAL-EQN-0002",
      template: "GT-014",
      band: "5-6",
      difficulty: 2,
      theme: "food",
      rounds: 3,
      legacy_v1_ref: "D6-08",
    },
    {
      code: "GL-C1-BAL-EQN-0003",
      template: "GT-014",
      band: "5-6",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
      legacy_v1_ref: "D6-08",
    },
    {
      code: "GL-C1-BAL-EQN-0004",
      template: "GT-014",
      band: "5-6",
      difficulty: 1,
      theme: "nature",
      rounds: 3,
      legacy_v1_ref: "D6-08",
    },
    {
      code: "GL-C1-BAL-EQN-0005",
      template: "GT-014",
      band: "5-6",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
      legacy_v1_ref: "D6-08",
    },
    {
      code: "GL-C1-NCOMP-PAIR-0026",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PAIR-0027",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PAIR-0028",
      template: "GT-004",
      band: "4-5",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PAIR-0029",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SORT-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SORT-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SORT-0003",
      template: "GT-006",
      band: "5-6",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SORT-0004",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SHAD-0001",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SHAD-0002",
      template: "GT-007",
      band: "4-5",
      difficulty: 4,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SHAD-0003",
      template: "GT-007",
      band: "4-5",
      difficulty: 5,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SHAD-0004",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SIZE-0001",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SIZE-0002",
      template: "GT-009",
      band: "4-5",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SIZE-0003",
      template: "GT-009",
      band: "4-5",
      difficulty: 5,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-SIZE-0004",
      template: "GT-009",
      band: "4-5",
      difficulty: 3,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PUZZ-0001",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PUZZ-0002",
      template: "GT-010",
      band: "4-5",
      difficulty: 4,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PUZZ-0003",
      template: "GT-010",
      band: "4-5",
      difficulty: 5,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PUZZ-0004",
      template: "GT-010",
      band: "4-5",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
  ],
};
