import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_NCOMP_08_IDENTITY: SkillIdentity = {
  code: "C1.NCOMP.08",
  strand_code: "C1.NCOMP",
  competency_code: "C1",
  name: "Tách số 9",
  age_min: 5,
  age_max: 5,
  difficulty: 4,
  thinking_processes: ["solve"],
  tier: "advanced",
  prerequisites: ["C1.NCOMP.07"],
  learning_objectives: [
    {
      code: "LO-C1.NCOMP.08-01",
      behaviour: "Nhận biết và thực hành Tách số 9 ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.NCOMP.08-02",
      behaviour: "Vận dụng Tách số 9 trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.NCOMP.08-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Tách số 9",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_NCOMP_08_DATASET: SkillDataset = {
  skill_code: "C1.NCOMP.08",
  concept_label: "Tách số 9",
  surface: "game",
  items: [
    {
      id: "n0",
      label: "số không",
      glyph: "0",
      value: 0,
      audio_path: "/audio/voice/common/numbers/0.mp3",
      image: {
        kind: "emoji",
        ref: "0️⃣",
      },
    },
    {
      id: "n1",
      label: "số một",
      glyph: "1",
      value: 1,
      audio_path: "/audio/voice/common/numbers/1.mp3",
      image: {
        kind: "emoji",
        ref: "1️⃣",
      },
    },
    {
      id: "n2",
      label: "số hai",
      glyph: "2",
      value: 2,
      audio_path: "/audio/voice/common/numbers/2.mp3",
      image: {
        kind: "emoji",
        ref: "2️⃣",
      },
    },
    {
      id: "n3",
      label: "số ba",
      glyph: "3",
      value: 3,
      audio_path: "/audio/voice/common/numbers/3.mp3",
      image: {
        kind: "emoji",
        ref: "3️⃣",
      },
    },
    {
      id: "n4",
      label: "số bốn",
      glyph: "4",
      value: 4,
      audio_path: "/audio/voice/common/numbers/4.mp3",
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "n5",
      label: "số năm",
      glyph: "5",
      value: 5,
      audio_path: "/audio/voice/common/numbers/5.mp3",
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "n6",
      label: "số sáu",
      glyph: "6",
      value: 6,
      audio_path: "/audio/voice/common/numbers/6.mp3",
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "n7",
      label: "số bảy",
      glyph: "7",
      value: 7,
      audio_path: "/audio/voice/common/numbers/7.mp3",
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "n8",
      label: "số tám",
      glyph: "8",
      value: 8,
      audio_path: "/audio/voice/common/numbers/8.mp3",
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "n9",
      label: "số chín",
      glyph: "9",
      value: 9,
      audio_path: "/audio/voice/common/numbers/9.mp3",
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
  ],
  relations: [
    {
      type: "subset",
      source_id: "n0",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_0_9",
        part_a: 0,
        part_b: 9,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n1",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_1_8",
        part_a: 1,
        part_b: 8,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n2",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_2_7",
        part_a: 2,
        part_b: 7,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n3",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_3_6",
        part_a: 3,
        part_b: 6,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n4",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_4_5",
        part_a: 4,
        part_b: 5,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n5",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_5_4",
        part_a: 5,
        part_b: 4,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n6",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_6_3",
        part_a: 6,
        part_b: 3,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n7",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_7_2",
        part_a: 7,
        part_b: 2,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n8",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_8_1",
        part_a: 8,
        part_b: 1,
        whole: 9,
      },
    },
    {
      type: "subset",
      source_id: "n9",
      target_id: "n9",
      metadata: {
        bond_id: "bond_9_9_0",
        part_a: 9,
        part_b: 0,
        whole: 9,
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "ten-frame",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "ten-frame",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "numeral",
    },
  ],
  phrasing: {
    prompt_template: "Thêm mấy nữa thì đủ {whole}?",
    narration_template: "Chúng mình cùng tìm hiểu về Tách số 9 nhé",
  },
  ordering: ["n0", "n1", "n2", "n3", "n4", "n5", "n6", "n7", "n8", "n9"],
};

export const C1_NCOMP_08_SEED: SkillSeed = {
  identity: C1_NCOMP_08_IDENTITY,
  dataset: C1_NCOMP_08_DATASET,
  levels: [
    {
      code: "GL-C1-NCOMP-PICT-0016",
      template: "GT-031",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PICT-0017",
      template: "GT-031",
      band: "5-6",
      difficulty: 4,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PICT-0018",
      template: "GT-031",
      band: "5-6",
      difficulty: 5,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PICT-0019",
      template: "GT-031",
      band: "5-6",
      difficulty: 3,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PICT-0020",
      template: "GT-031",
      band: "5-6",
      difficulty: 4,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TAP-0036",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TAP-0037",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TAP-0038",
      template: "GT-001",
      band: "4-5",
      difficulty: 5,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TAP-0039",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TAP-0040",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TCMP-0036",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TCMP-0037",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TCMP-0038",
      template: "GT-003",
      band: "4-5",
      difficulty: 5,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TCMP-0039",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-TCMP-0040",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PATT-0016",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PATT-0017",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PATT-0018",
      template: "GT-005",
      band: "4-5",
      difficulty: 5,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PATT-0019",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-NCOMP-PATT-0020",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "animal",
      rounds: 3,
    },
  ],
};
