import type { ActivitySeed } from "../types.js";

/**
 * Activities for competency C2 (69 activities).
 * Partitioned automatically by competency (Task #208 / G4).
 */
export const C2_ACTIVITIES: readonly ActivitySeed[] = [
  {
    kind: "activity",
    header: {
      code: "ACT-0011",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Tìm đồ vật hình tròn trong nhà",
      instruction: {
        preparation: "Chuẩn bị một chiếc rổ nhựa nhỏ.",
        steps: [
          {
            instruction: "Đưa cho bé một chiếc nắp hộp hình tròn làm mẫu.",
            say_to_child:
              '"Con nhìn chiếc nắp tròn này và đi tìm 3 món đồ hình tròn bỏ vào rổ nhé!"',
          },
          {
            instruction: "Bé mang đồ vật về và cùng kiểm tra cạnh bo tròn.",
            say_to_child:
              '"Con sờ xem miệng cốc này có cong tròn trơn láng không nào!"',
          },
        ],
        easier:
          "Chỉ cho bé 2 món đồ đặt sẵn trên bàn và hỏi món nào hình tròn.",
        harder: "Tìm thêm đồ vật hình vuông và xếp thành hai nhóm riêng biệt.",
      },
      materials: "Rổ nhựa, đồ vật gia đình (nắp hộp, đĩa nhựa, đồng hồ)",
      estimated_minutes: 10,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["circle_shape"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0012",
      content_version: 1,
      activity_kind: "movement",
      title: "Bước đi theo hình vẽ trên sàn",
      instruction: {
        preparation: "Dùng băng dính giấy dán hình tam giác lớn trên sàn nhà.",
        steps: [
          {
            instruction: "Bé đi thăng bằng trên các cạnh của hình tam giác.",
            say_to_child:
              '"Con hãy đi men theo 3 cạnh của hình tam giác mà không bước ra ngoài nhé!"',
          },
          {
            instruction: "Khi đến mỗi góc nhọn, bé dừng lại và đếm góc.",
            say_to_child:
              '"Đến góc nhọn rồi, đây là góc thứ nhất, góc thứ hai, góc thứ ba!"',
          },
        ],
        easier: "Đi theo đường thẳng hoặc đường tròn trước.",
        harder: "Vừa đi vừa đếm số bước chân trên mỗi cạnh.",
      },
      materials: "Băng dính giấy dán sàn dễ bóc",
      estimated_minutes: 12,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["triangle_shape"],
      thinking_tags: ["gross_motor_geometry"],
      theme_tag: "body",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0013",
      content_version: 1,
      activity_kind: "discussion",
      title: "Trò chuyện: Góc vuông của chiếc bàn",
      instruction: {
        preparation: "Ngồi cạnh chiếc bàn học hoặc bàn ăn hình chữ nhật.",
        steps: [
          {
            instruction: "Cùng bé quan sát mặt bàn.",
            say_to_child:
              '"Con sờ các cạnh của chiếc bàn và cho mẹ biết nó có mấy cạnh thẳng?"',
          },
          {
            instruction: "Hỏi câu hỏi mở về hình dạng.",
            say_to_child:
              '"Vì sao con thấy mặt bàn này giống hình chữ nhật thế nào?"',
          },
          {
            instruction: "Tìm đồ vật khác có góc tương tự.",
            say_to_child:
              '"Quyển sách trên bàn có giống hình chiếc bàn này không?"',
          },
        ],
        easier: "Chỉ vào góc bàn và đếm cùng bé từ 1 đến 4.",
        harder: "So sánh mặt bàn hình chữ nhật với chiếc đĩa hình tròn.",
      },
      materials: "Bàn học, sách truyện thiếu nhi",
      estimated_minutes: 8,
      access_tier: "login",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["rectangle_square"],
      thinking_tags: ["geometric_comparison"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0014",
      content_version: 1,
      activity_kind: "home_activity",
      title: "Giấu gấu bông: Trên, Dưới, Trong, Ngoài",
      instruction: {
        preparation: "Dùng một chú gấu bông nhỏ và một chiếc hộp các-tông.",
        steps: [
          {
            instruction: "Mẹ đặt gấu bông ở các vị trí không gian khác nhau.",
            say_to_child:
              '"Bạn gấu đang trốn ở đâu rồi con? Bạn đang ở trên hay dưới gầm bàn?"',
          },
          {
            instruction: "Bé chạy đi tìm và đặt gấu theo yêu cầu của mẹ.",
            say_to_child:
              '"Con hãy đặt bạn gấu vào bên trong chiếc hộp này nhé!"',
          },
        ],
        easier: "Chỉ phân biệt 2 vị trí đơn giản: Trên bàn và Dưới gầm bàn.",
        harder: "Mở rộng thêm vị trí: Phía trước, Phía sau, Bên cạnh.",
      },
      materials: "Gấu bông nhỏ, hộp các tông",
      estimated_minutes: 10,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spatial_relations"],
      thinking_tags: ["spatial_awareness"],
      theme_tag: "family",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0015",
      content_version: 1,
      activity_kind: "storytelling",
      title: "Kể chuyện: Chuyến phiêu lưu của Bạn Hình Vuông",
      instruction: {
        preparation:
          "Cắt sẵn 1 hình vuông và 1 hình tam giác từ bìa giấy cứng.",
        steps: [
          {
            instruction: "Mẹ kể chuyện Bạn Hình Vuông đi tìm mái nhà.",
            say_to_child:
              '"Bạn Hình Vuông muốn xây một ngôi nhà, bạn cần bạn Hình Tam Giác làm mái ngói đấy!"',
          },
          {
            instruction:
              "Bé ghép hình tam giác lên trên hình vuông để thành ngôi nhà.",
            say_to_child: '"Con giúp bạn ghép thành ngôi nhà thật đẹp nào!"',
          },
        ],
        easier: "Mẹ ghép mẫu trước và bé chỉ tay vào từng phần.",
        harder:
          "Bé ghép thêm hình chữ nhật làm cửa ra vào và hình tròn làm ông mặt trời.",
      },
      materials: "Bìa giấy màu cắt hình cơ bản",
      estimated_minutes: 12,
      access_tier: "login",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shape_composition"],
      thinking_tags: ["creative_geometry"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0016",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Xếp que tính thành các hình học",
      instruction: {
        preparation: "Chuẩn bị 12 que tính hoặc que kem sạch.",
        steps: [
          {
            instruction: "Bé dùng 3 que tính xếp thành hình tam giác.",
            say_to_child:
              '"Con dùng 3 que tính ghép lại thành hình tam giác có 3 góc nhé!"',
          },
          {
            instruction:
              "Bé dùng 4 que tính dài bằng nhau ghép thành hình vuông.",
            say_to_child:
              '"Con ghép 4 que này thành hình vuông có 4 cạnh bằng nhau nào!"',
          },
        ],
        easier: "Mẹ xếp sẵn 2 cạnh và bé xếp cạnh thứ 3 hoàn thiện.",
        harder: "Dùng 6 que tính xếp thành 2 hình tam giác dính liền.",
      },
      materials: "Que tính nhựa hoặc que kem sạch",
      estimated_minutes: 15,
      access_tier: "standard",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shape_construction"],
      thinking_tags: ["fine_motor"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0017",
      content_version: 1,
      activity_kind: "observation",
      title: "Đi tìm hình khối 3D trong bếp",
      instruction: {
        preparation: "Dẫn bé vào khu vực bếp quan sát đồ hộp và lon sữa.",
        steps: [
          {
            instruction:
              "Chỉ vào lon sữa đặc hình trụ và hộp bánh hình khối chữ nhật.",
            say_to_child:
              '"Con sờ lon sữa này xem nó lăn tròn được không nhé!"',
          },
          {
            instruction: "Hỏi bé về sự khác biệt giữa hộp bánh và lon sữa.",
            say_to_child: '"Hộp bánh này có lăn được như lon sữa không con?"',
          },
        ],
        easier: "Chỉ cho bé thấy hộp bánh đứng yên còn lon sữa lăn được.",
        harder: "Bé tự xếp chồng 3 lon sữa lên nhau xem có vững không.",
      },
      materials: "Lon sữa rỗng sạch, hộp bánh",
      estimated_minutes: 10,
      access_tier: "standard",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["3d_solids"],
      thinking_tags: ["spatial_solids"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0018",
      content_version: 1,
      activity_kind: "movement",
      title: "Lái xe vượt chướng ngại vật: Trái, Phải",
      instruction: {
        preparation: "Đặt 3 chiếc gối làm cọc tiêu trên sàn nhà.",
        steps: [
          {
            instruction: "Bé cầm chiếc đĩa nhựa làm vô lăng ô tô.",
            say_to_child:
              '"Bác tài xế ơi, rẽ sang bên tay phải để tránh chiếc gối nào!"',
          },
          {
            instruction: "Bé chuyển hướng sang trái, sang phải theo hiệu lệnh.",
            say_to_child: '"Bây giờ xe rẽ sang bên tay trái nhé, bíp bíp!"',
          },
        ],
        easier: "Mẹ cầm tay dắt bé đi chậm rãi qua từng chướng ngại vật.",
        harder: "Tăng tốc độ di chuyển và thêm hiệu lệnh lùi xe.",
      },
      materials: "Gối sofa êm, đĩa nhựa làm vô lăng",
      estimated_minutes: 10,
      access_tier: "standard",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["left_right_direction"],
      thinking_tags: ["directional_awareness"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0019",
      content_version: 1,
      activity_kind: "mini_project",
      title: "Xây lâu đài từ các khối hộp các-tông",
      instruction: {
        preparation: "Gom các vỏ hộp bánh, hộp thuốc sạch trong 2 ngày.",
        steps: [
          {
            instruction:
              "Buổi 1: Phân loại các vỏ hộp theo hình vuông và hình chữ nhật.",
            say_to_child:
              '"Chúng mình phân các hộp to làm móng nhà, hộp nhỏ làm tháp canh nhé!"',
          },
          {
            instruction:
              "Buổi 2: Xếp chồng các khối hộp thành toà lâu đài cao tầng.",
            say_to_child:
              '"Con xếp khối to ở dưới, khối nhỏ ở trên cho vững vàng nào!"',
          },
        ],
        easier: "Xếp tháp đơn giản gồm 3 chiếc hộp chồng lên nhau.",
        harder: "Tạo thêm cổng vòm cho lâu đài bằng bìa cứng uốn cong.",
      },
      materials: "Vỏ hộp các-tông sạch",
      estimated_minutes: 15,
      access_tier: "premium",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["architecture_play"],
      thinking_tags: ["structural_stability"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0020",
      content_version: 1,
      activity_kind: "assessment",
      title: "Đánh giá quan sát: Chỉ vị trí trước - sau",
      instruction: {
        preparation: "Đặt bạn gấu bông phía trước ghế, bạn thỏ phía sau ghế.",
        steps: [
          {
            instruction: "Hỏi bé vị trí của từng bạn thú bông.",
            say_to_child:
              '"Bạn nào đang ngồi ở phía trước chiếc ghế, con chỉ tay vào bạn đó nhé!"',
          },
          {
            instruction: "Quan sát phản xạ và câu trả lời của trẻ.",
            say_to_child: '"Còn bạn ngồi ở phía sau chiếc ghế là bạn nào?"',
          },
        ],
        easier: "Đặt đồ vật ngay trước mặt bé.",
        harder: "Đổi chỗ đồ vật và yêu cầu bé tự miêu tả lại vị trí.",
      },
      materials: "2 thú bông nhỏ, 1 chiếc ghế",
      estimated_minutes: 5,
      access_tier: "premium",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spatial_assessment"],
      thinking_tags: ["relative_position"],
      theme_tag: "family",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0109",
      content_version: 1,
      activity_kind: "movement",
      title: "Bước đi trong mê cung băng dính trên sàn",
      instruction: {
        preparation:
          "Dùng băng dính giấy dán đường mê cung đơn giản có 1 ngã rẽ trên sàn phòng khách.",
        steps: [
          {
            instruction:
              "Bé đứng ở vạch xuất phát và quan sát toàn bộ đường đi.",
            say_to_child:
              '"Con hãy đi dọc theo vạch băng dính đến kho báu gấu bông mà không giẫm ra ngoài nhé!"',
          },
          {
            instruction: "Bé tự điều hướng tại ngã rẽ để tránh đường cụt.",
            say_to_child:
              '"Đường này bị cụt rồi, con lùi lại ngã rẽ và chọn đường bên kia nhé!"',
          },
        ],
        easier: "Mê cung đường đơn uốn lượn không có ngã rẽ.",
        harder: "Mê cung có 2 ngã rẽ và các vật cản gối ôm trên đường đi.",
      },
      materials: "Cuộn băng dính giấy, gấu bông đích đến",
      estimated_minutes: 20,
      access_tier: "free",
      skill_codes: ["C2.MAZ.01"],
      learning_objective_codes: ["LO-C2.MAZ.01-01"],
      what_tags: ["maze", "wb09"],
      thinking_tags: ["plan", "spatial"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0119",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Truy tìm đồ vật có dạng khối 3D trong nhà",
      instruction: {
        preparation:
          "Gom các đồ vật: hộp bánh quy (khối lập phương/hộp chữ nhật), lon sữa đặc (khối trụ), quả bóng bàn (khối cầu), mũ sinh nhật (khối nón).",
        steps: [
          {
            instruction: "Bé sờ và lăn thử từng đồ vật trên sàn.",
            say_to_child:
              '"Con xem lon sữa và quả bóng có lăn được không? Hộp bánh có lăn được không?"',
          },
          {
            instruction:
              "Bé phân loại các đồ vật thành 2 nhóm: nhóm lăn được và nhóm chỉ trượt được.",
            say_to_child:
              '"Khối cầu lăn được mọi phía, khối trụ chỉ lăn được khi đặt nằm ngang!"',
          },
        ],
        easier:
          "Chỉ so sánh quả bóng tròn (khối cầu) và hộp bánh vuông (khối lập phương).",
        harder: "Đếm số mặt phẳng của khối lập phương hộp bánh.",
      },
      materials: "Hộp bánh, lon sữa, quả bóng, mũ sinh nhật",
      estimated_minutes: 20,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["3d_shapes", "wb19"],
      thinking_tags: ["spatial", "compare"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0207",
      content_version: 1,
      title: "Trò chơi số: Bạn gấu tìm hình",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SHP-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé giúp bạn gấu tìm hình tròn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "family",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0208",
      content_version: 1,
      title: "Trò chơi số: Gấu trốn vị trí",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-POS-LOC-0004",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm bạn gấu đang ở trên hay ở dưới ghế nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spatial_relations"],
      thinking_tags: ["spatial_reasoning"],
      theme_tag: "family",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0225",
      content_version: 1,
      title: "Trò chơi số: Chọn biển báo hình tròn",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SHP-CARD-0002",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn biển báo có dạng hình tròn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0226",
      content_version: 1,
      title: "Trò chơi số: Cất khối hình vào rổ",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SORT-SHP-0006",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp khối hình vào đúng ngăn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["sorting"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0227",
      content_version: 1,
      title: "Trò chơi số: Đặt gấu bông trên ghế",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-POS-LOC-0005",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé đặt chú gấu lên trên chiếc ghế nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["spatial_relations"],
      thinking_tags: ["spatial_reasoning"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0228",
      content_version: 1,
      title: "Trò chơi số: So sánh kích thước khối hình",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CMP-SIZ-0008",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm khối hình to hơn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["comparison"],
      thinking_tags: ["matching"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0229",
      content_version: 1,
      title: "Trò chơi số: Lái xe theo hướng mũi tên",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-DIR-NAV-0010",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé bấm mũi tên điều khiển xe rẽ phải nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["direction"],
      thinking_tags: ["directional_coordination"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0230",
      content_version: 1,
      title: "Trò chơi số: Xoay khối hình học",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ROT-TRANS-0021",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xoay khối hình để khớp vào ô trống nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["shift", "observe"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0231",
      content_version: 1,
      title: "Trò chơi số: Xoay bánh răng khớp răng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ROT-TRANS-0022",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xoay bánh răng để guồng máy hoạt động nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["shift", "observe"],
      theme_tag: "tool",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0232",
      content_version: 1,
      title: "Trò chơi số: Nhận diện hình đa giác",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SHP-CARD-0003",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm hình có 4 góc vuông nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0233",
      content_version: 1,
      title: "Trò chơi số: Vẽ cánh bướm đối xứng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-MIR-COMP-0024",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé hoàn thiện đôi cánh bướm xinh đẹp nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["match", "observe"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0234",
      content_version: 1,
      title: "Trò chơi số: Phân loại bướm và hoa",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SORT-SHP-0007",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp bướm và hoa vào đúng vườn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["sorting"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0235",
      content_version: 1,
      title: "Trò chơi số: Ghép thuyền buồm ra khơi",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SHP-0027",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé ghép các mảnh thành chiếc thuyền buồm nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["match", "observe"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0236",
      content_version: 1,
      title: "Trò chơi số: Tìm cánh buồm tam giác",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SHP-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn cánh buồm hình tam giác nào!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0237",
      content_version: 1,
      title: "Trò chơi số: Vẽ theo nét lượn sóng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-TRC-PTH-0030",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé rê tay theo đường nét đứt nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["plan", "observe"],
      theme_tag: "water",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0238",
      content_version: 1,
      title: "Trò chơi số: Đưa cá về đại dương",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-POS-LOC-0014",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé đặt chú cá bơi vào làn nước trong nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spatial_relations"],
      thinking_tags: ["spatial_reasoning"],
      theme_tag: "water",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0239",
      content_version: 1,
      title: "Trò chơi số: Đếm khối hộp xếp chồng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-BLK-STK-0033",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé đếm xem có bao nhiêu khối hộp nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["infer", "observe"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0240",
      content_version: 1,
      title: "Trò chơi số: Chọn khối lập phương",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SHP-CARD-0002",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chạm vào khối hình vuông nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0241",
      content_version: 1,
      title: "Trò chơi số: Vị trí trước sau của bạn thú",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-POS-LOC-0020",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm bạn nhỏ đứng ở phía trước nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spatial_relations"],
      thinking_tags: ["spatial_reasoning"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0242",
      content_version: 1,
      title: "Trò chơi số: Dãy xếp hàng con vật",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SEQ-PAT-0011",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp các bạn thú vào hàng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["order"],
      thinking_tags: ["sequencing"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0243",
      content_version: 1,
      title: "Trò chơi số: Chạm nhanh theo hướng mũi tên",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SUB-FAST-0013",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chạm nhanh mũi tên chỉ sang phải nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["subitizing"],
      thinking_tags: ["instant_recognition"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0244",
      content_version: 1,
      title: "Trò chơi số: Đối xứng trái phải",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-MIR-COMP-0025",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé hoàn thành nửa bên phải hình ngôi sao nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["match", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0245",
      content_version: 1,
      title: "Trò chơi số: Điều khiển tàu hỏa qua đường hầm",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-DIR-NAV-0016",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé dẫn đường cho đoàn tàu vào ga nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["direction"],
      thinking_tags: ["directional_coordination"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0246",
      content_version: 1,
      title: "Trò chơi số: Ghép các toa tàu",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SHP-0028",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé ghép các mảnh toa tàu lại với nhau nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["match", "observe"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0247",
      content_version: 1,
      title: "Trò chơi số: Nối đường bay máy bay",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-TRC-PTH-0031",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé vẽ đường bay cho chiếc máy bay lượn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["plan", "observe"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0248",
      content_version: 1,
      title: "Trò chơi số: Đếm các tầng tháp sân bay",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-BLK-STK-0034",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé đếm số tầng của tháp không lưu nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["infer", "observe"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0337",
      content_version: 1,
      title: "Trò chơi số: Khám phá hình học",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SHP-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn hình học để mở cửa mê cung nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.MAZ.01"],
      learning_objective_codes: ["LO-C2.MAZ.01-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0338",
      content_version: 1,
      title: "Trò chơi số: Xoay hướng trong mê cung",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ROT-TRANS-0021",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xoay mũi tên chỉ đúng hướng đi nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.MAZ.01"],
      learning_objective_codes: ["LO-C2.MAZ.01-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["shift", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0357",
      content_version: 1,
      title: "Trò chơi số: Nhận diện khối không gian",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-SHP-CARD-0002",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm khối lập phương nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["shapes_2d"],
      thinking_tags: ["shape_recognition"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0358",
      content_version: 1,
      title: "Trò chơi số: Lắp ghép khối không gian",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SHP-0027",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé ghép các khối thành lâu đài nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C2.GEO.01"],
      learning_objective_codes: ["LO-C2.GEO.01-01"],
      what_tags: ["geo", "spatial"],
      thinking_tags: ["match", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0507",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Xếp mâm ngũ quả ngày Tết: Phân loại hình khối trái cây",
      instruction: {
        preparation:
          "Chuẩn bị dụng cụ: Mâm nhựa, 5 loại quả thật hoặc mô hình.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Mâm nhựa, 5 loại quả thật hoặc mô hình",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["shp"],
      thinking_tags: ["sort"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0508",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SOLID-0001",
      title:
        "Thử thách số 1: Xếp mâm ngũ quả ngày Tết: Phân loại hình khối trái cây",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["shp"],
      thinking_tags: ["sort"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0509",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SOLID-0002",
      title:
        "Thử thách số 2: Xếp mâm ngũ quả ngày Tết: Phân loại hình khối trái cây",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["shp"],
      thinking_tags: ["sort"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0510",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Gói bánh chưng xanh: Hình vuông và lạt buộc song song",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Khuôn bánh chưng gỗ, lá dong, dây lạt.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Khuôn bánh chưng gỗ, lá dong, dây lạt",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shp"],
      thinking_tags: ["compare"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0511",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-GEO-MATCH-0003",
      title:
        "Thử thách số 1: Gói bánh chưng xanh: Hình vuông và lạt buộc song song",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shp"],
      thinking_tags: ["compare"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0512",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SOLID-0001",
      title:
        "Thử thách số 2: Gói bánh chưng xanh: Hình vuông và lạt buộc song song",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shp"],
      thinking_tags: ["compare"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0525",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Cô giáo dạy học: Sắp xếp bàn ghế lớp học ngăn nắp",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Bàn ghế học sinh mini, sách vở.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Bàn ghế học sinh mini, sách vở",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0526",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-POS-0002",
      title:
        "Thử thách số 1: Cô giáo dạy học: Sắp xếp bàn ghế lớp học ngăn nắp",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0527",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-POS-0001",
      title:
        "Thử thách số 2: Cô giáo dạy học: Sắp xếp bàn ghế lớp học ngăn nắp",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0528",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Chú công an giao thông: Điều khiển xe qua ngã tư",
      instruction: {
        preparation:
          "Chuẩn bị dụng cụ: Gậy chỉ huy giao thông, còi, mô hình xe.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Gậy chỉ huy giao thông, còi, mô hình xe",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0529",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-DIR-0002",
      title: "Thử thách số 1: Chú công an giao thông: Điều khiển xe qua ngã tư",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0530",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-DIR-0001",
      title: "Thử thách số 2: Chú công an giao thông: Điều khiển xe qua ngã tư",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0540",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Chú thợ xây khéo léo: Xếp gạch xây bức tường phẳng",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Khối xốp hình viên gạch, bay nhựa.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Khối xốp hình viên gạch, bay nhựa",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0541",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SOLID-0002",
      title:
        "Thử thách số 1: Chú thợ xây khéo léo: Xếp gạch xây bức tường phẳng",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0542",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SOLID-0001",
      title:
        "Thử thách số 2: Chú thợ xây khéo léo: Xếp gạch xây bức tường phẳng",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.CON.04"],
      learning_objective_codes: ["LO-C2.CON.04-01"],
      what_tags: ["shp"],
      thinking_tags: ["observe"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0549",
      content_version: 1,
      activity_kind: "manipulative",
      title:
        "Khám phá: Bản đồ Việt Nam hình chữ S: Khám phá 3 miền Bắc Trung Nam",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Bản đồ gỗ ghép hình Việt Nam.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Bản đồ gỗ ghép hình Việt Nam",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "homeland",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0550",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-POS-0002",
      title:
        "Thử thách số 1: Bản đồ Việt Nam hình chữ S: Khám phá 3 miền Bắc Trung Nam",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "homeland",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0551",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-POS-0001",
      title:
        "Thử thách số 2: Bản đồ Việt Nam hình chữ S: Khám phá 3 miền Bắc Trung Nam",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.03"],
      learning_objective_codes: ["LO-C2.ORI.03-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "homeland",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0573",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Gió thổi lá bay: Quan sát hướng gió thổi",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Chong chóng giấy, quạt tay mini.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Chong chóng giấy, quạt tay mini",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0574",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-DIR-0002",
      title: "Thử thách số 1: Gió thổi lá bay: Quan sát hướng gió thổi",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0575",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-ORI-DIR-0001",
      title: "Thử thách số 2: Gió thổi lá bay: Quan sát hướng gió thổi",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.ORI.04"],
      learning_objective_codes: ["LO-C2.ORI.04-01"],
      what_tags: ["spt"],
      thinking_tags: ["observe"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0609",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Phi hành gia tí hon: Vượt chướng ngại vật thiên thạch",
      instruction: {
        preparation:
          "Chuẩn bị dụng cụ: Sa bàn không gian vũ trụ, phi thuyền mini.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Sa bàn không gian vũ trụ, phi thuyền mini",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.MAZ.01"],
      learning_objective_codes: ["LO-C2.MAZ.01-01"],
      what_tags: ["spt"],
      thinking_tags: ["plan"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0610",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-MAZ-PATH-0002",
      title:
        "Thử thách số 1: Phi hành gia tí hon: Vượt chướng ngại vật thiên thạch",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.MAZ.01"],
      learning_objective_codes: ["LO-C2.MAZ.01-01"],
      what_tags: ["spt"],
      thinking_tags: ["plan"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0611",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-MAZ-PATH-0001",
      title:
        "Thử thách số 2: Phi hành gia tí hon: Vượt chướng ngại vật thiên thạch",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.MAZ.01"],
      learning_objective_codes: ["LO-C2.MAZ.01-01"],
      what_tags: ["spt"],
      thinking_tags: ["plan"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0612",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Chòm sao lấp lánh: Nối các điểm tạo hình con gấu",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Que dạ quang, bảng chấm sao.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Que dạ quang, bảng chấm sao",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shp"],
      thinking_tags: ["compare"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0613",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-GEO-MATCH-0003",
      title: "Thử thách số 1: Chòm sao lấp lánh: Nối các điểm tạo hình con gấu",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shp"],
      thinking_tags: ["compare"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0614",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C2-CON-SOLID-0001",
      title: "Thử thách số 2: Chòm sao lấp lánh: Nối các điểm tạo hình con gấu",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C2.GEO.02"],
      learning_objective_codes: ["LO-C2.GEO.02-01"],
      what_tags: ["shp"],
      thinking_tags: ["compare"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
];
