import type { ActivitySeed } from "../types.js";

/**
 * Activities for competency C3 (60 activities).
 * Partitioned automatically by competency (Task #208 / G4).
 */
export const C3_ACTIVITIES: readonly ActivitySeed[] = [
  {
    kind: "activity",
    header: {
      code: "ACT-0021",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Xếp chuỗi hạt màu AB (Đỏ - Xanh)",
      instruction: {
        preparation: "Chuẩn bị 6 khối lego đỏ và 6 khối lego xanh.",
        steps: [
          {
            instruction: "Mẹ xếp mẫu chuỗi: Đỏ - Xanh - Đỏ - Xanh.",
            say_to_child:
              '"Con nhìn xem: một viên đỏ, rồi đến một viên xanh, rồi lại đỏ, rồi lại xanh!"',
          },
          {
            instruction: "Hỏi bé khối màu tiếp theo cần xếp là màu gì.",
            say_to_child: '"Tiếp theo con sẽ xếp khối màu gì vào đây nào?"',
          },
        ],
        easier:
          "Chỉ làm chuỗi 3 khối: Đỏ - Xanh - Đỏ và để bé đặt khối Xanh cuối.",
        harder: "Mở rộng chuỗi quy luật ABC: Đỏ - Xanh - Vàng.",
      },
      materials: "Khối đồ chơi lego hoặc cúc áo to 2 màu",
      estimated_minutes: 10,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["ab_pattern"],
      thinking_tags: ["pattern_recognition"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0022",
      content_version: 1,
      activity_kind: "movement",
      title: "Nhịp điệu cơ thể: Vỗ tay - Giậm chân",
      instruction: {
        preparation: "Đứng cùng bé trong không gian phòng khách thoáng đãng.",
        steps: [
          {
            instruction:
              "Làm mẫu động tác theo chuỗi: Vỗ tay 1 cái -> Giậm chân 1 cái.",
            say_to_child:
              '"Con làm theo nhịp cùng mẹ nhé: Vỗ tay - Giậm chân - Vỗ tay - Giậm chân!"',
          },
          {
            instruction: "Bé thực hiện theo nhịp điệu và tự hô to hành động.",
            say_to_child:
              '"Con vừa làm vừa hô to xem động tác tiếp theo là gì nào!"',
          },
        ],
        easier: "Làm chậm từng nhịp và dừng lại chờ bé làm theo.",
        harder: "Tăng chuỗi AAB: Vỗ tay - Vỗ tay - Giậm chân.",
      },
      materials: "Khoảng trống an toàn trong nhà",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["body_rhythm"],
      thinking_tags: ["kinesthetic_pattern"],
      theme_tag: "body",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0023",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Phân loại tất vớ theo đôi",
      instruction: {
        preparation: "Lấy 5 đôi tất sạch của gia đình trộn lẫn trong giỏ.",
        steps: [
          {
            instruction: "Đổ tất ra thảm và yêu cầu bé tìm các đôi giống nhau.",
            say_to_child:
              '"Con tìm 2 chiếc tất có cùng màu sắc và họa tiết để ghép thành một đôi nhé!"',
          },
          {
            instruction: "Bé cuộn tròn từng đôi tất sau khi ghép đúng.",
            say_to_child: '"Con xem đôi tất này có màu gì giống nhau nào?"',
          },
        ],
        easier:
          "Chỉ dùng 3 đôi tất có màu sắc hoàn toàn khác biệt (đỏ, xanh, vàng).",
        harder: "Dùng 6 đôi tất và phân loại thêm theo tất của bố, mẹ và bé.",
      },
      materials: "Các đôi tất gia đình sạch",
      estimated_minutes: 10,
      access_tier: "login",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["sorting_matching"],
      thinking_tags: ["attribute_matching"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0024",
      content_version: 1,
      activity_kind: "discussion",
      title: "Trò chuyện: Cái nào không cùng nhóm?",
      instruction: {
        preparation: "Đặt lên bàn: 3 quả táo và 1 chiếc thìa ăn cơm.",
        steps: [
          {
            instruction: "Bé quan sát 4 món đồ trên bàn.",
            say_to_child:
              '"Trong 4 món đồ này, món nào khác biệt và không cùng nhóm với các món còn lại?"',
          },
          {
            instruction: "Khuyến khích bé giải thích lý do.",
            say_to_child:
              '"Vì sao chiếc thìa lại không cùng nhóm với những quả táo thế nào?"',
          },
        ],
        easier: "Dùng 3 con thú bông và 1 chiếc ô tô đồ chơi.",
        harder: "Dùng nhóm tinh tế hơn: 3 loại quả ngọt và 1 củ hành tây.",
      },
      materials: "3 quả táo, 1 chiếc thìa",
      estimated_minutes: 8,
      access_tier: "login",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["odd_one_out"],
      thinking_tags: ["logical_classification"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0025",
      content_version: 1,
      activity_kind: "storytelling",
      title: "Kể chuyện: Đoàn tàu sắc màu của bác Gấu",
      instruction: {
        preparation: "Xếp 6 chiếc hộp giấy nhỏ nối đuôi nhau làm toa tàu.",
        steps: [
          {
            instruction:
              "Mẹ kể chuyện đoàn tàu có các toa màu đỏ, vàng, đỏ, vàng.",
            say_to_child:
              '"Toa số 1 màu đỏ, toa số 2 màu vàng, toa số 3 màu đỏ, vậy toa số 4 màu gì con nhỉ?"',
          },
          {
            instruction: "Bé đặt bạn thú bông đúng màu vào toa tiếp theo.",
            say_to_child:
              '"Con xếp bạn thú vào đúng toa tàu theo quy luật nhé!"',
          },
        ],
        easier: "Mẹ nhắc lại màu của 3 toa đầu tiên thật chậm rãi.",
        harder: "Mở rộng đoàn tàu thêm quy luật toa To - Nhỏ xen kẽ.",
      },
      materials: "Hộp giấy nhỏ nhiều màu, thú bông",
      estimated_minutes: 12,
      access_tier: "standard",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["story_pattern"],
      thinking_tags: ["pattern_extension"],
      theme_tag: "vehicle",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0026",
      content_version: 1,
      activity_kind: "home_activity",
      title: "Xếp dọn đồ chơi theo giỏ màu",
      instruction: {
        preparation:
          "Chuẩn bị 2 giỏ đựng đồ chơi: 1 giỏ đồ chơi nhựa, 1 giỏ thú bông.",
        steps: [
          {
            instruction: "Hướng dẫn bé dọn dẹp đồ chơi sau khi chơi xong.",
            say_to_child:
              '"Con nhặt tất cả các bạn gấu bông vào giỏ vải, còn đồ chơi nhựa vào giỏ nhựa nhé!"',
          },
          {
            instruction: "Bé cầm từng món đồ và phân loại vào đúng giỏ.",
            say_to_child:
              '"Chiếc ô tô này làm bằng nhựa, con để vào giỏ nào nào?"',
          },
        ],
        easier: "Mẹ phân loại cùng bé từng món một.",
        harder:
          "Phân loại thành 3 giỏ: đồ chơi to, đồ chơi nhỏ, và sách truyện.",
      },
      materials: "2 giỏ đựng đồ gia đình",
      estimated_minutes: 10,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["sorting_by_material"],
      thinking_tags: ["organization"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0027",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Tạo vòng đeo tay chuỗi hạt quy luật",
      instruction: {
        preparation:
          "Chuẩn bị sợi dây dù mềm và các vòng ống hút cắt khúc (đỏ, vàng).",
        steps: [
          {
            instruction: "Bé xâu từng đoạn ống hút vào sợi dây dù.",
            say_to_child:
              '"Con xâu 1 đoạn ống hút đỏ, rồi đến 1 đoạn vàng, rồi lặp lại để làm chiếc vòng tay nhé!"',
          },
          {
            instruction: "Bé kiểm tra lại chuỗi sau khi xâu được 6 đoạn.",
            say_to_child:
              '"Con xem chuỗi vòng tay của mình đã đều màu chưa nào!"',
          },
        ],
        easier: "Dùng đoạn ống hút to dễ xâu và làm chuỗi ngắn 4 đoạn.",
        harder: "Tạo chuỗi quy luật AABB (2 đỏ, 2 vàng).",
      },
      materials: "Ống hút giấy cắt khúc, dây dù mềm",
      estimated_minutes: 15,
      access_tier: "standard",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["bead_pattern"],
      thinking_tags: ["fine_motor_sequencing"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0028",
      content_version: 1,
      activity_kind: "observation",
      title: "Tìm quy luật trên bộ quần áo",
      instruction: {
        preparation:
          "Chọn một chiếc áo kẻ sọc hoặc váy hoa có họa tiết lặp lại.",
        steps: [
          {
            instruction: "Cùng bé quan sát các đường kẻ sọc trên áo.",
            say_to_child:
              '"Con nhìn xem các sọc kẻ trên áo lặp lại như thế nào: sọc trắng rồi đến sọc xanh này!"',
          },
          {
            instruction:
              "Bé dùng ngón tay chỉ dọc theo các đường sọc và gọi tên màu.",
            say_to_child: '"Con chỉ tay và đọc tên các màu theo thứ tự nào!"',
          },
        ],
        easier: "Quan sát kẻ sọc 2 màu to bản rõ nét.",
        harder: "Tìm thêm họa tiết quy luật trên thảm trải sàn hoặc rèm cửa.",
      },
      materials: "Áo kẻ sọc hoặc vải có họa tiết",
      estimated_minutes: 8,
      access_tier: "standard",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["visual_pattern"],
      thinking_tags: ["pattern_detection"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0029",
      content_version: 1,
      activity_kind: "mini_project",
      title: "Làm cuốn sổ phân loại lá và hoa khô",
      instruction: {
        preparation: "Chuẩn bị 1 quyển sổ vẽ nháp và hồ dán an toàn.",
        steps: [
          {
            instruction:
              "Buổi 1: Thu thập hoa rụng và lá rụng ngoài sân, ép phẳng.",
            say_to_child:
              '"Chúng mình cùng nhặt cánh hoa và lá khô để làm sổ phân loại nhé!"',
          },
          {
            instruction:
              "Buổi 2: Dán trang bên trái toàn lá xanh, trang bên phải toàn hoa đỏ.",
            say_to_child:
              '"Trang này con dán tất cả các loại lá cây, trang kia dán cánh hoa nào!"',
          },
        ],
        easier: "Chỉ dán 2 chiếc lá to và 2 bông hoa nhỏ.",
        harder: "Phân loại lá thành 3 nhóm: lá dài, lá tròn, lá hình răng cưa.",
      },
      materials: "Sổ vẽ, hồ dán an toàn, lá cây khô",
      estimated_minutes: 15,
      access_tier: "premium",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["scrapbook_sorting"],
      thinking_tags: ["multi_criteria_sorting"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0030",
      content_version: 1,
      activity_kind: "assessment",
      title: "Đánh giá quan sát: Tiếp tục chuỗi quy luật",
      instruction: {
        preparation: "Xếp chuỗi thìa và dĩa: Thìa - Dĩa - Thìa - Dĩa - Thìa.",
        steps: [
          {
            instruction: "Đưa ra 1 chiếc thìa và 1 chiếc dĩa trên tay.",
            say_to_child:
              '"Con chọn chiếc thìa hay chiếc dĩa để đặt vào vị trí tiếp theo này?"',
          },
          {
            instruction: "Quan sát xem bé có chọn đúng chiếc dĩa không.",
            say_to_child: '"Con đặt món đồ con chọn vào cuối hàng nào!"',
          },
        ],
        easier: "Nhắc lại tên chuỗi 2 lần trước khi hỏi bé.",
        harder: "Yêu cầu bé tự đặt 2 món tiếp theo (Dĩa rồi đến Thìa).",
      },
      materials: "3 chiếc thìa, 3 chiếc dĩa ăn",
      estimated_minutes: 6,
      access_tier: "premium",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pattern_assessment"],
      thinking_tags: ["pattern_continuation"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0114",
      content_version: 1,
      activity_kind: "home_activity",
      title: "Thám tử nhí truy tìm con số bí ẩn",
      instruction: {
        preparation:
          "Bảng số từ 1 đến 10 viết trên giấy và các tấm bìa che số.",
        steps: [
          {
            instruction:
              "Mẹ đưa manh mối 1: 'Số bí ẩn lớn hơn 5'. Bé lấy bìa che các số từ 1 đến 5.",
            say_to_child:
              '"Manh mối 1 giúp con loại bỏ những số nào trên bảng?"',
          },
          {
            instruction:
              "Mẹ đưa manh mối 2: 'Số bí ẩn là số nhỏ hơn 7'. Bé che tiếp các số 7, 8, 9, 10 để tìm ra số 6.",
            say_to_child:
              '"Số duy nhất còn lại trên bảng chính là con số bí mật: Số 6!"',
          },
        ],
        easier: "Chơi trên bảng 1 đến 5 với 1 manh mối trực tiếp.",
        harder: "Thêm manh mối về chẵn/lẻ trên bảng số 1 đến 10.",
      },
      materials: "Bảng số 1 đến 10, các tấm bìa che số",
      estimated_minutes: 20,
      access_tier: "free",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["deduction", "wb14"],
      thinking_tags: ["deduce", "infer"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0117",
      content_version: 1,
      activity_kind: "home_activity",
      title: "Sudoku mini 4 ô không trùng lặp",
      instruction: {
        preparation:
          "Vẽ lưới 2x2 ô vuông trên bìa cứng và chuẩn bị 4 thẻ hình gồm 2 hình mặt trời ☀️ và 2 hình ngôi sao ⭐.",
        steps: [
          {
            instruction:
              "Mẹ giải thích luật: Mỗi hàng ngang và mỗi cột dọc chỉ được có đúng 1 mặt trời và 1 ngôi sao.",
            say_to_child:
              '"Hàng này đã có mặt trời rồi, ô còn lại phải đặt hình gì con nhỉ?"',
          },
          {
            instruction:
              "Bé xếp các thẻ hình vào 4 ô sao cho không hàng hay cột nào bị lặp lại hình.",
            say_to_child:
              '"Con kiểm tra lại từng hàng ngang và cột dọc xem có hình nào bị trùng nhau không!"',
          },
        ],
        easier: "Lưới 2x2 mẹ đã điền sẵn 3 ô, bé chỉ điền 1 ô cuối cùng.",
        harder:
          "Chuyển sang lưới Sudoku 3x3 với 3 loại hình dạng (Hình tròn, Vuông, Tam giác).",
      },
      materials: "Bìa cứng vẽ lưới 2x2, 4 thẻ hình",
      estimated_minutes: 20,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["sudoku", "wb17"],
      thinking_tags: ["deduce", "infer"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0121",
      content_version: 1,
      activity_kind: "home_activity",
      title: "Ma trận biến hình hai chiều",
      instruction: {
        preparation:
          "Bảng lưới 2x2 trên giấy. Ô hàng trên: Hình vuông nhỏ đỏ -> Hình vuông to đỏ. Ô hàng dưới: Hình tròn nhỏ xanh -> Ô trống [?].",
        steps: [
          {
            instruction:
              "Bé quan sát quy luật biến đổi ở hàng trên: hình dạng và màu sắc giữ nguyên, kích thước từ nhỏ biến thành to.",
            say_to_child:
              '"Ở hàng trên, hình vuông nhỏ đã biến hình thành hình vuông to!"',
          },
          {
            instruction:
              "Áp dụng quy luật tương tự cho hàng dưới: Hình tròn nhỏ xanh biến thành Hình tròn to xanh.",
            say_to_child:
              '"Vậy hình tròn nhỏ màu xanh sẽ biến hình thành hình gì ở ô trống?"',
          },
        ],
        easier:
          "Quy luật chỉ thay đổi màu sắc (Hình tròn đỏ -> Hình tròn xanh).",
        harder:
          "Ma trận biến đổi đồng thời cả kích thước và số lượng phần tử bên trong.",
      },
      materials: "Bảng lưới 2x2, thẻ hình lựa chọn",
      estimated_minutes: 20,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["matrix", "wb21"],
      thinking_tags: ["infer", "deduce"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0209",
      content_version: 1,
      title: "Trò chơi số: Quy luật màu sắc",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-PAT-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn màu sắc tiếp theo cho chuỗi hạt nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["patterns"],
      thinking_tags: ["pattern_recognition"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0210",
      content_version: 1,
      title: "Trò chơi số: Phân loại khối màu",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-CLS-BOX-0004",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp các khối đỏ và xanh vào đúng hộp nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["classification"],
      thinking_tags: ["sorting"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0249",
      content_version: 1,
      title: "Trò chơi số: Phân loại quả ngọt",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-PAT-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn tất cả các loại quả nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["patterns"],
      thinking_tags: ["pattern_recognition"],
      theme_tag: "fruit",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0250",
      content_version: 1,
      title: "Trò chơi số: Xếp rau củ vào giỏ",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-CLS-BOX-0004",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp rau củ vào đúng giỏ nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["classification"],
      thinking_tags: ["sorting"],
      theme_tag: "vegetable",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0251",
      content_version: 1,
      title: "Trò chơi số: Chuỗi quy luật hoa lá",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-PAT-SEQ-0006",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xem tiếp theo là hoa hay lá nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["patterns"],
      thinking_tags: ["pattern_recognition"],
      theme_tag: "flower",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0252",
      content_version: 1,
      title: "Trò chơi số: So sánh cặp hình tương phản",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-LOG-CMP-0008",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé nối cặp hoa cùng kích cỡ nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["comparison"],
      thinking_tags: ["matching"],
      theme_tag: "flower",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0253",
      content_version: 1,
      title: "Trò chơi số: Vị trí ô logic",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-LOG-POS-0011",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé đặt hình vào đúng góc phần tư nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["spatial_concept"],
      thinking_tags: ["spatial_reasoning"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0254",
      content_version: 1,
      title: "Trò chơi số: Chạm nhanh quy luật",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SUB-FAST-0013",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chạm thật nhanh hình tiếp theo của dãy nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["subitizing"],
      thinking_tags: ["instant_recognition"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0255",
      content_version: 1,
      title: "Trò chơi số: Manh mối con vật bí ẩn",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-CLU-DED-0021",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé đoán xem con vật nào phù hợp với gợi ý nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["log", "ded"],
      thinking_tags: ["infer", "observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0256",
      content_version: 1,
      title: "Trò chơi số: Ma trận logic màu sắc",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-MAT-CHO-0024",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn hình phù hợp cho ô trống ma trận nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["log", "mat"],
      thinking_tags: ["infer", "compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0257",
      content_version: 1,
      title: "Trò chơi số: Sudoku hình học mini",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SUD-MIN-0027",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé điền hình vào ô trống không bị trùng hàng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["log", "sud"],
      thinking_tags: ["infer", "plan"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0258",
      content_version: 1,
      title: "Trò chơi số: Tìm điểm khác biệt giữa hai bức tranh",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-VIS-SPOT-0030",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm điểm khác nhau giữa hai bức tranh nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat", "cmp"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0259",
      content_version: 1,
      title: "Trò chơi số: Thẻ phân loại đồ chơi",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-PAT-CARD-0002",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp thẻ đồ chơi vào hàng quy luật nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SEQ.01"],
      learning_objective_codes: ["LO-C3.SEQ.01-01"],
      what_tags: ["patterns"],
      thinking_tags: ["pattern_recognition"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0260",
      content_version: 1,
      title: "Trò chơi số: Thám tử nhí suy luận",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-CLU-DED-0022",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé dùng kính lúp tìm đồ vật theo gợi ý nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["log", "ded"],
      thinking_tags: ["infer", "observe"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0347",
      content_version: 1,
      title: "Trò chơi số: Phân loại theo tiêu chí logic",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-PAT-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn các đồ vật theo gợi ý nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["classification"],
      thinking_tags: ["sorting"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0348",
      content_version: 1,
      title: "Trò chơi số: Suy luận loại trừ đồ dùng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-CLU-DED-0021",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm đồ vật bí ẩn bằng các manh mối nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.DED.01"],
      learning_objective_codes: ["LO-C3.DED.01-01"],
      what_tags: ["log", "ded"],
      thinking_tags: ["infer", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0353",
      content_version: 1,
      title: "Trò chơi số: Phân loại ma trận",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-PAT-CARD-0002",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp hình vào ma trận đúng vị trí nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["classification"],
      thinking_tags: ["sorting"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0354",
      content_version: 1,
      title: "Trò chơi số: Ma trận logic hai chiều",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-MAT-CHO-0024",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm mảnh ghép còn thiếu trong ma trận nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["log", "mat"],
      thinking_tags: ["infer", "compare"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0361",
      content_version: 1,
      title: "Trò chơi số: Quy luật ma trận hình",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-PAT-SEQ-0006",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xem hình nào đứng tiếp theo trong hàng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["patterns"],
      thinking_tags: ["pattern_recognition"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0362",
      content_version: 1,
      title: "Trò chơi số: Điền ô ma trận Sudoku",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SUD-MIN-0027",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé điền hình vào ô trống không bị trùng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["log", "sud"],
      thinking_tags: ["infer", "plan"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0501",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Đèn lồng Tết Trung thu và quy luật sắc màu",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Đèn lồng giấy, giấy màu thủ công.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Đèn lồng giấy, giấy màu thủ công",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0502",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0001",
      title: "Thử thách số 1: Đèn lồng Tết Trung thu và quy luật sắc màu",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0503",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0002",
      title: "Thử thách số 2: Đèn lồng Tết Trung thu và quy luật sắc màu",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0516",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Pháo hoa đêm giao thừa: Dự đoán màu sắc rực rỡ",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Tranh pháo hoa, bút màu kim tuyến.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Tranh pháo hoa, bút màu kim tuyến",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0517",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0001",
      title: "Thử thách số 1: Pháo hoa đêm giao thừa: Dự đoán màu sắc rực rỡ",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0518",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0002",
      title: "Thử thách số 2: Pháo hoa đêm giao thừa: Dự đoán màu sắc rực rỡ",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0543",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Cô họa sĩ nhí: Pha màu và phối tranh phong cảnh",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Bảng pha màu, cọ vẽ, màu nước an toàn.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Bảng pha màu, cọ vẽ, màu nước an toàn",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0544",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-MULT-0002",
      title: "Thử thách số 1: Cô họa sĩ nhí: Pha màu và phối tranh phong cảnh",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0545",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-MULT-0001",
      title: "Thử thách số 2: Cô họa sĩ nhí: Pha màu và phối tranh phong cảnh",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "job",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0570",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Cầu vồng bảy sắc: Nhận biết thứ tự các dải màu",
      instruction: {
        preparation:
          "Chuẩn bị dụng cụ: Bộ dải màu cầu vồng bằng nỉ, thảm trắng.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Bộ dải màu cầu vồng bằng nỉ, thảm trắng",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0571",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0001",
      title: "Thử thách số 1: Cầu vồng bảy sắc: Nhận biết thứ tự các dải màu",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0572",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0002",
      title: "Thử thách số 2: Cầu vồng bảy sắc: Nhận biết thứ tự các dải màu",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0576",
      content_version: 1,
      activity_kind: "movement",
      title:
        "Khám phá: Bốn mùa tươi đẹp: Phân loại đặc trưng Xuân - Hạ - Thu - Đông",
      instruction: {
        preparation:
          "Chuẩn bị dụng cụ: 4 khay tương ứng 4 mùa, thẻ tranh phân loại.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "4 khay tương ứng 4 mùa, thẻ tranh phân loại",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0577",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-MULT-0001",
      title:
        "Thử thách số 1: Bốn mùa tươi đẹp: Phân loại đặc trưng Xuân - Hạ - Thu - Đông",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0578",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-MULT-0002",
      title:
        "Thử thách số 2: Bốn mùa tươi đẹp: Phân loại đặc trưng Xuân - Hạ - Thu - Đông",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0588",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Thu thập vỏ sò: Phân loại theo hình dạng và vân sọc",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Khay cát biển, 10 chiếc vỏ sò thật.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Khay cát biển, 10 chiếc vỏ sò thật",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0589",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-PAIR-0001",
      title:
        "Thử thách số 1: Thu thập vỏ sò: Phân loại theo hình dạng và vân sọc",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0590",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-PAIR-0002",
      title:
        "Thử thách số 2: Thu thập vỏ sò: Phân loại theo hình dạng và vân sọc",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.01"],
      learning_objective_codes: ["LO-C3.SRT.01-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0603",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Mặt trăng tròn khuyết: Trình tự các pha của mặt trăng",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Bộ thẻ pha mặt trăng, bánh quy tròn.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Bộ thẻ pha mặt trăng, bánh quy tròn",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0604",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0001",
      title:
        "Thử thách số 1: Mặt trăng tròn khuyết: Trình tự các pha của mặt trăng",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0605",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-RULE-PAT-0002",
      title:
        "Thử thách số 2: Mặt trăng tròn khuyết: Trình tự các pha của mặt trăng",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.RULE.02"],
      learning_objective_codes: ["LO-C3.RULE.02-01"],
      what_tags: ["pat"],
      thinking_tags: ["sequence"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0615",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Trái đất thân yêu: Phân biệt đại dương xanh và lục địa",
      instruction: {
        preparation:
          "Chuẩn bị dụng cụ: Quả địa cầu mini, sticker con vật trên cạn/dưới nước.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Quả địa cầu mini, sticker con vật trên cạn/dưới nước",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0616",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-MULT-0001",
      title:
        "Thử thách số 1: Trái đất thân yêu: Phân biệt đại dương xanh và lục địa",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0617",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-SRT-MULT-0002",
      title:
        "Thử thách số 2: Trái đất thân yêu: Phân biệt đại dương xanh và lục địa",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.SRT.02"],
      learning_objective_codes: ["LO-C3.SRT.02-01"],
      what_tags: ["cls"],
      thinking_tags: ["sort"],
      theme_tag: "space",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0630",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Ngày hội giao lưu tài năng toán học mầm non",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Bảng ma trận 3x3, các thẻ hình puzzle.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Bảng ma trận 3x3, các thẻ hình puzzle",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["infer"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0631",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-MTX-GRID-0002",
      title: "Thử thách số 1: Ngày hội giao lưu tài năng toán học mầm non",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["infer"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0632",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C3-MTX-GRID-0001",
      title: "Thử thách số 2: Ngày hội giao lưu tài năng toán học mầm non",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C3.MTX.01"],
      learning_objective_codes: ["LO-C3.MTX.01-01"],
      what_tags: ["pat"],
      thinking_tags: ["infer"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
];
