import type { ActivitySeed } from "../types.js";

/**
 * Activities for competency C4 (51 activities).
 * Partitioned automatically by competency (Task #208 / G4).
 */
export const C4_ACTIVITIES: readonly ActivitySeed[] = [
  {
    kind: "activity",
    header: {
      code: "ACT-0031",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Đo chiều dài chiếc bàn bằng bàn tay",
      instruction: {
        preparation: "Ngồi cùng bé cạnh bàn học.",
        steps: [
          {
            instruction:
              "Mẹ hướng dẫn bé xòe bàn tay và đặt gang tay liên tiếp.",
            say_to_child:
              '"Con xòe bàn tay ra và đếm xem chiếc bàn dài bao nhiêu gang tay của con nhé!"',
          },
          {
            instruction: "Bé đặt gang tay từ mép trái sang mép phải và đếm to.",
            say_to_child: '"Một gang tay, hai gang tay, ba gang tay nào!"',
          },
        ],
        easier: "Đo quyển sách nhỏ dài khoảng 2 gang tay.",
        harder: "Đo chiều dài chiếc giường hoặc ghế sofa.",
      },
      materials: "Bàn học, bàn tay của bé",
      estimated_minutes: 10,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["non_standard_measurement"],
      thinking_tags: ["length_comparison"],
      theme_tag: "body",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0032",
      content_version: 1,
      activity_kind: "manipulative",
      title: "So sánh nặng nhẹ bằng hai bàn tay",
      instruction: {
        preparation: "Chuẩn bị 1 quả cam và 1 chiếc lông vũ hoặc mẩu giấy vụn.",
        steps: [
          {
            instruction: "Đặt quả cam lên tay trái, mẩu giấy lên tay phải bé.",
            say_to_child:
              '"Con nhắm mắt lại và cảm nhận xem tay nào nặng hơn, tay nào nhẹ hơn nhé!"',
          },
          {
            instruction: "Bé nâng lên hạ xuống hai bàn tay như chiếc cân đĩa.",
            say_to_child:
              '"Quả cam nặng làm tay trĩu xuống, còn mẩu giấy nhẹ tênh này!"',
          },
        ],
        easier: "So sánh vật nặng rõ rệt (chai nước đầy vs chai nước rỗng).",
        harder: "So sánh 2 quả táo có kích thước xấp xỉ nhau.",
      },
      materials: "Quả cam, mẩu giấy vụn",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["weight_comparison"],
      thinking_tags: ["tactile_weight"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0033",
      content_version: 1,
      activity_kind: "discussion",
      title: "Trò chuyện: Buổi sáng, Buổi trưa, Buổi tối",
      instruction: {
        preparation: "Ngồi xem các bức ảnh sinh hoạt thường ngày của gia đình.",
        steps: [
          {
            instruction: "Hỏi bé về các hoạt động diễn ra vào buổi sáng.",
            say_to_child:
              '"Buổi sáng khi thức dậy, việc đầu tiên con thường làm là gì thế nào?"',
          },
          {
            instruction: "Chuyển sang các mốc thời gian khác trong ngày.",
            say_to_child:
              '"Thế buổi tối trước khi đi ngủ, nhà mình cùng làm gì nào?"',
          },
        ],
        easier:
          "Phân biệt 2 mốc rõ ràng: Ban ngày (trời sáng) và Ban đêm (trời tối).",
        harder:
          "Sắp xếp 4 bức tranh hoạt động theo đúng thứ tự thời gian trong ngày.",
      },
      materials: "Tranh ảnh sinh hoạt gia đình",
      estimated_minutes: 10,
      access_tier: "login",
      skill_codes: ["C4.MEM.02"],
      learning_objective_codes: ["LO-C4.MEM.02-01"],
      what_tags: ["time_routine"],
      thinking_tags: ["temporal_sequence"],
      theme_tag: "family",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0034",
      content_version: 1,
      activity_kind: "storytelling",
      title: "Kể chuyện: Chú rùa và chú thỏ chạy đua",
      instruction: {
        preparation: "Dùng 2 ngón tay mô phỏng bước đi của rùa và thỏ.",
        steps: [
          {
            instruction: "Kể về tốc độ di chuyển nhanh và chậm của hai bạn.",
            say_to_child:
              '"Bạn Thỏ chạy thật nhanh như gió, còn bạn Rùa bò chậm rãi từng bước một!"',
          },
          {
            instruction: "Bé bắt chước động tác đi nhanh và đi chậm.",
            say_to_child:
              '"Con bước nhanh như bạn thỏ, rồi lại bước chậm như bạn rùa nào!"',
          },
        ],
        easier: "Mẹ làm mẫu bước đi nhanh và chậm cho bé nhìn.",
        harder: "Đo thời gian xem ai bò từ cửa vào phòng nhanh hơn.",
      },
      materials: "Không gian phòng khách",
      estimated_minutes: 10,
      access_tier: "login",
      skill_codes: ["C4.MEM.02"],
      learning_objective_codes: ["LO-C4.MEM.02-01"],
      what_tags: ["speed_time"],
      thinking_tags: ["fast_slow_concept"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0035",
      content_version: 1,
      activity_kind: "home_activity",
      title: "Rót nước vào bình đo dung tích",
      instruction: {
        preparation: "Chuẩn bị 1 bình nhựa to và 3 chiếc cốc nhỏ bằng nhau.",
        steps: [
          {
            instruction: "Bé dùng chiếc cốc nhỏ múc nước đổ vào bình to.",
            say_to_child:
              '"Con đếm xem đổ mấy cốc nước nhỏ thì chiếc bình to này sẽ đầy nhé!"',
          },
          {
            instruction: "Bé cẩn thận rót nước và đếm số cốc.",
            say_to_child: '"Một cốc, hai cốc, chiếc bình đã gần đầy rồi này!"',
          },
        ],
        easier: "Đổ 2 cốc nước vào bát tô.",
        harder: "So sánh xem chiếc bình nào chứa được nhiều cốc nước hơn.",
      },
      materials: "Bình nhựa, cốc nhựa, nước sạch",
      estimated_minutes: 12,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["capacity_volume"],
      thinking_tags: ["volume_measurement"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0036",
      content_version: 1,
      activity_kind: "observation",
      title: "Vẽ biểu đồ cột thời tiết 3 ngày",
      instruction: {
        preparation: "Vẽ sẵn 3 cột trên tờ giấy trắng tương ứng 3 ngày.",
        steps: [
          {
            instruction: "Cùng bé nhìn ra cửa sổ xem thời tiết hôm nay.",
            say_to_child:
              '"Hôm nay trời nắng hay trời mưa, con vẽ ông mặt trời vào cột ngày hôm nay nhé!"',
          },
          {
            instruction:
              "Đếm xem có bao nhiêu ngày nắng và bao nhiêu ngày mưa.",
            say_to_child:
              '"Con nhìn biểu đồ xem tuần này có mấy ngày trời nắng nào?"',
          },
        ],
        easier: "Chỉ quan sát trời nắng và dán sticker mặt trời.",
        harder: "Ghi nhận thêm ngày nhiều mây và ngày có gió lớn.",
      },
      materials: "Giấy trắng, bút sáp màu",
      estimated_minutes: 10,
      access_tier: "standard",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["weather_chart"],
      thinking_tags: ["simple_bar_chart"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0037",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Xếp bút chì theo thứ tự dài ngắn",
      instruction: {
        preparation: "Chuẩn bị 4 chiếc bút chì có độ dài ngắn khác nhau.",
        steps: [
          {
            instruction: "Đặt các chiếc bút chì lộn xộn trên mặt bàn.",
            say_to_child:
              '"Con hãy xếp 4 chiếc bút chì này thành hàng theo thứ tự từ ngắn nhất đến dài nhất nhé!"',
          },
          {
            instruction: "Bé so sánh từng cặp bút chì để sắp xếp thứ tự.",
            say_to_child:
              '"Chiếc bút màu xanh dài hơn hay chiếc bút màu vàng dài hơn nào?"',
          },
        ],
        easier: "Chỉ so sánh 2 chiếc bút chì (1 dài, 1 ngắn).",
        harder:
          "Sắp xếp 5 que tính theo thứ tự giảm dần từ dài nhất đến ngắn nhất.",
      },
      materials: "4 chiếc bút chì hoặc bút sáp màu",
      estimated_minutes: 10,
      access_tier: "standard",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["seriation_length"],
      thinking_tags: ["ordering_comparison"],
      theme_tag: "art",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0038",
      content_version: 1,
      activity_kind: "movement",
      title: "Nhảy xa: Ai nhảy được dài hơn?",
      instruction: {
        preparation: "Dán vạch xuất phát bằng băng dính giấy trên sàn.",
        steps: [
          {
            instruction: "Bé đứng tại vạch và nhảy bật xa về phía trước.",
            say_to_child:
              '"Con nhún chân và nhảy thật xa về phía trước xem bước nhảy dài bao nhiêu nhé!"',
          },
          {
            instruction: "Đánh dấu điểm tiếp đất và đo bằng số bước chân.",
            say_to_child:
              '"Mẹ và con cùng đếm xem cú nhảy này dài mấy bàn chân nào!"',
          },
        ],
        easier: "Chỉ nhảy bước ngắn và so sánh ai nhảy xa hơn.",
        harder: "Nhảy 2 lần và so sánh lần nào nhảy dài hơn lần nào.",
      },
      materials: "Băng dính giấy dán sàn",
      estimated_minutes: 12,
      access_tier: "standard",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["distance_measurement"],
      thinking_tags: ["kinesthetic_length"],
      theme_tag: "body",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0039",
      content_version: 1,
      activity_kind: "mini_project",
      title: "Đo chiều cao cây xanh mini sau 3 ngày",
      instruction: {
        preparation: "Chuẩn bị 1 chậu cây mầm nhỏ và thước dây mềm.",
        steps: [
          {
            instruction:
              "Buổi 1: Đặt que gỗ cạnh cây mầm và đánh dấu chiều cao hôm nay.",
            say_to_child:
              '"Chúng mình đánh dấu vạch đỏ này để xem mầm cây cao đến đâu nhé!"',
          },
          {
            instruction:
              "Buổi 2: Sau 3 ngày tưới nước, quan sát xem cây đã cao hơn vạch cũ bao nhiêu.",
            say_to_child:
              '"Con nhìn xem ngọn cây đã vượt qua vạch đánh dấu cũ chưa nào!"',
          },
        ],
        easier: "Chỉ so sánh cây mầm với ngón tay của bé.",
        harder: "Đo chính xác xem cây mầm cao thêm mấy đốt ngón tay.",
      },
      materials: "Chậu cây mầm, que gỗ nhỏ, bút dạ",
      estimated_minutes: 15,
      access_tier: "premium",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["growth_tracking"],
      thinking_tags: ["data_collection"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0040",
      content_version: 1,
      activity_kind: "assessment",
      title: "Đánh giá quan sát: Phân biệt nặng hơn - nhẹ hơn",
      instruction: {
        preparation: "Đặt trên bàn: 1 chai nước đầy và 1 quả bóng nhựa rỗng.",
        steps: [
          {
            instruction: "Yêu cầu bé cầm lần lượt 2 món đồ trên tay.",
            say_to_child:
              '"Món đồ nào nặng hơn, con hãy nhấc món đồ đó lên và đưa cho mẹ nhé!"',
          },
          {
            instruction: "Quan sát xem bé có chọn đúng chai nước đầy không.",
            say_to_child: '"Vì sao con biết chai nước này nặng hơn quả bóng?"',
          },
        ],
        easier: "Mẹ cầm tay bé để cảm nhận sức nặng của chai nước.",
        harder: "Thử thách với 3 món đồ có khối lượng tăng dần.",
      },
      materials: "1 chai nước đầy, 1 quả bóng nhựa nhẹ",
      estimated_minutes: 6,
      access_tier: "premium",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["weight_assessment"],
      thinking_tags: ["observable_assessment"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0103",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khớp hình bìa vào bóng vẽ trên giấy",
      instruction: {
        preparation:
          "Cắt các hình tròn, vuông, tam giác bằng bìa cứng lớn (>5cm) và vẽ bóng đen tương ứng trên tờ giấy A4.",
        steps: [
          {
            instruction:
              "Đặt các hình bìa bên cạnh tờ giấy có vẽ sẵn bóng đen.",
            say_to_child:
              '"Con tìm xem hình tam giác này khớp với bóng nào trên giấy nhé!"',
          },
          {
            instruction: "Bé cầm từng hình đặt chồng khít lên bóng vẽ.",
            say_to_child:
              '"Con đặt thật khít để không bị hở bóng đen ra ngoài nào!"',
          },
        ],
        easier: "Bắt đầu với 2 hình đơn giản là hình tròn và hình vuông.",
        harder: "Thêm hình chữ nhật và hình bầu dục xoay nhiều hướng.",
      },
      materials: "Bìa carton cứng cắt hình lớn, giấy A4 vẽ bóng đen",
      estimated_minutes: 15,
      access_tier: "free",
      skill_codes: ["C4.VIS.02"],
      learning_objective_codes: ["LO-C4.VIS.02-01"],
      what_tags: ["shapes", "wb03"],
      thinking_tags: ["visual", "match"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0110",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Pha chế các cấp độ đậm nhạt của màu",
      instruction: {
        preparation:
          "Chuẩn bị 3 cốc nước trong suốt, màu thực phẩm đỏ và 1 ống hút nhỏ giọt.",
        steps: [
          {
            instruction:
              "Nhỏ 1 giọt màu vào cốc 1, 3 giọt vào cốc 2, và 6 giọt vào cốc 3.",
            say_to_child:
              '"Con quan sát xem 3 cốc nước màu đỏ này khác nhau như thế nào?"',
          },
          {
            instruction:
              "Bé sắp xếp 3 cốc nước theo thứ tự từ nhạt nhất đến đậm nhất.",
            say_to_child:
              '"Bé xếp cốc nhạt nhất ở đầu và cốc đậm nhất ở cuối nhé!"',
          },
        ],
        easier: "Chỉ so sánh 2 cốc màu: 1 giọt và 5 giọt.",
        harder: "Tạo 4 bậc sắc độ từ rất nhạt đến rất đậm.",
      },
      materials: "3 cốc nước trong, màu thực phẩm, ống nhỏ giọt",
      estimated_minutes: 20,
      access_tier: "free",
      skill_codes: ["C4.SEN.01"],
      learning_objective_codes: ["LO-C4.SEN.01-01"],
      what_tags: ["colors", "wb10"],
      thinking_tags: ["compare", "sequence"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0211",
      content_version: 1,
      title: "Trò chơi số: Quan sát đồ vật",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm món đồ dùng học tập quen thuộc nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["observation_details"],
      thinking_tags: ["observation"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0212",
      content_version: 1,
      title: "Trò chơi số: Phân loại nặng nhẹ",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DIF-BOX-0004",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé phân loại đồ vật nặng và nhẹ vào hai hộp nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["visual_discrimination"],
      thinking_tags: ["sorting"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0261",
      content_version: 1,
      title: "Trò chơi số: Quan sát lá cây",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm chiếc lá có hình răng cưa nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["observation_details"],
      thinking_tags: ["observation"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0262",
      content_version: 1,
      title: "Trò chơi số: Phân loại kích thước lá",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DIF-BOX-0004",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp lá to và lá nhỏ vào hai giỏ nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["visual_discrimination"],
      thinking_tags: ["sorting"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0263",
      content_version: 1,
      title: "Trò chơi số: Tìm hoa giấu trên cành",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-LOC-0005",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm bông hoa nở ở ngọn cành nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["spatial_concept"],
      thinking_tags: ["spatial_reasoning"],
      theme_tag: "flower",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0264",
      content_version: 1,
      title: "Trò chơi số: Dãy tăng dần chiều dài",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-SEQ-OBS-0006",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp các cành cây từ ngắn đến dài nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["order"],
      thinking_tags: ["sequencing"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0265",
      content_version: 1,
      title: "Trò chơi số: Ghép đôi hoa cùng màu",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DIF-CMP-0007",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé nối các bông hoa cùng màu lại nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["comparison"],
      thinking_tags: ["matching"],
      theme_tag: "flower",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0266",
      content_version: 1,
      title: "Trò chơi số: Nhìn nhanh chọn chiếc nơ xinh",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-SUB-FAST-0010",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn thật nhanh chiếc nơ màu hồng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["subitizing"],
      thinking_tags: ["instant_recognition"],
      theme_tag: "clothing",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0267",
      content_version: 1,
      title: "Trò chơi số: Tìm đồ chơi giấu trong phòng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SCENE-0021",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm chiếc ô tô đồ chơi giấu sau tủ nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["observe", "match"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0268",
      content_version: 1,
      title: "Trò chơi số: So sánh 3 điểm khác nhau",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SPOT-0024",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child:
              '"Bé khoanh tròn 3 điểm khác nhau giữa hai phòng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0269",
      content_version: 1,
      title: "Trò chơi số: Quan sát đồ vật nhà bếp",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-CARD-0002",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chạm vào chiếc nồi nấu ăn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["observation_details"],
      thinking_tags: ["observation"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0270",
      content_version: 1,
      title: "Trò chơi số: Tìm thìa dĩa trong bếp",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SCENE-0022",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm chiếc thìa đang nằm trên bàn ăn nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["observe", "match"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0271",
      content_version: 1,
      title: "Trò chơi số: Cất bát đĩa vào tủ",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-BOX-0008",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé xếp bát vào ngăn bát và đĩa vào ngăn đĩa nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["visual_discrimination"],
      thinking_tags: ["sorting"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0272",
      content_version: 1,
      title: "Trò chơi số: Tìm điểm khác của chiếc cốc",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SPOT-0025",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chỉ ra chiếc cốc có quai khác màu nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0273",
      content_version: 1,
      title: "Trò chơi số: Quan sát thời tiết",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn bức tranh có ông mặt trời tỏa nắng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["observation_details"],
      thinking_tags: ["observation"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0274",
      content_version: 1,
      title: "Trò chơi số: Ghép trang phục theo thời tiết",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DIF-CMP-0013",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chọn áo ấm cho ngày trời đông lạnh giá nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.MEM.02"],
      learning_objective_codes: ["LO-C4.MEM.02-01"],
      what_tags: ["comparison"],
      thinking_tags: ["matching"],
      theme_tag: "clothing",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0275",
      content_version: 1,
      title: "Trò chơi số: Chuỗi các mùa trong năm",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-SEQ-OBS-0012",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child:
              '"Bé xếp tranh các mùa theo thứ tự xuân, hạ, thu, đông nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.MEM.02"],
      learning_objective_codes: ["LO-C4.MEM.02-01"],
      what_tags: ["order"],
      thinking_tags: ["sequencing"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0276",
      content_version: 1,
      title: "Trò chơi số: Đặt đồng hồ đúng vị trí",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-LOC-0009",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé treo chiếc đồng hồ lên giữa bức tường nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["spatial_concept"],
      thinking_tags: ["spatial_reasoning"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0277",
      content_version: 1,
      title: "Trò chơi số: Chạm nhanh quả bóng nặng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-SUB-FAST-0015",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chạm nhanh vào quả bóng sắt nặng nhất nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["subitizing"],
      thinking_tags: ["instant_recognition"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0278",
      content_version: 1,
      title: "Trò chơi số: Tìm quả cân ẩn",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SCENE-0023",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm quả cân nhỏ giấu bên cạnh đĩa cân nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["observe", "match"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0279",
      content_version: 1,
      title: "Trò chơi số: Phân loại lịch biểu tuần",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-BOX-0014",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child:
              '"Bé xếp các ngày đi học và ngày nghỉ vào hai hộp nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["visual_discrimination"],
      thinking_tags: ["sorting"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0280",
      content_version: 1,
      title: "Trò chơi số: Tìm điểm khác trên tờ lịch",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SPOT-0026",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm ô ngày có màu đỏ trên tờ lịch nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0281",
      content_version: 1,
      title: "Trò chơi số: Thẻ giờ giấc sinh hoạt",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-CARD-0011",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé chạm vào bức tranh bé đang ngủ ngon nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.MEM.02"],
      learning_objective_codes: ["LO-C4.MEM.02-01"],
      what_tags: ["observation_details"],
      thinking_tags: ["observation"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0282",
      content_version: 1,
      title: "Trò chơi số: Tìm chiếc gối êm trong phòng ngủ",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SCENE-0021",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm chiếc gối ngủ giấu trên giường nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.MEM.02"],
      learning_objective_codes: ["LO-C4.MEM.02-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["observe", "match"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0283",
      content_version: 1,
      title: "Trò chơi số: Xếp đồ vật nặng nhẹ vào kệ",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-BOX-0020",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child:
              '"Bé xếp đồ nặng ở tầng dưới và đồ nhẹ ở tầng trên nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["visual_discrimination"],
      thinking_tags: ["sorting"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0284",
      content_version: 1,
      title: "Trò chơi số: Tìm chiếc lông vũ khác biệt",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SPOT-0024",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child:
              '"Bé tìm chiếc lông vũ có màu sắc khác với các chiếc còn lại nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0325",
      content_version: 1,
      title: "Trò chơi số: Tìm bóng vật thể",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-OBS-CARD-0001",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm bóng đen của đồ vật nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.VIS.01"],
      learning_objective_codes: ["LO-C4.VIS.01-01"],
      what_tags: ["visual_discrimination"],
      thinking_tags: ["observation"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0326",
      content_version: 1,
      title: "Trò chơi số: Tìm điểm khác biệt của bóng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SPOT-0024",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm điểm khác nhau giữa hai chiếc bóng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.VIS.01"],
      learning_objective_codes: ["LO-C4.VIS.01-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0339",
      content_version: 1,
      title: "Trò chơi số: Ghép đôi đồ vật xúc giác",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DIF-CMP-0007",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé ghép các đồ vật có cảm giác giống nhau nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.SEN.01"],
      learning_objective_codes: ["LO-C4.SEN.01-01"],
      what_tags: ["observation_details"],
      thinking_tags: ["matching"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0340",
      content_version: 1,
      title: "Trò chơi số: Tìm đồ vật ẩn trong phòng",
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-VIS-SCENE-0021",
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: '"Bé tìm món đồ bí ẩn giấu trong phòng nhé!"',
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: ["C4.SEN.01"],
      learning_objective_codes: ["LO-C4.SEN.01-01"],
      what_tags: ["obs", "vis"],
      thinking_tags: ["observe", "match"],
      theme_tag: "household",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0546",
      content_version: 1,
      activity_kind: "movement",
      title: "Khám phá: Lá cờ đỏ sao vàng: Khám phá biểu tượng Tổ quốc",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Cờ Tổ quốc cầm tay, giấy màu đỏ vàng.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Cờ Tổ quốc cầm tay, giấy màu đỏ vàng",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["cls"],
      thinking_tags: ["observe"],
      theme_tag: "homeland",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0547",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DET-FIND-0002",
      title: "Thử thách số 1: Lá cờ đỏ sao vàng: Khám phá biểu tượng Tổ quốc",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["cls"],
      thinking_tags: ["observe"],
      theme_tag: "homeland",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0548",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DET-FIND-0001",
      title: "Thử thách số 2: Lá cờ đỏ sao vàng: Khám phá biểu tượng Tổ quốc",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["cls"],
      thinking_tags: ["observe"],
      theme_tag: "homeland",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0567",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Mưa rơi tí tách: Hứng giọt nước và đếm nhịp mưa rơi",
      instruction: {
        preparation:
          "Chuẩn bị dụng cụ: Ống xúc xắc tạo âm thanh hạt mưa, bát nước.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Ống xúc xắc tạo âm thanh hạt mưa, bát nước",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["lst"],
      thinking_tags: ["recall"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0568",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-SEN-SND-0001",
      title:
        "Thử thách số 1: Mưa rơi tí tách: Hứng giọt nước và đếm nhịp mưa rơi",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["lst"],
      thinking_tags: ["recall"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0569",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-SEN-SND-0002",
      title:
        "Thử thách số 2: Mưa rơi tí tách: Hứng giọt nước và đếm nhịp mưa rơi",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C4.SEN.03"],
      learning_objective_codes: ["LO-C4.SEN.03-01"],
      what_tags: ["lst"],
      thinking_tags: ["recall"],
      theme_tag: "weather",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0597",
      content_version: 1,
      activity_kind: "manipulative",
      title: "Khám phá: Đáy biển sâu huyền bí: Tìm kiếm sinh vật phát sáng",
      instruction: {
        preparation: "Chuẩn bị dụng cụ: Phòng rèm tối, thẻ tranh dạ quang.",
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: "Phòng rèm tối, thẻ tranh dạ quang",
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["cls"],
      thinking_tags: ["observe"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0598",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DET-FIND-0001",
      title:
        "Thử thách số 1: Đáy biển sâu huyền bí: Tìm kiếm sinh vật phát sáng",
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["cls"],
      thinking_tags: ["observe"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
  {
    kind: "activity",
    header: {
      code: "ACT-0599",
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: "GL-C4-DET-FIND-0002",
      title:
        "Thử thách số 2: Đáy biển sâu huyền bí: Tìm kiếm sinh vật phát sáng",
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: ["C4.DET.03"],
      learning_objective_codes: ["LO-C4.DET.03-01"],
      what_tags: ["cls"],
      thinking_tags: ["observe"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
  },
];
