import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_ORD_04_IDENTITY: SkillIdentity = {
  code: "C1.ORD.04",
  strand_code: "C1.ORD",
  competency_code: "C1",
  name: "Thứ tự đến thứ mười",
  age_min: 5,
  age_max: 5,
  difficulty: 3,
  thinking_processes: ["sequence", "count"],
  tier: "core",
  prerequisites: ["C1.ORD.03", "C1.NREC.03"],
  learning_objectives: [
    {
      code: "LO-C1.ORD.04-01",
      behaviour: "Nhận biết và thực hành Thứ tự đến thứ mười ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.ORD.04-02",
      behaviour: "Vận dụng Thứ tự đến thứ mười trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.ORD.04-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Thứ tự đến thứ mười",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_ORD_04_DATASET: SkillDataset = {
  skill_code: "C1.ORD.04",
  concept_label: "Thứ tự đến thứ mười",
  surface: "game",
  items: [
    {
      id: "ord_1",
      label: "thứ nhất",
      glyph: "1.",
      value: 1,
      image: {
        kind: "emoji",
        ref: "🥇",
      },
    },
    {
      id: "ord_2",
      label: "thứ hai",
      glyph: "2.",
      value: 2,
      image: {
        kind: "emoji",
        ref: "🥈",
      },
    },
    {
      id: "ord_3",
      label: "thứ ba",
      glyph: "3.",
      value: 3,
      image: {
        kind: "emoji",
        ref: "🥉",
      },
    },
    {
      id: "ord_4",
      label: "thứ tư",
      glyph: "4.",
      value: 4,
      image: {
        kind: "emoji",
        ref: "4️⃣",
      },
    },
    {
      id: "ord_5",
      label: "thứ năm",
      glyph: "5.",
      value: 5,
      image: {
        kind: "emoji",
        ref: "5️⃣",
      },
    },
    {
      id: "ord_6",
      label: "thứ sáu",
      glyph: "6.",
      value: 6,
      image: {
        kind: "emoji",
        ref: "6️⃣",
      },
    },
    {
      id: "ord_7",
      label: "thứ bảy",
      glyph: "7.",
      value: 7,
      image: {
        kind: "emoji",
        ref: "7️⃣",
      },
    },
    {
      id: "ord_8",
      label: "thứ tám",
      glyph: "8.",
      value: 8,
      image: {
        kind: "emoji",
        ref: "8️⃣",
      },
    },
    {
      id: "ord_9",
      label: "thứ chín",
      glyph: "9.",
      value: 9,
      image: {
        kind: "emoji",
        ref: "9️⃣",
      },
    },
    {
      id: "ord_10",
      label: "thứ mười",
      glyph: "10.",
      value: 10,
      image: {
        kind: "emoji",
        ref: "🔟",
      },
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "ord_1",
      target_id: "ord_2",
    },
    {
      type: "sequence",
      source_id: "ord_2",
      target_id: "ord_3",
    },
    {
      type: "sequence",
      source_id: "ord_3",
      target_id: "ord_4",
    },
    {
      type: "sequence",
      source_id: "ord_4",
      target_id: "ord_5",
    },
  ],
  axes: {
    ordinal: {
      values: [
        "thứ nhất",
        "thứ hai",
        "thứ ba",
        "thứ tư",
        "thứ năm",
        "thứ sáu",
        "thứ bảy",
        "thứ tám",
        "thứ chín",
        "thứ mười",
      ],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "ten-frame",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "ten-frame",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "numeral",
    },
  ],
  phrasing: {
    prompt_template: "Bạn nào đứng thứ {position}?",
    narration_template: "Chúng mình cùng tìm hiểu về Thứ tự đến thứ mười nhé",
  },
  ordering: [
    "ord_1",
    "ord_2",
    "ord_3",
    "ord_4",
    "ord_5",
    "ord_6",
    "ord_7",
    "ord_8",
    "ord_9",
    "ord_10",
  ],
};

export const C1_ORD_04_SEED: SkillSeed = {
  identity: C1_ORD_04_IDENTITY,
  dataset: C1_ORD_04_DATASET,
  levels: [
    {
      code: "GL-C1-ORD-TAP-0013",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TAP-0014",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TAP-0015",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TAP-0016",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCNT-0013",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCNT-0014",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCNT-0015",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCNT-0016",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCMP-0013",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCMP-0014",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCMP-0015",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-TCMP-0016",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SORT-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SORT-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SORT-0003",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SORT-0004",
      template: "GT-006",
      band: "5-6",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SHAD-0009",
      template: "GT-007",
      band: "4-5",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SHAD-0010",
      template: "GT-007",
      band: "4-5",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SHAD-0011",
      template: "GT-007",
      band: "4-5",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-ORD-SHAD-0012",
      template: "GT-007",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
  ],
};
