import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_DAT_03_IDENTITY: SkillIdentity = {
  code: "C1.DAT.03",
  strand_code: "C1.DAT",
  competency_code: "C1",
  name: "So cột cao – thấp",
  age_min: 5,
  age_max: 5,
  difficulty: 3,
  thinking_processes: ["compare", "observe"],
  tier: "core",
  prerequisites: ["C1.DAT.02", "C1.CMP.08"],
  learning_objectives: [
    {
      code: "LO-C1.DAT.03-01",
      behaviour: "Nhận biết và thực hành So cột cao – thấp ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.DAT.03-02",
      behaviour: "Vận dụng So cột cao – thấp trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.DAT.03-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới So cột cao – thấp",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_DAT_03_DATASET: SkillDataset = {
  skill_code: "C1.DAT.03",
  concept_label: "So cột cao – thấp",
  surface: "game",
  items: [
    {
      id: "col_1",
      label: "cột vàng thấp nhất",
      glyph: "🟨",
      value: 1,
      audio_path: "/audio/voice/c1/dat/col_yellow.mp3",
      image: {
        kind: "emoji",
        ref: "🟨",
      },
      contrast_group: "column",
    },
    {
      id: "col_2",
      label: "cột đỏ thấp",
      glyph: "🟥",
      value: 2,
      audio_path: "/audio/voice/c1/dat/col_short.mp3",
      image: {
        kind: "emoji",
        ref: "🟥",
      },
      contrast_group: "column",
    },
    {
      id: "col_3",
      label: "cột xanh cao",
      glyph: "🟦",
      value: 4,
      audio_path: "/audio/voice/c1/dat/col_blue.mp3",
      image: {
        kind: "emoji",
        ref: "🟦",
      },
      contrast_group: "column",
    },
    {
      id: "col_4",
      label: "cột xanh cao nhất",
      glyph: "🟩",
      value: 6,
      audio_path: "/audio/voice/c1/dat/col_tall.mp3",
      image: {
        kind: "emoji",
        ref: "🟩",
      },
      contrast_group: "column",
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "col_1",
      target_id: "col_2",
    },
    {
      type: "sequence",
      source_id: "col_2",
      target_id: "col_3",
    },
    {
      type: "sequence",
      source_id: "col_3",
      target_id: "col_4",
    },
    {
      type: "contrast",
      source_id: "col_4",
      target_id: "col_1",
      metadata: {
        dimension: "height",
      },
    },
  ],
  axes: {
    height: {
      values: ["thấp nhất", "thấp", "cao", "cao nhất"],
      ordered: true,
    },
  },
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "ten-frame",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "ten-frame",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "numeral",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy đếm số lượng {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về So cột cao – thấp nhé",
  },
};

export const C1_DAT_03_SEED: SkillSeed = {
  identity: C1_DAT_03_IDENTITY,
  dataset: C1_DAT_03_DATASET,
  levels: [
    {
      code: "GL-C1-DAT-TAP-0009",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TAP-0010",
      template: "GT-001",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TAP-0011",
      template: "GT-001",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TAP-0012",
      template: "GT-001",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCNT-0009",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCNT-0010",
      template: "GT-002",
      band: "4-5",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCNT-0011",
      template: "GT-002",
      band: "4-5",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCNT-0012",
      template: "GT-002",
      band: "4-5",
      difficulty: 2,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCMP-0009",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCMP-0010",
      template: "GT-003",
      band: "4-5",
      difficulty: 3,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCMP-0011",
      template: "GT-003",
      band: "4-5",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-TCMP-0012",
      template: "GT-003",
      band: "4-5",
      difficulty: 2,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PAIR-0005",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PAIR-0006",
      template: "GT-004",
      band: "4-5",
      difficulty: 3,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PAIR-0007",
      template: "GT-004",
      band: "4-5",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PAIR-0008",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "body",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PATT-0005",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PATT-0006",
      template: "GT-005",
      band: "4-5",
      difficulty: 3,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PATT-0007",
      template: "GT-005",
      band: "4-5",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-PATT-0008",
      template: "GT-005",
      band: "4-5",
      difficulty: 2,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-MIR-0001",
      template: "GT-021",
      band: "5-6",
      difficulty: 3,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-DAT-SPOT-0001",
      template: "GT-025",
      band: "5-6",
      difficulty: 3,
      theme: "home",
      rounds: 3,
    },
  ],
};
