#!/usr/bin/env node
/**
 * Sinh `.env.example` từ `ENV_REGISTRY` (BR-ENV-09).
 *
 * Bốn file, một registry: bản ở gốc cho máy trạm, và ba bản `apps/<app>/` lọc
 * theo trường `apps` — mẫu của file runtime `/etc/mindkid/env/<app>.env` mà
 * pm2 nạp riêng cho từng tiến trình (BR-ENV-04, BR-SUP-04).
 *
 * Việc **kiểm** file đã lệch hay chưa là của `tests/env-example.test.ts` —
 * script này chỉ ghi, vì một file sinh ra mà không ai đối chiếu thì sẽ lệch.
 *
 *   node packages/config/scripts/generate-env-example.ts
 */
import { writeFileSync } from "node:fs";
import { type AppType, ENV_REGISTRY, type EnvVarDef } from "#src/env-contract";
import { repoPath } from "#src/repo-paths";

/**
 * Giá trị chạy được trên máy dev, tra theo tên trước khi rơi về mẫu chung của
 * `kind`.
 *
 * `kind` chỉ nói *dạng* — `kind: "url"` được `checkKindValidation` kiểm bằng
 * `new URL()`, nên `https://example.com/endpoint` vẫn hợp lệ cho một chuỗi kết
 * nối Postgres. Mẫu chung ở đây vì thế là mẫu **im lặng sai**: file sinh ra đi
 * qua cổng env màu xanh, rồi `getAppDb()` treo tới timeout. Tên nào cần một
 * giá trị thật để `pnpm test` chạy được thì phải nằm trong bảng này.
 */
const LOCAL_DEV_EXAMPLES: Record<string, string> = {
  DATABASE_URL: "postgres://postgres:postgres@localhost:5433/mindkid",
  DATABASE_URL_APP:
    "postgres://mindkid_app:mindkid_app_password@localhost:5433/mindkid",
  VALKEY_URL: "valkey://127.0.0.1:6380",
  SITE_URL: "http://localhost:3000",
  STORAGE_BASE_URL: "http://localhost:3000/assets",
  NUXT_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001",
  TRUSTED_PROXY_IPS: "127.0.0.1,::1",
};

function getPortExample(name: string): string {
  if (name.includes("MIN")) {
    return "5";
  }
  if (name.includes("MAX")) {
    return "20";
  }
  return "3000";
}

function getExampleValue(item: EnvVarDef): string {
  const localDevValue = LOCAL_DEV_EXAMPLES[item.name];
  if (localDevValue) {
    return localDevValue;
  }
  if (item.kind === "port") {
    return getPortExample(item.name);
  }
  if (item.kind === "url") {
    return "https://example.com/endpoint";
  }
  if (item.kind === "secret") {
    return "replace_with_at_least_32_bytes_cryptographic_secret_key!";
  }
  if (item.kind === "email") {
    return "dev@mindkid.vn";
  }
  if (item.kind === "enum" && item.enumValues) {
    return item.enumValues[0] || "";
  }
  return "example_value";
}

/** Biến của một tiến trình; không truyền `app` thì lấy cả danh mục. */
function registryFor(app?: AppType): readonly EnvVarDef[] {
  if (app === undefined) {
    return ENV_REGISTRY;
  }
  return ENV_REGISTRY.filter((item) => item.apps.includes(app));
}

const ROOT_HEADER: readonly string[] = [
  "# =============================================================================",
  "# MindKid Platform — Environment Variables Contract (.env.example)",
  "# Auto-generated from packages/config/src/env-contract.ts (BR-ENV-09)",
  "# DO NOT EDIT THIS FILE MANUALLY.",
  "# =============================================================================",
  "",
];

/**
 * Bản của từng app nói rõ nó dùng ở đâu: người vận hành chép nó thành file
 * runtime `/etc/mindkid/env/<app>.env` (env-contract.md §7.3). Không nói thì
 * người đọc tưởng máy trạm phải có `apps/<app>/.env`, rồi tạo một file thiếu
 * biến và tự dựng lại đúng cái bẫy che file gốc.
 */
function appHeader(app: AppType): readonly string[] {
  return [
    "# =============================================================================",
    `# MindKid Platform — Environment Variables Contract (apps/${app}/.env.example)`,
    "# Auto-generated from packages/config/src/env-contract.ts (BR-ENV-09)",
    "# DO NOT EDIT THIS FILE MANUALLY.",
    "#",
    `# Mẫu của file runtime /etc/mindkid/env/${app}.env (env-contract.md §7.3).`,
    "# Chỉ chứa biến tiến trình này thật sự đọc (BR-ENV-04).",
    "# Máy trạm KHÔNG cần file này — dùng .env ở gốc repo.",
    "# =============================================================================",
    "",
  ];
}

/**
 * Generates .env.example from canonical ENV_REGISTRY (BR-ENV-09).
 * Có `app` thì lọc theo tiến trình đó; không có thì giữ nguyên bản đầy đủ.
 */
export function generateEnvExample(app?: AppType): string {
  const lines: string[] = [
    ...(app === undefined ? ROOT_HEADER : appHeader(app)),
  ];

  for (const item of registryFor(app)) {
    const appsList = item.apps.join(", ");
    const reqStr =
      item.required === "when-enabled"
        ? `when enabled by ${item.enabledBy}`
        : item.required;

    const exampleValue = getExampleValue(item);

    lines.push(`# [${appsList}] ${item.note} (${reqStr})`);
    lines.push(`${item.name}=${exampleValue}`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Bốn file, một registry: bản gốc cho máy trạm và ba bản mẫu cho file runtime
 * của từng tiến trình.
 */
export const TARGETS: readonly { path: string; app?: AppType }[] = [
  { path: ".env.example" },
  { path: "apps/web/.env.example", app: "web" },
  { path: "apps/admin/.env.example", app: "admin" },
  { path: "apps/worker/.env.example", app: "worker" },
];

// Chế độ `--check` cũ giờ là test `tests/env-example.test.ts`; script này chỉ
// còn việc **sinh** file. Ghi CHỈ khi chạy trực tiếp: test import
// `generateEnvExample` từ đây, và một test Cấm — NEVER ghi vào cây nguồn.
if (import.meta.url === `file://${process.argv[1]}`) {
  for (const target of TARGETS) {
    writeFileSync(
      repoPath(target.path),
      generateEnvExample(target.app),
      "utf8"
    );
    process.stdout.write(
      `✅ Đã sinh ${target.path} (${registryFor(target.app).length} biến)\n`
    );
  }
}
