import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  ENV_REGISTRY,
  type EnvVarDef,
} from "../packages/config/src/env-contract.js";

function getUrlExample(name: string): string {
  if (name === "DATABASE_URL") {
    return "postgres://postgres:postgres@localhost:5433/mindkid";
  }
  if (name === "VALKEY_URL") {
    return "valkey://127.0.0.1:6380";
  }
  if (name === "SITE_URL") {
    return "http://localhost:3000";
  }
  if (name === "ADMIN_SITE_URL") {
    return "http://localhost:3002";
  }
  return "https://example.com/endpoint";
}

function getPortExample(name: string): string {
  if (name.includes("MIN")) {
    return "5";
  }
  if (name.includes("MAX")) {
    return "20";
  }
  return "3000";
}

function getExampleValue(item: EnvVarDef): string {
  if (item.kind === "port") {
    return getPortExample(item.name);
  }
  if (item.kind === "url") {
    return getUrlExample(item.name);
  }
  if (item.kind === "secret") {
    return "replace_with_at_least_32_bytes_cryptographic_secret_key!";
  }
  if (item.kind === "email") {
    return "dev@mindkid.vn";
  }
  if (item.kind === "enum" && item.enumValues) {
    return item.enumValues[0] || "";
  }
  return "example_value";
}

/**
 * Generates .env.example from canonical ENV_REGISTRY (BR-ENV-09)
 */
export function generateEnvExample(): string {
  const lines: string[] = [
    "# =============================================================================",
    "# MindKid Platform — Environment Variables Contract (.env.example)",
    "# Auto-generated from packages/config/src/env-contract.ts (BR-ENV-09)",
    "# DO NOT EDIT THIS FILE MANUALLY.",
    "# =============================================================================",
    "",
  ];

  for (const item of ENV_REGISTRY) {
    const appsList = item.apps.join(", ");
    const reqStr =
      item.required === "when-enabled"
        ? `when enabled by ${item.enabledBy}`
        : item.required;

    const exampleValue = getExampleValue(item);

    lines.push(`# [${appsList}] ${item.note} (${reqStr})`);
    lines.push(`${item.name}=${exampleValue}`);
    lines.push("");
  }

  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const content = generateEnvExample();
  const targetPath = resolve(process.cwd(), ".env.example");
  writeFileSync(targetPath, content, "utf8");
  console.log(`✅ Generated .env.example (${ENV_REGISTRY.length} variables)`);
}
