import type { ContentSeed } from "../types.js";

export const C6_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C6-MEM-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Ghi nhớ đồ vật đã thấy",
      instruction_vi: "Em hãy chọn hình chiếc nơ đỏ.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "ribbon", emoji: "🎀" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C6-MEM-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Ghi nhớ hình ảnh chuông vàng",
      instruction_vi: "Em chọn hình chiếc chuông xinh.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "b1", emoji: "🔔" },
        { id: "b2", emoji: "🔔" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 3 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C6-ATT-CARD-0003",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Tập trung tìm món quà",
      instruction_vi: "Chạm vào hộp quà màu sinh nhật.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C6.INH.01"],
      learning_objective_codes: ["LO-C6.INH.01-01"],
      what_tags: ["fnc"],
      thinking_tags: ["inhibitory"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "gift", emoji: "🎁" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C6-MEM-BOX-0004",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Cất đồ chơi vào đúng chỗ",
      instruction_vi: "Kéo ô tô chơi vào giỏ đồ.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "toy_basket", label: "Giỏ đồ chơi", target_type: "toy" },
      ],
      drag_items: [
        { id: "car", emoji: "🚗", type: "toy" },
        { id: "book", emoji: "📖", type: "book" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C6-ATT-BOX-0005",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Kiềm chế chú ý khi chọn đồ",
      instruction_vi: "Chỉ chọn quả bóng tròn nhẵn.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C6.INH.01"],
      learning_objective_codes: ["LO-C6.INH.01-01"],
      what_tags: ["fnc"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "ball_box", label: "Hộp bóng", target_type: "ball" }],
      drag_items: [
        { id: "b1", emoji: "⚽", type: "ball" },
        { id: "c1", emoji: "🎲", type: "dice" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C6-MEM-SEQ-0006",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Ghi nhớ chuỗi 2 biểu tượng",
      instruction_vi: "Chọn biểu tượng tiếp theo đúng trí nhớ.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🔴", "🟢", "🔴", "🟢"],
      options: ["🔴", "🟢", "🔵"],
      correct_option: "🔴",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C6-MEM-CMP-0007",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "So sánh hình ảnh vừa nhớ",
      instruction_vi: "Chọn hình giống hình vừa xem.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🍏" }],
      right_group: [{ emoji: "🍎" }],
      target: "match",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C6-ATT-LOC-0008",
      content_version: 1,
      template_code: "GT-005",
      title_vi: "Tập trung thị giác tìm điểm giấu",
      instruction_vi: "Chạm vào ô có chú ong vàng.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C6.INH.01"],
      learning_objective_codes: ["LO-C6.INH.01-01"],
      what_tags: ["fnc"],
      thinking_tags: ["inhibitory"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "bee", emoji: "🐝", target: true },
          { id: "flower", emoji: "🌸", target: false },
        ],
      ],
      target_id: "bee",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C6-SUB-FAST-0009",
      content_version: 1,
      template_code: "GT-006",
      title_vi: "Nhớ nhanh 1 hình ảnh xuất hiện",
      instruction_vi: "Vật gì vừa chớp qua vậy em.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🚀" }],
      flash_duration_ms: 1500,
      options: ["Tên lửa", "Ô tô"],
      correct_answer: "Tên lửa",
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C6-MEM-CARD-0010",
      content_version: 1,
      template_code: "GT-001",
      title_vi: "Nhớ vị trí hình ảnh 3 đối tượng",
      instruction_vi: "Đếm số bông hoa cúc vừa hiện.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "f1", emoji: "🌼" },
        { id: "f2", emoji: "🌼" },
        { id: "f3", emoji: "🌼" },
      ],
      target_count: 3,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C6-ATT-BOX-0011",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại tập trung không xao nhãng",
      instruction_vi: "Bỏ khối vuông đỏ vào hộp.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C6.INH.01"],
      learning_objective_codes: ["LO-C6.INH.01-01"],
      what_tags: ["fnc"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "red_sq_box", label: "Hộp đỏ", target_color: "red" }],
      drag_items: [
        { id: "rs", emoji: "🟥", color: "red" },
        { id: "bs", emoji: "🟦", color: "blue" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C6-MEM-SEQ-0012",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Ghi nhớ chuỗi 3 biểu tượng",
      instruction_vi: "Chọn biểu tượng tiếp theo.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["☀️", "🌙", "⭐️", "☀️", "🌙"],
      options: ["☀️", "🌙", "⭐️"],
      correct_option: "⭐️",
    },
    difficulty_params: { pattern_length: 3 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C6-SUB-FAST-0013",
      content_version: 1,
      template_code: "GT-006",
      title_vi: "Thử thách ghi nhớ chớp nhoáng 2 hình",
      instruction_vi: "Hai hình vừa rồi là quả gì.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🍎" }, { emoji: "🍌" }],
      flash_duration_ms: 1200,
      options: ["Táo và chuối", "Cam và dưa"],
      correct_answer: "Táo và chuối",
    },
    difficulty_params: { flash_duration_ms: 1200 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C6-ATT-LOC-0014",
      content_version: 1,
      template_code: "GT-005",
      title_vi: "Quan sát điểm khác biệt ẩn trong lưới",
      instruction_vi: "Chạm vào ô có kim cương đỏ.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C6.INH.01"],
      learning_objective_codes: ["LO-C6.INH.01-01"],
      what_tags: ["fnc"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "d1", emoji: "♦️", target: true },
          { id: "d2", emoji: "♣️", target: false },
        ],
      ],
      target_id: "d1",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C6-MEM-CMP-0015",
      content_version: 1,
      template_code: "GT-003",
      title_vi: "Ghi nhớ cặp thẻ trùng khớp",
      instruction_vi: "Chọn nhóm thẻ có cùng loại trái cây.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🍇" }, { emoji: "🍇" }],
      right_group: [{ emoji: "🍇" }, { emoji: "🍊" }],
      target: "match",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C6-ATT-BOX-0016",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Phân loại chú ý kháng xao nhãng cao",
      instruction_vi: "Bỏ sinh vật biển vào bể kính.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C6.INH.01"],
      learning_objective_codes: ["LO-C6.INH.01-01"],
      what_tags: ["fnc"],
      thinking_tags: ["inhibitory"],
      theme_tag: "ocean",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "aquarium", label: "Bể cá", target_habitat: "water" }],
      drag_items: [
        { id: "octopus", emoji: "🐙", habitat: "water" },
        { id: "duck", emoji: "🦆", habitat: "land" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C6-MEM-SEQ-0017",
      content_version: 1,
      template_code: "GT-004",
      title_vi: "Ghi nhớ dãy số đảo ngược đơn giản",
      instruction_vi: "Chọn số tiếp theo trong dãy.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["sequential"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["5", "4", "3", "2"],
      options: ["1", "5", "0"],
      correct_option: "1",
    },
    difficulty_params: { pattern_length: 4 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C6-SUB-FAST-0018",
      content_version: 1,
      template_code: "GT-006",
      title_vi: "Thử thách ghi nhớ cực nhanh 1000ms",
      instruction_vi: "Số lượng chấm tròn vừa chớp là bao nhiêu.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [
        { emoji: "🔴" },
        { emoji: "🔴" },
        { emoji: "🔴" },
        { emoji: "🔴" },
      ],
      flash_duration_ms: 1000,
      options: [3, 4, 5],
      correct_answer: 4,
    },
    difficulty_params: { flash_duration_ms: 1000 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C6-ATT-LOC-0019",
      content_version: 1,
      template_code: "GT-005",
      title_vi: "Tập trung chú ý tìm ô vuông màu sắc",
      instruction_vi: "Chạm vào ô vuông màu vàng.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C6.INH.01"],
      learning_objective_codes: ["LO-C6.INH.01-01"],
      what_tags: ["fnc"],
      thinking_tags: ["inhibitory"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "ys", emoji: "🟨", target: true },
          { id: "rs", emoji: "🟥", target: false },
        ],
        [
          { id: "bs", emoji: "🟦", target: false },
          { id: "gs", emoji: "🟩", target: false },
        ],
      ],
      target_id: "ys",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C6-MEM-BOX-0020",
      content_version: 1,
      template_code: "GT-002",
      title_vi: "Sắp xếp bộ nhớ làm việc đa đối tượng",
      instruction_vi: "Bỏ rau củ quả vào giỏ đi chợ.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C6.WM.03"],
      learning_objective_codes: ["LO-C6.WM.03-01"],
      what_tags: ["mem"],
      thinking_tags: ["inhibitory"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "market_basket", label: "Giỏ đi chợ", target_category: "veggie" },
      ],
      drag_items: [
        { id: "v1", emoji: "🥦", category: "veggie" },
        { id: "t1", emoji: "⚽", category: "toy" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
];
