import fs from "node:fs";

// Danh sách 45 bài học theo bản đồ lesson-map.md
const lessonDefs = [
  // W28 (Festival)
  {
    code: "LES-0061",
    title: "Đèn lồng Tết Trung thu và quy luật sắc màu",
    theme: "festival",
    skill: "C3.RULE.02",
    age_min: 4,
    age_max: 5,
    what: ["pattern"],
    thinking: ["sequence"],
    gameLevel: "GL-C3-RULE-PAT-0001",
    outcome: "Bé nhận biết và tiếp tục chuỗi quy luật màu sắc đèn lồng AB.",
    mat: "Đèn lồng giấy, giấy màu thủ công",
  },
  {
    code: "LES-0062",
    title: "Đếm bao lì xì may mắn và chia lộc đầu xuân",
    theme: "festival",
    skill: "C1.CNT.09",
    age_min: 4,
    age_max: 5,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-STEP-0005",
    outcome: "Bé đếm số lượng bao lì xì từ 1 đến 10.",
    mat: "Bao lì xì đỏ, tiền xu đồ chơi",
  },
  {
    code: "LES-0063",
    title: "Xếp mâm ngũ quả ngày Tết: Phân loại hình khối trái cây",
    theme: "festival",
    skill: "C2.CON.04",
    age_min: 4,
    age_max: 5,
    what: ["geo"],
    thinking: ["classify"],
    gameLevel: "GL-C2-CON-SOLID-0001",
    outcome: "Bé phân loại các loại quả theo hình khối tròn, dài, bầu dục.",
    mat: "Mâm nhựa, 5 loại quả thật hoặc mô hình",
  },

  // W29 (Festival)
  {
    code: "LES-0064",
    title: "Gói bánh chưng xanh: Hình vuông và lạt buộc song song",
    theme: "festival",
    skill: "C2.GEO.02",
    age_min: 5,
    age_max: 6,
    what: ["geo"],
    thinking: ["compare"],
    gameLevel: "GL-C2-GEO-MATCH-0103",
    outcome: "Bé nhận biết hình vuông và tạo các đường kẻ song song.",
    mat: "Khuôn bánh chưng gỗ, lá dong, dây lạt",
  },
  {
    code: "LES-0065",
    title: "Chợ hoa ngày Tết: Đếm cành đào, nhành mai",
    theme: "festival",
    skill: "C1.CNT.10",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-CARD-0004",
    outcome: "Bé đếm số lượng hoa đào hoa mai nở trên cành.",
    mat: "Cành hoa lụa đào, mai, bình hoa",
  },
  {
    code: "LES-0066",
    title: "Pháo hoa đêm giao thừa: Dự đoán màu sắc rực rỡ",
    theme: "festival",
    skill: "C3.RULE.02",
    age_min: 5,
    age_max: 6,
    what: ["pattern"],
    thinking: ["sequence"],
    gameLevel: "GL-C3-RULE-PAT-0001",
    outcome: "Bé quan sát và dự đoán màu sắc chùm pháo hoa tiếp theo.",
    mat: "Tranh pháo hoa, bút màu kim tuyến",
  },

  // W30 (Job)
  {
    code: "LES-0067",
    title: "Bác sĩ khám bệnh: Đo nhiệt độ và phân loại dụng cụ y tế",
    theme: "job",
    skill: "C5.DES.04",
    age_min: 4,
    age_max: 5,
    what: ["describe"],
    thinking: ["deduce"],
    gameLevel: "GL-C5-DES-RSN-0001",
    outcome: "Bé phân biệt các dụng cụ y tế và giải thích công dụng.",
    mat: "Bộ đồ chơi bác sĩ, nhiệt kế, ống nghe",
  },
  {
    code: "LES-0068",
    title: "Chú lính cứu hỏa dũng cảm: Lập đường đi dập lửa",
    theme: "job",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["plan"],
    thinking: ["plan"],
    gameLevel: "GL-C6-PLN-SCH-0002",
    outcome: "Bé lập kế hoạch đường đi ngắn nhất cho xe cứu hỏa.",
    mat: "Xe cứu hỏa đồ chơi, sa bàn mê cung xốp",
  },
  {
    code: "LES-0069",
    title: "Cô giáo dạy học: Sắp xếp bàn ghế lớp học ngăn nắp",
    theme: "job",
    skill: "C2.ORI.03",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel: "GL-C2-ORI-POS-0002",
    outcome: "Bé sắp xếp đồ dùng ở các vị trí trước, sau, trên, dưới.",
    mat: "Bàn ghế học sinh mini, sách vở",
  },

  // W31 (Job)
  {
    code: "LES-0070",
    title: "Chú công an giao thông: Điều khiển xe qua ngã tư",
    theme: "job",
    skill: "C2.ORI.04",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel: "GL-C2-ORI-DIR-0002",
    outcome: "Bé phân biệt hướng rẽ trái và rẽ phải khi tham gia giao thông.",
    mat: "Gậy chỉ huy giao thông, còi, mô hình xe",
  },
  {
    code: "LES-0071",
    title: "Bác nông dân gieo hạt: Đếm luống rau thẳng tắp",
    theme: "job",
    skill: "C1.CNT.02",
    age_min: 4,
    age_max: 5,
    what: ["cnt"],
    thinking: ["count", "observe"],
    gameLevel: "GL-C1-CNT-STEP-0005",
    outcome: "Bé đếm các cây rau theo thứ tự trên từng luống đất.",
    mat: "Khay cát mô phỏng luống rau, rau mầm",
  },
  {
    code: "LES-0072",
    title: "Chú phi công bay lượn: Định vị đường bay trên bầu trời",
    theme: "job",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["plan"],
    thinking: ["plan"],
    gameLevel: "GL-C6-PLN-SCH-0002",
    outcome: "Bé lập kế hoạch lộ trình bay tránh chướng ngại vật mây giông.",
    mat: "Mô hình máy bay, bản đồ bầu trời",
  },

  // W32 (Job)
  {
    code: "LES-0073",
    title: "Bác đầu bếp tài ba: Đo lường gia vị nấu súp",
    theme: "job",
    skill: "C5.VOL.01",
    age_min: 4,
    age_max: 5,
    what: ["measure"],
    thinking: ["compare"],
    gameLevel: "GL-C5-LIS-AUDIO-0021",
    outcome: "Bé đong đếm thể tích nước và gia vị bằng cốc, thìa.",
    mat: "Nồi súp mini, cốc đong, thìa đong, nước sạch",
  },
  {
    code: "LES-0074",
    title: "Chú thợ xây khéo léo: Xếp gạch xây bức tường phẳng",
    theme: "job",
    skill: "C2.CON.04",
    age_min: 4,
    age_max: 5,
    what: ["geo"],
    thinking: ["observe"],
    gameLevel: "GL-C2-CON-SOLID-0002",
    outcome: "Bé nhận biết khối chữ nhật và xếp các viên gạch so le vững chắc.",
    mat: "Khối xốp hình viên gạch, bay nhựa",
  },
  {
    code: "LES-0075",
    title: "Cô họa sĩ nhí: Pha màu và phối tranh phong cảnh",
    theme: "job",
    skill: "C3.SRT.02",
    age_min: 5,
    age_max: 6,
    what: ["logic"],
    thinking: ["classify"],
    gameLevel: "GL-C3-SRT-MULT-0002",
    outcome: "Bé phân loại màu sắc và tạo màu mới từ hai màu cơ bản.",
    mat: "Bảng pha màu, cọ vẽ, màu nước an toàn",
  },

  // W33 (Homeland)
  {
    code: "LES-0076",
    title: "Lá cờ đỏ sao vàng: Khám phá biểu tượng Tổ quốc",
    theme: "homeland",
    skill: "C4.DET.03",
    age_min: 4,
    age_max: 5,
    what: ["obs"],
    thinking: ["observe"],
    gameLevel: "GL-C4-DET-FIND-0002",
    outcome: "Bé quan sát và nhận biết đặc điểm lá cờ đỏ sao vàng Việt Nam.",
    mat: "Cờ Tổ quốc cầm tay, giấy màu đỏ vàng",
  },
  {
    code: "LES-0077",
    title: "Bản đồ Việt Nam hình chữ S: Khám phá 3 miền Bắc Trung Nam",
    theme: "homeland",
    skill: "C2.ORI.03",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel: "GL-C2-ORI-POS-0002",
    outcome:
      "Bé nhận biết hình dáng đất nước và định vị miền Bắc ở trên, miền Nam ở dưới.",
    mat: "Bản đồ gỗ ghép hình Việt Nam",
  },
  {
    code: "LES-0078",
    title: "Hoa sen thắm ngát: Đếm cánh hoa và quan sát nhị vàng",
    theme: "homeland",
    skill: "C1.CNT.05",
    age_min: 4,
    age_max: 5,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-CARD-0004",
    outcome: "Bé đếm số lượng cánh hoa sen và quan sát chi tiết bông sen.",
    mat: "Bông hoa sen tươi, đĩa gốm nhỏ",
  },

  // W34 (Homeland)
  {
    code: "LES-0079",
    title: "Thăm Lăng Bác Hồ: Đếm hàng tre xanh bát ngát",
    theme: "homeland",
    skill: "C1.CNT.06",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-CARD-0005",
    outcome: "Bé xếp hàng cây tre theo thứ tự và đếm số lượng.",
    mat: "Mô hình cây tre nhựa, tranh Lăng Bác",
  },
  {
    code: "LES-0080",
    title: "Di tích Văn Miếu: Đếm bia tiến sĩ trên lưng rùa",
    theme: "homeland",
    skill: "C1.CNT.07",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-CARD-0006",
    outcome: "Bé đếm số lượng cụ rùa đá trong sân Văn Miếu.",
    mat: "Mô hình cụ rùa đội bia tiến sĩ",
  },
  {
    code: "LES-0081",
    title: "Nhịp cầu quê hương: Đo chiều dài cây cầu bắc qua sông",
    theme: "homeland",
    skill: "C5.LEN.01",
    age_min: 5,
    age_max: 6,
    what: ["measure"],
    thinking: ["compare"],
    gameLevel: "GL-C5-VOC-SEQ-0014",
    outcome: "Bé đo chiều dài cây cầu bằng các đơn vị đo quy ước.",
    mat: "Mô hình cầu gỗ, que tính đo lường",
  },

  // W35 (Weather)
  {
    code: "LES-0082",
    title: "Nắng ấm ban mai: Đếm tia nắng chiếu qua kẽ lá",
    theme: "weather",
    skill: "C1.CNT.01",
    age_min: 3,
    age_max: 4,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-CARD-0001",
    outcome: "Bé nhận biết biểu tượng ông mặt trời và đếm tia nắng.",
    mat: "Ông mặt trời bìa cứng, que kẹp gỗ làm tia nắng",
  },
  {
    code: "LES-0083",
    title: "Mưa rơi tí tách: Hứng giọt nước và đếm nhịp mưa rơi",
    theme: "weather",
    skill: "C4.SEN.03",
    age_min: 4,
    age_max: 5,
    what: ["sound"],
    thinking: ["recall"],
    gameLevel: "GL-C4-SEN-SND-0001",
    outcome: "Bé lắng nghe âm thanh tiếng mưa và đếm nhịp rơi.",
    mat: "Ống xúc xắc tạo âm thanh hạt mưa, bát nước",
  },
  {
    code: "LES-0084",
    title: "Cầu vồng bảy sắc: Nhận biết thứ tự các dải màu",
    theme: "weather",
    skill: "C3.RULE.02",
    age_min: 4,
    age_max: 5,
    what: ["pattern"],
    thinking: ["sequence"],
    gameLevel: "GL-C3-RULE-PAT-0001",
    outcome: "Bé nhận biết và sắp xếp các dải màu cầu vồng theo thứ tự.",
    mat: "Bộ dải màu cầu vồng bằng nỉ, thảm trắng",
  },

  // W36 (Weather)
  {
    code: "LES-0085",
    title: "Gió thổi lá bay: Quan sát hướng gió thổi",
    theme: "weather",
    skill: "C2.ORI.04",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel: "GL-C2-ORI-DIR-0002",
    outcome: "Bé xác định hướng gió thổi sang bên trái hoặc bên phải.",
    mat: "Chong chóng giấy, quạt tay mini",
  },
  {
    code: "LES-0086",
    title: "Bốn mùa tươi đẹp: Phân loại đặc trưng Xuân - Hạ - Thu - Đông",
    theme: "weather",
    skill: "C3.SRT.02",
    age_min: 4,
    age_max: 5,
    what: ["logic"],
    thinking: ["classify"],
    gameLevel: "GL-C3-SRT-MULT-0001",
    outcome: "Bé phân loại trang phục và thời tiết theo 4 mùa trong năm.",
    mat: "4 khay tương ứng 4 mùa, thẻ tranh phân loại",
  },
  {
    code: "LES-0087",
    title: "Nhiệt kế thần kỳ: Nhận biết ngày nóng và ngày lạnh",
    theme: "weather",
    skill: "C5.DES.04",
    age_min: 5,
    age_max: 6,
    what: ["describe"],
    thinking: ["deduce"],
    gameLevel: "GL-C5-DES-RSN-0001",
    outcome: "Bé quan sát cột nhiệt độ và đưa ra nhận xét nóng hay lạnh.",
    mat: "Nhiệt kế đồ chơi có cột dải màu điều chỉnh",
  },

  // W37 (Ocean)
  {
    code: "LES-0088",
    title: "Tàu ngầm lặn biển: Khám phá độ sâu đại dương",
    theme: "ocean",
    skill: "C5.LEN.02",
    age_min: 5,
    age_max: 6,
    what: ["measure"],
    thinking: ["compare"],
    gameLevel: "GL-C5-VOC-SEQ-0014",
    outcome: "Bé so sánh độ sâu của các tầng nước biển.",
    mat: "Thước dây đo chiều sâu, mô hình tàu ngầm",
  },
  {
    code: "LES-0089",
    title: "Đàn cá hề bơi lội: Tách gộp số lượng cá trong rạn san hô",
    theme: "ocean",
    skill: "C1.PROB.01",
    age_min: 4,
    age_max: 5,
    what: ["calc"],
    thinking: ["count"],
    gameLevel: "GL-C1-ADD-COMB-0001",
    outcome: "Bé tách đàn cá 6 con thành 2 nhóm nhỏ vào 2 hốc đá.",
    mat: "Mô hình rạn san hô, 6 chú cá hề mini",
  },
  {
    code: "LES-0090",
    title: "Thu thập vỏ sò: Phân loại theo hình dạng và vân sọc",
    theme: "ocean",
    skill: "C3.SRT.01",
    age_min: 4,
    age_max: 5,
    what: ["logic"],
    thinking: ["classify"],
    gameLevel: "GL-C3-SRT-PAIR-0001",
    outcome: "Bé phân loại vỏ sò xoắn ốc và vỏ sò dẹp phẳng.",
    mat: "Khay cát biển, 10 chiếc vỏ sò thật",
  },

  // W38 (Ocean)
  {
    code: "LES-0091",
    title: "Đua thuyền buồm: Hướng gió đẩy thuyền đi nhanh",
    theme: "ocean",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["plan"],
    thinking: ["plan"],
    gameLevel: "GL-C6-PLN-SCH-0001",
    outcome: "Bé điều chỉnh hướng buồm để thuyền về đích đúng lộ trình.",
    mat: "Chậu nước lớn, thuyền buồm giấy",
  },
  {
    code: "LES-0092",
    title: "Chú bạch tuộc thông minh: Đếm 8 xúc tu dài",
    theme: "ocean",
    skill: "C1.CNT.08",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-CARD-0003",
    outcome: "Bé đếm đủ 8 xúc tu bạch tuộc xòe đều.",
    mat: "Đất nặn, mắt thần kỳ",
  },
  {
    code: "LES-0093",
    title: "Đáy biển sâu huyền bí: Tìm kiếm sinh vật phát sáng",
    theme: "ocean",
    skill: "C4.DET.03",
    age_min: 5,
    age_max: 6,
    what: ["obs"],
    thinking: ["observe"],
    gameLevel: "GL-C4-DET-FIND-0001",
    outcome: "Bé dùng đèn pin tìm kiếm các sinh vật phát quang ẩn nấp.",
    mat: "Phòng rèm tối, thẻ tranh dạ quang",
  },

  // W39 (Space)
  {
    code: "LES-0094",
    title: "Tên lửa phóng vào không gian: Đếm ngược 10, 9, 8...",
    theme: "space",
    skill: "C1.ORD.02",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-ORD-STEP-0001",
    outcome: "Bé đếm lùi thành thạo từ 10 về 0 để phóng tên lửa.",
    mat: "Mô hình tên lửa xốp, bệ phóng",
  },
  {
    code: "LES-0095",
    title: "Mặt trăng tròn khuyết: Trình tự các pha của mặt trăng",
    theme: "space",
    skill: "C3.RULE.02",
    age_min: 5,
    age_max: 6,
    what: ["pattern"],
    thinking: ["sequence"],
    gameLevel: "GL-C3-RULE-PAT-0001",
    outcome: "Bé sắp xếp chu kỳ biến đổi từ trăng lưỡi liềm đến trăng rằm.",
    mat: "Bộ thẻ pha mặt trăng, bánh quy tròn",
  },
  {
    code: "LES-0096",
    title: "Hệ mặt trời kỳ thú: Sắp xếp các hành tinh theo khoảng cách",
    theme: "space",
    skill: "C5.LEN.01",
    age_min: 5,
    age_max: 6,
    what: ["measure"],
    thinking: ["compare"],
    gameLevel: "GL-C5-VOC-SEQ-0014",
    outcome: "Bé sắp xếp các hành tinh theo khoảng cách gần/xa mặt trời.",
    mat: "Mô hình 8 hành tinh hệ mặt trời",
  },

  // W40 (Space)
  {
    code: "LES-0097",
    title: "Phi hành gia tí hon: Vượt chướng ngại vật thiên thạch",
    theme: "space",
    skill: "C2.MAZ.01",
    age_min: 5,
    age_max: 6,
    what: ["spt"],
    thinking: ["plan"],
    gameLevel: "GL-C2-MAZ-PATH-0002",
    outcome: "Bé tìm đường qua mê cung thiên thạch để về tàu vũ trụ.",
    mat: "Sa bàn không gian vũ trụ, phi thuyền mini",
  },
  {
    code: "LES-0098",
    title: "Chòm sao lấp lánh: Nối các điểm tạo hình con gấu",
    theme: "space",
    skill: "C2.GEO.02",
    age_min: 5,
    age_max: 6,
    what: ["geo"],
    thinking: ["compare"],
    gameLevel: "GL-C2-GEO-MATCH-0103",
    outcome: "Bé dùng que nối các ngôi sao tạo thành chòm sao hình học.",
    mat: "Que dạ quang, bảng chấm sao",
  },
  {
    code: "LES-0099",
    title: "Trái đất thân yêu: Phân biệt đại dương xanh và lục địa",
    theme: "space",
    skill: "C3.SRT.02",
    age_min: 5,
    age_max: 6,
    what: ["logic"],
    thinking: ["classify"],
    gameLevel: "GL-C3-SRT-MULT-0001",
    outcome: "Bé phân biệt mảng màu nước biển và đất liền trên địa cầu.",
    mat: "Quả địa cầu mini, sticker con vật trên cạn/dưới nước",
  },

  // W41 (School)
  {
    code: "LES-0100",
    title: "Chiếc đồng hồ thần kỳ: Đọc giờ đúng sinh hoạt",
    theme: "school",
    skill: "C5.TIM.01",
    age_min: 5,
    age_max: 6,
    what: ["time"],
    thinking: ["observe"],
    gameLevel: "GL-C5-VOC-SEQ-0014",
    outcome:
      "Bé nhận biết giờ đúng trên mặt đồng hồ và gắn với hoạt động trong ngày.",
    mat: "Đồng hồ kim xoay đồ chơi, thẻ sinh hoạt",
  },
  {
    code: "LES-0122",
    title: "Chuẩn bị hành trang vào lớp 1: Đếm và sắp cặp sách",
    theme: "school",
    skill: "C1.CNT.10",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-CNT-STEP-0005",
    outcome: "Bé đếm đủ 10 món đồ dùng học tập xếp vào cặp.",
    mat: "Cặp sách tiểu học, vở, bút chì, gôm tẩy",
  },
  {
    code: "LES-0123",
    title: "Bảng chữ số diệu kỳ: Nối chữ số với lượng đồ vật",
    theme: "school",
    skill: "C1.NREC.01",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel: "GL-C1-NREC-CARD-0102",
    outcome: "Bé gắn thẻ số 1-10 tương ứng với các nhóm đồ chơi.",
    mat: "Thẻ chữ số gỗ 1-10, rổ đồ chơi",
  },

  // W42 (Graduation)
  {
    code: "LES-0124",
    title: "Trò chơi tư duy tổng hợp: Chinh phục đỉnh núi tri thức",
    theme: "nature",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["plan"],
    thinking: ["plan"],
    gameLevel: "GL-C6-PLN-SCH-0001",
    outcome: "Bé vượt qua 4 trạm câu đố logic để lên đỉnh núi.",
    mat: "Sa bàn ngọn núi, cờ chiến thắng",
  },
  {
    code: "LES-0125",
    title: "Ngày hội giao lưu tài năng toán học mầm non",
    theme: "art",
    skill: "C3.MTX.01",
    age_min: 5,
    age_max: 6,
    what: ["matrix"],
    thinking: ["deduce"],
    gameLevel: "GL-C3-MTX-GRID-0002",
    outcome: "Bé giải ma trận hình ảnh và tự tin giải thích kết quả.",
    mat: "Bảng ma trận 3x3, các thẻ hình puzzle",
  },
  {
    code: "LES-0126",
    title: "Lễ tốt nghiệp mầm non: Nhìn lại hành trình 42 tuần rực rỡ",
    theme: "school",
    skill: "C6.PLN.03",
    age_min: 5,
    age_max: 6,
    what: ["money"],
    thinking: ["plan"],
    gameLevel: "GL-C6-PLN-FIN-0002",
    outcome: "Bé tổng kết các kỹ năng đã học và tự tin bước vào lớp 1.",
    mat: "Mũ cử nhân nhí, giấy chứng nhận thông thái",
  },
];

console.log("Total new lessons:", lessonDefs.length);

// Sinh lessons
const lessons = lessonDefs.map((def, idx) => {
  const numStr = String(idx + 1).padStart(3, "0");
  const act1Code = `ACT-P1-${numStr}`;
  const act2Code = `ACT-P2-${numStr}`;
  const act3Code = `ACT-P3-${numStr}`;

  return {
    kind: "lesson",
    header: {
      code: def.code,
      content_version: 1,
      title: def.title,
      guide: {
        outcome: def.outcome,
        preparation: [
          "Chuẩn bị không gian thoáng mát, sạch sẽ cho bé hoạt động.",
          `Chuẩn bị dụng cụ: ${def.mat}.`,
        ],
        opening: `Hôm nay mẹ và bé cùng tham gia bài học "${def.title}" nhé!`,
        if_child_succeeds:
          "Khen ngợi nỗ lực của bé và khuyến khích bé thử thách với bài toán nâng cao.",
        if_child_needs_help:
          "Mẹ hướng dẫn từng bước nhỏ, thao tác mẫu chậm rãi và khích lệ bé tự tin làm lại.",
      },
      target_age_min: def.age_min,
      target_age_max: def.age_max,
      estimated_minutes: 20,
      materials: def.mat,
      warm_up: "Khởi động: Cùng vận động nhẹ nhàng theo nhạc chủ đề 3 phút.",
      reflection: "Đúc kết: Bé nhắc lại điều thú vị nhất vừa học được hôm nay.",
      assessment: def.outcome,
      extension:
        "Bé áp dụng kiến thức vừa học vào các tình huống sinh hoạt thực tế trong gia đình.",
      access_tier: idx % 3 === 0 ? "free" : "standard",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      activity_codes: [act1Code, act2Code, act3Code],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };
});

// Sinh activities
const activities = lessonDefs.flatMap((def, idx) => {
  const numStr = String(idx + 1).padStart(3, "0");
  const act1Code = `ACT-P1-${numStr}`;
  const act2Code = `ACT-P2-${numStr}`;
  const act3Code = `ACT-P3-${numStr}`;

  const act1 = {
    kind: "activity",
    header: {
      code: act1Code,
      content_version: 1,
      activity_kind: idx % 2 === 0 ? "manipulative" : "movement",
      title: `Khám phá: ${def.title}`,
      instruction: {
        preparation: `Chuẩn bị dụng cụ: ${def.mat}.`,
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: def.mat,
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };

  const act2 = {
    kind: "activity",
    header: {
      code: act2Code,
      content_version: 1,
      activity_kind: idx % 2 === 0 ? "discussion" : "storytelling",
      title: `Trọng tâm: ${def.title}`,
      instruction: {
        preparation: "Bé ngồi thoải mái trên thảm thảo luận.",
        steps: [
          {
            instruction: "Đặt câu hỏi gợi mở để bé tư duy và diễn đạt ý kiến.",
            say_to_child: '"Con có nhận xét gì về các đồ vật này không?"',
          },
          {
            instruction: "Khuyến khích bé so sánh và đúc kết quy luật.",
            say_to_child: '"Con thử tìm xem điều gì đặc biệt ở đây nào!"',
          },
        ],
        easier: "Gợi ý đáp án bằng hai lựa chọn đơn giản.",
        harder: "Khuyến khích bé tự đặt câu hỏi ngược lại cho bạn chơi.",
      },
      materials: def.mat,
      estimated_minutes: 7,
      access_tier: "free",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };

  const act3 = {
    kind: "activity",
    header: {
      code: act3Code,
      content_version: 1,
      activity_kind: "digital_game",
      title: `Luyện tập số: ${def.title}`,
      game_level_code: def.gameLevel,
      instruction: {
        preparation: "Mở màn hình bài tập trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };

  return [act1, act2, act3];
});

// Ghi file lessons
const lessonFileContent = `import type { LessonSeed } from "#src/seed-content/types";

/**
 * Task #192: Seeder cho 45 bài học bổ sung đạt sàn 126 tiết (BR-LCD-01).
 */
export const PEDAGOGY_LESSONS_45: LessonSeed[] = ${JSON.stringify(lessons, null, 2)};
`;
fs.writeFileSync(
  "./packages/db/src/seed-content/lessons/batch-pedagogy-45.ts",
  lessonFileContent
);

// Ghi file activities
const actFileContent = `import type { ActivitySeed } from "#src/seed-content/types";

/**
 * Task #192: Seeder cho 135 hoạt động bổ sung cho 45 bài học.
 */
export const PEDAGOGY_ACTIVITIES_45: ActivitySeed[] = ${JSON.stringify(activities, null, 2)};
`;
fs.writeFileSync(
  "./packages/db/src/seed-content/activities/pedagogy-activities-45.ts",
  actFileContent
);

console.log("✓ Wrote batch-pedagogy-45.ts (45 lessons)");
console.log("✓ Wrote pedagogy-activities-45.ts (135 activities)");
