import fs from "node:fs";
import { createRng, getLevelGenerator } from "@mindkid/game-engine";
import { getThemeVocabulary } from "../src/seed-content/vocab/themes.js";

// ==========================================
// 1. CHUẨN HOÁ 55 MISSING SKILL LEVELS
// ==========================================
const levelSpecs = [
  // 19 kỹ năng đợt 1
  {
    skill: "C1.CNT.02",
    eng: "GT-001",
    theme: "school",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C1-CNT-STEP-0005",
    title: "Đếm đồ dùng học tập theo thứ tự",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cnt"],
    thinking: ["count", "observe"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C1.NREC.01",
    eng: "GT-001",
    theme: "farm",
    age_min: 3,
    age_max: 4,
    age_band: "3-4",
    code: "GL-C1-NREC-CARD-0003",
    title: "Nhận biết số lượng nông trại",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cnt"],
    thinking: ["count"],
    diff: 1,
    tier: "free",
  },
  {
    skill: "C1.PROB.06",
    eng: "GT-004",
    theme: "food",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-PROB-BAL-0001",
    title: "Đổi hoa quả và phân loại",
    instruction: "Bé xếp hoa quả vào đúng nhóm nhé!",
    what: ["ops"],
    thinking: ["infer", "compare"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C1.PROB.06",
    eng: "GT-007",
    theme: "home",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-PROB-BAL-0002",
    title: "Tách gộp số lượng đồ vật",
    instruction: "Bé tìm phần còn thiếu nhé!",
    what: ["ops"],
    thinking: ["infer", "count"],
    diff: 4,
    tier: "standard",
  },
  {
    skill: "C1.MEAS.07",
    eng: "GT-006",
    theme: "nature",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-SCALE-0001",
    title: "Trình tự thời gian và đo lường",
    instruction: "Bé sắp xếp các bước theo thứ tự nhé!",
    what: ["msr"],
    thinking: ["compare", "sequence"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C1.MEAS.07",
    eng: "GT-001",
    theme: "school",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-SCALE-0002",
    title: "So sánh kích thước đồ dùng",
    instruction: "Bé hãy chọn đúng hình mẫu nhé!",
    what: ["msr"],
    thinking: ["compare"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C2.ORI.03",
    eng: "GT-005",
    theme: "home",
    age_min: 3,
    age_max: 4,
    age_band: "3-4",
    code: "GL-C2-ORI-POS-0001",
    title: "Nối vị trí đồ dùng trong nhà",
    instruction: "Bé nối các hình tương ứng nhé!",
    what: ["spt"],
    thinking: ["observe", "match"],
    diff: 1,
    tier: "free",
  },
  {
    skill: "C2.ORI.03",
    eng: "GT-022",
    theme: "animal",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C2-ORI-POS-0002",
    title: "Tìm con vật ở phía trước",
    instruction: "Bé chạm vào con vật trong tranh nhé!",
    what: ["spt"],
    thinking: ["observe"],
    diff: 2,
    tier: "standard",
  },
  {
    skill: "C2.ORI.04",
    eng: "GT-005",
    theme: "school",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C2-ORI-DIR-0001",
    title: "Nối hướng đồ dùng học tập",
    instruction: "Bé nối các hình tương ứng nhé!",
    what: ["spt"],
    thinking: ["observe", "match"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C2.ORI.04",
    eng: "GT-022",
    theme: "vehicle",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C2-ORI-DIR-0002",
    title: "Tìm phương tiện bên phải",
    instruction: "Bé chạm vào chiếc xe trong tranh nhé!",
    what: ["spt"],
    thinking: ["observe"],
    diff: 2,
    tier: "standard",
  },
  {
    skill: "C2.GEO.02",
    eng: "GT-005",
    theme: "nature",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C2-GEO-MATCH-0003",
    title: "Nối hình học thiên nhiên",
    instruction: "Bé nối các hình tương ứng nhé!",
    what: ["shp"],
    thinking: ["compare"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C2.CON.04",
    eng: "GT-004",
    theme: "home",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C2-CON-SOLID-0001",
    title: "Phân loại hình khối đồ dùng",
    instruction: "Bé xếp hình khối vào đúng nhóm nhé!",
    what: ["shp"],
    thinking: ["sort"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C2.CON.04",
    eng: "GT-007",
    theme: "school",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C2-CON-SOLID-0002",
    title: "Tách ghép khối hình học",
    instruction: "Bé chọn phần còn thiếu nhé!",
    what: ["shp"],
    thinking: ["observe"],
    diff: 3,
    tier: "standard",
  },
  {
    skill: "C2.MAZ.01",
    eng: "GT-007",
    theme: "animal",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C2-MAZ-PATH-0001",
    title: "Tìm đường về tổ",
    instruction: "Bé chọn số bước phù hợp nhé!",
    what: ["spt"],
    thinking: ["plan"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C2.MAZ.01",
    eng: "GT-020",
    theme: "farm",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C2-MAZ-PATH-0002",
    title: "Vượt mê cung nông trại",
    instruction: "Bé lập kế hoạch đường đi nhé!",
    what: ["spt"],
    thinking: ["plan"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C3.SRT.01",
    eng: "GT-001",
    theme: "food",
    age_min: 3,
    age_max: 4,
    age_band: "3-4",
    code: "GL-C3-SRT-PAIR-0001",
    title: "Phân loại món ăn quen thuộc",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cls"],
    thinking: ["sort"],
    diff: 1,
    tier: "free",
  },
  {
    skill: "C3.SRT.01",
    eng: "GT-005",
    theme: "nature",
    age_min: 3,
    age_max: 4,
    age_band: "3-4",
    code: "GL-C3-SRT-PAIR-0002",
    title: "Nối các cặp lá cây",
    instruction: "Bé nối các hình tương ứng nhé!",
    what: ["cls"],
    thinking: ["match"],
    diff: 1,
    tier: "standard",
  },
  {
    skill: "C3.SRT.02",
    eng: "GT-004",
    theme: "vehicle",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C3-SRT-MULT-0001",
    title: "Phân loại phương tiện giao thông",
    instruction: "Bé xếp xe vào đúng rổ nhé!",
    what: ["cls"],
    thinking: ["sort"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C3.SRT.02",
    eng: "GT-005",
    theme: "school",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C3-SRT-MULT-0002",
    title: "Nối đồ dùng học tập theo nhóm",
    instruction: "Bé nối các hình tương ứng nhé!",
    what: ["cls"],
    thinking: ["sort"],
    diff: 2,
    tier: "standard",
  },
  {
    skill: "C3.RULE.02",
    eng: "GT-013",
    theme: "festival",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C3-RULE-PAT-0001",
    title: "Quy luật trang trí lễ hội",
    instruction: "Bé chọn hình tiếp theo theo quy luật nhé!",
    what: ["pat"],
    thinking: ["sequence"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C3.RULE.02",
    eng: "GT-019",
    theme: "job",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C3-RULE-PAT-0002",
    title: "Dự đoán đồ nghề bác sĩ",
    instruction: "Bé chọn hình tiếp theo nhé!",
    what: ["pat"],
    thinking: ["sequence"],
    diff: 3,
    tier: "standard",
  },
  {
    skill: "C3.MTX.01",
    eng: "GT-017",
    theme: "animal",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C3-MTX-GRID-0001",
    title: "Ma trận con vật 2 chiều",
    instruction: "Bé điền hình còn thiếu vào ma trận nhé!",
    what: ["pat"],
    thinking: ["infer"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C3.MTX.01",
    eng: "GT-007",
    theme: "nature",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C3-MTX-GRID-0002",
    title: "Khám phá quy tắc lưới 2D",
    instruction: "Bé chọn phần còn thiếu nhé!",
    what: ["pat"],
    thinking: ["infer"],
    diff: 4,
    tier: "standard",
  },

  {
    skill: "C4.DET.03",
    eng: "GT-018",
    theme: "weather",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C4-DET-FIND-0001",
    title: "Lắng nghe thanh âm thời tiết",
    instruction: "Bé nghe âm thanh và chọn hình đúng nhé!",
    what: ["lst"],
    thinking: ["observe"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C4.DET.03",
    eng: "GT-001",
    theme: "homeland",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C4-DET-FIND-0002",
    title: "Quan sát biểu tượng quê hương",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cls"],
    thinking: ["observe"],
    diff: 2,
    tier: "standard",
  },
  {
    skill: "C4.SEN.03",
    eng: "GT-018",
    theme: "animal",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C4-SEN-SND-0001",
    title: "Nghe tiếng con vật và nhận biết",
    instruction: "Bé nghe âm thanh và chọn con vật nhé!",
    what: ["lst"],
    thinking: ["recall"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C4.SEN.03",
    eng: "GT-002",
    theme: "body",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C4-SEN-SND-0002",
    title: "Đếm số nhịp cảm nhận",
    instruction: "Bé đếm số lượng nhé!",
    what: ["lst"],
    thinking: ["count"],
    diff: 1,
    tier: "standard",
  },
  {
    skill: "C4.MEM.02",
    eng: "GT-011",
    theme: "food",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C4-MEM-SEQ-0001",
    title: "Ghi nhớ chuỗi món ăn",
    instruction: "Bé ghi nhớ và chọn theo thứ tự nhé!",
    what: ["mem"],
    thinking: ["recall", "sequence"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C4.MEM.02",
    eng: "GT-018",
    theme: "school",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C4-MEM-SEQ-0002",
    title: "Nghe và nhớ đồ dùng",
    instruction: "Bé nghe và chọn theo thứ tự nhé!",
    what: ["mem"],
    thinking: ["recall", "sequence"],
    diff: 2,
    tier: "standard",
  },

  {
    skill: "C5.DES.04",
    eng: "GT-001",
    theme: "job",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C5-DES-RSN-0001",
    title: "Chọn đồ dùng nghề nghiệp",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cls"],
    thinking: ["infer"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C5.DES.04",
    eng: "GT-003",
    theme: "homeland",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C5-DES-RSN-0002",
    title: "Phân loại biểu tượng quê hương",
    instruction: "Bé kéo hình vào đúng khung nhé!",
    what: ["cls"],
    thinking: ["infer"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C6.PLN.02",
    eng: "GT-020",
    theme: "family",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C6-PLN-SCH-0001",
    title: "Kế hoạch công việc gia đình",
    instruction: "Bé lập kế hoạch thực hiện nhé!",
    what: ["flw"],
    thinking: ["plan"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C6.PLN.02",
    eng: "GT-024",
    theme: "job",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C6-PLN-SCH-0002",
    title: "Lựa chọn dụng cụ làm việc",
    instruction: "Bé chọn món đồ phù hợp nhé!",
    what: ["cls"],
    thinking: ["plan"],
    diff: 3,
    tier: "standard",
  },
  {
    skill: "C6.PLN.03",
    eng: "GT-024",
    theme: "food",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C6-PLN-FIN-0001",
    title: "Đi chợ mua sắm thông minh",
    instruction: "Bé chọn mua đồ trong ngân sách nhé!",
    what: ["ops"],
    thinking: ["plan", "count"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C6.PLN.03",
    eng: "GT-020",
    theme: "school",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C6-PLN-FIN-0002",
    title: "Kế hoạch tiết kiệm đồ dùng",
    instruction: "Bé lập kế hoạch tiết kiệm nhé!",
    what: ["ops"],
    thinking: ["plan"],
    diff: 3,
    tier: "standard",
  },

  // 10 kỹ năng đợt 2 (với mã canonical chính xác)
  {
    skill: "C1.CNT.09",
    eng: "GT-001",
    theme: "festival",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0009",
    title: "Đếm 9 bao lì xì Tết",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cnt"],
    thinking: ["count"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C1.CNT.09",
    eng: "GT-006",
    theme: "festival",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0019",
    title: "Sắp xếp dãy 9 đèn lồng",
    instruction: "Bé xếp các hình theo thứ tự nhé!",
    what: ["cnt"],
    thinking: ["count", "sequence"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.CNT.10",
    eng: "GT-001",
    theme: "school",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0010",
    title: "Đếm 10 đồ dùng học sinh",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cnt"],
    thinking: ["count"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C1.CNT.10",
    eng: "GT-006",
    theme: "nature",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0020",
    title: "Đếm 10 bông hoa xuân",
    instruction: "Bé xếp các hình theo thứ tự nhé!",
    what: ["cnt"],
    thinking: ["count", "sequence"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.MEAS.05",
    eng: "GT-006",
    theme: "job",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-CAP-0001",
    title: "So sánh cốc nước đầy vơi",
    instruction: "Bé sắp xếp các cốc nước nhé!",
    what: ["msr"],
    thinking: ["compare"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C1.MEAS.05",
    eng: "GT-001",
    theme: "food",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-CAP-0002",
    title: "Nhận biết bình chứa lớn",
    instruction: "Bé hãy chọn đúng hình mẫu nhé!",
    what: ["msr"],
    thinking: ["compare"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.CNT.07",
    eng: "GT-001",
    theme: "homeland",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0007",
    title: "Đếm 7 cành hoa sen",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cnt"],
    thinking: ["count"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C1.CNT.07",
    eng: "GT-006",
    theme: "space",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0017",
    title: "Sắp xếp 7 ngôi sao sáng",
    instruction: "Bé xếp các hình theo thứ tự nhé!",
    what: ["cnt"],
    thinking: ["count", "sequence"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.MEAS.01",
    eng: "GT-006",
    theme: "homeland",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-LEN-0001",
    title: "So sánh nhịp cầu quê hương",
    instruction: "Bé sắp xếp cây cầu theo độ dài nhé!",
    what: ["msr"],
    thinking: ["compare"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C1.MEAS.01",
    eng: "GT-001",
    theme: "school",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-LEN-0002",
    title: "Tìm thước kẻ dài hơn",
    instruction: "Bé hãy chọn đúng hình mẫu nhé!",
    what: ["msr"],
    thinking: ["compare"],
    diff: 2,
    tier: "standard",
  },

  {
    skill: "C1.MEAS.02",
    eng: "GT-006",
    theme: "nature",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-HGT-0001",
    title: "Đo chiều cao cây xanh",
    instruction: "Bé sắp xếp cây từ thấp đến cao nhé!",
    what: ["msr"],
    thinking: ["compare", "sequence"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C1.MEAS.02",
    eng: "GT-001",
    theme: "ocean",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-HGT-0002",
    title: "Đo độ sâu tàu ngầm",
    instruction: "Bé hãy chọn đúng hình mẫu nhé!",
    what: ["msr"],
    thinking: ["compare"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.PROB.01",
    eng: "GT-004",
    theme: "ocean",
    age_min: 4,
    age_max: 5,
    age_band: "4-5",
    code: "GL-C1-PROB-SEP-0001",
    title: "Tách đàn cá về 2 hốc đá",
    instruction: "Bé xếp các bạn cá vào đúng nhóm nhé!",
    what: ["ops"],
    thinking: ["infer", "count"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C1.PROB.01",
    eng: "GT-007",
    theme: "farm",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-PROB-SEP-0002",
    title: "Gộp nông sản vào giỏ",
    instruction: "Bé tìm phần còn thiếu nhé!",
    what: ["ops"],
    thinking: ["infer", "count"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.CNT.08",
    eng: "GT-001",
    theme: "ocean",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0008",
    title: "Đếm 8 xúc tu bạch tuộc",
    instruction: "Bé hãy chạm vào hình giống mẫu nhé!",
    what: ["cnt"],
    thinking: ["count"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C1.CNT.08",
    eng: "GT-006",
    theme: "animal",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-STEP-0018",
    title: "Sắp xếp 8 bạn thú rừng",
    instruction: "Bé xếp các hình theo thứ tự nhé!",
    what: ["cnt"],
    thinking: ["count", "sequence"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.CNT.04",
    eng: "GT-006",
    theme: "space",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-BCK-0001",
    title: "Đếm ngược phóng tên lửa",
    instruction: "Bé sắp xếp số đếm ngược nhé!",
    what: ["cnt"],
    thinking: ["count", "sequence"],
    diff: 3,
    tier: "free",
  },
  {
    skill: "C1.CNT.04",
    eng: "GT-001",
    theme: "school",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-CNT-BCK-0002",
    title: "Tìm số đếm lùi tiếp theo",
    instruction: "Bé hãy chọn đúng hình mẫu nhé!",
    what: ["cnt"],
    thinking: ["count"],
    diff: 3,
    tier: "standard",
  },

  {
    skill: "C1.MEAS.13",
    eng: "GT-006",
    theme: "school",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-CLK-0001",
    title: "Trình tự sinh hoạt một ngày",
    instruction: "Bé sắp xếp các hoạt động trong ngày nhé!",
    what: ["msr"],
    thinking: ["sequence"],
    diff: 2,
    tier: "free",
  },
  {
    skill: "C1.MEAS.13",
    eng: "GT-001",
    theme: "home",
    age_min: 5,
    age_max: 6,
    age_band: "5-6",
    code: "GL-C1-MEAS-CLK-0002",
    title: "Nhận biết giờ sinh hoạt đúng",
    instruction: "Bé hãy chọn đúng hình mẫu nhé!",
    what: ["msr"],
    thinking: ["observe"],
    diff: 2,
    tier: "standard",
  },
];

const generatedLevels = levelSpecs.map((s, i) => {
  const gen = getLevelGenerator(s.eng);
  if (!gen) {
    throw new Error(`Generator not found for template ${s.eng}`);
  }
  const vocab = getThemeVocabulary(s.theme);
  const rng = createRng(12_345_678 + i);
  const generated = gen.generate({
    rng,
    age_band: s.age_band as "3-4" | "4-5" | "5-6",
    theme: s.theme,
    vocabulary: vocab,
  });

  return {
    header: {
      code: s.code,
      content_version: 1,
      template_code: s.eng,
      title: s.title,
      instruction: s.instruction,
      age_min: s.age_min,
      age_max: s.age_max,
      difficulty: s.diff,
      access_tier: s.tier,
      skill_codes: [s.skill],
      learning_objective_codes: [`LO-${s.skill}-01`],
      what_tags: s.what,
      thinking_tags: s.thinking,
      theme_tag: s.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: generated.content_pack,
    difficulty_params: generated.difficulty_params,
  };
});

fs.writeFileSync(
  "./packages/db/src/seed-content/pedagogy-missing-skills.ts",
  `import type { ContentSeed } from "#src/seed-content/types";

/**
 * Task #192: Level seeder cho toàn bộ các kỹ năng cần đạt sàn >= 2 level (BR-LCD-10).
 */
export const PEDAGOGY_MISSING_SKILL_LEVELS: ContentSeed<unknown, unknown>[] = ${JSON.stringify(generatedLevels, null, 2)};
`
);

console.log(
  "✓ Standardized pedagogy-missing-skills.ts with",
  generatedLevels.length,
  "levels."
);

// ==========================================
// 2. CHUẨN HOÁ 45 BÀI HỌC VÀ 135 HOẠT ĐỘNG
// ==========================================
const lessonDefs = [
  // W28 (Festival)
  {
    code: "LES-0061",
    title: "Đèn lồng Tết Trung thu và quy luật sắc màu",
    theme: "festival",
    skill: "C3.RULE.02",
    age_min: 4,
    age_max: 5,
    what: ["pat"],
    thinking: ["sequence"],
    gameLevel1: "GL-C3-RULE-PAT-0001",
    gameLevel2: "GL-C3-RULE-PAT-0002",
    outcome: "Bé nhận biết và tiếp tục chuỗi quy luật màu sắc đèn lồng AB.",
    mat: "Đèn lồng giấy, giấy màu thủ công",
  },
  {
    code: "LES-0062",
    title: "Đếm bao lì xì may mắn và chia lộc đầu xuân",
    theme: "festival",
    skill: "C1.CNT.09",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-STEP-0009",
    gameLevel2: "GL-C1-CNT-STEP-0019",
    outcome: "Bé đếm số lượng bao lì xì từ 1 đến 10.",
    mat: "Bao lì xì đỏ, tiền xu đồ chơi",
  },
  {
    code: "LES-0063",
    title: "Xếp mâm ngũ quả ngày Tết: Phân loại hình khối trái cây",
    theme: "festival",
    skill: "C2.CON.04",
    age_min: 4,
    age_max: 5,
    what: ["shp"],
    thinking: ["sort"],
    gameLevel1: "GL-C2-CON-SOLID-0001",
    gameLevel2: "GL-C2-CON-SOLID-0002",
    outcome: "Bé phân loại các loại quả theo hình khối tròn, dài, bầu dục.",
    mat: "Mâm nhựa, 5 loại quả thật hoặc mô hình",
  },

  // W29 (Festival)
  {
    code: "LES-0064",
    title: "Gói bánh chưng xanh: Hình vuông và lạt buộc song song",
    theme: "festival",
    skill: "C2.GEO.02",
    age_min: 5,
    age_max: 6,
    what: ["shp"],
    thinking: ["compare"],
    gameLevel1: "GL-C2-GEO-MATCH-0003",
    gameLevel2: "GL-C2-CON-SOLID-0001",
    outcome: "Bé nhận biết hình vuông và tạo các đường kẻ song song.",
    mat: "Khuôn bánh chưng gỗ, lá dong, dây lạt",
  },
  {
    code: "LES-0065",
    title: "Chợ hoa ngày Tết: Đếm cành đào, nhành mai",
    theme: "festival",
    skill: "C1.CNT.10",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-STEP-0010",
    gameLevel2: "GL-C1-CNT-STEP-0020",
    outcome: "Bé đếm số lượng hoa đào hoa mai nở trên cành.",
    mat: "Cành hoa lụa đào, mai, bình hoa",
  },
  {
    code: "LES-0066",
    title: "Pháo hoa đêm giao thừa: Dự đoán màu sắc rực rỡ",
    theme: "festival",
    skill: "C3.RULE.02",
    age_min: 5,
    age_max: 6,
    what: ["pat"],
    thinking: ["sequence"],
    gameLevel1: "GL-C3-RULE-PAT-0001",
    gameLevel2: "GL-C3-RULE-PAT-0002",
    outcome: "Bé quan sát và dự đoán màu sắc chùm pháo hoa tiếp theo.",
    mat: "Tranh pháo hoa, bút màu kim tuyến",
  },

  // W30 (Job)
  {
    code: "LES-0067",
    title: "Bác sĩ khám bệnh: Đo nhiệt độ và phân loại dụng cụ y tế",
    theme: "job",
    skill: "C5.DES.04",
    age_min: 5,
    age_max: 6,
    what: ["cls"],
    thinking: ["infer"],
    gameLevel1: "GL-C5-DES-RSN-0001",
    gameLevel2: "GL-C5-DES-RSN-0002",
    outcome: "Bé phân biệt các dụng cụ y tế và giải thích công dụng.",
    mat: "Bộ đồ chơi bác sĩ, nhiệt kế, ống nghe",
  },
  {
    code: "LES-0068",
    title: "Chú lính cứu hỏa dũng cảm: Lập đường đi dập lửa",
    theme: "job",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["cls"],
    thinking: ["plan"],
    gameLevel1: "GL-C6-PLN-SCH-0002",
    gameLevel2: "GL-C6-PLN-SCH-0001",
    outcome: "Bé lập kế hoạch đường đi ngắn nhất cho xe cứu hỏa.",
    mat: "Xe cứu hỏa đồ chơi, sa bàn mê cung xốp",
  },
  {
    code: "LES-0069",
    title: "Cô giáo dạy học: Sắp xếp bàn ghế lớp học ngăn nắp",
    theme: "job",
    skill: "C2.ORI.03",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel1: "GL-C2-ORI-POS-0002",
    gameLevel2: "GL-C2-ORI-POS-0001",
    outcome: "Bé sắp xếp đồ dùng ở các vị trí trước, sau, trên, dưới.",
    mat: "Bàn ghế học sinh mini, sách vở",
  },

  // W31 (Job)
  {
    code: "LES-0070",
    title: "Chú công an giao thông: Điều khiển xe qua ngã tư",
    theme: "job",
    skill: "C2.ORI.04",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel1: "GL-C2-ORI-DIR-0002",
    gameLevel2: "GL-C2-ORI-DIR-0001",
    outcome: "Bé phân biệt hướng rẽ trái và rẽ phải khi tham gia giao thông.",
    mat: "Gậy chỉ huy giao thông, còi, mô hình xe",
  },
  {
    code: "LES-0071",
    title: "Bác nông dân gieo hạt: Đếm luống rau thẳng tắp",
    theme: "job",
    skill: "C1.CNT.02",
    age_min: 4,
    age_max: 5,
    what: ["cnt"],
    thinking: ["count", "observe"],
    gameLevel1: "GL-C1-CNT-STEP-0005",
    gameLevel2: "GL-C1-MEAS-SCALE-0001",
    outcome: "Bé đếm các cây rau theo thứ tự trên từng luống đất.",
    mat: "Khay cát mô phỏng luống rau, rau mầm",
  },
  {
    code: "LES-0072",
    title: "Chú phi công bay lượn: Định vị đường bay trên bầu trời",
    theme: "job",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["cls"],
    thinking: ["plan"],
    gameLevel1: "GL-C6-PLN-SCH-0002",
    gameLevel2: "GL-C6-PLN-SCH-0001",
    outcome: "Bé lập kế hoạch lộ trình bay tránh chướng ngại vật mây giông.",
    mat: "Mô hình máy bay, bản đồ bầu trời",
  },

  // W32 (Job)
  {
    code: "LES-0073",
    title: "Bác đầu bếp tài ba: Đo lường gia vị nấu súp",
    theme: "job",
    skill: "C1.MEAS.05",
    age_min: 5,
    age_max: 6,
    what: ["msr"],
    thinking: ["compare"],
    gameLevel1: "GL-C1-MEAS-CAP-0001",
    gameLevel2: "GL-C1-MEAS-CAP-0002",
    outcome: "Bé đong đếm thể tích nước và gia vị bằng cốc, thìa.",
    mat: "Nồi súp mini, cốc đong, thìa đong, nước sạch",
  },
  {
    code: "LES-0074",
    title: "Chú thợ xây khéo léo: Xếp gạch xây bức tường phẳng",
    theme: "job",
    skill: "C2.CON.04",
    age_min: 4,
    age_max: 5,
    what: ["shp"],
    thinking: ["observe"],
    gameLevel1: "GL-C2-CON-SOLID-0002",
    gameLevel2: "GL-C2-CON-SOLID-0001",
    outcome: "Bé nhận biết khối chữ nhật và xếp các viên gạch so le vững chắc.",
    mat: "Khối xốp hình viên gạch, bay nhựa",
  },
  {
    code: "LES-0075",
    title: "Cô họa sĩ nhí: Pha màu và phối tranh phong cảnh",
    theme: "job",
    skill: "C3.SRT.02",
    age_min: 5,
    age_max: 6,
    what: ["cls"],
    thinking: ["sort"],
    gameLevel1: "GL-C3-SRT-MULT-0002",
    gameLevel2: "GL-C3-SRT-MULT-0001",
    outcome: "Bé phân loại màu sắc và tạo màu mới từ hai màu cơ bản.",
    mat: "Bảng pha màu, cọ vẽ, màu nước an toàn",
  },

  // W33 (Homeland)
  {
    code: "LES-0076",
    title: "Lá cờ đỏ sao vàng: Khám phá biểu tượng Tổ quốc",
    theme: "homeland",
    skill: "C4.DET.03",
    age_min: 4,
    age_max: 5,
    what: ["cls"],
    thinking: ["observe"],
    gameLevel1: "GL-C4-DET-FIND-0002",
    gameLevel2: "GL-C4-DET-FIND-0001",
    outcome: "Bé quan sát và nhận biết đặc điểm lá cờ đỏ sao vàng Việt Nam.",
    mat: "Cờ Tổ quốc cầm tay, giấy màu đỏ vàng",
  },
  {
    code: "LES-0077",
    title: "Bản đồ Việt Nam hình chữ S: Khám phá 3 miền Bắc Trung Nam",
    theme: "homeland",
    skill: "C2.ORI.03",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel1: "GL-C2-ORI-POS-0002",
    gameLevel2: "GL-C2-ORI-POS-0001",
    outcome:
      "Bé nhận biết hình dáng đất nước và định vị miền Bắc ở trên, miền Nam ở dưới.",
    mat: "Bản đồ gỗ ghép hình Việt Nam",
  },
  {
    code: "LES-0078",
    title: "Hoa sen thắm ngát: Đếm cánh hoa và quan sát nhị vàng",
    theme: "homeland",
    skill: "C1.CNT.05",
    age_min: 4,
    age_max: 5,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-CARD-0004",
    gameLevel2: "GL-C1-MEAS-SCALE-0001",
    outcome: "Bé đếm số lượng cánh hoa sen và quan sát chi tiết bông sen.",
    mat: "Bông hoa sen tươi, đĩa gốm nhỏ",
  },

  // W34 (Homeland)
  {
    code: "LES-0079",
    title: "Thăm Lăng Bác Hồ: Đếm hàng tre xanh bát ngát",
    theme: "homeland",
    skill: "C1.CNT.06",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-CARD-0005",
    gameLevel2: "GL-C1-MEAS-SCALE-0001",
    outcome: "Bé xếp hàng cây tre theo thứ tự và đếm số lượng.",
    mat: "Mô hình cây tre nhựa, tranh Lăng Bác",
  },
  {
    code: "LES-0080",
    title: "Di tích Văn Miếu: Đếm bia tiến sĩ trên lưng rùa",
    theme: "homeland",
    skill: "C1.CNT.07",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-STEP-0007",
    gameLevel2: "GL-C1-CNT-STEP-0017",
    outcome: "Bé đếm số lượng cụ rùa đá trong sân Văn Miếu.",
    mat: "Mô hình cụ rùa đội bia tiến sĩ",
  },
  {
    code: "LES-0081",
    title: "Nhịp cầu quê hương: Đo chiều dài cây cầu bắc qua sông",
    theme: "homeland",
    skill: "C1.MEAS.01",
    age_min: 5,
    age_max: 6,
    what: ["msr"],
    thinking: ["compare"],
    gameLevel1: "GL-C1-MEAS-LEN-0001",
    gameLevel2: "GL-C1-MEAS-LEN-0002",
    outcome: "Bé đo chiều dài cây cầu bằng các đơn vị đo quy ước.",
    mat: "Mô hình cầu gỗ, que tính đo lường",
  },

  // W35 (Weather)
  {
    code: "LES-0082",
    title: "Nắng ấm ban mai: Đếm tia nắng chiếu qua kẽ lá",
    theme: "weather",
    skill: "C1.CNT.01",
    age_min: 3,
    age_max: 4,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-CARD-0001",
    gameLevel2: "GL-C1-PROB-BAL-0001",
    outcome: "Bé nhận biết biểu tượng ông mặt trời và đếm tia nắng.",
    mat: "Ông mặt trời bìa cứng, que kẹp gỗ làm tia nắng",
  },
  {
    code: "LES-0083",
    title: "Mưa rơi tí tách: Hứng giọt nước và đếm nhịp mưa rơi",
    theme: "weather",
    skill: "C4.SEN.03",
    age_min: 4,
    age_max: 5,
    what: ["lst"],
    thinking: ["recall"],
    gameLevel1: "GL-C4-SEN-SND-0001",
    gameLevel2: "GL-C4-SEN-SND-0002",
    outcome: "Bé lắng nghe âm thanh tiếng mưa và đếm nhịp rơi.",
    mat: "Ống xúc xắc tạo âm thanh hạt mưa, bát nước",
  },
  {
    code: "LES-0084",
    title: "Cầu vồng bảy sắc: Nhận biết thứ tự các dải màu",
    theme: "weather",
    skill: "C3.RULE.02",
    age_min: 4,
    age_max: 5,
    what: ["pat"],
    thinking: ["sequence"],
    gameLevel1: "GL-C3-RULE-PAT-0001",
    gameLevel2: "GL-C3-RULE-PAT-0002",
    outcome: "Bé nhận biết và sắp xếp các dải màu cầu vồng theo thứ tự.",
    mat: "Bộ dải màu cầu vồng bằng nỉ, thảm trắng",
  },

  // W36 (Weather)
  {
    code: "LES-0085",
    title: "Gió thổi lá bay: Quan sát hướng gió thổi",
    theme: "weather",
    skill: "C2.ORI.04",
    age_min: 4,
    age_max: 5,
    what: ["spt"],
    thinking: ["observe"],
    gameLevel1: "GL-C2-ORI-DIR-0002",
    gameLevel2: "GL-C2-ORI-DIR-0001",
    outcome: "Bé xác định hướng gió thổi sang bên trái hoặc bên phải.",
    mat: "Chong chóng giấy, quạt tay mini",
  },
  {
    code: "LES-0086",
    title: "Bốn mùa tươi đẹp: Phân loại đặc trưng Xuân - Hạ - Thu - Đông",
    theme: "weather",
    skill: "C3.SRT.02",
    age_min: 4,
    age_max: 5,
    what: ["cls"],
    thinking: ["sort"],
    gameLevel1: "GL-C3-SRT-MULT-0001",
    gameLevel2: "GL-C3-SRT-MULT-0002",
    outcome: "Bé phân loại trang phục và thời tiết theo 4 mùa trong năm.",
    mat: "4 khay tương ứng 4 mùa, thẻ tranh phân loại",
  },
  {
    code: "LES-0087",
    title: "Nhiệt kế thần kỳ: Nhận biết ngày nóng và ngày lạnh",
    theme: "weather",
    skill: "C5.DES.04",
    age_min: 5,
    age_max: 6,
    what: ["cls"],
    thinking: ["infer"],
    gameLevel1: "GL-C5-DES-RSN-0001",
    gameLevel2: "GL-C5-DES-RSN-0002",
    outcome: "Bé quan sát cột nhiệt độ và đưa ra nhận xét nóng hay lạnh.",
    mat: "Nhiệt kế đồ chơi có cột dải màu điều chỉnh",
  },

  // W37 (Ocean)
  {
    code: "LES-0088",
    title: "Tàu ngầm lặn biển: Khám phá độ sâu đại dương",
    theme: "ocean",
    skill: "C1.MEAS.02",
    age_min: 5,
    age_max: 6,
    what: ["msr"],
    thinking: ["compare"],
    gameLevel1: "GL-C1-MEAS-HGT-0002",
    gameLevel2: "GL-C1-MEAS-HGT-0001",
    outcome: "Bé so sánh độ sâu của các tầng nước biển.",
    mat: "Thước dây đo chiều sâu, mô hình tàu ngầm",
  },
  {
    code: "LES-0089",
    title: "Đàn cá hề bơi lội: Tách gộp số lượng cá trong rạn san hô",
    theme: "ocean",
    skill: "C1.PROB.01",
    age_min: 4,
    age_max: 5,
    what: ["ops"],
    thinking: ["infer", "count"],
    gameLevel1: "GL-C1-PROB-SEP-0001",
    gameLevel2: "GL-C1-PROB-SEP-0002",
    outcome: "Bé tách đàn cá 6 con thành 2 nhóm nhỏ vào 2 hốc đá.",
    mat: "Mô hình rạn san hô, 6 chú cá hề mini",
  },
  {
    code: "LES-0090",
    title: "Thu thập vỏ sò: Phân loại theo hình dạng và vân sọc",
    theme: "ocean",
    skill: "C3.SRT.01",
    age_min: 4,
    age_max: 5,
    what: ["cls"],
    thinking: ["sort"],
    gameLevel1: "GL-C3-SRT-PAIR-0001",
    gameLevel2: "GL-C3-SRT-PAIR-0002",
    outcome: "Bé phân loại vỏ sò xoắn ốc và vỏ sò dẹp phẳng.",
    mat: "Khay cát biển, 10 chiếc vỏ sò thật",
  },

  // W38 (Ocean)
  {
    code: "LES-0091",
    title: "Đua thuyền buồm: Hướng gió đẩy thuyền đi nhanh",
    theme: "ocean",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["flw"],
    thinking: ["plan"],
    gameLevel1: "GL-C6-PLN-SCH-0001",
    gameLevel2: "GL-C6-PLN-SCH-0002",
    outcome: "Bé điều chỉnh hướng buồm để thuyền về đích đúng lộ trình.",
    mat: "Chậu nước lớn, thuyền buồm giấy",
  },
  {
    code: "LES-0092",
    title: "Chú bạch tuộc thông minh: Đếm 8 xúc tu dài",
    theme: "ocean",
    skill: "C1.CNT.08",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-STEP-0008",
    gameLevel2: "GL-C1-CNT-STEP-0018",
    outcome: "Bé đếm đủ 8 xúc tu bạch tuộc xòe đều.",
    mat: "Đất nặn, mắt thần kỳ",
  },
  {
    code: "LES-0093",
    title: "Đáy biển sâu huyền bí: Tìm kiếm sinh vật phát sáng",
    theme: "ocean",
    skill: "C4.DET.03",
    age_min: 5,
    age_max: 6,
    what: ["cls"],
    thinking: ["observe"],
    gameLevel1: "GL-C4-DET-FIND-0001",
    gameLevel2: "GL-C4-DET-FIND-0002",
    outcome: "Bé dùng đèn pin tìm kiếm các sinh vật phát quang ẩn nấp.",
    mat: "Phòng rèm tối, thẻ tranh dạ quang",
  },

  // W39 (Space)
  {
    code: "LES-0094",
    title: "Tên lửa phóng vào không gian: Đếm ngược 10, 9, 8...",
    theme: "space",
    skill: "C1.CNT.04",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count", "sequence"],
    gameLevel1: "GL-C1-CNT-BCK-0001",
    gameLevel2: "GL-C1-CNT-BCK-0002",
    outcome: "Bé đếm lùi thành thạo từ 10 về 0 để phóng tên lửa.",
    mat: "Mô hình tên lửa xốp, bệ phóng",
  },
  {
    code: "LES-0095",
    title: "Mặt trăng tròn khuyết: Trình tự các pha của mặt trăng",
    theme: "space",
    skill: "C3.RULE.02",
    age_min: 5,
    age_max: 6,
    what: ["pat"],
    thinking: ["sequence"],
    gameLevel1: "GL-C3-RULE-PAT-0001",
    gameLevel2: "GL-C3-RULE-PAT-0002",
    outcome: "Bé sắp xếp chu kỳ biến đổi từ trăng lưỡi liềm đến trăng rằm.",
    mat: "Bộ thẻ pha mặt trăng, bánh quy tròn",
  },
  {
    code: "LES-0096",
    title: "Hệ mặt trời kỳ thú: Sắp xếp các hành tinh theo khoảng cách",
    theme: "space",
    skill: "C1.MEAS.01",
    age_min: 5,
    age_max: 6,
    what: ["msr"],
    thinking: ["compare"],
    gameLevel1: "GL-C1-MEAS-LEN-0002",
    gameLevel2: "GL-C1-MEAS-LEN-0001",
    outcome: "Bé sắp xếp các hành tinh theo khoảng cách gần/xa mặt trời.",
    mat: "Mô hình 8 hành tinh hệ mặt trời",
  },

  // W40 (Space)
  {
    code: "LES-0097",
    title: "Phi hành gia tí hon: Vượt chướng ngại vật thiên thạch",
    theme: "space",
    skill: "C2.MAZ.01",
    age_min: 5,
    age_max: 6,
    what: ["spt"],
    thinking: ["plan"],
    gameLevel1: "GL-C2-MAZ-PATH-0002",
    gameLevel2: "GL-C2-MAZ-PATH-0001",
    outcome: "Bé tìm đường qua mê cung thiên thạch để về tàu vũ trụ.",
    mat: "Sa bàn không gian vũ trụ, phi thuyền mini",
  },
  {
    code: "LES-0098",
    title: "Chòm sao lấp lánh: Nối các điểm tạo hình con gấu",
    theme: "space",
    skill: "C2.GEO.02",
    age_min: 5,
    age_max: 6,
    what: ["shp"],
    thinking: ["compare"],
    gameLevel1: "GL-C2-GEO-MATCH-0003",
    gameLevel2: "GL-C2-CON-SOLID-0001",
    outcome: "Bé dùng que nối các ngôi sao tạo thành chòm sao hình học.",
    mat: "Que dạ quang, bảng chấm sao",
  },
  {
    code: "LES-0099",
    title: "Trái đất thân yêu: Phân biệt đại dương xanh và lục địa",
    theme: "space",
    skill: "C3.SRT.02",
    age_min: 5,
    age_max: 6,
    what: ["cls"],
    thinking: ["sort"],
    gameLevel1: "GL-C3-SRT-MULT-0001",
    gameLevel2: "GL-C3-SRT-MULT-0002",
    outcome: "Bé phân biệt mảng màu nước biển và đất liền trên địa cầu.",
    mat: "Quả địa cầu mini, sticker con vật trên cạn/dưới nước",
  },

  // W41 (School)
  {
    code: "LES-0122",
    title: "Chuẩn bị hành trang vào lớp 1: Đếm và sắp cặp sách",
    theme: "school",
    skill: "C1.CNT.10",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-CNT-STEP-0010",
    gameLevel2: "GL-C1-CNT-STEP-0020",
    outcome: "Bé đếm đủ 10 món đồ dùng học tập xếp vào cặp.",
    mat: "Cặp sách tiểu học, vở, bút chì, gôm tẩy",
  },
  {
    code: "LES-0123",
    title: "Bảng chữ số diệu kỳ: Nối chữ số với lượng đồ vật",
    theme: "school",
    skill: "C1.NREC.01",
    age_min: 5,
    age_max: 6,
    what: ["cnt"],
    thinking: ["count"],
    gameLevel1: "GL-C1-NREC-CARD-0003",
    gameLevel2: "GL-C1-CNT-STEP-0020",
    outcome: "Bé gắn thẻ số 1-10 tương ứng với các nhóm đồ chơi.",
    mat: "Thẻ chữ số gỗ 1-10, rổ đồ chơi",
  },
  {
    code: "LES-0124",
    title: "Chiếc đồng hồ thần kỳ: Đọc giờ đúng sinh hoạt",
    theme: "school",
    skill: "C1.MEAS.13",
    age_min: 5,
    age_max: 6,
    what: ["msr"],
    thinking: ["sequence"],
    gameLevel1: "GL-C1-MEAS-CLK-0001",
    gameLevel2: "GL-C1-MEAS-CLK-0002",
    outcome:
      "Bé nhận biết giờ đúng trên mặt đồng hồ và gắn với hoạt động trong ngày.",
    mat: "Đồng hồ kim xoay đồ chơi, thẻ sinh hoạt",
  },

  // W42 (Graduation)
  {
    code: "LES-0125",
    title: "Trò chơi tư duy tổng hợp: Chinh phục đỉnh núi tri thức",
    theme: "nature",
    skill: "C6.PLN.02",
    age_min: 5,
    age_max: 6,
    what: ["flw"],
    thinking: ["plan"],
    gameLevel1: "GL-C6-PLN-SCH-0001",
    gameLevel2: "GL-C6-PLN-SCH-0002",
    outcome: "Bé vượt qua 4 trạm câu đố logic để lên đỉnh núi.",
    mat: "Sa bàn ngọn núi, cờ chiến thắng",
  },
  {
    code: "LES-0126",
    title: "Ngày hội giao lưu tài năng toán học mầm non",
    theme: "art",
    skill: "C3.MTX.01",
    age_min: 5,
    age_max: 6,
    what: ["pat"],
    thinking: ["infer"],
    gameLevel1: "GL-C3-MTX-GRID-0002",
    gameLevel2: "GL-C3-MTX-GRID-0001",
    outcome: "Bé giải ma trận hình ảnh và tự tin giải thích kết quả.",
    mat: "Bảng ma trận 3x3, các thẻ hình puzzle",
  },
  {
    code: "LES-0127",
    title: "Lễ tốt nghiệp mầm non: Nhìn lại hành trình 42 tuần rực rỡ",
    theme: "school",
    skill: "C6.PLN.03",
    age_min: 5,
    age_max: 6,
    what: ["ops"],
    thinking: ["plan"],
    gameLevel1: "GL-C6-PLN-FIN-0002",
    gameLevel2: "GL-C6-PLN-FIN-0001",
    outcome: "Bé tổng kết các kỹ năng đã học và tự tin bước vào lớp 1.",
    mat: "Mũ cử nhân nhí, giấy chứng nhận thông thái",
  },
];

// Activity code bắt đầu từ ACT-0501 (định dạng ACT-xxxx, 4 chữ số, không đụng ai)
let actCounter = 501;

const lessons = lessonDefs.map((def, idx) => {
  const act1Code = `ACT-${String(actCounter++).padStart(4, "0")}`;
  const act2Code = `ACT-${String(actCounter++).padStart(4, "0")}`;
  const act3Code = `ACT-${String(actCounter++).padStart(4, "0")}`;

  return {
    kind: "lesson",
    header: {
      code: def.code,
      content_version: 1,
      title: def.title,
      guide: {
        outcome: def.outcome,
        preparation: [
          "Chuẩn bị không gian thoáng mát, sạch sẽ cho bé hoạt động.",
          `Chuẩn bị dụng cụ: ${def.mat}.`,
        ],
        opening: `Hôm nay mẹ và bé cùng tham gia bài học "${def.title}" nhé!`,
        if_child_succeeds:
          "Khen ngợi nỗ lực của bé và khuyến khích bé thử thách với bài toán nâng cao.",
        if_child_needs_help:
          "Mẹ hướng dẫn từng bước nhỏ, thao tác mẫu chậm rãi và khích lệ bé tự tin làm lại.",
      },
      target_age_min: def.age_min,
      target_age_max: def.age_max,
      estimated_minutes: 20,
      materials: def.mat,
      warm_up: "Khởi động: Cùng vận động nhẹ nhàng theo nhạc chủ đề 3 phút.",
      reflection: "Đúc kết: Bé nhắc lại điều thú vị nhất vừa học được hôm nay.",
      assessment: def.outcome,
      extension:
        "Bé áp dụng kiến thức vừa học vào các tình huống sinh hoạt thực tế trong gia đình.",
      access_tier: idx % 3 === 0 ? "free" : "standard",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      activity_codes: [act1Code, act2Code, act3Code],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };
});

let actGenCounter = 501;
const activities = lessonDefs.flatMap((def, idx) => {
  const act1Code = `ACT-${String(actGenCounter++).padStart(4, "0")}`;
  const act2Code = `ACT-${String(actGenCounter++).padStart(4, "0")}`;
  const act3Code = `ACT-${String(actGenCounter++).padStart(4, "0")}`;

  const act1 = {
    kind: "activity",
    header: {
      code: act1Code,
      content_version: 1,
      activity_kind: idx % 2 === 0 ? "manipulative" : "movement",
      title: `Khám phá: ${def.title}`,
      instruction: {
        preparation: `Chuẩn bị dụng cụ: ${def.mat}.`,
        steps: [
          {
            instruction:
              "Người lớn giới thiệu đồ dùng và làm mẫu thao tác chậm rãi.",
            say_to_child: '"Con hãy cùng mẹ khám phá món đồ đặc biệt này nhé!"',
          },
          {
            instruction: "Trẻ tự tay thao tác với vật mẫu theo chỉ dẫn.",
            say_to_child: '"Bây giờ con hãy thử tự làm xem nào!"',
          },
        ],
        easier: "Giảm bớt số lượng vật thể và làm mẫu lại cùng bé.",
        harder: "Tăng thêm số lượng vật thể hoặc yêu cầu bé giải thích lý do.",
      },
      materials: def.mat,
      estimated_minutes: 8,
      access_tier: "free",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };

  const act2 = {
    kind: "activity",
    header: {
      code: act2Code,
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: def.gameLevel1,
      title: `Thử thách số 1: ${def.title}`,
      instruction: {
        preparation: "Mở màn hình trò chơi thứ nhất trên ứng dụng.",
        steps: [
          {
            instruction: "Bé chạm và tương tác với các hình ảnh trên màn hình.",
            say_to_child: '"Bé hãy làm thử thách trên màn hình nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };

  const act3 = {
    kind: "activity",
    header: {
      code: act3Code,
      content_version: 1,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: def.gameLevel2,
      title: `Thử thách số 2: ${def.title}`,
      instruction: {
        preparation: "Mở màn hình trò chơi củng cố trên ứng dụng.",
        steps: [
          {
            instruction: "Bé giải câu đố tư duy nâng cao trên màn hình.",
            say_to_child: '"Bé hãy hoàn thành màn chơi củng cố này nhé!"',
          },
        ],
        easier: "Bật chế độ hướng dẫn bàn tay ảo nếu bé cần trợ giúp.",
        harder: "Thử thách bé hoàn thành với tốc độ nhanh hơn.",
      },
      materials: "Thiết bị màn hình cảm ứng",
      estimated_minutes: 6,
      access_tier: "free",
      skill_codes: [def.skill],
      learning_objective_codes: [`LO-${def.skill}-01`],
      what_tags: def.what,
      thinking_tags: def.thinking,
      theme_tag: def.theme,
      origin: "human",
      authored_in: "repo_seed",
    },
  };

  return [act1, act2, act3];
});

fs.writeFileSync(
  "./packages/db/src/seed-content/lessons/batch-pedagogy-45.ts",
  `import type { LessonSeed } from "#src/seed-content/types";

/**
 * Task #192: Seeder cho 45 bài học bổ sung đạt sàn 126 tiết (BR-LCD-01).
 */
export const PEDAGOGY_LESSONS_45: LessonSeed[] = ${JSON.stringify(lessons, null, 2)};
`
);

fs.writeFileSync(
  "./packages/db/src/seed-content/activities/pedagogy-activities-45.ts",
  `import type { ActivitySeed } from "#src/seed-content/types";

/**
 * Task #192: Seeder cho 135 hoạt động bổ sung cho 45 bài học.
 */
export const PEDAGOGY_ACTIVITIES_45: ActivitySeed[] = ${JSON.stringify(activities, null, 2)};
`
);

console.log("✓ Standardized batch-pedagogy-45.ts (45 lessons)");
console.log("✓ Standardized pedagogy-activities-45.ts (135 activities)");
