import type { ContentSeed } from "@mindkid/content";

/**
 * Batch: SEED-GT032
 * So lượng chất lỏng (pour-quantity)
 * 10 levels, GT-032, legacy_v1_ref: "D5-09", band 5-6, themes: home, school, food, farm, nature, festival
 */
export const SEED_GT032: ContentSeed<unknown, unknown>[] = [
  {
    header: {
      code: "GL-C1-LIQ-POUR-0001",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Tìm cốc nhiều nước hơn (2 cốc chuẩn)",
      instruction: "Bé chạm vào cốc có nhiều nước hơn nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.MEAS.05"],
      learning_objective_codes: ["LO-C1.MEAS.05-01"],
      what_tags: ["quantity"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có nhiều nước hơn nhé!",
      question_type: "more",
      conservation_trap: false,
      cups: [
        {
          cup_id: "cup_1",
          shape: "standard",
          capacity_units: 6,
          fill_units: 2,
          color: "sky",
        },
        {
          cup_id: "cup_2",
          shape: "standard",
          capacity_units: 6,
          fill_units: 5,
          color: "sky",
        },
      ],
    },
    difficulty_params: {
      cup_count: 2,
      level_steps: 6,
      conservation_trap: false,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0002",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Tìm cốc ít nước hơn (2 cốc chuẩn)",
      instruction: "Bé chạm vào cốc có ít nước hơn nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C1.MEAS.05"],
      learning_objective_codes: ["LO-C1.MEAS.05-01"],
      what_tags: ["quantity"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có ít nước hơn nhé!",
      question_type: "less",
      conservation_trap: false,
      cups: [
        {
          cup_id: "cup_1",
          shape: "standard",
          capacity_units: 6,
          fill_units: 4,
          color: "mint",
        },
        {
          cup_id: "cup_2",
          shape: "standard",
          capacity_units: 6,
          fill_units: 1,
          color: "mint",
        },
      ],
    },
    difficulty_params: {
      cup_count: 2,
      level_steps: 6,
      conservation_trap: false,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0003",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Bẫy bảo toàn Piaget: Cốc cao hẹp và thấp rộng (mức 4)",
      instruction: "Bé chọn các cốc có lượng nước bằng nhau nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MEAS.05"],
      learning_objective_codes: ["LO-C1.MEAS.05-01"],
      what_tags: ["quantity"],
      thinking_tags: ["infer", "compare"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có lượng nước bằng nhau nhé!",
      question_type: "same",
      conservation_trap: true,
      cups: [
        {
          cup_id: "cup_tall",
          shape: "narrow_tall",
          capacity_units: 8,
          fill_units: 4,
          color: "berry",
        },
        {
          cup_id: "cup_wide",
          shape: "wide_short",
          capacity_units: 8,
          fill_units: 4,
          color: "berry",
        },
        {
          cup_id: "cup_small",
          shape: "standard",
          capacity_units: 8,
          fill_units: 2,
          color: "berry",
        },
      ],
    },
    difficulty_params: {
      cup_count: 3,
      level_steps: 8,
      conservation_trap: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0004",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Tìm cốc nhiều nước nhất giữa 3 cốc",
      instruction: "Bé chạm vào cốc có nhiều nước nhất nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MEAS.05"],
      learning_objective_codes: ["LO-C1.MEAS.05-01"],
      what_tags: ["quantity"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có nhiều nước nhất nhé!",
      question_type: "more",
      conservation_trap: false,
      cups: [
        {
          cup_id: "cup_1",
          shape: "standard",
          capacity_units: 8,
          fill_units: 3,
          color: "sky",
        },
        {
          cup_id: "cup_2",
          shape: "narrow_tall",
          capacity_units: 8,
          fill_units: 7,
          color: "sky",
        },
        {
          cup_id: "cup_3",
          shape: "wide_short",
          capacity_units: 8,
          fill_units: 5,
          color: "sky",
        },
      ],
    },
    difficulty_params: {
      cup_count: 3,
      level_steps: 8,
      conservation_trap: false,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0005",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Tìm cốc ít nước nhất giữa 3 cốc",
      instruction: "Bé chạm vào cốc có ít nước nhất nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C1.MEAS.05"],
      learning_objective_codes: ["LO-C1.MEAS.05-01"],
      what_tags: ["quantity"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "nature",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có ít nước nhất nhé!",
      question_type: "less",
      conservation_trap: false,
      cups: [
        {
          cup_id: "cup_1",
          shape: "fluted",
          capacity_units: 10,
          fill_units: 6,
          color: "amber",
        },
        {
          cup_id: "cup_2",
          shape: "wide_short",
          capacity_units: 10,
          fill_units: 2,
          color: "amber",
        },
        {
          cup_id: "cup_3",
          shape: "narrow_tall",
          capacity_units: 10,
          fill_units: 8,
          color: "amber",
        },
      ],
    },
    difficulty_params: {
      cup_count: 3,
      level_steps: 10,
      conservation_trap: false,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0006",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Bẫy bảo toàn Piaget: Cốc loe vs cốc chuẩn (mức 5)",
      instruction: "Bé tìm hai cốc có lượng nước bằng nhau nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "login",
      skill_codes: ["C1.MEAS.06"],
      learning_objective_codes: ["LO-C1.MEAS.06-01"],
      what_tags: ["quantity"],
      thinking_tags: ["infer", "compare"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có lượng nước bằng nhau nhé!",
      question_type: "same",
      conservation_trap: true,
      cups: [
        {
          cup_id: "cup_fluted",
          shape: "fluted",
          capacity_units: 10,
          fill_units: 5,
          color: "mint",
        },
        {
          cup_id: "cup_standard",
          shape: "standard",
          capacity_units: 10,
          fill_units: 5,
          color: "mint",
        },
        {
          cup_id: "cup_other",
          shape: "narrow_tall",
          capacity_units: 10,
          fill_units: 8,
          color: "mint",
        },
      ],
    },
    difficulty_params: {
      cup_count: 3,
      level_steps: 10,
      conservation_trap: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0007",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "So sánh nước trong 4 cốc khác hình",
      instruction: "Bé chạm vào chiếc cốc nhiều nước nhất nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "login",
      skill_codes: ["C1.MEAS.06"],
      learning_objective_codes: ["LO-C1.MEAS.06-01"],
      what_tags: ["quantity"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có nhiều nước nhất nhé!",
      question_type: "more",
      conservation_trap: false,
      cups: [
        {
          cup_id: "cup_1",
          shape: "standard",
          capacity_units: 10,
          fill_units: 3,
          color: "sky",
        },
        {
          cup_id: "cup_2",
          shape: "narrow_tall",
          capacity_units: 10,
          fill_units: 9,
          color: "sky",
        },
        {
          cup_id: "cup_3",
          shape: "wide_short",
          capacity_units: 10,
          fill_units: 6,
          color: "sky",
        },
        {
          cup_id: "cup_4",
          shape: "fluted",
          capacity_units: 10,
          fill_units: 4,
          color: "sky",
        },
      ],
    },
    difficulty_params: {
      cup_count: 4,
      level_steps: 10,
      conservation_trap: false,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0008",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Bẫy bảo toàn Piaget: 4 cốc nước sắc màu (mức 6)",
      instruction: "Bé chọn các cốc có lượng nước bằng nhau nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "login",
      skill_codes: ["C1.MEAS.06"],
      learning_objective_codes: ["LO-C1.MEAS.06-01"],
      what_tags: ["quantity"],
      thinking_tags: ["infer", "compare"],
      theme_tag: "food",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có lượng nước bằng nhau nhé!",
      question_type: "same",
      conservation_trap: true,
      cups: [
        {
          cup_id: "cup_1",
          shape: "narrow_tall",
          capacity_units: 10,
          fill_units: 6,
          color: "berry",
        },
        {
          cup_id: "cup_2",
          shape: "wide_short",
          capacity_units: 10,
          fill_units: 6,
          color: "berry",
        },
        {
          cup_id: "cup_3",
          shape: "standard",
          capacity_units: 10,
          fill_units: 3,
          color: "berry",
        },
        {
          cup_id: "cup_4",
          shape: "fluted",
          capacity_units: 10,
          fill_units: 9,
          color: "berry",
        },
      ],
    },
    difficulty_params: {
      cup_count: 4,
      level_steps: 10,
      conservation_trap: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0009",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Tìm cốc ít nước nhất giữa 4 cốc",
      instruction: "Bé chạm vào cốc có ít nước nhất nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "login",
      skill_codes: ["C1.MEAS.06"],
      learning_objective_codes: ["LO-C1.MEAS.06-01"],
      what_tags: ["quantity"],
      thinking_tags: ["compare", "observe"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có ít nước nhất nhé!",
      question_type: "less",
      conservation_trap: false,
      cups: [
        {
          cup_id: "cup_1",
          shape: "wide_short",
          capacity_units: 10,
          fill_units: 8,
          color: "mint",
        },
        {
          cup_id: "cup_2",
          shape: "narrow_tall",
          capacity_units: 10,
          fill_units: 10,
          color: "mint",
        },
        {
          cup_id: "cup_3",
          shape: "standard",
          capacity_units: 10,
          fill_units: 2,
          color: "mint",
        },
        {
          cup_id: "cup_4",
          shape: "fluted",
          capacity_units: 10,
          fill_units: 5,
          color: "mint",
        },
      ],
    },
    difficulty_params: {
      cup_count: 4,
      level_steps: 10,
      conservation_trap: false,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
  {
    header: {
      code: "GL-C1-LIQ-POUR-0010",
      legacy_v1_ref: "D5-09",
      content_version: 1,
      template_code: "GT-032",
      title: "Bẫy bảo toàn Piaget nâng cao: 4 cốc nước quả",
      instruction: "Bé tìm hai cốc có lượng nước quả bằng nhau nhé.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "login",
      skill_codes: ["C1.MEAS.06"],
      learning_objective_codes: ["LO-C1.MEAS.06-01"],
      what_tags: ["quantity"],
      thinking_tags: ["infer", "compare"],
      theme_tag: "festival",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      prompt: "Bé hãy chạm vào chiếc cốc có lượng nước bằng nhau nhé!",
      question_type: "same",
      conservation_trap: true,
      cups: [
        {
          cup_id: "cup_1",
          shape: "fluted",
          capacity_units: 10,
          fill_units: 7,
          color: "amber",
        },
        {
          cup_id: "cup_2",
          shape: "narrow_tall",
          capacity_units: 10,
          fill_units: 7,
          color: "amber",
        },
        {
          cup_id: "cup_3",
          shape: "wide_short",
          capacity_units: 10,
          fill_units: 4,
          color: "amber",
        },
        {
          cup_id: "cup_4",
          shape: "standard",
          capacity_units: 10,
          fill_units: 10,
          color: "amber",
        },
      ],
    },
    difficulty_params: {
      cup_count: 4,
      level_steps: 10,
      conservation_trap: true,
      allow_retry: true,
      hint_after_ms: 8000,
    },
  },
];
