/**
 * Spec sở hữu: docs/specs/05-content/lesson-template-variety.md
 * Rule sở hữu: BR-LTV-01..08
 *
 * Danh sách activities kiểu digital_game nối bài học vào các game level.
 */

import type { ActivitySeed } from "#src/seed-content/types";

interface DigitalGameDef {
  code: string;
  title: string;
  gameLevelCode: string;
  skillCode: string;
  loCode: string;
  whatTags: string[];
  thinkingTags: string[];
  themeTag: string;
  sayToChild: string;
}

const DIGITAL_GAMES: DigitalGameDef[] = [
  // LES-0001 (C1)
  {
    code: "ACT-0201",
    title: "Trò chơi số: Đếm số táo đỏ",
    gameLevelCode: "GL-C1-CNT-CARD-0001",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "farm",
    sayToChild: '"Con hãy chạm vào các quả táo để đếm nhé!"',
  },
  {
    code: "ACT-0202",
    title: "Trò chơi số: Xếp táo vào hộp",
    gameLevelCode: "GL-C1-SORT-BOX-0006",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["sorting"],
    themeTag: "farm",
    sayToChild: '"Bé kéo táo vào đúng chiếc hộp nhé!"',
  },

  // LES-0002 (C1)
  {
    code: "ACT-0203",
    title: "Trò chơi số: Đếm vịt bơi ao",
    gameLevelCode: "GL-C1-CNT-CARD-0002",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "nature",
    sayToChild: '"Bé đếm xem có bao nhiêu chú vịt nào!"',
  },
  {
    code: "ACT-0204",
    title: "Trò chơi số: So sánh số lượng vịt",
    gameLevelCode: "GL-C1-CMP-NUM-0010",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-02",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "nature",
    sayToChild: '"Bé tìm nhóm vịt có số lượng nhiều hơn nhé!"',
  },

  // LES-0003 (C1)
  {
    code: "ACT-0205",
    title: "Trò chơi số: Đếm cá dưới nước",
    gameLevelCode: "GL-C1-CNT-CARD-0003",
    skillCode: "C1.CNT.02",
    loCode: "LO-C1.CNT.02-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "water",
    sayToChild: '"Con hãy đếm các chú cá đang bơi nhé!"',
  },
  {
    code: "ACT-0206",
    title: "Trò chơi số: Dãy số cá bơi",
    gameLevelCode: "GL-C1-SEQ-PAT-0014",
    skillCode: "C1.CNT.02",
    loCode: "LO-C1.CNT.02-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "water",
    sayToChild: '"Bé xếp đàn cá theo thứ tự từ nhỏ tới lớn nhé!"',
  },

  // LES-0004 (C2)
  {
    code: "ACT-0207",
    title: "Trò chơi số: Bạn gấu tìm hình",
    gameLevelCode: "GL-C2-SHP-CARD-0001",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["shape_recognition"],
    themeTag: "family",
    sayToChild: '"Bé giúp bạn gấu tìm hình tròn nhé!"',
  },
  {
    code: "ACT-0208",
    title: "Trò chơi số: Gấu trốn vị trí",
    gameLevelCode: "GL-C2-POS-LOC-0004",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["spatial_relations"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "family",
    sayToChild: '"Bé tìm bạn gấu đang ở trên hay ở dưới ghế nhé!"',
  },

  // LES-0005 (C3)
  {
    code: "ACT-0209",
    title: "Trò chơi số: Quy luật màu sắc",
    gameLevelCode: "GL-C3-PAT-CARD-0001",
    skillCode: "C3.PAT.01",
    loCode: "LO-C3.PAT.01-01",
    whatTags: ["patterns"],
    thinkingTags: ["pattern_recognition"],
    themeTag: "art",
    sayToChild: '"Bé chọn màu sắc tiếp theo cho chuỗi hạt nhé!"',
  },
  {
    code: "ACT-0210",
    title: "Trò chơi số: Phân loại khối màu",
    gameLevelCode: "GL-C3-CLS-BOX-0004",
    skillCode: "C3.PAT.01",
    loCode: "LO-C3.PAT.01-01",
    whatTags: ["classification"],
    thinkingTags: ["sorting"],
    themeTag: "art",
    sayToChild: '"Bé xếp các khối đỏ và xanh vào đúng hộp nhé!"',
  },

  // LES-0006 (C4)
  {
    code: "ACT-0211",
    title: "Trò chơi số: Quan sát đồ vật",
    gameLevelCode: "GL-C4-OBS-CARD-0001",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["observation_details"],
    thinkingTags: ["observation"],
    themeTag: "household",
    sayToChild: '"Bé tìm món đồ dùng học tập quen thuộc nhé!"',
  },
  {
    code: "ACT-0212",
    title: "Trò chơi số: Phân loại nặng nhẹ",
    gameLevelCode: "GL-C4-DIF-BOX-0004",
    skillCode: "C4.WGT.01",
    loCode: "LO-C4.WGT.01-01",
    whatTags: ["visual_discrimination"],
    thinkingTags: ["sorting"],
    themeTag: "household",
    sayToChild: '"Bé phân loại đồ vật nặng và nhẹ vào hai hộp nhé!"',
  },

  // LES-0007 (C1)
  {
    code: "ACT-0213",
    title: "Trò chơi số: Đếm que kem mát lạnh",
    gameLevelCode: "GL-C1-CNT-CARD-0004",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "food",
    sayToChild: '"Bé đếm xem có mấy que kem dâu nào!"',
  },
  {
    code: "ACT-0214",
    title: "Trò chơi số: Đặt kem vào tủ lạnh",
    gameLevelCode: "GL-C1-POS-LOC-0017",
    skillCode: "C1.CNT.03",
    loCode: "LO-C1.CNT.03-01",
    whatTags: ["spatial_concept"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "food",
    sayToChild: '"Bé xếp kem vào ngăn trên cùng của tủ lạnh nhé!"',
  },

  // LES-0008 (C1)
  {
    code: "ACT-0215",
    title: "Trò chơi số: Đếm bóng bay rực rỡ",
    gameLevelCode: "GL-C1-CNT-CARD-0005",
    skillCode: "C1.CNT.03",
    loCode: "LO-C1.CNT.03-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "household",
    sayToChild: '"Con hãy đếm các chùm bóng bay nhé!"',
  },
  {
    code: "ACT-0216",
    title: "Trò chơi số: Nhận diện nhanh số bóng",
    gameLevelCode: "GL-C1-SUB-FAST-0019",
    skillCode: "C1.NREC.05",
    loCode: "LO-C1.NREC.05-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "household",
    sayToChild: '"Bé chọn thật nhanh số bóng vừa bay lên nhé!"',
  },

  // LES-0009 (C1)
  {
    code: "ACT-0217",
    title: "Trò chơi số: Phân loại số lượng hạt",
    gameLevelCode: "GL-C1-SORT-BOX-0007",
    skillCode: "C1.NREC.05",
    loCode: "LO-C1.NREC.05-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["sorting"],
    themeTag: "farm",
    sayToChild: '"Bé xếp các nhóm hạt giống vào giỏ tương ứng nhé!"',
  },
  {
    code: "ACT-0218",
    title: "Trò chơi số: Biểu tượng số lượng hạt",
    gameLevelCode: "GL-C1-SUB-SYM-0031",
    skillCode: "C1.NREC.09",
    loCode: "LO-C1.NREC.09-01",
    whatTags: ["cnt", "alg"],
    thinkingTags: ["infer", "count"],
    themeTag: "farm",
    sayToChild: '"Bé tìm số lượng hạt bí ẩn nhé!"',
  },

  // LES-0010 (C1)
  {
    code: "ACT-0219",
    title: "Trò chơi số: Ghép đôi số lượng",
    gameLevelCode: "GL-C1-CMP-NUM-0011",
    skillCode: "C1.CNT.11",
    loCode: "LO-C1.CNT.11-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "school",
    sayToChild: '"Bé nối các nhóm có cùng số lượng nhé!"',
  },
  {
    code: "ACT-0220",
    title: "Trò chơi số: Cân bằng số lượng",
    gameLevelCode: "GL-C1-BAL-SCL-0034",
    skillCode: "C1.CNT.11",
    loCode: "LO-C1.CNT.11-01",
    whatTags: ["cnt", "mea"],
    thinkingTags: ["compare", "observe"],
    themeTag: "school",
    sayToChild: '"Bé đặt thêm quả để hai đĩa cân bằng nhau nhé!"',
  },

  // LES-0011 (C1)
  {
    code: "ACT-0221",
    title: "Trò chơi số: Dãy số tăng dần",
    gameLevelCode: "GL-C1-SEQ-PAT-0015",
    skillCode: "C1.CNT.03",
    loCode: "LO-C1.CNT.03-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "school",
    sayToChild: '"Bé sắp xếp các số theo thứ tự 1, 2, 3 nhé!"',
  },
  {
    code: "ACT-0222",
    title: "Trò chơi số: Xoay kim đồng hồ số",
    gameLevelCode: "GL-C1-CLK-HND-0037",
    skillCode: "C1.NREC.09",
    loCode: "LO-C1.NREC.09-01",
    whatTags: ["cnt", "tim"],
    thinkingTags: ["shift", "observe"],
    themeTag: "household",
    sayToChild: '"Bé chỉnh kim đồng hồ đến đúng số nhé!"',
  },

  // LES-0012 (C1)
  {
    code: "ACT-0223",
    title: "Trò chơi số: Đếm ngón tay bạn nhỏ",
    gameLevelCode: "GL-C1-CNT-CARD-0001",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé đếm số ngón tay đang giơ lên nhé!"',
  },
  {
    code: "ACT-0224",
    title: "Trò chơi số: Ghi nhớ chớp nhoáng ngón tay",
    gameLevelCode: "GL-C1-MEM-FLASH-0040",
    skillCode: "C1.CNT.11",
    loCode: "LO-C1.CNT.11-01",
    whatTags: ["cnt", "mem"],
    thinkingTags: ["recall", "count"],
    themeTag: "school",
    sayToChild: '"Bé nhớ lại xem bạn giơ mấy ngón tay nhé!"',
  },

  // LES-0013 (C2)
  {
    code: "ACT-0225",
    title: "Trò chơi số: Chọn biển báo hình tròn",
    gameLevelCode: "GL-C2-SHP-CARD-0002",
    skillCode: "C2.2D.02",
    loCode: "LO-C2.2D.02-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["shape_recognition"],
    themeTag: "household",
    sayToChild: '"Bé chọn biển báo có dạng hình tròn nhé!"',
  },
  {
    code: "ACT-0226",
    title: "Trò chơi số: Cất khối hình vào rổ",
    gameLevelCode: "GL-C2-SORT-SHP-0006",
    skillCode: "C2.2D.02",
    loCode: "LO-C2.2D.02-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["sorting"],
    themeTag: "household",
    sayToChild: '"Bé xếp khối hình vào đúng ngăn nhé!"',
  },

  // LES-0014 (C2)
  {
    code: "ACT-0227",
    title: "Trò chơi số: Đặt gấu bông trên ghế",
    gameLevelCode: "GL-C2-POS-LOC-0005",
    skillCode: "C2.2D.01",
    loCode: "LO-C2.2D.01-01",
    whatTags: ["spatial_relations"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "household",
    sayToChild: '"Bé đặt chú gấu lên trên chiếc ghế nhé!"',
  },
  {
    code: "ACT-0228",
    title: "Trò chơi số: So sánh kích thước khối hình",
    gameLevelCode: "GL-C2-CMP-SIZ-0008",
    skillCode: "C2.3D.01",
    loCode: "LO-C2.3D.01-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "household",
    sayToChild: '"Bé tìm khối hình to hơn nhé!"',
  },

  // LES-0015 (C2)
  {
    code: "ACT-0229",
    title: "Trò chơi số: Lái xe theo hướng mũi tên",
    gameLevelCode: "GL-C2-DIR-NAV-0010",
    skillCode: "C2.3D.01",
    loCode: "LO-C2.3D.01-01",
    whatTags: ["direction"],
    thinkingTags: ["directional_coordination"],
    themeTag: "vehicle",
    sayToChild: '"Bé bấm mũi tên điều khiển xe rẽ phải nhé!"',
  },
  {
    code: "ACT-0230",
    title: "Trò chơi số: Xoay khối hình học",
    gameLevelCode: "GL-C2-ROT-TRANS-0021",
    skillCode: "C2.3D.01",
    loCode: "LO-C2.3D.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["shift", "observe"],
    themeTag: "household",
    sayToChild: '"Bé xoay khối hình để khớp vào ô trống nhé!"',
  },

  // LES-0016 (C2)
  {
    code: "ACT-0231",
    title: "Trò chơi số: Xoay bánh răng khớp răng",
    gameLevelCode: "GL-C2-ROT-TRANS-0022",
    skillCode: "C2.2D.01",
    loCode: "LO-C2.2D.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["shift", "observe"],
    themeTag: "tool",
    sayToChild: '"Bé xoay bánh răng để guồng máy hoạt động nhé!"',
  },
  {
    code: "ACT-0232",
    title: "Trò chơi số: Nhận diện hình đa giác",
    gameLevelCode: "GL-C2-SHP-CARD-0003",
    skillCode: "C2.2D.02",
    loCode: "LO-C2.2D.02-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["shape_recognition"],
    themeTag: "household",
    sayToChild: '"Bé tìm hình có 4 góc vuông nhé!"',
  },

  // LES-0017 (C2)
  {
    code: "ACT-0233",
    title: "Trò chơi số: Vẽ cánh bướm đối xứng",
    gameLevelCode: "GL-C2-MIR-COMP-0024",
    skillCode: "C2.3D.01",
    loCode: "LO-C2.3D.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["match", "observe"],
    themeTag: "nature",
    sayToChild: '"Bé hoàn thiện đôi cánh bướm xinh đẹp nhé!"',
  },
  {
    code: "ACT-0234",
    title: "Trò chơi số: Phân loại bướm và hoa",
    gameLevelCode: "GL-C2-SORT-SHP-0007",
    skillCode: "C2.3D.01",
    loCode: "LO-C2.3D.01-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["sorting"],
    themeTag: "nature",
    sayToChild: '"Bé xếp bướm và hoa vào đúng vườn nhé!"',
  },

  // LES-0018 (C2)
  {
    code: "ACT-0235",
    title: "Trò chơi số: Ghép thuyền buồm ra khơi",
    gameLevelCode: "GL-C2-CON-SHP-0027",
    skillCode: "C2.2D.01",
    loCode: "LO-C2.2D.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["match", "observe"],
    themeTag: "vehicle",
    sayToChild: '"Bé ghép các mảnh thành chiếc thuyền buồm nhé!"',
  },
  {
    code: "ACT-0236",
    title: "Trò chơi số: Tìm cánh buồm tam giác",
    gameLevelCode: "GL-C2-SHP-CARD-0001",
    skillCode: "C2.2D.02",
    loCode: "LO-C2.2D.02-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["shape_recognition"],
    themeTag: "vehicle",
    sayToChild: '"Bé chọn cánh buồm hình tam giác nào!"',
  },

  // LES-0019 (C2)
  {
    code: "ACT-0237",
    title: "Trò chơi số: Vẽ theo nét lượn sóng",
    gameLevelCode: "GL-C2-TRC-PTH-0030",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["plan", "observe"],
    themeTag: "water",
    sayToChild: '"Bé rê tay theo đường nét đứt nhé!"',
  },
  {
    code: "ACT-0238",
    title: "Trò chơi số: Đưa cá về đại dương",
    gameLevelCode: "GL-C2-POS-LOC-0014",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["spatial_relations"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "water",
    sayToChild: '"Bé đặt chú cá bơi vào làn nước trong nhé!"',
  },

  // LES-0020 (C2)
  {
    code: "ACT-0239",
    title: "Trò chơi số: Đếm khối hộp xếp chồng",
    gameLevelCode: "GL-C2-BLK-STK-0033",
    skillCode: "C2.POS.02",
    loCode: "LO-C2.POS.02-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["infer", "observe"],
    themeTag: "household",
    sayToChild: '"Bé đếm xem có bao nhiêu khối hộp nhé!"',
  },
  {
    code: "ACT-0240",
    title: "Trò chơi số: Chọn khối lập phương",
    gameLevelCode: "GL-C2-SHP-CARD-0002",
    skillCode: "C2.POS.02",
    loCode: "LO-C2.POS.02-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["shape_recognition"],
    themeTag: "household",
    sayToChild: '"Bé chạm vào khối hình vuông nhé!"',
  },

  // LES-0021 (C2)
  {
    code: "ACT-0241",
    title: "Trò chơi số: Vị trí trước sau của bạn thú",
    gameLevelCode: "GL-C2-POS-LOC-0020",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["spatial_relations"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "farm",
    sayToChild: '"Bé tìm bạn nhỏ đứng ở phía trước nhé!"',
  },
  {
    code: "ACT-0242",
    title: "Trò chơi số: Dãy xếp hàng con vật",
    gameLevelCode: "GL-C2-SEQ-PAT-0011",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "farm",
    sayToChild: '"Bé xếp các bạn thú vào hàng nhé!"',
  },

  // LES-0022 (C2)
  {
    code: "ACT-0243",
    title: "Trò chơi số: Chạm nhanh theo hướng mũi tên",
    gameLevelCode: "GL-C2-SUB-FAST-0013",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "school",
    sayToChild: '"Bé chạm nhanh mũi tên chỉ sang phải nhé!"',
  },
  {
    code: "ACT-0244",
    title: "Trò chơi số: Đối xứng trái phải",
    gameLevelCode: "GL-C2-MIR-COMP-0025",
    skillCode: "C2.POS.02",
    loCode: "LO-C2.POS.02-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["match", "observe"],
    themeTag: "school",
    sayToChild: '"Bé hoàn thành nửa bên phải hình ngôi sao nhé!"',
  },

  // LES-0023 (C2)
  {
    code: "ACT-0245",
    title: "Trò chơi số: Điều khiển tàu hỏa qua đường hầm",
    gameLevelCode: "GL-C2-DIR-NAV-0016",
    skillCode: "C2.POS.02",
    loCode: "LO-C2.POS.02-01",
    whatTags: ["direction"],
    thinkingTags: ["directional_coordination"],
    themeTag: "vehicle",
    sayToChild: '"Bé dẫn đường cho đoàn tàu vào ga nhé!"',
  },
  {
    code: "ACT-0246",
    title: "Trò chơi số: Ghép các toa tàu",
    gameLevelCode: "GL-C2-CON-SHP-0028",
    skillCode: "C2.POS.02",
    loCode: "LO-C2.POS.02-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["match", "observe"],
    themeTag: "vehicle",
    sayToChild: '"Bé ghép các mảnh toa tàu lại với nhau nhé!"',
  },

  // LES-0024 (C2)
  {
    code: "ACT-0247",
    title: "Trò chơi số: Nối đường bay máy bay",
    gameLevelCode: "GL-C2-TRC-PTH-0031",
    skillCode: "C2.POS.01",
    loCode: "LO-C2.POS.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["plan", "observe"],
    themeTag: "vehicle",
    sayToChild: '"Bé vẽ đường bay cho chiếc máy bay lượn nhé!"',
  },
  {
    code: "ACT-0248",
    title: "Trò chơi số: Đếm các tầng tháp sân bay",
    gameLevelCode: "GL-C2-BLK-STK-0034",
    skillCode: "C2.POS.02",
    loCode: "LO-C2.POS.02-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["infer", "observe"],
    themeTag: "vehicle",
    sayToChild: '"Bé đếm số tầng của tháp không lưu nhé!"',
  },

  // LES-0025 (C3)
  {
    code: "ACT-0249",
    title: "Trò chơi số: Phân loại quả ngọt",
    gameLevelCode: "GL-C3-PAT-CARD-0001",
    skillCode: "C3.SRT.01",
    loCode: "LO-C3.SRT.01-01",
    whatTags: ["patterns"],
    thinkingTags: ["pattern_recognition"],
    themeTag: "fruit",
    sayToChild: '"Bé chọn tất cả các loại quả nhé!"',
  },
  {
    code: "ACT-0250",
    title: "Trò chơi số: Xếp rau củ vào giỏ",
    gameLevelCode: "GL-C3-CLS-BOX-0004",
    skillCode: "C3.SRT.01",
    loCode: "LO-C3.SRT.01-01",
    whatTags: ["classification"],
    thinkingTags: ["sorting"],
    themeTag: "vegetable",
    sayToChild: '"Bé xếp rau củ vào đúng giỏ nhé!"',
  },

  // LES-0026 (C3)
  {
    code: "ACT-0251",
    title: "Trò chơi số: Chuỗi quy luật hoa lá",
    gameLevelCode: "GL-C3-PAT-SEQ-0006",
    skillCode: "C3.PAT.02",
    loCode: "LO-C3.PAT.02-01",
    whatTags: ["patterns"],
    thinkingTags: ["pattern_recognition"],
    themeTag: "flower",
    sayToChild: '"Bé xem tiếp theo là hoa hay lá nhé!"',
  },
  {
    code: "ACT-0252",
    title: "Trò chơi số: So sánh cặp hình tương phản",
    gameLevelCode: "GL-C3-LOG-CMP-0008",
    skillCode: "C3.SRT.02",
    loCode: "LO-C3.SRT.02-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "flower",
    sayToChild: '"Bé nối cặp hoa cùng kích cỡ nhé!"',
  },

  // LES-0027 (C3)
  {
    code: "ACT-0253",
    title: "Trò chơi số: Vị trí ô logic",
    gameLevelCode: "GL-C3-LOG-POS-0011",
    skillCode: "C3.PAT.02",
    loCode: "LO-C3.PAT.02-01",
    whatTags: ["spatial_concept"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "school",
    sayToChild: '"Bé đặt hình vào đúng góc phần tư nhé!"',
  },
  {
    code: "ACT-0254",
    title: "Trò chơi số: Chạm nhanh quy luật",
    gameLevelCode: "GL-C3-SUB-FAST-0013",
    skillCode: "C3.PAT.01",
    loCode: "LO-C3.PAT.01-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "school",
    sayToChild: '"Bé chạm thật nhanh hình tiếp theo của dãy nhé!"',
  },

  // LES-0028 (C3)
  {
    code: "ACT-0255",
    title: "Trò chơi số: Manh mối con vật bí ẩn",
    gameLevelCode: "GL-C3-CLU-DED-0021",
    skillCode: "C3.SRT.02",
    loCode: "LO-C3.SRT.02-01",
    whatTags: ["log", "ded"],
    thinkingTags: ["infer", "observe"],
    themeTag: "farm",
    sayToChild: '"Bé đoán xem con vật nào phù hợp với gợi ý nhé!"',
  },
  {
    code: "ACT-0256",
    title: "Trò chơi số: Ma trận logic màu sắc",
    gameLevelCode: "GL-C3-MAT-CHO-0024",
    skillCode: "C3.PAT.02",
    loCode: "LO-C3.PAT.02-01",
    whatTags: ["log", "mat"],
    thinkingTags: ["infer", "compare"],
    themeTag: "school",
    sayToChild: '"Bé chọn hình phù hợp cho ô trống ma trận nhé!"',
  },

  // LES-0029 (C3)
  {
    code: "ACT-0257",
    title: "Trò chơi số: Sudoku hình học mini",
    gameLevelCode: "GL-C3-SUD-MIN-0027",
    skillCode: "C3.PAT.01",
    loCode: "LO-C3.PAT.01-01",
    whatTags: ["log", "sud"],
    thinkingTags: ["infer", "plan"],
    themeTag: "school",
    sayToChild: '"Bé điền hình vào ô trống không bị trùng hàng nhé!"',
  },
  {
    code: "ACT-0258",
    title: "Trò chơi số: Tìm điểm khác biệt giữa hai bức tranh",
    gameLevelCode: "GL-C3-VIS-SPOT-0030",
    skillCode: "C3.PAT.02",
    loCode: "LO-C3.PAT.02-01",
    whatTags: ["pat", "cmp"],
    thinkingTags: ["compare", "observe"],
    themeTag: "school",
    sayToChild: '"Bé tìm điểm khác nhau giữa hai bức tranh nhé!"',
  },

  // LES-0030 (C3)
  {
    code: "ACT-0259",
    title: "Trò chơi số: Thẻ phân loại đồ chơi",
    gameLevelCode: "GL-C3-PAT-CARD-0002",
    skillCode: "C3.PAT.01",
    loCode: "LO-C3.PAT.01-01",
    whatTags: ["patterns"],
    thinkingTags: ["pattern_recognition"],
    themeTag: "household",
    sayToChild: '"Bé xếp thẻ đồ chơi vào hàng quy luật nhé!"',
  },
  {
    code: "ACT-0260",
    title: "Trò chơi số: Thám tử nhí suy luận",
    gameLevelCode: "GL-C3-CLU-DED-0022",
    skillCode: "C3.SRT.01",
    loCode: "LO-C3.SRT.01-01",
    whatTags: ["log", "ded"],
    thinkingTags: ["infer", "observe"],
    themeTag: "household",
    sayToChild: '"Bé dùng kính lúp tìm đồ vật theo gợi ý nhé!"',
  },

  // LES-0031 (C4)
  {
    code: "ACT-0261",
    title: "Trò chơi số: Quan sát lá cây",
    gameLevelCode: "GL-C4-OBS-CARD-0001",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["observation_details"],
    thinkingTags: ["observation"],
    themeTag: "nature",
    sayToChild: '"Bé tìm chiếc lá có hình răng cưa nhé!"',
  },
  {
    code: "ACT-0262",
    title: "Trò chơi số: Phân loại kích thước lá",
    gameLevelCode: "GL-C4-DIF-BOX-0004",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["visual_discrimination"],
    thinkingTags: ["sorting"],
    themeTag: "nature",
    sayToChild: '"Bé xếp lá to và lá nhỏ vào hai giỏ nhé!"',
  },

  // LES-0032 (C4)
  {
    code: "ACT-0263",
    title: "Trò chơi số: Tìm hoa giấu trên cành",
    gameLevelCode: "GL-C4-OBS-LOC-0005",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["spatial_concept"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "flower",
    sayToChild: '"Bé tìm bông hoa nở ở ngọn cành nhé!"',
  },
  {
    code: "ACT-0264",
    title: "Trò chơi số: Dãy tăng dần chiều dài",
    gameLevelCode: "GL-C4-SEQ-OBS-0006",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "nature",
    sayToChild: '"Bé xếp các cành cây từ ngắn đến dài nhé!"',
  },

  // LES-0033 (C4)
  {
    code: "ACT-0265",
    title: "Trò chơi số: Ghép đôi hoa cùng màu",
    gameLevelCode: "GL-C4-DIF-CMP-0007",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "flower",
    sayToChild: '"Bé nối các bông hoa cùng màu lại nhé!"',
  },
  {
    code: "ACT-0266",
    title: "Trò chơi số: Nhìn nhanh chọn chiếc nơ xinh",
    gameLevelCode: "GL-C4-SUB-FAST-0010",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "clothing",
    sayToChild: '"Bé chọn thật nhanh chiếc nơ màu hồng nhé!"',
  },

  // LES-0034 (C4)
  {
    code: "ACT-0267",
    title: "Trò chơi số: Tìm đồ chơi giấu trong phòng",
    gameLevelCode: "GL-C4-VIS-SCENE-0021",
    skillCode: "C4.DAT.01",
    loCode: "LO-C4.DAT.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["observe", "match"],
    themeTag: "household",
    sayToChild: '"Bé tìm chiếc ô tô đồ chơi giấu sau tủ nhé!"',
  },
  {
    code: "ACT-0268",
    title: "Trò chơi số: So sánh 3 điểm khác nhau",
    gameLevelCode: "GL-C4-VIS-SPOT-0024",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["compare", "observe"],
    themeTag: "household",
    sayToChild: '"Bé khoanh tròn 3 điểm khác nhau giữa hai phòng nhé!"',
  },

  // LES-0035 (C4)
  {
    code: "ACT-0269",
    title: "Trò chơi số: Quan sát đồ vật nhà bếp",
    gameLevelCode: "GL-C4-OBS-CARD-0002",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["observation_details"],
    thinkingTags: ["observation"],
    themeTag: "household",
    sayToChild: '"Bé chạm vào chiếc nồi nấu ăn nhé!"',
  },
  {
    code: "ACT-0270",
    title: "Trò chơi số: Tìm thìa dĩa trong bếp",
    gameLevelCode: "GL-C4-VIS-SCENE-0022",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["observe", "match"],
    themeTag: "household",
    sayToChild: '"Bé tìm chiếc thìa đang nằm trên bàn ăn nhé!"',
  },

  // LES-0036 (C4)
  {
    code: "ACT-0271",
    title: "Trò chơi số: Cất bát đĩa vào tủ",
    gameLevelCode: "GL-C4-OBS-BOX-0008",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["visual_discrimination"],
    thinkingTags: ["sorting"],
    themeTag: "household",
    sayToChild: '"Bé xếp bát vào ngăn bát và đĩa vào ngăn đĩa nhé!"',
  },
  {
    code: "ACT-0272",
    title: "Trò chơi số: Tìm điểm khác của chiếc cốc",
    gameLevelCode: "GL-C4-VIS-SPOT-0025",
    skillCode: "C4.LEN.01",
    loCode: "LO-C4.LEN.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["compare", "observe"],
    themeTag: "household",
    sayToChild: '"Bé chỉ ra chiếc cốc có quai khác màu nhé!"',
  },

  // LES-0037 (C4)
  {
    code: "ACT-0273",
    title: "Trò chơi số: Quan sát thời tiết",
    gameLevelCode: "GL-C4-OBS-CARD-0001",
    skillCode: "C4.WGT.01",
    loCode: "LO-C4.WGT.01-01",
    whatTags: ["observation_details"],
    thinkingTags: ["observation"],
    themeTag: "weather",
    sayToChild: '"Bé chọn bức tranh có ông mặt trời tỏa nắng nhé!"',
  },
  {
    code: "ACT-0274",
    title: "Trò chơi số: Ghép trang phục theo thời tiết",
    gameLevelCode: "GL-C4-DIF-CMP-0013",
    skillCode: "C4.TIM.01",
    loCode: "LO-C4.TIM.01-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "clothing",
    sayToChild: '"Bé chọn áo ấm cho ngày trời đông lạnh giá nhé!"',
  },

  // LES-0038 (C4)
  {
    code: "ACT-0275",
    title: "Trò chơi số: Chuỗi các mùa trong năm",
    gameLevelCode: "GL-C4-SEQ-OBS-0012",
    skillCode: "C4.TIM.01",
    loCode: "LO-C4.TIM.01-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "weather",
    sayToChild: '"Bé xếp tranh các mùa theo thứ tự xuân, hạ, thu, đông nhé!"',
  },
  {
    code: "ACT-0276",
    title: "Trò chơi số: Đặt đồng hồ đúng vị trí",
    gameLevelCode: "GL-C4-OBS-LOC-0009",
    skillCode: "C4.DAT.01",
    loCode: "LO-C4.DAT.01-01",
    whatTags: ["spatial_concept"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "household",
    sayToChild: '"Bé treo chiếc đồng hồ lên giữa bức tường nhé!"',
  },

  // LES-0039 (C4)
  {
    code: "ACT-0277",
    title: "Trò chơi số: Chạm nhanh quả bóng nặng",
    gameLevelCode: "GL-C4-SUB-FAST-0015",
    skillCode: "C4.WGT.01",
    loCode: "LO-C4.WGT.01-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "household",
    sayToChild: '"Bé chạm nhanh vào quả bóng sắt nặng nhất nhé!"',
  },
  {
    code: "ACT-0278",
    title: "Trò chơi số: Tìm quả cân ẩn",
    gameLevelCode: "GL-C4-VIS-SCENE-0023",
    skillCode: "C4.WGT.01",
    loCode: "LO-C4.WGT.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["observe", "match"],
    themeTag: "household",
    sayToChild: '"Bé tìm quả cân nhỏ giấu bên cạnh đĩa cân nhé!"',
  },

  // LES-0040 (C4)
  {
    code: "ACT-0279",
    title: "Trò chơi số: Phân loại lịch biểu tuần",
    gameLevelCode: "GL-C4-OBS-BOX-0014",
    skillCode: "C4.DAT.01",
    loCode: "LO-C4.DAT.01-01",
    whatTags: ["visual_discrimination"],
    thinkingTags: ["sorting"],
    themeTag: "school",
    sayToChild: '"Bé xếp các ngày đi học và ngày nghỉ vào hai hộp nhé!"',
  },
  {
    code: "ACT-0280",
    title: "Trò chơi số: Tìm điểm khác trên tờ lịch",
    gameLevelCode: "GL-C4-VIS-SPOT-0026",
    skillCode: "C4.DAT.01",
    loCode: "LO-C4.DAT.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["compare", "observe"],
    themeTag: "school",
    sayToChild: '"Bé tìm ô ngày có màu đỏ trên tờ lịch nhé!"',
  },

  // LES-0041 (C4)
  {
    code: "ACT-0281",
    title: "Trò chơi số: Thẻ giờ giấc sinh hoạt",
    gameLevelCode: "GL-C4-OBS-CARD-0011",
    skillCode: "C4.TIM.01",
    loCode: "LO-C4.TIM.01-01",
    whatTags: ["observation_details"],
    thinkingTags: ["observation"],
    themeTag: "school",
    sayToChild: '"Bé chạm vào bức tranh bé đang ngủ ngon nhé!"',
  },
  {
    code: "ACT-0282",
    title: "Trò chơi số: Tìm chiếc gối êm trong phòng ngủ",
    gameLevelCode: "GL-C4-VIS-SCENE-0021",
    skillCode: "C4.TIM.01",
    loCode: "LO-C4.TIM.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["observe", "match"],
    themeTag: "household",
    sayToChild: '"Bé tìm chiếc gối ngủ giấu trên giường nhé!"',
  },

  // LES-0042 (C4)
  {
    code: "ACT-0283",
    title: "Trò chơi số: Xếp đồ vật nặng nhẹ vào kệ",
    gameLevelCode: "GL-C4-OBS-BOX-0020",
    skillCode: "C4.WGT.01",
    loCode: "LO-C4.WGT.01-01",
    whatTags: ["visual_discrimination"],
    thinkingTags: ["sorting"],
    themeTag: "household",
    sayToChild: '"Bé xếp đồ nặng ở tầng dưới và đồ nhẹ ở tầng trên nhé!"',
  },
  {
    code: "ACT-0284",
    title: "Trò chơi số: Tìm chiếc lông vũ khác biệt",
    gameLevelCode: "GL-C4-VIS-SPOT-0024",
    skillCode: "C4.DAT.01",
    loCode: "LO-C4.DAT.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["compare", "observe"],
    themeTag: "household",
    sayToChild:
      '"Bé tìm chiếc lông vũ có màu sắc khác với các chiếc còn lại nhé!"',
  },

  // LES-0043 (C5)
  {
    code: "ACT-0285",
    title: "Trò chơi số: Thẻ từ vựng con vật",
    gameLevelCode: "GL-C5-VOC-CARD-0001",
    skillCode: "C5.MEM.01",
    loCode: "LO-C5.MEM.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["naming"],
    themeTag: "farm",
    sayToChild: '"Bé gọi tên chú cún con đáng yêu nào!"',
  },
  {
    code: "ACT-0286",
    title: "Trò chơi số: Phân loại thú nuôi và thú rừng",
    gameLevelCode: "GL-C5-VOC-BOX-0004",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["sorting"],
    themeTag: "farm",
    sayToChild: '"Bé đưa các bạn thú về đúng ngôi nhà của mình nhé!"',
  },

  // LES-0044 (C5)
  {
    code: "ACT-0287",
    title: "Trò chơi số: Ghép cặp từ trái nghĩa",
    gameLevelCode: "GL-C5-EXP-CMP-0006",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["adjectives_opposites"],
    thinkingTags: ["comparison"],
    themeTag: "school",
    sayToChild: '"Bé nối từ cao với từ thấp nhé!"',
  },
  {
    code: "ACT-0288",
    title: "Trò chơi số: Kể chuyện theo tranh thứ tự",
    gameLevelCode: "GL-C5-VOC-SEQ-0008",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "school",
    sayToChild: '"Bé xếp các bức tranh theo diễn biến câu chuyện nhé!"',
  },

  // LES-0045 (C5)
  {
    code: "ACT-0289",
    title: "Trò chơi số: Đặt đồ vật theo lời mô tả",
    gameLevelCode: "GL-C5-VOC-LOC-0009",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["spatial_concept"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "household",
    sayToChild: '"Bé đặt quả bóng vào bên cạnh chú gấu bông nhé!"',
  },
  {
    code: "ACT-0290",
    title: "Trò chơi số: Nhận diện nhanh chữ cái",
    gameLevelCode: "GL-C5-SUB-FAST-0010",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "school",
    sayToChild: '"Bé chạm thật nhanh vào chữ A nhé!"',
  },

  // LES-0046 (C5)
  {
    code: "ACT-0291",
    title: "Trò chơi số: Nghe âm thanh tiếng chim hót",
    gameLevelCode: "GL-C5-LIS-AUDIO-0021",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["lan", "aud"],
    thinkingTags: ["recall", "observe"],
    themeTag: "music",
    sayToChild: '"Bé nghe và chọn chú chim vừa cất tiếng hót nhé!"',
  },
  {
    code: "ACT-0292",
    title: "Trò chơi số: Thẻ từ vựng đồ dùng học tập",
    gameLevelCode: "GL-C5-VOC-CARD-0002",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["naming"],
    themeTag: "school",
    sayToChild: '"Bé chọn chiếc bút chì màu sáp nhé!"',
  },

  // LES-0047 (C5)
  {
    code: "ACT-0293",
    title: "Trò chơi số: Phân loại rau quả theo màu",
    gameLevelCode: "GL-C5-VOC-BOX-0005",
    skillCode: "C5.MEM.01",
    loCode: "LO-C5.MEM.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["sorting"],
    themeTag: "fruit",
    sayToChild: '"Bé xếp quả đỏ và quả vàng vào hai giỏ nhé!"',
  },
  {
    code: "ACT-0294",
    title: "Trò chơi số: Nghe tiếng các nhạc cụ",
    gameLevelCode: "GL-C5-LIS-AUDIO-0022",
    skillCode: "C5.MEM.01",
    loCode: "LO-C5.MEM.01-01",
    whatTags: ["lan", "aud"],
    thinkingTags: ["recall", "observe"],
    themeTag: "music",
    sayToChild: '"Bé nghe tiếng đàn piano và chạm vào phím đàn nhé!"',
  },

  // LES-0048 (C5)
  {
    code: "ACT-0295",
    title: "Trò chơi số: Ghép từ hành động",
    gameLevelCode: "GL-C5-EXP-CMP-0007",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["adjectives_opposites"],
    thinkingTags: ["comparison"],
    themeTag: "school",
    sayToChild: '"Bé nối hình bé chạy với hình bé nhảy nhé!"',
  },
  {
    code: "ACT-0296",
    title: "Trò chơi số: Chuỗi ngày sinh nhật",
    gameLevelCode: "GL-C5-VOC-SEQ-0014",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "school",
    sayToChild: '"Bé xếp các bước chuẩn bị bánh sinh nhật nhé!"',
  },

  // LES-0049 (C5)
  {
    code: "ACT-0297",
    title: "Trò chơi số: Thẻ phương tiện giao thông",
    gameLevelCode: "GL-C5-VOC-CARD-0003",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["naming"],
    themeTag: "vehicle",
    sayToChild: '"Bé đọc tên chiếc máy bay trực thăng nhé!"',
  },
  {
    code: "ACT-0298",
    title: "Trò chơi số: Đặt xe vào bãi đỗ",
    gameLevelCode: "GL-C5-VOC-LOC-0015",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["spatial_concept"],
    thinkingTags: ["spatial_reasoning"],
    themeTag: "vehicle",
    sayToChild: '"Bé đỗ xe vào ô số 1 bên tay trái nhé!"',
  },

  // LES-0050 (C5)
  {
    code: "ACT-0299",
    title: "Trò chơi số: Chạm nhanh biển báo giao thông",
    gameLevelCode: "GL-C5-SUB-FAST-0016",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "vehicle",
    sayToChild: '"Bé chạm nhanh vào đèn tín hiệu màu xanh nhé!"',
  },
  {
    code: "ACT-0300",
    title: "Trò chơi số: Nghe tiếng còi xe cứu thương",
    gameLevelCode: "GL-C5-LIS-AUDIO-0023",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["lan", "aud"],
    thinkingTags: ["recall", "sequence"],
    themeTag: "vehicle",
    sayToChild: '"Bé lắng nghe tiếng còi xe và chọn xe cứu thương nhé!"',
  },

  // LES-0051 (C5)
  {
    code: "ACT-0301",
    title: "Trò chơi số: Thu gom đồ dùng vào vali",
    gameLevelCode: "GL-C5-VOC-BOX-0012",
    skillCode: "C5.MEM.01",
    loCode: "LO-C5.MEM.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["sorting"],
    themeTag: "travel",
    sayToChild: '"Bé xếp quần áo và mũ vào vali đi biển nhé!"',
  },
  {
    code: "ACT-0302",
    title: "Trò chơi số: So sánh nóng và lạnh",
    gameLevelCode: "GL-C5-EXP-CMP-0013",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["adjectives_opposites"],
    thinkingTags: ["comparison"],
    themeTag: "weather",
    sayToChild: '"Bé nối cốc kem lạnh với cốc trà nóng nhé!"',
  },

  // LES-0052 (C5)
  {
    code: "ACT-0303",
    title: "Trò chơi số: Dãy câu chuyện hạt mầm",
    gameLevelCode: "GL-C5-VOC-SEQ-0019",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "nature",
    sayToChild: '"Bé xếp tranh quá trình hạt mầm nảy mầm thành cây nhé!"',
  },
  {
    code: "ACT-0304",
    title: "Trò chơi số: Nghe tiếng mưa rơi rả rích",
    gameLevelCode: "GL-C5-LIS-AUDIO-0021",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["lan", "aud"],
    thinkingTags: ["recall", "observe"],
    themeTag: "weather",
    sayToChild: '"Bé nghe tiếng mưa và chạm vào chiếc ô xinh nhé!"',
  },

  // LES-0053 (C5)
  {
    code: "ACT-0305",
    title: "Trò chơi số: Thẻ ngành nghề bác sĩ, cô giáo",
    gameLevelCode: "GL-C5-VOC-CARD-0011",
    skillCode: "C5.MEM.01",
    loCode: "LO-C5.MEM.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["naming"],
    themeTag: "profession",
    sayToChild: '"Bé gọi tên chú lính cứu hỏa dũng cảm nhé!"',
  },
  {
    code: "ACT-0306",
    title: "Trò chơi số: Đồ dùng cho từng nghề nghiệp",
    gameLevelCode: "GL-C5-VOC-BOX-0018",
    skillCode: "C5.MEM.01",
    loCode: "LO-C5.MEM.01-01",
    whatTags: ["vocabulary_nouns"],
    thinkingTags: ["sorting"],
    themeTag: "profession",
    sayToChild: '"Bé đưa ống nghe cho bác sĩ và bảng đen cho cô giáo nhé!"',
  },

  // LES-0054 (C5)
  {
    code: "ACT-0307",
    title: "Trò chơi số: Ghép đôi dụng cụ lao động",
    gameLevelCode: "GL-C5-EXP-CMP-0017",
    skillCode: "C5.RSN.01",
    loCode: "LO-C5.RSN.01-01",
    whatTags: ["adjectives_opposites"],
    thinkingTags: ["comparison"],
    themeTag: "tool",
    sayToChild: '"Bé nối chiếc cọ vẽ với bảng màu nhé!"',
  },
  {
    code: "ACT-0308",
    title: "Trò chơi số: Nghe lời thoại và đoán nghề",
    gameLevelCode: "GL-C5-LIS-AUDIO-0022",
    skillCode: "C5.SPL.01",
    loCode: "LO-C5.SPL.01-01",
    whatTags: ["lan", "aud"],
    thinkingTags: ["recall", "observe"],
    themeTag: "profession",
    sayToChild: '"Bé lắng nghe giọng chào của cô giáo nhé!"',
  },

  // LES-0055 (C6)
  {
    code: "ACT-0309",
    title: "Trò chơi số: Thẻ trí nhớ vị trí quả táo",
    gameLevelCode: "GL-C6-MEM-CARD-0001",
    skillCode: "C6.VAL.01",
    loCode: "LO-C6.VAL.01-01",
    whatTags: ["working_memory"],
    thinkingTags: ["recall"],
    themeTag: "school",
    sayToChild: '"Bé nhớ lại xem quả táo giấu ở ô nào nhé!"',
  },
  {
    code: "ACT-0310",
    title: "Trò chơi số: Lật thẻ tìm cặp chữ số",
    gameLevelCode: "GL-C6-MEM-FLIP-0024",
    skillCode: "C6.SAV.01",
    loCode: "LO-C6.SAV.01-01",
    whatTags: ["mem", "att"],
    thinkingTags: ["recall", "match"],
    themeTag: "school",
    sayToChild: '"Bé lật hai thẻ có hình giống nhau nhé!"',
  },

  // LES-0056 (C6)
  {
    code: "ACT-0311",
    title: "Trò chơi số: Thu dọn đồ chơi theo phân loại",
    gameLevelCode: "GL-C6-ATT-BOX-0005",
    skillCode: "C6.VAL.01",
    loCode: "LO-C6.VAL.01-01",
    whatTags: ["working_memory"],
    thinkingTags: ["sorting"],
    themeTag: "school",
    sayToChild: '"Bé xếp khối hình tròn vào giỏ đỏ nhé!"',
  },
  {
    code: "ACT-0312",
    title: "Trò chơi số: Nhìn chớp nhớ màu sắc đồ vật",
    gameLevelCode: "GL-C6-MEM-FLASH-0027",
    skillCode: "C6.SAV.01",
    loCode: "LO-C6.SAV.01-01",
    whatTags: ["mem", "att"],
    thinkingTags: ["recall", "observe"],
    themeTag: "school",
    sayToChild: '"Bé nhớ lại xem bạn gấu mặc áo màu gì nhé!"',
  },

  // LES-0057 (C6)
  {
    code: "ACT-0313",
    title: "Trò chơi số: Mê cung đường về nhà",
    gameLevelCode: "GL-C6-PLN-MAZE-0021",
    skillCode: "C6.EXC.01",
    loCode: "LO-C6.EXC.01-01",
    whatTags: ["pln", "spa"],
    thinkingTags: ["plan", "observe"],
    themeTag: "school",
    sayToChild: '"Bé vẽ đường đi giúp bạn thỏ về hang nhé!"',
  },
  {
    code: "ACT-0314",
    title: "Trò chơi số: Đèn xanh đèn đỏ kiềm chế bước chân",
    gameLevelCode: "GL-C6-INH-NOGO-0030",
    skillCode: "C6.EXC.01",
    loCode: "LO-C6.EXC.01-01",
    whatTags: ["inh", "att"],
    thinkingTags: ["inhibit", "observe"],
    themeTag: "school",
    sayToChild: '"Đèn đỏ bé đứng yên, đèn xanh bé hãy chạm nhé!"',
  },

  // LES-0058 (C6)
  {
    code: "ACT-0315",
    title: "Trò chơi số: Đổi luật chơi màu sang hình",
    gameLevelCode: "GL-C6-FLX-SWT-0033",
    skillCode: "C6.VAL.01",
    loCode: "LO-C6.VAL.01-01",
    whatTags: ["flx", "att"],
    thinkingTags: ["shift", "sort"],
    themeTag: "school",
    sayToChild: '"Lần này bé phân loại theo hình dạng nhé!"',
  },
  {
    code: "ACT-0316",
    title: "Trò chơi số: Dãy nhớ bước chân",
    gameLevelCode: "GL-C6-MEM-SEQ-0006",
    skillCode: "C6.EXC.01",
    loCode: "LO-C6.EXC.01-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "school",
    sayToChild: '"Bé lặp lại đúng thứ tự các ô bước chân nhé!"',
  },

  // LES-0059 (C6)
  {
    code: "ACT-0317",
    title: "Trò chơi số: So sánh vị trí khác biệt",
    gameLevelCode: "GL-C6-MEM-CMP-0007",
    skillCode: "C6.VAL.01",
    loCode: "LO-C6.VAL.01-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "school",
    sayToChild: '"Bé tìm cặp thẻ ở hai góc đối diện nhé!"',
  },
  {
    code: "ACT-0318",
    title: "Trò chơi số: Nhịn chạm quả bom gai",
    gameLevelCode: "GL-C6-INH-NOGO-0031",
    skillCode: "C6.SAV.01",
    loCode: "LO-C6.SAV.01-01",
    whatTags: ["inh", "att"],
    thinkingTags: ["inhibit", "observe"],
    themeTag: "school",
    sayToChild: '"Bé chỉ hái quả ngọt và nhịn hái quả gai nhé!"',
  },

  // LES-0060 (C6)
  {
    code: "ACT-0319",
    title: "Trò chơi số: Chuyển đổi luật linh hoạt cấp cao",
    gameLevelCode: "GL-C6-FLX-SWT-0034",
    skillCode: "C6.VAL.01",
    loCode: "LO-C6.VAL.01-01",
    whatTags: ["flx", "att"],
    thinkingTags: ["shift", "sort"],
    themeTag: "school",
    sayToChild:
      '"Bé chú ý xem vòng này phân loại theo màu hay theo kích cỡ nhé!"',
  },
  {
    code: "ACT-0320",
    title: "Trò chơi số: Lật tìm thẻ siêu nhân",
    gameLevelCode: "GL-C6-MEM-FLIP-0025",
    skillCode: "C6.EXC.01",
    loCode: "LO-C6.EXC.01-01",
    whatTags: ["mem", "att"],
    thinkingTags: ["recall", "match"],
    themeTag: "school",
    sayToChild: '"Bé lật mở hai thẻ siêu nhân giống nhau nhé!"',
  },

  // Montessori (LES-0101 .. LES-0121)
  {
    code: "ACT-0321",
    title: "Trò chơi số: Thẻ số nhám và thẻ đếm",
    gameLevelCode: "GL-C1-CNT-CARD-0001",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "household",
    sayToChild: '"Bé đếm các thẻ gỗ tương ứng với thẻ số nhé!"',
  },
  {
    code: "ACT-0322",
    title: "Trò chơi số: Nhìn nhanh hạt đếm",
    gameLevelCode: "GL-C1-MEM-FLASH-0040",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["cnt", "mem"],
    thinkingTags: ["recall", "count"],
    themeTag: "farm",
    sayToChild: '"Bé đếm nhanh số lượng hạt vừa hiện ra nhé!"',
  },
  {
    code: "ACT-0323",
    title: "Trò chơi số: Gậy số đỏ xanh",
    gameLevelCode: "GL-C1-CNT-CARD-0002",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé đếm các đoạn màu trên gậy số nhé!"',
  },
  {
    code: "ACT-0324",
    title: "Trò chơi số: Xếp gậy số vào khay",
    gameLevelCode: "GL-C1-SORT-BOX-0006",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé xếp các gậy số từ ngắn tới dài vào khay nhé!"',
  },
  {
    code: "ACT-0325",
    title: "Trò chơi số: Tìm bóng vật thể",
    gameLevelCode: "GL-C4-OBS-CARD-0001",
    skillCode: "C4.VIS.01",
    loCode: "LO-C4.VIS.01-01",
    whatTags: ["visual_discrimination"],
    thinkingTags: ["observation"],
    themeTag: "household",
    sayToChild: '"Bé tìm bóng đen của đồ vật nhé!"',
  },
  {
    code: "ACT-0326",
    title: "Trò chơi số: Tìm điểm khác biệt của bóng",
    gameLevelCode: "GL-C4-VIS-SPOT-0024",
    skillCode: "C4.VIS.01",
    loCode: "LO-C4.VIS.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["compare", "observe"],
    themeTag: "household",
    sayToChild: '"Bé tìm điểm khác nhau giữa hai chiếc bóng nhé!"',
  },
  {
    code: "ACT-0327",
    title: "Trò chơi số: Đếm quả trên cây",
    gameLevelCode: "GL-C1-CNT-CARD-0003",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "farm",
    sayToChild: '"Bé đếm xem có mấy quả táo trên cây nhé!"',
  },
  {
    code: "ACT-0328",
    title: "Trò chơi số: Thay thế biểu tượng đếm",
    gameLevelCode: "GL-C1-SUB-SYM-0031",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["cnt", "alg"],
    thinkingTags: ["infer", "count"],
    themeTag: "farm",
    sayToChild: '"Bé tìm số lượng quả táo còn thiếu nhé!"',
  },
  {
    code: "ACT-0329",
    title: "Trò chơi số: Ghép đôi hoa quả",
    gameLevelCode: "GL-C1-CMP-NUM-0010",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "fruit",
    sayToChild: '"Bé ghép các cặp quả giống nhau nhé!"',
  },
  {
    code: "ACT-0330",
    title: "Trò chơi số: Cân thăng bằng trái cây",
    gameLevelCode: "GL-C1-BAL-SCL-0034",
    skillCode: "C1.CNT.01",
    loCode: "LO-C1.CNT.01-01",
    whatTags: ["cnt", "mea"],
    thinkingTags: ["compare", "observe"],
    themeTag: "fruit",
    sayToChild: '"Bé đặt quả lên đĩa cân để hai bên bằng nhau nhé!"',
  },
  {
    code: "ACT-0331",
    title: "Trò chơi số: Xếp số theo thứ tự",
    gameLevelCode: "GL-C1-SEQ-PAT-0014",
    skillCode: "C1.CMP.04",
    loCode: "LO-C1.CMP.04-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "school",
    sayToChild: '"Bé xếp các số từ bé đến lớn nhé!"',
  },
  {
    code: "ACT-0332",
    title: "Trò chơi số: Xoay kim đồng hồ đo lường",
    gameLevelCode: "GL-C1-CLK-HND-0037",
    skillCode: "C1.CMP.04",
    loCode: "LO-C1.CMP.04-01",
    whatTags: ["cnt", "tim"],
    thinkingTags: ["shift", "observe"],
    themeTag: "household",
    sayToChild: '"Bé xoay kim đồng hồ chỉ đúng giờ nhé!"',
  },
  {
    code: "ACT-0333",
    title: "Trò chơi số: Nhận diện nhanh số lượng",
    gameLevelCode: "GL-C1-SUB-FAST-0019",
    skillCode: "C1.NCOMP.04",
    loCode: "LO-C1.NCOMP.04-01",
    whatTags: ["subitizing"],
    thinkingTags: ["instant_recognition"],
    themeTag: "household",
    sayToChild: '"Bé chọn nhanh số lượng vừa nhìn thấy nhé!"',
  },
  {
    code: "ACT-0334",
    title: "Trò chơi số: Ghi nhớ chớp nhoáng thẻ số",
    gameLevelCode: "GL-C1-MEM-FLASH-0040",
    skillCode: "C1.NCOMP.04",
    loCode: "LO-C1.NCOMP.04-01",
    whatTags: ["cnt", "mem"],
    thinkingTags: ["recall", "count"],
    themeTag: "farm",
    sayToChild: '"Bé nhớ lại xem có mấy chấm tròn nhé!"',
  },
  {
    code: "ACT-0335",
    title: "Trò chơi số: Đếm que tính vào hộp",
    gameLevelCode: "GL-C1-CNT-CARD-0001",
    skillCode: "C1.NCOMP.09",
    loCode: "LO-C1.NCOMP.09-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé đếm số que tính trên bàn nhé!"',
  },
  {
    code: "ACT-0336",
    title: "Trò chơi số: Tách gộp biểu tượng",
    gameLevelCode: "GL-C1-SUB-SYM-0031",
    skillCode: "C1.NCOMP.09",
    loCode: "LO-C1.NCOMP.09-01",
    whatTags: ["cnt", "alg"],
    thinkingTags: ["infer", "count"],
    themeTag: "school",
    sayToChild: '"Bé tìm số kẹp còn thiếu để đủ 10 kẹp nhé!"',
  },
  {
    code: "ACT-0337",
    title: "Trò chơi số: Khám phá hình học",
    gameLevelCode: "GL-C2-SHP-CARD-0001",
    skillCode: "C2.MAZ.01",
    loCode: "LO-C2.MAZ.01-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["shape_recognition"],
    themeTag: "school",
    sayToChild: '"Bé chọn hình học để mở cửa mê cung nhé!"',
  },
  {
    code: "ACT-0338",
    title: "Trò chơi số: Xoay hướng trong mê cung",
    gameLevelCode: "GL-C2-ROT-TRANS-0021",
    skillCode: "C2.MAZ.01",
    loCode: "LO-C2.MAZ.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["shift", "observe"],
    themeTag: "school",
    sayToChild: '"Bé xoay mũi tên chỉ đúng hướng đi nhé!"',
  },
  {
    code: "ACT-0339",
    title: "Trò chơi số: Ghép đôi đồ vật xúc giác",
    gameLevelCode: "GL-C4-DIF-CMP-0007",
    skillCode: "C4.SEN.01",
    loCode: "LO-C4.SEN.01-01",
    whatTags: ["observation_details"],
    thinkingTags: ["matching"],
    themeTag: "household",
    sayToChild: '"Bé ghép các đồ vật có cảm giác giống nhau nhé!"',
  },
  {
    code: "ACT-0340",
    title: "Trò chơi số: Tìm đồ vật ẩn trong phòng",
    gameLevelCode: "GL-C4-VIS-SCENE-0021",
    skillCode: "C4.SEN.01",
    loCode: "LO-C4.SEN.01-01",
    whatTags: ["obs", "vis"],
    thinkingTags: ["observe", "match"],
    themeTag: "household",
    sayToChild: '"Bé tìm món đồ bí ẩn giấu trong phòng nhé!"',
  },
  {
    code: "ACT-0341",
    title: "Trò chơi số: Đếm đồ chơi giác quan",
    gameLevelCode: "GL-C1-CNT-CARD-0002",
    skillCode: "C1.CNT.05",
    loCode: "LO-C1.CNT.05-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé đếm số đồ chơi trong khay nhé!"',
  },
  {
    code: "ACT-0342",
    title: "Trò chơi số: Cân bằng trọng lượng đồ vật",
    gameLevelCode: "GL-C1-BAL-SCL-0034",
    skillCode: "C1.CNT.05",
    loCode: "LO-C1.CNT.05-01",
    whatTags: ["cnt", "mea"],
    thinkingTags: ["compare", "observe"],
    themeTag: "school",
    sayToChild: '"Bé cân xem đồ vật nào nặng hơn nhé!"',
  },
  {
    code: "ACT-0343",
    title: "Trò chơi số: Xếp khối theo thứ tự",
    gameLevelCode: "GL-C1-SEQ-PAT-0016",
    skillCode: "C1.PROB.06",
    loCode: "LO-C1.PROB.06-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "school",
    sayToChild: '"Bé xếp các khối theo thứ tự đúng nhé!"',
  },
  {
    code: "ACT-0344",
    title: "Trò chơi số: Xem giờ hoạt động",
    gameLevelCode: "GL-C1-CLK-HND-0037",
    skillCode: "C1.PROB.06",
    loCode: "LO-C1.PROB.06-01",
    whatTags: ["cnt", "tim"],
    thinkingTags: ["shift", "observe"],
    themeTag: "school",
    sayToChild: '"Bé chỉnh đồng hồ đúng giờ giải lao nhé!"',
  },
  {
    code: "ACT-0345",
    title: "Trò chơi số: Phân chia đồ vật vào hộp",
    gameLevelCode: "GL-C1-SORT-BOX-0008",
    skillCode: "C1.NCOMP.09",
    loCode: "LO-C1.NCOMP.09-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé chia đều đồ vật vào hai hộp nhé!"',
  },
  {
    code: "ACT-0346",
    title: "Trò chơi số: Thay thế biểu tượng tính toán",
    gameLevelCode: "GL-C1-SUB-SYM-0031",
    skillCode: "C1.NCOMP.09",
    loCode: "LO-C1.NCOMP.09-01",
    whatTags: ["cnt", "alg"],
    thinkingTags: ["infer", "count"],
    themeTag: "school",
    sayToChild: '"Bé giải bài toán biểu tượng nhé!"',
  },
  {
    code: "ACT-0347",
    title: "Trò chơi số: Phân loại theo tiêu chí logic",
    gameLevelCode: "GL-C3-PAT-CARD-0001",
    skillCode: "C3.DED.01",
    loCode: "LO-C3.DED.01-01",
    whatTags: ["classification"],
    thinkingTags: ["sorting"],
    themeTag: "school",
    sayToChild: '"Bé chọn các đồ vật theo gợi ý nhé!"',
  },
  {
    code: "ACT-0348",
    title: "Trò chơi số: Suy luận loại trừ đồ dùng",
    gameLevelCode: "GL-C3-CLU-DED-0021",
    skillCode: "C3.DED.01",
    loCode: "LO-C3.DED.01-01",
    whatTags: ["log", "ded"],
    thinkingTags: ["infer", "observe"],
    themeTag: "school",
    sayToChild: '"Bé tìm đồ vật bí ẩn bằng các manh mối nhé!"',
  },
  {
    code: "ACT-0349",
    title: "Trò chơi số: Dãy quy luật chuỗi hạt",
    gameLevelCode: "GL-C1-SEQ-PAT-0014",
    skillCode: "C1.PAT.04",
    loCode: "LO-C1.PAT.04-01",
    whatTags: ["order"],
    thinkingTags: ["sequencing"],
    themeTag: "craft",
    sayToChild: '"Bé xâu hạt tiếp theo theo đúng quy luật nhé!"',
  },
  {
    code: "ACT-0350",
    title: "Trò chơi số: Nhìn chớp nhớ màu chuỗi hạt",
    gameLevelCode: "GL-C1-MEM-FLASH-0040",
    skillCode: "C1.PAT.04",
    loCode: "LO-C1.PAT.04-01",
    whatTags: ["cnt", "mem"],
    thinkingTags: ["recall", "count"],
    themeTag: "craft",
    sayToChild: '"Bé nhớ lại màu hạt vừa xuất hiện nhé!"',
  },
  {
    code: "ACT-0351",
    title: "Trò chơi số: So sánh nặng nhẹ",
    gameLevelCode: "GL-C1-CMP-NUM-0012",
    skillCode: "C1.MEAS.07",
    loCode: "LO-C1.MEAS.07-01",
    whatTags: ["comparison"],
    thinkingTags: ["matching"],
    themeTag: "school",
    sayToChild: '"Bé nối vật nặng với vật nhẹ nhé!"',
  },
  {
    code: "ACT-0352",
    title: "Trò chơi số: Đòn cân thăng bằng",
    gameLevelCode: "GL-C1-BAL-SCL-0034",
    skillCode: "C1.MEAS.07",
    loCode: "LO-C1.MEAS.07-01",
    whatTags: ["cnt", "mea"],
    thinkingTags: ["compare", "observe"],
    themeTag: "school",
    sayToChild: '"Bé đặt vật lên đòn cân để cân bằng nhé!"',
  },
  {
    code: "ACT-0353",
    title: "Trò chơi số: Phân loại ma trận",
    gameLevelCode: "GL-C3-PAT-CARD-0002",
    skillCode: "C3.MTX.01",
    loCode: "LO-C3.MTX.01-01",
    whatTags: ["classification"],
    thinkingTags: ["sorting"],
    themeTag: "school",
    sayToChild: '"Bé xếp hình vào ma trận đúng vị trí nhé!"',
  },
  {
    code: "ACT-0354",
    title: "Trò chơi số: Ma trận logic hai chiều",
    gameLevelCode: "GL-C3-MAT-CHO-0024",
    skillCode: "C3.MTX.01",
    loCode: "LO-C3.MTX.01-01",
    whatTags: ["log", "mat"],
    thinkingTags: ["infer", "compare"],
    themeTag: "school",
    sayToChild: '"Bé tìm mảnh ghép còn thiếu trong ma trận nhé!"',
  },
  {
    code: "ACT-0355",
    title: "Trò chơi số: Đếm đồ vật đo lường",
    gameLevelCode: "GL-C1-CNT-CARD-0003",
    skillCode: "C1.MEAS.13",
    loCode: "LO-C1.MEAS.13-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé đếm số vạch đo trên thước nhé!"',
  },
  {
    code: "ACT-0356",
    title: "Trò chơi số: Đo lường thời gian kim giờ",
    gameLevelCode: "GL-C1-CLK-HND-0037",
    skillCode: "C1.MEAS.13",
    loCode: "LO-C1.MEAS.13-01",
    whatTags: ["cnt", "tim"],
    thinkingTags: ["shift", "observe"],
    themeTag: "school",
    sayToChild: '"Bé chỉnh kim đồng hồ đến đúng giờ nhé!"',
  },
  {
    code: "ACT-0357",
    title: "Trò chơi số: Nhận diện khối không gian",
    gameLevelCode: "GL-C2-SHP-CARD-0002",
    skillCode: "C2.GEO.01",
    loCode: "LO-C2.GEO.01-01",
    whatTags: ["shapes_2d"],
    thinkingTags: ["shape_recognition"],
    themeTag: "school",
    sayToChild: '"Bé tìm khối lập phương nhé!"',
  },
  {
    code: "ACT-0358",
    title: "Trò chơi số: Lắp ghép khối không gian",
    gameLevelCode: "GL-C2-CON-SHP-0027",
    skillCode: "C2.GEO.01",
    loCode: "LO-C2.GEO.01-01",
    whatTags: ["geo", "spatial"],
    thinkingTags: ["match", "observe"],
    themeTag: "school",
    sayToChild: '"Bé ghép các khối thành lâu đài nhé!"',
  },
  {
    code: "ACT-0359",
    title: "Trò chơi số: Xếp hạt vào khay đếm",
    gameLevelCode: "GL-C1-SORT-BOX-0006",
    skillCode: "C1.PROB.06",
    loCode: "LO-C1.PROB.06-01",
    whatTags: ["numbers_1_5"],
    thinkingTags: ["counting"],
    themeTag: "school",
    sayToChild: '"Bé xếp hạt vào khay đủ số lượng nhé!"',
  },
  {
    code: "ACT-0360",
    title: "Trò chơi số: Nhìn nhanh đếm hạt khay",
    gameLevelCode: "GL-C1-MEM-FLASH-0040",
    skillCode: "C1.PROB.06",
    loCode: "LO-C1.PROB.06-01",
    whatTags: ["cnt", "mem"],
    thinkingTags: ["recall", "count"],
    themeTag: "school",
    sayToChild: '"Bé đếm nhanh xem có mấy hạt nhé!"',
  },
  {
    code: "ACT-0361",
    title: "Trò chơi số: Quy luật ma trận hình",
    gameLevelCode: "GL-C3-PAT-SEQ-0006",
    skillCode: "C3.MTX.01",
    loCode: "LO-C3.MTX.01-01",
    whatTags: ["patterns"],
    thinkingTags: ["pattern_recognition"],
    themeTag: "school",
    sayToChild: '"Bé xem hình nào đứng tiếp theo trong hàng nhé!"',
  },
  {
    code: "ACT-0362",
    title: "Trò chơi số: Điền ô ma trận Sudoku",
    gameLevelCode: "GL-C3-SUD-MIN-0027",
    skillCode: "C3.MTX.01",
    loCode: "LO-C3.MTX.01-01",
    whatTags: ["log", "sud"],
    thinkingTags: ["infer", "plan"],
    themeTag: "school",
    sayToChild: '"Bé điền hình vào ô trống không bị trùng nhé!"',
  },
];

export const DIGITAL_GAME_ACTIVITIES: ActivitySeed[] = DIGITAL_GAMES.map(
  (g) => ({
    kind: "activity",
    header: {
      code: g.code,
      content_version: 1,
      title: g.title,
      activity_kind: "digital_game",
      ref_type: "game_level",
      ref_code: g.gameLevelCode,
      instruction: {
        preparation: "Mở màn chơi số trên thiết bị.",
        steps: [
          {
            instruction: "Cho bé thực hiện thử thách trên màn hình.",
            say_to_child: g.sayToChild,
          },
        ],
        easier: "Bật gợi ý trực quan trên màn chơi.",
        harder: "Thực hiện màn chơi ở độ khó cao hơn.",
      },
      target_age_min: 3,
      target_age_max: 6,
      estimated_minutes: 5,
      access_tier: "free",
      skill_codes: [g.skillCode],
      learning_objective_codes: [g.loCode],
      what_tags: g.whatTags,
      thinking_tags: g.thinkingTags,
      theme_tag: g.themeTag,
      origin: "human",
      authored_in: "repo_seed",
    },
  })
);
