import type { ContentSeed } from "../types.js";

export const C5_SEED_LEVELS: ContentSeed<unknown, unknown>[] = [
  // Level 1 (Free)
  {
    header: {
      code: "GL-C5-VOC-CARD-0001",
      content_version: 1,
      template_code: "GT-001",
      title: "Học từ vựng con vật",
      instruction: "Em hãy chọn hình chú chó nhé.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "free",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "dog", emoji: "🐶" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 2 (Login)
  {
    header: {
      code: "GL-C5-VOC-CARD-0002",
      content_version: 1,
      template_code: "GT-001",
      title: "Học từ vựng con mèo",
      instruction: "Em chọn hình chú mèo ngoan.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "cat1", emoji: "🐱" },
        { id: "cat2", emoji: "🐱" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 3 },
  },
  // Level 3 (Login)
  {
    header: {
      code: "GL-C5-VOC-CARD-0003",
      content_version: 1,
      template_code: "GT-001",
      title: "Học từ vựng chú gà gáy",
      instruction: "Chạm vào chú gà trống báo thức.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: { items: [{ id: "rooster", emoji: "🐓" }], target_count: 1 },
    difficulty_params: { count_limit: 3 },
  },
  // Level 4 (Login)
  {
    header: {
      code: "GL-C5-VOC-BOX-0004",
      content_version: 1,
      template_code: "GT-002",
      title: "Ghép thẻ từ vựng trái cây",
      instruction: "Kéo quả táo vào ô chữ táo.",
      age_min: 3,
      age_max: 4,
      difficulty: 1,
      access_tier: "login",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "word_apple", label: "Táo", target_word: "apple" }],
      drag_items: [
        { id: "a1", emoji: "🍎", word: "apple" },
        { id: "b1", emoji: "🍌", word: "banana" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 5 (Login)
  {
    header: {
      code: "GL-C5-VOC-BOX-0005",
      content_version: 1,
      template_code: "GT-002",
      title: "Ghép thẻ từ vựng chuối",
      instruction: "Kéo quả chuối vào ô chữ chuối.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "word_banana", label: "Chuối", target_word: "banana" },
      ],
      drag_items: [
        { id: "b1", emoji: "🍌", word: "banana" },
        { id: "o1", emoji: "🍊", word: "orange" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 6 (Login)
  {
    header: {
      code: "GL-C5-EXP-CMP-0006",
      content_version: 1,
      template_code: "GT-003",
      title: "Diễn đạt từ trái nghĩa to nhỏ",
      instruction: "Chọn hình mô tả khái niệm to.",
      age_min: 3,
      age_max: 4,
      difficulty: 2,
      access_tier: "login",
      skill_codes: ["C5.DES.01"],
      learning_objective_codes: ["LO-C5.DES.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🏠", concept: "big" }],
      right_group: [{ emoji: "🛖", concept: "small" }],
      target: "big",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 7 (Standard)
  {
    header: {
      code: "GL-C5-EXP-CMP-0007",
      content_version: 1,
      template_code: "GT-003",
      title: "Diễn đạt từ trái nghĩa cao thấp",
      instruction: "Chọn hình mô tả khái niệm cao.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C5.DES.01"],
      learning_objective_codes: ["LO-C5.DES.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🦒", concept: "tall" }],
      right_group: [{ emoji: "🐿️", concept: "short" }],
      target: "tall",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 8 (Standard)
  {
    header: {
      code: "GL-C5-VOC-SEQ-0008",
      content_version: 1,
      template_code: "GT-004",
      title: "Chuỗi từ vựng gia đình",
      instruction: "Chọn thành viên gia đình tiếp theo.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["👨", "👩", "👨", "👩"],
      options: ["👨", "👩", "👶"],
      correct_option: "👨",
    },
    difficulty_params: { pattern_length: 2 },
  },
  // Level 9 (Standard)
  {
    header: {
      code: "GL-C5-VOC-LOC-0009",
      content_version: 1,
      template_code: "GT-005",
      title: "Gọi tên đồ dùng học tập",
      instruction: "Chạm vào quyển sách màu xanh.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "book", emoji: "📘", word: "book" },
          { id: "pen", emoji: "✏️", word: "pen" },
        ],
      ],
      target_id: "book",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 10 (Standard)
  {
    header: {
      code: "GL-C5-SUB-FAST-0010",
      content_version: 1,
      template_code: "GT-006",
      title: "Nghe từ nhận diện nhanh",
      instruction: "Hình nào mang từ vựng quả táo.",
      age_min: 4,
      age_max: 5,
      difficulty: 2,
      access_tier: "standard",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🍎" }],
      flash_duration_ms: 1500,
      options: ["Quả táo", "Quả cam"],
      correct_answer: "Quả táo",
    },
    difficulty_params: { flash_duration_ms: 1500 },
  },
  // Level 11 (Standard)
  {
    header: {
      code: "GL-C5-VOC-CARD-0011",
      content_version: 1,
      template_code: "GT-001",
      title: "Học từ vựng xe cảnh sát",
      instruction: "Đếm số chiếc xe cảnh sát.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      items: [
        { id: "p1", emoji: "🚔" },
        { id: "p2", emoji: "🚔" },
      ],
      target_count: 2,
    },
    difficulty_params: { count_limit: 5 },
  },
  // Level 12 (Standard)
  {
    header: {
      code: "GL-C5-VOC-BOX-0012",
      content_version: 1,
      template_code: "GT-002",
      title: "Ghép từ vựng phương tiện bay",
      instruction: "Kéo máy bay vào bầu trời.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "standard",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [{ id: "sky", label: "Bầu trời", target_category: "air" }],
      drag_items: [
        { id: "plane", emoji: "✈️", category: "air" },
        { id: "boat", emoji: "⛵", category: "water" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 13 (Premium)
  {
    header: {
      code: "GL-C5-EXP-CMP-0013",
      content_version: 1,
      template_code: "GT-003",
      title: "Diễn đạt quan hệ trước sau",
      instruction: "Chọn sự vật diễn ra trước.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C5.DES.01"],
      learning_objective_codes: ["LO-C5.DES.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "farm",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "🌱", stage: "first" }],
      right_group: [{ emoji: "🌳", stage: "second" }],
      target: "first",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 14 (Premium)
  {
    header: {
      code: "GL-C5-VOC-SEQ-0014",
      content_version: 1,
      template_code: "GT-004",
      title: "Chuỗi câu chuyện đơn giản",
      instruction: "Chọn bước tiếp theo của câu chuyện.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C5.DES.01"],
      learning_objective_codes: ["LO-C5.DES.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🥚", "🐣", "🐥"],
      options: ["🐔", "🥚", "🦆"],
      correct_option: "🐔",
    },
    difficulty_params: { pattern_length: 3 },
  },
  // Level 15 (Premium)
  {
    header: {
      code: "GL-C5-VOC-LOC-0015",
      content_version: 1,
      template_code: "GT-005",
      title: "Nhận biết biển báo học đường",
      instruction: "Chạm vào biển báo sang đường.",
      age_min: 5,
      age_max: 6,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      grid: [
        [
          { id: "crosswalk", emoji: "🚸", sign: "crosswalk" },
          { id: "stop", emoji: "🛑", sign: "stop" },
        ],
      ],
      target_id: "crosswalk",
    },
    difficulty_params: { grid_size: 2 },
  },
  // Level 16 (Premium)
  {
    header: {
      code: "GL-C5-SUB-FAST-0016",
      content_version: 1,
      template_code: "GT-006",
      title: "Nhớ từ vựng siêu tốc",
      instruction: "Từ vựng nào vừa xuất hiện.",
      age_min: 4,
      age_max: 5,
      difficulty: 3,
      access_tier: "premium",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "🚀" }],
      flash_duration_ms: 1200,
      options: ["Tên lửa", "Máy bay"],
      correct_answer: "Tên lửa",
    },
    difficulty_params: { flash_duration_ms: 1200 },
  },
  // Level 17 (Premium)
  {
    header: {
      code: "GL-C5-EXP-CMP-0017",
      content_version: 1,
      template_code: "GT-003",
      title: "Diễn đạt từ đồng nghĩa",
      instruction: "Chọn từ đồng nghĩa với vui vẻ.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C5.DES.01"],
      learning_objective_codes: ["LO-C5.DES.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      left_group: [{ emoji: "😄", word: "happy" }],
      right_group: [{ emoji: "😢", word: "sad" }],
      target: "happy",
    },
    difficulty_params: { max_difference: 1 },
  },
  // Level 18 (Premium)
  {
    header: {
      code: "GL-C5-VOC-BOX-0018",
      content_version: 1,
      template_code: "GT-002",
      title: "Phân loại nhóm từ chỉ nghề nghiệp",
      instruction: "Kéo dụng cụ bác sĩ vào túi.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      containers: [
        { id: "doctor_kit", label: "Túi bác sĩ", target_job: "doctor" },
      ],
      drag_items: [
        { id: "d1", emoji: "🩺", job: "doctor" },
        { id: "p1", emoji: "🎨", job: "artist" },
      ],
    },
    difficulty_params: { item_count: 2 },
  },
  // Level 19 (Premium)
  {
    header: {
      code: "GL-C5-VOC-SEQ-0019",
      content_version: 1,
      template_code: "GT-004",
      title: "Dãy từ vựng thời gian 4 mùa",
      instruction: "Chọn mùa tiếp theo trong năm.",
      age_min: 5,
      age_max: 6,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C5.STO.01"],
      learning_objective_codes: ["LO-C5.STO.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "school",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      sequence: ["🌸", "☀️", "🍂"],
      options: ["❄️", "🌸", "🌧️"],
      correct_option: "❄️",
    },
    difficulty_params: { pattern_length: 4 },
  },
  // Level 20 (Premium)
  {
    header: {
      code: "GL-C5-SUB-FAST-0020",
      content_version: 1,
      template_code: "GT-006",
      title: "Thử thách nhận diện biểu cảm nhanh",
      instruction: "Khuôn mặt vừa rồi có cảm xúc gì.",
      age_min: 4,
      age_max: 5,
      difficulty: 4,
      access_tier: "premium",
      skill_codes: ["C5.DES.01"],
      learning_objective_codes: ["LO-C5.DES.01-01"],
      what_tags: ["voc"],
      thinking_tags: ["associative"],
      theme_tag: "home",
      origin: "human",
      authored_in: "repo_seed",
    },
    content_pack: {
      flash_items: [{ emoji: "😍" }],
      flash_duration_ms: 1000,
      options: ["Yêu thương", "Tức giận"],
      correct_answer: "Yêu thương",
    },
    difficulty_params: { flash_duration_ms: 1000 },
  },
];
