import type { SkillDataset, SkillIdentity, SkillSeed } from "@mindkid/shared";

export const C1_PROB_01_IDENTITY: SkillIdentity = {
  code: "C1.PROB.01",
  strand_code: "C1.PROB",
  competency_code: "C1",
  name: "Chọn cách giải",
  age_min: 6,
  age_max: 6,
  difficulty: 5,
  thinking_processes: ["plan", "solve"],
  tier: "advanced",
  prerequisites: ["C1.ADD.04", "C1.SUB.03"],
  learning_objectives: [
    {
      code: "LO-C1.PROB.01-01",
      behaviour: "Nhận biết và thực hành Chọn cách giải ở mức cơ bản",
      observable_criteria:
        "Trẻ thực hiện đúng không qua gợi ý trong 3 lần thử liên tiếp.",
      position: 1,
    },
    {
      code: "LO-C1.PROB.01-02",
      behaviour: "Vận dụng Chọn cách giải trong môi trường tương tác",
      observable_criteria:
        "Trẻ hoàn thành thử thách độc lập trong vòng 2 phút.",
      position: 2,
    },
    {
      code: "LO-C1.PROB.01-03",
      behaviour: "Giải quyết vấn đề nâng cao liên quan tới Chọn cách giải",
      observable_criteria:
        "Trẻ trả lời chính xác câu hỏi phân loại/suy luận liên quan.",
      position: 3,
    },
  ],
};

export const C1_PROB_01_DATASET: SkillDataset = {
  skill_code: "C1.PROB.01",
  concept_label: "Chọn cách giải",
  surface: "game",
  items: [
    {
      id: "plan_step_1",
      label: "bước một: đọc đề bài",
      glyph: "📖",
      value: 1,
      audio_path: "/audio/voice/c1/prob/step_1.mp3",
      image: {
        kind: "emoji",
        ref: "📖",
      },
      contrast_group: "step",
    },
    {
      id: "plan_step_2",
      label: "bước hai: chọn phép tính",
      glyph: "🤔",
      value: 2,
      audio_path: "/audio/voice/c1/prob/step_2.mp3",
      image: {
        kind: "emoji",
        ref: "🤔",
      },
      contrast_group: "step",
    },
    {
      id: "plan_step_3",
      label: "bước ba: tính kết quả",
      glyph: "✍️",
      value: 3,
      audio_path: "/audio/voice/c1/prob/step_3.mp3",
      image: {
        kind: "emoji",
        ref: "✍️",
      },
      contrast_group: "step",
    },
    {
      id: "plan_step_4",
      label: "bước bốn: kiểm tra lại",
      glyph: "✅",
      value: 4,
      audio_path: "/audio/voice/c1/prob/step_4.mp3",
      image: {
        kind: "emoji",
        ref: "✅",
      },
      contrast_group: "step",
    },
  ],
  relations: [
    {
      type: "sequence",
      source_id: "plan_step_1",
      target_id: "plan_step_2",
      metadata: {
        step: 1,
      },
    },
    {
      type: "sequence",
      source_id: "plan_step_2",
      target_id: "plan_step_3",
      metadata: {
        step: 2,
      },
    },
    {
      type: "sequence",
      source_id: "plan_step_3",
      target_id: "plan_step_4",
      metadata: {
        step: 3,
      },
    },
  ],
  ladder: [
    {
      rung: 1,
      dimension: "range",
      description: "Làm quen cơ bản",
      representation: "discrete-object",
    },
    {
      rung: 2,
      dimension: "range",
      description: "Nhận biết và chọn đúng",
      representation: "discrete-object",
    },
    {
      rung: 3,
      dimension: "distractor_count",
      description: "Phân biệt với phương án nhiễu",
      representation: "ten-frame",
    },
    {
      rung: 4,
      dimension: "item_count",
      description: "Mở rộng phạm vi và số lượng",
      representation: "ten-frame",
    },
    {
      rung: 5,
      dimension: "speed_scaffolding",
      description: "Thuần thục và độc lập thực hiện",
      representation: "numeral",
    },
  ],
  phrasing: {
    prompt_template: "Bé hãy giải bài toán tìm {label} nhé!",
    narration_template: "Chúng mình cùng tìm hiểu về Chọn cách giải nhé",
  },
  ordering: ["plan_step_4", "plan_step_3", "plan_step_2", "plan_step_1"],
};

export const C1_PROB_01_SEED: SkillSeed = {
  identity: C1_PROB_01_IDENTITY,
  dataset: C1_PROB_01_DATASET,
  levels: [
    {
      code: "GL-C1-PROB-SEP-0001",
      template: "GT-004",
      band: "4-5",
      difficulty: 2,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SEP-0002",
      template: "GT-007",
      band: "5-6",
      difficulty: 3,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SORT-0001",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SORT-0002",
      template: "GT-006",
      band: "5-6",
      difficulty: 5,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SORT-0003",
      template: "GT-006",
      band: "5-6",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SORT-0004",
      template: "GT-006",
      band: "5-6",
      difficulty: 5,
      theme: "vehicle",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SHAD-0001",
      template: "GT-007",
      band: "5-6",
      difficulty: 4,
      theme: "art",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SHAD-0002",
      template: "GT-007",
      band: "5-6",
      difficulty: 5,
      theme: "space",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SHAD-0003",
      template: "GT-007",
      band: "5-6",
      difficulty: 4,
      theme: "family",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SIZE-0001",
      template: "GT-009",
      band: "5-6",
      difficulty: 4,
      theme: "weather",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SIZE-0002",
      template: "GT-009",
      band: "5-6",
      difficulty: 5,
      theme: "festival",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SIZE-0003",
      template: "GT-009",
      band: "5-6",
      difficulty: 4,
      theme: "job",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-SIZE-0004",
      template: "GT-009",
      band: "5-6",
      difficulty: 5,
      theme: "homeland",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-MAZE-0001",
      template: "GT-013",
      band: "5-6",
      difficulty: 4,
      theme: "school",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-MAZE-0002",
      template: "GT-013",
      band: "5-6",
      difficulty: 5,
      theme: "farm",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-MAZE-0003",
      template: "GT-013",
      band: "5-6",
      difficulty: 4,
      theme: "home",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-MAZE-0004",
      template: "GT-013",
      band: "5-6",
      difficulty: 5,
      theme: "animal",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-HIDE-0001",
      template: "GT-015",
      band: "5-6",
      difficulty: 4,
      theme: "nature",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-HIDE-0002",
      template: "GT-015",
      band: "5-6",
      difficulty: 5,
      theme: "ocean",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-HIDE-0003",
      template: "GT-015",
      band: "5-6",
      difficulty: 4,
      theme: "food",
      rounds: 3,
    },
    {
      code: "GL-C1-PROB-HIDE-0004",
      template: "GT-015",
      band: "5-6",
      difficulty: 5,
      theme: "vehicle",
      rounds: 3,
    },
  ],
};
